fedspendingtransparency/usaspending-website

- src/js/components/icons/BaseIcon.jsx
- src/js/components/search/SearchSidebar.jsx
- src/js/containers/BarChart.jsx
- src/js/containers/Table.jsx
- src/js/redux/actions/sessionActions.js
- src/js/redux/reducers/index.jsx
- Reworking options map to keep return statement cleaner.
- Removing excess, unnecessary references to session/login
- Adding reminder notes of where to pass in API data next sprint
> Scaffolding to dev

- src/js/containers/search/SearchContainer.jsx
- src/js/dataMapping/search/tableSearchFields.js
- src/js/models/results/award/AwardSummary.js
* Updates results table to use the `toptier_agency` name
* Results table now displays only `piid` for contracts and `fain` for other award types
> Show Awarding Agency in Results Table

- src/js/helpers/searchHelper.js
* Synced merge with fedspendingtransparency/usaspending-api#123
> Update award endpoint URL

- src/js/models/search/queryBuilders/LocationQuery.js
* Fixes location filter to filter against the correct API field
> Fix: Search by place of performance

- src/_scss/components/visualizations/_scope.scss
- src/_scss/pages/search/_filterExpand.scss
- src/_scss/pages/search/_searchOption.scss
- src/_scss/pages/search/results/visualizations/rank/_pager.scss
- src/js/components/search/SearchOption.jsx
- src/js/components/search/SearchSidebar.jsx
* Changed the title of the filter “Primary Place of Performance” to
“Place of Performance” to avoid pushing the guide icon to the next
line.
* Updated the font-weight of the buttons within the scope.scss file
(light blue background area on search results page.)
* Updated the SASS for the buttons beneath the “Spending By:”
visualization.
> Table style updates

- src/_scss/layouts/default/header/_positioning.scss
- src/_scss/layouts/default/header/nav/_menu.scss
- src/_scss/layouts/search/header/_downloadButton.scss
- src/_scss/layouts/search/header/_options.scss
- src/_scss/pages/search/_searchOption.scss
- src/_scss/pages/search/results/table/_tableTypes.scss
- src/_scss/pages/search/results/visualizations/rank/_topSection.scss
- src/_scss/pages/search/results/visualizations/time/_topSection.scss
- src/js/components/search/FilterExpandButton.jsx
- src/js/components/search/SearchOption.jsx
- src/js/components/search/header/DownloadButton.jsx
- src/js/components/search/header/SearchHeader.jsx
- src/js/components/search/table/ResultsTableTabItem.jsx
- src/js/components/search/visualizations/rank/RankVisualizationScopeButton.jsx
- src/js/components/search/visualizations/rank/RankVisualizationSection.jsx
- src/js/components/search/visualizations/time/TimeVisualizationPeriodButton.jsx
- src/js/components/search/visualizations/time/TimeVisualizationSection.jsx
- src/js/components/sharedComponents/header/NavBar.jsx
- src/js/containers/search/table/ResultsTableContainer.jsx
Disable and label unfinished features in the Search Results page.
> Add “coming-soon” labels to unfinished features on the Search page (with lint error and code review fixes)

- src/js/components/search/SearchOption.jsx
- src/js/components/search/filters/awardType/PrimaryAwardType.jsx
- src/js/components/search/filters/awardType/SecondaryAwardType.jsx
- src/js/components/search/filters/awardType/SingleAwardType.jsx
- src/js/components/search/filters/timePeriod/AllFiscalYears.jsx
- src/js/components/search/filters/timePeriod/TimePeriod.jsx
- src/js/containers/router/RouterContainer.jsx
- src/js/containers/search/filters/AgencyContainer.jsx
- src/js/containers/search/filters/location/LocationSearchContainer.jsx
- src/js/containers/search/filters/recipient/RecipientSearchContainer.jsx
DS-739
Analytics for search page filters
> Feature analytics

- src/_scss/pages/search/filters/location/_errorMessage.scss
- src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
- src/js/containers/search/filters/AgencyListContainer.jsx
- src/js/containers/search/filters/location/LocationListContainer.jsx
- src/js/containers/search/filters/recipient/RecipientLocationContainer.jsx
- src/js/containers/search/filters/recipient/RecipientNameDUNSContainer.jsx
Fixed all annoying Autocomplete issues (500ms -> 1s delay on 1-character input error, auto height of error box, shows error when API returns error or 0 results, shows logical error messages, fixes timing issue when user enters text and clears it before API promise returns)
> Autocomplete Fixes

- src/js/components/search/filters/keyword/Keyword.jsx
- Adding handling for a user hitting enter rather than clicking ‘submit’
> Hotfix: Free Text Search

- src/_scss/pages/search/filters/awardAmount/_specificAwardAmount.scss
- src/js/components/search/filters/awardAmount/SpecificAwardAmountItem.jsx
CSS fixes for Award Amount input so that it matches other text inputs and has a consistent button with Search filter
> Hotfix - Award Amount Button and Input Styles

- src/js/components/award/financialAssistance/GrantDetails.jsx
Updating Grants page ‘See Additional Details’ class name to allow the button to display properly
> Grants Hotfix

- src/graphics/homepage.json
- src/js/components/homepage/Homepage.jsx
- src/js/components/homepage/Landing.jsx
- src/js/components/homepage/visualizations/TreeMap.jsx
- src/js/helpers/homepageHelper.js
- Moved homepage data into json
- Updated treemap component accordingly
- Small text update
> Hotfix homepage

- .travis.yml
* Jest unit tests now run 95% faster on Travis
> 2 Fast 2 Test

- src/js/components/account/visualizations/rank/AccountRankVisualizationSection.jsx
- src/js/components/search/visualizations/rank/chart/HorizontalChart.jsx
- src/js/containers/account/visualizations/AccountRankVisualizationContainer.jsx
- src/js/dataMapping/accounts/accountFields.js
- src/js/models/account/queries/AccountSearchBalanceOperation.js
- src/js/models/account/queries/AccountSearchOperation.js
- tests/containers/account/visualizations/AccountRankVisualizationContainer-test.jsx
* Displays program activity, object class, and TAS names instead of codes on the Y axis
* Enables options to display object class and TAS ranks instead of only program activity
* Fixes a bug on both federal account and award search rank visualizations where resizing the window could cause the Y axis line to shift position incorrectly
> Federal Account Page: Updated Spending by Category visualization

- .travis.yml
- src/_scss/pages/account/results/_filters.scss
- src/_scss/pages/account/results/searchResults.scss
- src/_scss/pages/search/_filters.scss
- src/_scss/pages/search/filters/budgetCategory/_ObjectClassItem.scss
- src/_scss/pages/search/filters/budgetCategory/budgetCategory.scss
- src/_scss/pages/search/filters/timePeriod/_toggleButtons.scss
- src/js/components/account/SearchSidebar.jsx
- src/js/components/account/filters/objectClass/ObjectClassFilter.jsx
- src/js/components/account/filters/objectClass/ObjectClassItem.jsx
- src/js/components/account/topFilterBar/filterGroups/AccountTopFilterGroupGenerator.jsx
- src/js/components/account/topFilterBar/filterGroups/ObjectClassFilterGroup.jsx
- src/js/components/search/filters/timePeriod/TimePeriod.jsx
- src/js/containers/account/filters/AccountObjectClassContainer.jsx
- src/js/containers/account/filters/AccountTimePeriodContainer.jsx
- src/js/containers/account/topFilterBar/AccountTopFilterBarContainer.jsx
- src/js/dataMapping/search/budgetCategory.js
- src/js/models/account/queries/AccountSearchOperation.js
- src/js/models/account/queries/queryBuilders/ObjectClassQuery.js
- src/js/redux/actions/account/accountFilterActions.js
- src/js/redux/reducers/account/accountReducer.js
- src/js/redux/reducers/account/filters/accountObjectClassFunctions.js
- tests/containers/account/defaultFilters.js
- tests/containers/account/filters/AccountObjectClassContainer-test.jsx
- tests/containers/account/topFilterBar/AccountTopFilterBarContainer-test.jsx
- tests/containers/account/visualizations/AccountRankVisualizationContainer-test.jsx
- tests/containers/account/visualizations/AccountTimeVisualizationContainer-test.jsx
- tests/redux/reducers/account/accountReducer-test.js
* Object class filter UI and top filter bar group
* Integrates with `/tas/categories/total` API endpoint
* Implements object class filter for spending by category visualization only, pending API stablization on spending over time
> Object Class Filter (Federal Account page)

- src/_scss/pages/homepage/homePage.scss
- src/js/components/homepage/Homepage.jsx
- src/js/components/homepage/visualizations/MapVisualization.jsx
- src/js/containers/homepage/MapVisualizationContainer.jsx
- tests/containers/homepage/MapVisualizationContainer-test.jsx
- Copied over existing map files from search section, reworked for individual year call, removed unnecessary functions concerning filters
- Added `total` value to state to allow for percentages to render in this simplified map component
- Jest Test written for the container holding it
> [DS-1004] Map Section on Homepage

- .travis.yml
- src/js/containers/award/table/AssistanceTransactionsTableContainer.jsx
- src/js/containers/award/table/ContractTransactionsTableContainer.jsx
- src/js/containers/award/table/FinancialSystemTableContainer.jsx
- src/js/dataMapping/contracts/financialSystem.js
- src/js/models/results/other/FinancialSystemItem.js
- src/js/redux/reducers/award/awardReducer.js
- tests/containers/award/table/AssistanceTransactionsTableContainer-test.jsx
- tests/containers/award/table/ContractTransactionsTableContainer-test.jsx
- tests/containers/award/table/FinancialSystemTableContainer-test.jsx
- tests/containers/award/table/mockContractTransaction.js
- tests/containers/award/table/mockGrantTransaction.js
- tests/redux/reducers/award/awardReducer-test.js
* Update Financial System Details model to correctly parse updated API response
> Fix: Object Class in Financial System

- src/js/containers/search/visualizations/rank/SpendingByCategoryRankVisualizationSectionContainer.jsx
Issue stems from grouping by Federal Account when not appropriate
> Hotfix - Fixing duplicate Budget Function / Object Class issue

- src/js/components/award/details/additional/ContractAdditionalDetails.jsx
- src/js/dataMapping/contracts/additionalDetails.js
- Executive Compensation section added to Contract Awards
- Fields added to dataMapping
> [Ds-1071] executive compensation section

- src/_scss/pages/award/table/_subawards.scss
- src/_scss/pages/award/table/_table.scss
- src/_scss/pages/award/table/detailsTable.scss
- src/js/components/award/AwardInfo.jsx
- src/js/components/award/details/DetailsSection.jsx
- src/js/components/award/details/DetailsTabBar.jsx
- src/js/components/award/subawards/SubawardsTable.jsx
- src/js/components/award/subawards/cells/SubawardsHeaderCell.jsx
- src/js/containers/award/AwardContainer.jsx
- src/js/containers/award/subawards/SubawardsContainer.jsx
- src/js/containers/award/subawards/cells/SubawardsHeaderCellContainer.jsx
- src/js/containers/search/SearchContainer.jsx
- src/js/dataMapping/contracts/subawardTable.js
- src/js/helpers/accountHelper.js
- src/js/helpers/searchHelper.js
- src/js/models/results/award/AwardSummary.js
- src/js/models/results/award/SubawardItem.js
- src/js/redux/actions/award/awardActions.js
- src/js/redux/reducers/award/awardReducer.js
- tests/containers/award/mockSubawards.js
- tests/containers/award/subawards/SubawardsContainer-test.jsx
- tests/redux/reducers/award/awardReducer-test.js
- tests/redux/reducers/award/mockAward.js
* Implements the subaward tab on the awards page
* Allows column sorting and pagination
* Integrates with API
> Subaward tab on Awards Page

- src/js/dataMapping/contracts/additionalDetails.js
* Adds officer names to executive compensation table
> Executive Compensation: Officer Names

- src/js/components/account/filters/programActivity/ProgramActivityFilter.jsx
- Orders Program Activity filter options on Federal Account page by the numerical conversion of the Program Activity Code
> Program Activity Filter Item Ordering

- src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
* Temporarily increase map visualization API request limit to 500
> Hotfix: Wyoming

- src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
Ensures country code is "USA" for all results of Geo visualization
> Fixing place of performance to show only American locations

- src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
Reverts fedspendingtransparency/usaspending-website#185
> Revert "Fixing place of performance to show only American locations"

- src/_scss/pages/award/_loanDetails.scss
- src/js/components/award/LoanAmounts.jsx
- Rounding & truncating % digits to 2
- Updating style to display 2-line amounts properly
> Hotfix Loan Amount Display

- index.html
- src/_scss/pages/homepage/_treemapSource.scss
- src/_scss/pages/homepage/mapTopBar.scss
- src/_scss/pages/homepage/treemapSidebar.scss
- Added meta tag so that the media queries function correctly on mobile devices.
- Hid the “More” button and the Map options on the homepage until the components are developed.
> Updates to the homepage. Meta tag added.

- src/js/components/homepage/LinksSection.jsx
- src/js/components/sharedComponents/header/NavBar.jsx
> Hotfix updated link to top nav and to the bottom section of on the homepage

- src/js/components/homepage/LinksSection.jsx
- src/js/components/sharedComponents/header/NavBar.jsx
* Demote by way of `mergeconflict` branch
> Demote dev-stable to dev

- src/js/components/about/NextSteps.jsx
- src/js/components/sharedComponents/header/NavBar.jsx
Added a “subject” to the mailto: links for “Help” (Located within the site header) and “Contact Us” (On the About page).
> Added a “subject” to the mailto: links for “Help” and “Contact Us”.

- src/_scss/pages/homepage/_mapSegue.scss
- src/_scss/pages/homepage/byCategorySection.scss
- src/graphics/homepage.json
- src/js/components/homepage/visualizations/categoryMap/BudgetLabel.jsx
- src/js/components/homepage/visualizations/categoryMap/BudgetLine.jsx
- src/js/components/homepage/visualizations/categoryMap/CategoryMap.jsx
- Adding new tile to breakdown treemap
- Adding label to desktop size
> [DS-1297] Additions to Category Breakdown Treemap (Homepage)

- src/js/containers/search/modals/ExtraModalContainer.jsx
Reverts fedspendingtransparency/usaspending-website#262
> Revert "CSV"

- src/js/containers/search/filters/AgencyListContainer.jsx
- Show error state for results of Funding Agency autocomplete search that contain exclusively subtier Funding Agencies
> Fix - Funding Agency search error message

- src/_scss/components/checkbox/_sharedCheckboxStyle.scss
- src/_scss/pages/homepage/byCategorySection.scss
- src/_scss/pages/homepage/visualizations/_byCategoryVisualization.scss
- src/_scss/pages/homepage/visualizations/_treemapVisualization.scss
- src/graphics/homepage.json
- src/js/components/homepage/visualizations/categoryMap/BudgetLabel.jsx
- src/js/components/homepage/visualizations/categoryMap/BudgetLine.jsx
- src/js/components/homepage/visualizations/categoryMap/CategoryMap.jsx
- src/js/components/homepage/visualizations/categoryMap/CategoryMapTooltip.jsx
- Adjusted a few styles.
- Added the total amount for each category to the tooltip.
> Updated the data for the “Spending By” treeMap on the homepage.

- src/_scss/pages/search/filters/budgetCategory/budgetCategory.scss
- src/js/components/sharedComponents/checkbox/PrimaryCheckboxType.jsx
Force unified checkboxes to expand when some but not all children are selected
> Fix: Checkboxes

- gulpfile.babel.js
* Remove uninstalled libraries from core.js to prevent potential build issues
> Fix: Prevent potential Webpack core build errors

- src/js/components/homepage/visualizations/geo/MapVisualization.jsx
- src/js/components/homepage/visualizations/geo/tooltips/GeoTotalTooltip.jsx
* Update homepage map disclaimer
* Update homepage map tooltip
> Fix: Homepage Map Disclaimer

- src/js/dataMapping/search/tableSearchFields.js
- src/js/redux/reducers/search/columnVisibilityReducerInitialState.js
- tests/redux/reducers/search/columnVisibilityReducer-test.js
- Made Awarding Agency and Awarding Sub-Agency columns visible by default for all tabs
- Made Funding Agency and Funding Sub-Agency columns hidden by default for all tabs
> Show Awarding Agency in the table by default

- src/_scss/pages/agency/_overview.scss
- src/js/components/agency/overview/AgencyOverview.jsx
- src/js/containers/agency/AgencyContainer.jsx
- src/js/helpers/agencyHelper.js
- src/js/redux/reducers/agency/agencyReducer.js
- tests/containers/agency/AgencyContainer-test.jsx
- tests/containers/agency/mockAgency.js
- tests/redux/reducers/agency/agencyReducer-test.js
* Implements agency container
* Implements agency overview section
* Adds tests for agency container and agency reducer
> Agency Container

- src/_scss/pages/agency/_section.scss
- src/js/components/agency/visualizations/objectClass/ObjectClassTreeMap.jsx
- Bolded "object class"
- Modified margins
> Agency Object Class Visualization - Style Updates

- src/js/components/agency/AgencyError.jsx
- src/js/components/agency/AgencyLoading.jsx
- src/js/containers/agency/AgencyContainer.jsx
* Styled error and loading messages
> Update: Handle invalid agency IDs

- src/_scss/pages/agency/_contentWrap.scss
- src/_scss/pages/agency/agencyPage.scss
- src/_scss/pages/agency/footer/footer.scss
- src/js/components/agency/AgencyContent.jsx
- src/js/components/agency/footer/AgencyFooter.jsx
- src/js/containers/agency/AgencyFooterContainer.jsx
* Adds the Let's Go button
* Clicking Let's Go takes you to the search page, but with all filters nuked
> Agency Page Footer

- src/js/components/search/filters/budgetCategory/SelectedFederalAccounts.jsx
- src/js/components/search/topFilterBar/filterGroups/BudgetCategoryFilterGroup.jsx
- src/js/containers/search/filters/budgetCategory/BudgetCategoryAccountContainer.jsx
- src/js/helpers/budgetCategoryHelper.js
- tests/containers/search/filters/budgetCategory/BudgetCategoryAccountContainer-test.jsx
- tests/helpers/budgetCategoryHelper-test.js
- Allow user to perform a full-text search on a combination of the three individual fields listed in the placeholder (agency ID, main account code, and account title)
> Update Federal Account Autocomplete Endpoint

- src/js/components/homepage/visualizations/treemap/BudgetSubfunctions/BudgetSubfunctions.jsx
- src/js/components/homepage/visualizations/treemap/BudgetSubfunctions/BudgetSubfunctionsDescription.jsx
Some Budget Subfunction totals are negative due to being income, not spending, which produces Treemaps with percentages that add up to over 100%.
- Add note to the Budget Function description if the Budget Function's positive subfunctions sum to more than 100% of its net total (currently Net Interest, International Affairs, and General Government).
> Budget Function Description Note (DS-1425)

- src/_scss/pages/search/searchSidebar.scss
- src/js/components/account/SearchSidebar.jsx
* Fixes the federal account filter sidebar
* Fixes longstanding "Filter by" alignment issue on IE
> Fix: Fix federal account filter bar style

- src/_scss/pages/agency/visualizations/federalAccount/federalAccount.scss
- src/_scss/pages/agency/visualizations/visualizations.scss
- src/js/components/agency/AgencyContent.jsx
- src/js/components/agency/visualizations/federalAccount/FederalAccountChart.jsx
- src/js/components/agency/visualizations/federalAccount/FederalAccountTooltip.jsx
- src/js/components/agency/visualizations/federalAccount/FederalAccountVisualization.jsx
- src/js/components/agency/visualizations/recipient/RecipientChart.jsx
- src/js/components/search/visualizations/rank/chart/HorizontalChart.jsx
- src/js/containers/agency/visualizations/FederalAccountContainer.jsx
- src/js/helpers/agencyHelper.js
- src/js/models/agency/AgencyOverviewModel.js
- tests/containers/agency/visualizations/FederalAccountContainer-test.jsx
- tests/containers/agency/visualizations/mocks/mockFederalAccount.js
* Implements federal account visualization on agency page
* Federal accounts link to their federal account detail page
* Shows only top 10
> Federal Account visualization on Agency page

- src/js/components/award/RecipientAddress.jsx
* Fixes Award page address bug that prevented individual award pages from rendering
> Hotfix: Temporary award address fix

- src/js/dataMapping/search/filterFields.js
- src/js/models/account/queries/queryBuilders/ObjectClassQuery.js
- src/js/models/search/SearchAccountAwardsOperation.js
- src/js/models/search/SearchOperation.js
- src/js/models/search/SearchTASCategoriesOperation.js
- src/js/models/search/queryBuilders/AgencyQuery.js
- User selections of Budget Function, Federal Account, and Object Class filters will be reflected in the Awards table
> Fix - Use Budget Category Filters in Awards Table Results

- src/_scss/layouts/default/header/nav/_lowerMenu.scss
- src/_scss/layouts/default/header/nav/_menuItem.scss
- src/_scss/layouts/default/header/nav/_profileMenu.scss
- src/js/components/sharedComponents/header/NavBar.jsx
- src/js/components/sharedComponents/header/ProfileButton.jsx
* Added Profiles dropdown and updated menu items
> Updated Site Navigation

- src/index.html
- webpack/plugins/git-hash-plugin.js
- webpack/webpack.common.js
* Reveals the git commit that the current frontend build is based on in an automatically-generated HTML comment via a custom Webpack plugin
> Expose Webpack Commit Hash

- src/js/components/award/RecipientAddress.jsx
- src/js/components/award/contract/ContractDetails.jsx
- Updating fields in Address component to map correctly so all display
- Updating default value of cityState in PoP to an empty string rather than null
> Individual Award Address Fix

- src/_scss/elements/_titleSelector.scss
- src/_scss/layouts/default/header/nav/_profileMenu.scss
- src/_scss/pages/about/mastHead.scss
- src/_scss/pages/award/table/detailsTable.scss
> Hotfix: IE Fixes

- src/_scss/pages/search/filters/otherFilters/otherFilters.scss
Update to text size and margins in CFDA, PSC and NAICS filters to bring them in line with other filters
> Text Fix in New Filters

- src/js/components/agency/overview/AgencyOverview.jsx
- src/js/components/agency/visualizations/obligated/ObligatedVisualization.jsx
Changed `budget authority` to `budgetary resources`
> Update wording on the agency profile page

- src/_scss/pages/search/searchPage.scss
- src/js/components/search/SearchPage.jsx
- src/js/components/search/SearchResults.jsx
- src/js/containers/search/SearchContainer.jsx
- src/js/helpers/searchHelper.js
- tests/containers/search/SearchContainer-test.jsx
- tests/containers/search/filters/searchHelper.js
* Adds last update date to search results page
> Show last update date

- src/_scss/custom.scss
- src/_scss/pages/errorPage/errorPage.scss
- src/js/components/errorPage/ErrorPage.jsx
- src/js/containers/router/Router.js
- src/js/containers/router/RouterRoutes.jsx
- src/js/helpers/metaTagHelper.js
* Someone will design something cooler eventually
> Temporary 404 Page

- src/js/components/award/details/DetailsSection.jsx
- src/js/components/award/subawards/SubawardsTable.jsx
Sample award with subawards: 1057929
> Re-enable Subawards

- src/js/components/agency/AgencyContent.jsx
- src/js/components/agency/visualizations/obligated/ObligatedVisualization.jsx
- src/js/containers/agency/visualizations/ObligatedContainer.jsx
- tests/containers/agency/visualizations/ObligatedContainer-test.jsx
- "As of" date under the Obligated Amount visualization should match the date in the Overview section
- Obligated values are displayed with 1 decimal point precision
> Fix agency obligated date

- src/js/components/award/RecipientInfo.jsx
- Link to collapse the list of business types now reads "See fewer"
> Change less to fewer

- src/js/components/award/details/DetailsSection.jsx
* Subawards aren't ready, so taking them out again
> Fix: Remove Subawards (again)

- src/js/containers/search/SearchContainer.jsx
> Hide last updated date

- src/js/dataMapping/search/filterFields.js
- src/js/models/search/SearchTASCategoriesOperation.js
- src/js/models/search/queryBuilders/AgencyQuery.js
> Hotfix: FREC on v1/tas/categories endpoints

- src/_scss/layouts/default/header/nav/_menuItem.scss
- src/_scss/layouts/default/header/nav/_profileMenu.scss
- src/js/components/homepage/SearchSection.jsx
- src/js/components/sharedComponents/header/NavBar.jsx
- src/js/components/sharedComponents/header/ProfileButton.jsx
* Nav reshuffle
* Homepage reshuffle
> More homepage updates

- src/js/models/search/SearchAwardsOperation.js
* Time period should always be inside an array
> Hotfix: Date Range v2 API integration

- src/js/components/search/visualizations/rank/chart/ChartGroup.jsx
* This will enable opening links in new tabs on most browsers
> Use SVG-compliant links in visualizations

- src/js/components/search/filters/contractFilters/ContractFilter.jsx
- src/js/components/search/topFilterBar/filterGroups/ExtentCompetedFilterGroup.jsx
- src/js/components/search/topFilterBar/filterGroups/PricingTypeFilterGroup.jsx
- src/js/components/search/topFilterBar/filterGroups/SetAsideFilterGroup.jsx
- src/js/containers/router/Router.js
- src/js/containers/router/RouterContainer.jsx
- src/js/containers/router/RouterRoutes.jsx
- src/js/containers/search/filters/ExtentCompetedContainer.jsx
- src/js/containers/search/filters/PricingTypeContainer.jsx
- src/js/containers/search/filters/SetAsideContainer.jsx
- src/js/containers/search/filters/TimePeriodContainer.jsx
- src/js/containers/search/filters/location/LocationListContainer.jsx
- src/js/redux/reducers/records/recordReducer.js
- tests/containers/router/Router-test.js
- tests/containers/router/RouterContainer-test.jsx
- tests/containers/router/mockRouter.js
- tests/containers/router/mockRoutes.js
- tests/containers/search/filters/TimePeriodContainer-test.jsx
- tests/containers/search/filters/fiscalYearHelper.js
- tests/containers/search/filters/location/LocationListContainer-test.jsx
- tests/containers/search/filters/location/mockLocations.js
- tests/containers/search/filters/mockTimePeriod.js
- tests/redux/reducers/records/recordReducer-test.js
- tests/redux/reducers/search/cfdaReducer-test.js
- tests/redux/reducers/search/naicsReducer-test.js
- tests/redux/reducers/search/pscReducer-test.js
* Removed deprecated `React.PropTypes` from contract filters
* Added tests for containers and reducers that were missing them
> Increase test coverage

- src/js/components/sharedComponents/Footer.jsx
Adding to dev-stable, to be merged up through staging and prod before Tuesday 9/26
> Hotfix - Analytics Link

- src/_scss/pages/agency/visualizations/federalAccount/federalAccount.scss
- src/js/components/agency/overview/AgencyOverview.jsx
- src/js/components/agency/visualizations/federalAccount/FederalAccountChart.jsx
- src/js/components/agency/visualizations/federalAccount/FederalAccountVisualization.jsx
- src/js/containers/agency/visualizations/FederalAccountContainer.jsx
- src/js/containers/agency/visualizations/RecipientContainer.jsx
- src/js/containers/agencyLanding/AgencyLandingContainer.jsx
- tests/containers/agency/agencyHelper.js
- tests/containers/agency/visualizations/FederalAccountContainer-test.jsx
- tests/containers/agency/visualizations/ObjectClassContainer-test.jsx
- tests/containers/agency/visualizations/ObligatedContainer-test.jsx
- tests/containers/agency/visualizations/mocks/mockObligatedAmounts.js
- tests/containers/agencyLanding/mockToptierAgencies.js
Resolve merge conflicts in #429
> Resolve Merge Conflict: Dev-Stable to Dev

- src/js/containers/account/awards/AccountAwardsHeaderCellContainer.jsx
- src/js/containers/agencyLanding/table/AgencyLandingHeaderCellContainer.jsx
- src/js/containers/search/filters/AwardTypeContainer.jsx
- src/js/containers/search/filters/location/LocationSearchContainer.jsx
- tests/containers/account/awards/AccountAwardsHeaderCellContainer-test.jsx
- tests/containers/agency/AgencyFooterContainer-test.jsx
- tests/containers/agency/agencyHelper.js
- tests/containers/agency/mockAgency.js
- tests/containers/agencyLanding/AgencyLandingHeaderCellContainer-test.jsx
- tests/containers/search/filters/AwardTypeContainer-test.jsx
- tests/containers/search/filters/location/LocationSearchContainer-test.jsx
- AccountAwardsHeaderCellContainer
- AgencyFooterContainer
- AgencyLandingHeaderCellContainer
- AwardTypeContainer
- LocationSearchContainer
> Writing new tests for:

- src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
- src/js/components/explorer/detail/visualization/toolbar/BreakdownDropdown.jsx
- Keeps higher-level dropdown options available when changing the subdivision type and not applying a filter
- Fixes the dropdown alignment
> Spending Explorer Dropdown Updates

- src/js/components/search/SearchPage.jsx
- src/js/components/search/SearchResults.jsx
- src/js/components/search/mobile/MobileFilters.jsx
* Search filters work again on mobile
> Hotfix: Restore mobile filter functionality

- src/_scss/pages/agency/agencyPage.scss
- src/js/components/agency/AgencyContent.jsx
- src/js/components/agency/TreasuryDisclaimer.jsx
- src/js/containers/agency/AgencyContainer.jsx
* Adds a disclaimer to the Treasury agency page (and only the Treasury agency page)
**Going into dev-stable!**
> Disclaimer for Treasury

- src/js/components/sharedComponents/Footer.jsx
> Hotfix: Data Lab

- src/_scss/pages/agencyLanding/table/table.scss
- src/js/components/agencyLanding/table/TableRow.jsx
- src/js/components/agencyLanding/table/cells/AgencyLinkCell.jsx
- src/js/components/explorer/detail/header/DetailHeader.jsx
* Disables Department of Transportation agency links on agency landing page and spending explorer
* 🚚
> Hotfix: Disable Department of Transportation

- src/js/components/homepage/HomepageProfileItem.jsx
- src/js/components/homepage/SearchSection.jsx
- src/js/components/sharedComponents/header/ProfileButton.jsx
- src/js/components/sharedComponents/header/ProfileItem.jsx
- src/js/components/sharedComponents/header/mobile/MobileProfiles.jsx
- src/js/dataMapping/profiles/availableProfiles.js
* Profiles can be enabled and disabled site-wide from a single file
* Going into dev-stable in case more flip flops occur
> Centralize profile management

- src/js/components/account/AccountHeader.jsx
- src/js/components/agency/footer/AgencyFooter.jsx
- src/js/components/agency/header/AgencyHeader.jsx
- src/js/components/award/SummaryBar.jsx
* Refer to detail pages as profiles and award search as award search
https://federal-spending-transparency.atlassian.net/browse/DS-1686
> Consistent feature naming

- src/js/components/homepage/HomepageProfileItem.jsx
- src/js/components/homepage/SearchSection.jsx
- src/js/components/sharedComponents/header/ProfileButton.jsx
- src/js/components/sharedComponents/header/ProfileItem.jsx
- src/js/components/sharedComponents/header/mobile/MobileProfiles.jsx
- src/js/dataMapping/profiles/availableProfiles.js
> Demote dev stable to dev

- src/_scss/layouts/default/header/nav/_primaryMenu.scss
- src/_scss/layouts/default/header/nav/_profileMenu.scss
- src/_scss/layouts/search/header/_downloadButton.scss
- src/_scss/layouts/search/header/_formatItem.scss
- src/_scss/layouts/search/header/_options.scss
- src/js/components/search/header/DownloadButton.jsx
- src/js/components/search/header/NoDownloadHover.jsx
- src/js/components/sharedComponents/header/ProfileButton.jsx
* Adds a hover tooltip to explain why download is not available when there are more than 500,000 rows
* Adds an exclamation icon to the download button when it is not available
> Explain Why Download is Disabled

- src/js/containers/search/filters/TimePeriodContainer.jsx
- src/js/redux/reducers/search/searchFiltersReducer.js
- tests/redux/reducers/search/mockFiscalYearHelper.js
- tests/redux/reducers/search/searchFiltersReducer-test.js
**DIRECT TO PROD**
* Enables FY 18 time period filter option on Award Search page
* Updates relevant tests to pass
> Special Hotfix: Enable fy18

- src/js/components/about/NextSteps.jsx
- src/js/components/sharedComponents/Footer.jsx
https://federal-spending-transparency.atlassian.net/browse/PUB-726
> Updated FAQ and Community links

- src/_scss/pages/bulkDownload/archivePage.scss
- src/data/archive.json
- src/js/components/bulkDownload/BulkDownloadPage.jsx
- src/js/components/bulkDownload/archive/ArchivePage.jsx
- src/js/components/bulkDownload/archive/ArchiveTable.jsx
- src/js/components/bulkDownload/archive/ArchiveTableRow.jsx
- src/js/containers/router/RouterRoutes.jsx
- src/js/helpers/archiveHelper.js
** Merges into #506 **
* Implements the archive download page
https://federal-spending-transparency.atlassian.net/browse/DS-1904
> Archive download page

- src/js/components/award/details/additional/ContractAdditionalDetails.jsx
- src/js/dataMapping/contracts/additionalDetails.js
- src/js/models/results/award/AwardSummary.js
https://federal-spending-transparency.atlassian.net/browse/DS-1923
> Handle null executive compensation

- src/_scss/layouts/search/header/_downloadButton.scss
- src/js/components/search/header/DownloadButton.jsx
- src/js/components/search/header/NoDownloadHover.jsx
- src/js/components/sharedComponents/Footer.jsx
** Do not merge until #506 is merged **
* Adds link to bulk download in site footer
* Adds link to bulk download in hover message that appears when the baby download button is disabled
https://federal-spending-transparency.atlassian.net/browse/DS-1913
> Links to Bulk Download

- src/js/components/agencyLanding/table/TableRow.jsx
- src/js/components/agencyLanding/table/cells/AgencyLinkCell.jsx
- src/js/components/explorer/detail/header/DetailHeader.jsx
- Enables DOT Agency Page link from Spending Explorer and Agency Landing Page
> Hottest Fix - DOT Agency Page

- src/_scss/pages/bulkDownload/form/_agencyPicker.scss
- src/_scss/pages/search/filters/location/_dropdown.scss
- src/js/components/bulkDownload/awards/AwardDataContent.jsx
- src/js/components/bulkDownload/awards/UserSelections.jsx
- src/js/components/bulkDownload/awards/filters/AgencyFilter.jsx
- src/js/containers/bulkDownload/awards/AwardDataContainer.jsx
- Added headings for CFO Agencies & Other Agencies
- Updated list styling and reduced padding
> Update Bulk Download Agencies List

- src/_scss/layouts/landingPage/landingPage.scss
- Addresses Bug [DS-1881](https://federal-spending-transparency.atlassian.net/browse/DS-1881)
> Center agency landing header

- src/js/components/award/financialAssistance/FinancialAssistanceDetails.jsx
- Surfaces CFDA Number and CFDA Program Title
Bug: https://federal-spending-transparency.atlassian.net/browse/DS-1950
Test with Award ID 42058820
> Bug Fix - Surface CFDA Data on Grants page

- src/js/components/award/contract/ContractDetails.jsx
- src/js/components/award/financialAssistance/FinancialAssistanceDetails.jsx
Bug: https://federal-spending-transparency.atlassian.net/browse/DS-1880 part (3)
Test Award ID: 9351690
> Fix - Show Period of Performance in Financial Assistance Details

- src/js/components/search/table/ResultsTableSection.jsx
* Removes the hidden column picker from the award search table
* Picker *either* this PR or fedspendingtransparency/usaspending-website#540
> Performance Option: Remove all hidden columns

- src/js/components/bulkDownload/awards/filters/AgencyFilter.jsx
- Specifies `awarding` agency on the bulk download page
> Hotfix Bulk Download Agency Filter Title

- src/js/components/search/SearchResults.jsx
- src/js/components/search/header/SearchHeader.jsx
* Removes spending by category
> Remove rank visualization

- src/js/components/about/DataSources.jsx
* `hundreds of federal agencies` is now `more than a hundred federal agencies`
> About Page Text Change

- src/_scss/pages/search/results/visualizations/geo/_message.scss
- src/_scss/pages/search/results/visualizations/geo/geoVisualization.scss
- src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
- src/js/components/search/visualizations/geo/MapMessage.jsx
- src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
Award search map shows messages for loading, no results, and errors.
> Add loading messages to map

- src/js/containers/search/filters/cfda/CFDAListContainer.jsx
* Use a placeholder that has results
> Change CFDA placeholder text

- src/_scss/pages/search/results/visualizations/geo/_message.scss
- src/js/components/search/visualizations/geo/MapMessage.jsx
* Move loading message to center of the map
> Center map loading message

- src/_scss/pages/search/_filterExpand.scss
- src/_scss/pages/search/filters/keyword/_keywordHover.scss
- src/js/components/search/SearchSidebar.jsx
- src/js/components/search/filters/keyword/KeywordHover.jsx
- src/js/components/sharedComponents/filterSidebar/FilterExpandButton.jsx
- src/js/components/sharedComponents/filterSidebar/FilterOption.jsx
- src/js/components/sharedComponents/filterSidebar/FilterSidebar.jsx
- Shows a message when a user hovers over the information icon with a mouse
- Shows a message when a user taps on the information icon on mobile
- Sets up an internal data model that will reduce the effort in adding additional hover tooltips to other filters in the future
https://federal-spending-transparency.atlassian.net/browse/DS-1967
> Keyword Hover Tooltip

- src/js/containers/search/filters/AgencyListContainer.jsx
Bug: https://federal-spending-transparency.atlassian.net/browse/DS-1708
> Fix - Allow Users to Search for Agencies by Agency Abbreviation

- src/_scss/pages/homepage/visualizations/geo/mapSection.scss
- src/_scss/pages/search/results/visualizations/geo/map/_legend.scss
- src/js/components/search/visualizations/geo/map/MapBox.jsx
* Adds OpenStreetMaps full attribution to Mapbox
* Adjusts positioning of legend box so it doesn't cover attribution on smaller screens
> Hotfix: OSM Full Attribution

- src/js/components/bulkDownload/modal/ModalContent.jsx
* Changed bulk download modal message
> Update: Bulk Download Message

- src/js/models/search/SearchAwardsOperation.js
https://federal-spending-transparency.atlassian.net/browse/DS-2044
> Special handling of "all foreign" location

- src/_scss/pages/bulkDownload/_archiveInfoBox.scss
- src/js/components/bulkDownload/archive/table/TableRow.jsx
- src/js/containers/bulkDownload/archive/AwardDataArchiveContainer.jsx
- tests/containers/bulkDownload/archive/AwardDataArchiveContainer-test.jsx
* Re-enable monthly download link
* File download URLs now point to the correct location
> Fix: Re-enable monthly download link

- src/_scss/pages/modals/bulkDownload/bulkDownload.scss
- src/_scss/pages/modals/fullDownload/fullDownload.scss
https://federal-spending-transparency.atlassian.net/browse/DS-2054
Fixing missed design components for award search modal
- Increase award search modal width
- Increase padding around the modal
> Hotfix Feature download experience

- src/js/containers/search/table/ResultsTableContainer.jsx
- Logs the page number by award type when users scroll to a new page of results
> Award Table Analytics 

- src/js/components/search/SearchSidebarSubmit.jsx
- src/js/containers/search/SearchSidebarSubmitContainer.jsx
- src/js/redux/actions/search/appliedFilterActions.js
- tests/containers/search/SearchSidebarSubmitContainer-test.jsx
- tests/containers/search/mockSubmit.js
* Changes label on "Reset filters" button to "Reset search"
* Reset search button automatically applies cleared filters to current award search page
* Mild fix: merge first to dev-stable, then promote to staging (but not prod until normal deploy)
> Mild Fix: Reset Search button

- src/js/components/about/DataQuality.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-50
- Rename all Q2, Q3, and Q4 DATA Act ".yml" files to “Quarterly Assurance Statement” from Agency_Qualification_Statement. Please keep the same naming construct, just replace 'Agency Qualification Statement' with 'Quarterly Assurance Statement'. (e.g., currently, the files are named "2017 / Q2 / 005 - Government Accountability Office (GAO) / 2017-Q2-005_Government Accountability Office (GAO)-Quarterly_Assurance_Statement.txt")
- Update text on "About Page" to the following: "For more information about the data, see the FAQs and the Data Dictionary. The federal agencies' raw quarterly submission files, including Quarterly Assurance Statements about the data, are available here.
> DEV-50 Update raw broker files naming

- src/js/components/sharedComponents/IBTable/components/Table.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-107
- Increasing row height padding onto bottom when there is only one row so that the horizontal scroll bar doesnt cover it up
> adding padding to keep data from being blocked

- src/js/components/bulkDownload/awards/filters/dateRange/TimePeriodButtons.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-289
> Fix Bulk Download Missing FY 2013

- src/_scss/pages/homepage2/features/_carousel.scss
- src/_scss/pages/homepage2/features/_dropdown.scss
- src/_scss/pages/homepage2/features/_profile.scss
- src/_scss/pages/homepage2/features/_search.scss
- src/_scss/pages/homepage2/features/_spendingExplorer.scss
- src/_scss/pages/homepage2/features/features.scss
- src/_scss/pages/homepage2/hero/_heroButton.scss
- src/_scss/pages/homepage2/hero/hero.scss
- src/js/components/homepage2/features/FeatureDropdown.jsx
- src/js/components/homepage2/features/Features.jsx
- src/js/components/homepage2/features/ImageCarousel.jsx
- src/js/components/homepage2/features/ProfileFeature.jsx
- src/js/components/homepage2/features/SearchFeature.jsx
- src/js/components/homepage2/features/SpendingExplorerFeature.jsx
- src/js/components/homepage2/hero/Hero.jsx
- src/js/components/homepage2/hero/HeroButton.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-331
* Move new home page (except for site header, which is shared across the site so may run into problems) to BEM CSS architecture
> New Homepage: Phase 3.5 - BEM it like Beckham

- src/js/components/award/table/FinancialSystemTable.jsx
- src/js/components/award/table/TransactionsTable.jsx
- src/js/containers/award/table/FinancialSystemTableContainer.jsx
- Fix infinite scrolling issue in Financial System Details tab on Award page by passing the auto-loading function via the correct prop name
Bug: https://federal-spending-transparency.atlassian.net/browse/DEV-354
Test with Award ID 454614.
> Fix - Infinite Scroll in Financial Systems Details tab

- src/_scss/pages/keyword/header/header.scss
- src/js/components/keyword/KeywordPage.jsx
- src/js/components/keyword/header/KeywordHeader.jsx
- src/js/containers/keyword/KeywordContainer.jsx
- src/js/helpers/bulkDownloadHelper.js
- tests/containers/keyword/KeywordContainer-test.jsx
- tests/containers/keyword/mockResults.js
- tests/containers/keyword/table/ResultsTableContainer-test.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-330
- Adds a download button to the Keyword search page that is disabled before a keyword is entered and when there are more than 500,000 results
- Clicking the download button opens a modal that starts the download and shows the URL that the download file will be available at
- Uses shared bottom download bar UI as other download features on the site
> Feature keyword download

- src/_scss/pages/keyword/_searchBar.scss
- src/_scss/pages/keyword/table/resultsTable.scss
- src/js/components/keyword/KeywordSearchBar.jsx
https://projects.invisionapp.com/share/BQFM79K429H#/screens
- Adds a blue background to the keyword search bar
- Updates the icon and border colors 
- Adds title text to indicate the three character minimum
> Update Keyword Search Bar Styling

- src/js/components/award/AwardInfoBar.jsx
- src/js/components/award/RecipientInfo.jsx
* Fixes a bug where the recipient info bar was only coded to handle either 0 or >2 business types
* Reduces complexity of `buildSnippets` by separating responsibility to individual functions
> Fix: More recipient business type fixes

- src/js/components/award/AwardInfoBar.jsx
- src/js/components/award/RecipientInfo.jsx
> Demote business type hotfix to dev

- src/_scss/pages/keyword/_searchBar.scss
- src/_scss/pages/keyword/keywordPage.scss
- src/js/components/keyword/KeywordPage.jsx
- src/js/components/keyword/KeywordSearchBar.jsx
- src/js/components/keyword/table/ResultsTableSection.jsx
- Adds more space between the search bar and results section
- Converts the search bar to BEM classes
> Fix Keyword Search Padding

- src/js/components/about/DBInfo.jsx
- src/js/containers/router/RouterRoutes.jsx
* Restores "very important D&B information" that you must click here for.
> Restore D&B info page

- src/js/components/about/AboutContent.jsx
- src/js/components/about/DataQuality.jsx
- src/js/components/about/MoreInfo.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-377
* Adds a sentence to Data Quality
* Adds a new More Information section with more information
> About Page Content Update

- src/js/components/keyword/KeywordPage.jsx
- src/js/components/keyword/header/KeywordHeader.jsx
* Disable keyword download for sprint 57
> Hotfix: Disable keyword download

- src/js/components/account/awards/LegacyResultsTable.jsx
- src/js/models/v2/BaseFederalAccountAwardRow.js
* Fixes a bug where the federal account page award table's body cell render function did not use the correct column property to identify Award ID columns
* Updates the Federal Account Award model to include PIID/FAIN/URI
> Hotfix: Federal Account Award ID Column

- src/js/containers/accountLanding/AccountLandingContainer.jsx
- tests/containers/accountLanding/AccountLandingContainer-test.jsx
- Reset the page number to 1 when the sort changes
> Fix Account Landing Sort

- src/js/components/bulkDownload/BulkDownloadPage.jsx
- src/js/components/bulkDownload/sidebar/BulkDownloadSidebar.jsx
- src/js/components/bulkDownload/sidebar/SidebarButton.jsx
- src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
- src/js/containers/router/RouterRoutes.jsx
- src/js/dataMapping/navigation/menuOptions.js
- tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
- tests/containers/bulkDownload/mockData.js
- tests/containers/bulkDownload/mockRouter.js
- Changes `bulk_download` and `bulk_download/award_data_archive` to `download_center/custom_award_data` and `download_center/award_data_archive`, respectively
- `/download_center` redirects to `download_center/custom_award_data`
> Update download center urls

- src/_scss/layouts/default/header/_warning.scss
- src/js/components/sharedComponents/header/InfoBanner.jsx
- src/js/components/sharedComponents/header/WarningBanner.jsx
- Changes the text in the info banner when `IN_BETA = false`
- Converts info banner to BEM classes
> Update banner text

- src/_scss/layouts/default/stickyHeader/header.scss
- src/_scss/pages/account/header/_options.scss
- src/_scss/pages/award/_summaryStatus.scss
- Fixes mobile and tablet views for the updated header bar in the Award and Federal Account Profile pages
Bug: https://federal-spending-transparency.atlassian.net/browse/DEV-530
> Fix - Header Mobile and Tablet Views

- src/_scss/layouts/default/footer/_footerCopyright.scss
- src/_scss/layouts/default/footer/_footerLinks.scss
- src/_scss/layouts/default/footer/_footerLogo.scss
- src/_scss/layouts/default/footer/footer.scss
- src/_scss/pages/about/_section.scss
- src/_scss/pages/about/_sidebar.scss
- src/_scss/pages/about/aboutPage.scss
- src/js/components/about/Background.jsx
- src/js/components/about/Contact.jsx
- src/js/components/about/DataQuality.jsx
- src/js/components/about/DataSources.jsx
- src/js/components/about/Mission.jsx
- src/js/components/about/MoreInfo.jsx
- src/js/components/about/legal/AccessibilityPage.jsx
- src/js/components/about/legal/FOIAPage.jsx
- src/js/components/about/legal/PrivacyPage.jsx
- src/js/components/about/legal/common/LegalContent.jsx
- src/js/components/about/legal/common/LegalContents.jsx
- src/js/components/about/legal/common/LegalPage.jsx
- src/js/components/sharedComponents/Footer.jsx
- src/js/components/sharedComponents/sidebar/Sidebar.jsx
- src/js/containers/router/RouterRoutes.jsx
- Adds links to Privacy Policy, Accessibility, and FOIA pages in the footer 
- Implements Privacy Policy, Accessibility, and FOIA pages
Issue: https://federal-spending-transparency.atlassian.net/browse/DEV-492
> Feature - Legal Disclaimers

- src/js/components/sharedComponents/header/DropdownItem.jsx
- src/js/components/sharedComponents/header/NavBar.jsx
- src/js/components/sharedComponents/header/mobile/MobileDropdownItem.jsx
- src/js/components/sharedComponents/header/mobile/MobileNav.jsx
- src/js/components/sharedComponents/header/mobile/MobileTop.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-531
- Adds a Google Analytics event for when users click a link in the header (desktop or mobile)
> Feature Header Analytics

- src/_scss/pages/homepage/download/_detail.scss
- src/_scss/pages/homepage/download/download.scss
- src/js/components/homepage/download/DesktopButton.jsx
- src/js/components/homepage/download/DownloadDetail.jsx
- src/js/dataMapping/navigation/menuOptions.js
- Enables Custom Account Data button functionality on Homepage
- Changes Call To Action of Custom Account Data Download view to "Coming Soon"
Bug: https://federal-spending-transparency.atlassian.net/browse/DEV-527
Mock: https://bahdigital.invisionapp.com/d/main/#/console/8586929/273832670/preview
> Enable Custom Account Data Button with "Coming Soon" Status

- src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
- src/js/components/search/visualizations/geo/GeoVisualizationTooltip.jsx
- src/js/components/search/visualizations/time/TimeVisualizationTooltip.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-551
* Advanced Search Time and Map visualization tooltips have been relabelled to indicate they are obligations
* Spending Explorer treemap disclaimer has been updated to indicate amounts are reported by agencies
> Update copy language for precision

- LICENSE.md
> Feature - LICENSE.md

- src/js/dataMapping/financialAssistance/assistanceActionTypes.js
- src/js/models/results/transactions/AssistanceTransaction.js
- src/js/models/results/transactions/LoanTransaction.js
* Implements a frontend mapping to display transaction action types and their descriptions in the award profile table for financial assistance awards.
> Financial Assistance Transaction Action Type

- src/js/containers/account/awards/AccountAwardsContainer.jsx
- src/js/dataMapping/search/accountTableSearchFields.js
- src/js/models/v2/BaseFederalAccountAwardRow.js
> Fix loan values

- src/js/components/about/DataQuality.jsx
- src/js/components/about/DataSources.jsx
- Updates made per Track Changes in [about page.docx](https://github.com/fedspendingtransparency/usaspending-website/files/1775912/about.page.docx)
> About Page Content Updates

- src/js/dataMapping/search/accountTableSearchFields.js
- src/js/models/v2/BaseFederalAccountAwardRow.js
Test with Staging API and Federal Account 2060
> Updating Loan Fields on Federal Account Awards Table

- src/js/dataMapping/search/accountTableSearchFields.js
- src/js/models/v2/BaseFederalAccountAwardRow.js
- Update date field
- Update subsidy cost field
- Update default sort field
Test with Staging API and Federal Account 2060
> Update Loan Fields for Federal Account Award Table

- src/_scss/pages/homepage/download/_mobileLinks.scss
- src/js/components/homepage/community/Community.jsx
- src/js/components/homepage/download/DownloadDetail.jsx
- src/js/components/homepage/download/MobileLinkItem.jsx
- src/js/components/homepage/features/FeatureDropdown.jsx
- src/js/components/homepage/features/SpendingExplorerFeature.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
- Adds analytics to banner & homepage links
- Trigger the redirect modal for external link in tablet-view of the homepage download section
> Feature banner analytics

- src/js/components/explorer/detail/sidebar/ExplorerSidebar.jsx
- Adds a 10-second-delayed Analytics event in the Spending Explorer when the user changes either the Fiscal Year or Quarter selection
Issue: https://federal-spending-transparency.atlassian.net/browse/DEV-583
> Spending Explorer Time Period Analytics

- src/_scss/pages/agency/visualizations/_obligated.scss
- src/_scss/pages/bulkDownload/form/_userSelections.scss
- src/_scss/pages/bulkDownload/form/downloadForm.scss
- src/_scss/pages/bulkDownload/sidebar/sidebar.scss
- src/_scss/pages/explorer/detail/header/header.scss
- src/_scss/pages/explorer/detail/sidebar/_quarter.scss
- src/_scss/pages/explorer/detail/sidebar/_trail.scss
- src/_scss/pages/explorer/landing/_option.scss
- src/_scss/pages/search/_submitHint.scss
- src/js/components/agency/visualizations/obligated/ObligatedGraph.jsx
- src/js/components/agency/visualizations/obligated/ObligatedVisualization.jsx
- src/js/components/bulkDownload/awards/filters/AgencyFilter.jsx
- src/js/components/bulkDownload/awards/filters/AwardLevelFilter.jsx
- src/js/components/bulkDownload/awards/filters/AwardTypeFilter.jsx
- src/js/components/bulkDownload/awards/filters/DateTypeFilter.jsx
- src/js/components/bulkDownload/awards/filters/FileFormatFilter.jsx
- src/js/components/bulkDownload/awards/filters/dateRange/TimePeriodFilter.jsx
- src/js/components/bulkDownload/sidebar/SidebarButton.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-567
https://federal-spending-transparency.atlassian.net/browse/DEV-569
https://federal-spending-transparency.atlassian.net/browse/DEV-571
https://federal-spending-transparency.atlassian.net/browse/DEV-574
https://federal-spending-transparency.atlassian.net/browse/DEV-575
https://federal-spending-transparency.atlassian.net/browse/DEV-599
* Updates color contrast on the download sidebar and validation icons
* Updates color contrast and adds gap in agency obligation visualization
* Updates color contrast for advanced search submit hints
* Updates color contrast on Spending Explorer header text with bolder totals
* Updates color contrast on Spending Explorer quarter selector
* Updates color contrast on Spending Explorer landing …
> Update: 508 Color Contrast Improvements

- src/js/components/search/SearchSidebar.jsx
- src/js/components/search/filters/keyword/Keyword.jsx
- src/js/components/search/filters/keyword/KeywordHover.jsx
- src/js/components/search/topFilterBar/filterGroups/KeywordFilterGroup.jsx
- src/js/components/search/topFilterBar/filterGroups/TopFilterGroupGenerator.jsx
- src/js/containers/search/filters/KeywordContainer.jsx
- src/js/containers/search/helpers/searchAnalytics.js
- src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
- src/js/dataMapping/search/awardsOperationKeys.js
- src/js/dataMapping/search/filterFields.js
- src/js/models/search/SearchAwardsOperation.js
- src/js/redux/actions/search/searchFilterActions.js
- src/js/redux/reducers/search/searchFiltersReducer.js
- tests/containers/search/filters/keyword/KeywordContainer-test.jsx
- tests/containers/search/helpers/searchAnalytics-test.js
- tests/containers/search/mockSearchHashes.js
- tests/containers/search/topFilterBar/TopFilterBarContainer-test.jsx
* Restores advanced search keyword filter
* Restores top filter bar handling for keyword
* Restores associated tests
> Restore advanced search keyword filter

- src/_scss/pages/search/filters/keyword/_keywordHover.scss
- src/js/components/search/filters/keyword/KeywordHover.jsx
* Award Descriptions are now included
> Update Advanced Search Keyword Hover

- src/_scss/layouts/default/header/_officialSite.scss
- src/_scss/layouts/default/header/nav/headerNav.scss
- src/js/components/about/MoreInfo.jsx
- src/js/components/sharedComponents/Footer.jsx
- src/js/components/sharedComponents/header/Header.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
* Remove reference to legacy in banner
* Implement universal header design
* Updated about page link to Competition in Contracting Data Lab visualization
* Updated Data Lab link URL in footer
> Update: Universal Header

- src/_scss/pages/award/_loanDetails.scss
- src/js/components/award/AwardAmounts.jsx
- src/js/components/award/LoanAmounts.jsx
* Refactor loan amounts Sass to BEM
* Hide "of face value" when percentage is hidden
* Fix recipient name in narrative to be capitalized
> More loan amounts UI fixes

- src/js/components/search/filters/recipient/RecipientType.jsx
- src/js/dataMapping/search/recipientType.js
* Updates the recipient types filter values on the Advanced Search page to new values used by the backend
> Updated Recipient Types List

- src/_scss/layouts/default/stickyHeader/header.scss
- src/_scss/pages/explorer/detail/explorerDetail.scss
- src/_scss/pages/explorer/detail/header/header.scss
- src/_scss/pages/explorer/detail/sidebar/sidebar.scss
- src/_scss/pages/explorer/detail/visualization/_breakdown.scss
- src/_scss/pages/explorer/detail/visualization/_menu.scss
- src/_scss/pages/explorer/detail/visualization/table/_table.scss
- src/_scss/pages/explorer/detail/visualization/treemap/_treemap.scss
- src/_scss/pages/explorer/detail/visualization/visualization.scss
- src/_scss/pages/search/mobile/mobileFilterButton.scss
- src/js/components/explorer/detail/header/DetailHeader.jsx
- src/js/components/explorer/detail/header/RootHeader.jsx
- src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
- src/js/components/explorer/detail/visualization/toolbar/BreakdownDropdown.jsx
- src/js/components/explorer/detail/visualization/toolbar/DropdownItem.jsx
- src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-521
* Fix spending explorer treemap resizing on Internet Explorer
* Fix spending explorer title text wrapping on Internet Explorer
* Fix title bar text alignment on Internet Explorer
> Fix Spending Explorer Resizing on IE

- src/js/components/account/AccountOverview.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-558
* Puts the sankey's FY in its title
> Retitle Federal Account Sankey with FY

- src/_scss/pages/keyword/table/resultsTable.scss
- src/js/components/keyword/table/ResultsTableSection.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-674
> Add keyword table heading

- src/_scss/pages/bulkDownload/_archiveInfoBox.scss
- src/_scss/pages/bulkDownload/bulkDownloadPage.scss
- src/_scss/pages/bulkDownload/downloadData.scss
- src/_scss/pages/bulkDownload/form/_agencyPicker.scss
- src/_scss/pages/bulkDownload/form/_locationFilter.scss
- src/_scss/pages/bulkDownload/form/_tooltip.scss
- src/_scss/pages/bulkDownload/form/_userSelections.scss
- src/_scss/pages/bulkDownload/form/downloadForm.scss
- src/js/components/bulkDownload/BulkDownloadPage.jsx
- src/js/components/bulkDownload/awards/AwardDataContent.jsx
- src/js/components/bulkDownload/awards/DownloadTooltip.jsx
- src/js/components/bulkDownload/awards/SubmitButton.jsx
- src/js/components/bulkDownload/awards/UserSelections.jsx
- src/js/components/bulkDownload/awards/filters/AgencyFilter.jsx
- src/js/components/bulkDownload/awards/filters/AwardLevelFilter.jsx
- src/js/components/bulkDownload/awards/filters/AwardTypeFilter.jsx
- src/js/components/bulkDownload/awards/filters/DateTypeFilter.jsx
- src/js/components/bulkDownload/awards/filters/FileFormatFilter.jsx
- src/js/components/bulkDownload/awards/filters/LocationFilter.jsx
- src/js/components/bulkDownload/awards/filters/dateRange/TimePeriodFilter.jsx
- src/js/components/search/filters/location/EntityDropdown.jsx
- src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
- src/js/containers/bulkDownload/awards/AwardDataContainer.jsx
- src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js
- tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
- tests/containers/bulkDownload/awards/AwardDataContainer-test.jsx
- tests/containers/bulkDownload/mockData.js
https://federal-spending-transparency.atlassian.net/browse/DEV-641
- Implements an optional recipient location filter for Custom Award Data download
- User can filter by United States or All Foreign Countries
- When United States is selected, user can filter by state
- Implements a tooltip for the disabled download button
- Converts download filters to BEM classes
> Download recipient location filter

- src/js/components/award/table/cells/FinSysAccountCell.jsx
- src/js/components/award/table/cells/FinSysGenericCell.jsx
- src/js/components/award/table/cells/TransactionTableGenericCell.jsx
- src/js/components/search/table/cells/ResultsTableFormattedCell.jsx
- src/js/components/sharedComponents/IBTable/components/TableBody.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-664
- Fix table description by adding in HTML title attribute so that it shows up on hover for all browsers.
> Fix Table Description

- package.json
- src/index.html
- Updated Mapbox-GL to version 0.44.2 and changed the CSS link in index.html to match the update.
> Feature Mapbox Update

- src/_scss/pages/homepage/features/_featurePane.scss
- src/_scss/pages/homepage/features/features.scss
- src/js/components/homepage/features/Features.jsx
- src/js/components/homepage/features/PaneFeature.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-826
- Implemented 3 pane layout for featured content.
> Feature Three Pane Layout

- src/js/components/award/subawards/SubawardsTable.jsx
- src/js/components/bulkDownload/awards/AwardDataContent.jsx
- src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
https://federal-spending-transparency.atlassian.net/browse/DEV-895
- Updated Sub-Awards text on various pages to make it appear consistent throughout the site.
> Feature Sub-Awards Text Update

- src/js/components/about/DataQuality.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-936
- Updated text on the about page
> Feature Update Text About Page

- src/js/components/search/filters/awardID/AwardIDSearch.jsx
- src/js/components/search/filters/keyword/Keyword.jsx
- src/js/components/search/filters/keyword/SelectedKeywords.jsx
- src/js/components/search/filters/keyword/ShownKeyword.jsx
- src/js/components/search/filters/recipient/RecipientName.jsx
- src/js/components/search/topFilterBar/filterGroups/KeywordFilterGroup.jsx
- src/js/containers/search/filters/KeywordContainer.jsx
- src/js/containers/search/filters/awardID/AwardIDSearchContainer.jsx
- src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
- src/js/dataMapping/search/awardsOperationKeys.js
- src/js/models/search/SearchAwardsOperation.js
- src/js/redux/actions/search/searchFilterActions.js
- src/js/redux/reducers/search/filters/keywordFilterFunctions.js
- src/js/redux/reducers/search/filters/recipientFilterFunctions.js
- src/js/redux/reducers/search/searchFiltersReducer.js
- tests/containers/search/SearchContainer-test.jsx
- tests/containers/search/filters/awardID/AwardIDSearchContainer-test.jsx
- tests/containers/search/filters/keyword/KeywordContainer-test.jsx
- tests/containers/search/mockSearchHashes.js
- tests/containers/search/topFilterBar/TopFilterBarContainer-test.jsx
- tests/redux/reducers/search/searchFiltersReducer-test.js
- tests/testResources/defaultReduxFilters.js
https://federal-spending-transparency.atlassian.net/browse/DEV-914
- Implemented support for multiple keywords
- Implemented support for multiple recipients
- Implemented support for multiple award ids
> Feature Multiple Recipients, Award IDs, Keyword Filters

- src/_scss/pages/state/_contentWrap.scss
- src/_scss/pages/state/overview/_overview.scss
- src/_scss/pages/state/spendingovertime/_stateTimeVisualization.scss
- src/_scss/pages/state/topFive/_table.scss
- src/_scss/pages/state/topFive/_topFive.scss
- src/js/components/search/visualizations/geo/MapWrapper.jsx
- src/js/components/state/overview/StateOverview.jsx
- src/js/components/state/spendingovertime/StateTimeVisualizationSection.jsx
- src/js/components/state/topFive/TopFiveSection.jsx
- src/js/containers/state/visualizations/geo/GeoVisualizationSectionContainer.jsx
- tests/containers/state/visualizations/geo/GeoVisualizationSectionContainer-test.jsx
- Truncates table text instead of wrapping
- Hides the map legend 
- Resets the map layer to `county` when the state id changes
- Uses consistent header and description styles across the page
> State Profile Page updates

- src/_scss/pages/state/spendingovertime/_stateTimeVisualization.scss
- src/js/components/state/StateFooter.jsx
- src/js/components/stateLanding/StateLandingContent.jsx
- src/js/components/stateLanding/table/StateLandingTable.jsx
- src/js/containers/state/StateTimeVisualizationSectionContainer.jsx
- src/js/helpers/fiscalYearHelper.js
- Displays all fiscal years in the state profile spending over time visualization
- Specifies "State or Territory" on the state profile landing page
> Hotfix state spending over time

- src/js/components/about/Contact.jsx
- src/js/components/about/legal/AccessibilityPage.jsx
- src/js/components/about/legal/PrivacyPage.jsx
- src/js/components/sharedComponents/Footer.jsx
Updates the email address for "Contact Us" links in the following places:
- Site Footer
- Contact section of the About page
- Accessibility page
- Privacy page
> Hotfix contact us

- api_contracts/contracts/spendingExplorer/SpendingExplorer.md
- src/_scss/pages/explorer/detail/_unreportedErrorScreen.scss
- src/_scss/pages/explorer/detail/explorerDetail.scss
- src/_scss/pages/explorer/detail/header/header.scss
- src/_scss/pages/explorer/detail/visualization/visualization.scss
- src/_scss/pages/modals/redirect/redirectModal.scss
- src/js/components/explorer/detail/DetailContent.jsx
- src/js/components/explorer/detail/ExplorerInfoTooltip.jsx
- src/js/components/explorer/detail/UnreportedErrorScreen.jsx
- src/js/components/explorer/detail/header/DetailHeader.jsx
- src/js/components/explorer/detail/header/RootHeader.jsx
- src/js/components/explorer/detail/visualization/ExplorerInfoTooltip.jsx
- src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
- src/js/components/explorer/detail/visualization/table/ExplorerTable.jsx
- src/js/components/explorer/detail/visualization/table/TableRow.jsx
- src/js/components/explorer/detail/visualization/table/cells/LinkCell.jsx
- src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
- src/js/components/explorer/detail/visualization/treemap/TreemapCell.jsx
- src/js/containers/explorer/detail/DetailContentContainer.jsx
- src/js/containers/explorer/detail/table/ExplorerTableContainer.jsx
- src/js/containers/router/RouterRoutes.jsx
- tests/containers/explorer/detail/DetailContentContainer-test.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1062
- Implemented Unreported Data page
- Implemented disclaimer
> Feature Unreported Data Explorer

- api_contracts/contracts/award/AwardProfile.md
> Contract v2 sub-awards & transactions

- src/_scss/pages/state/overview/_overview.scss
https://federal-spending-transparency.atlassian.net/browse/DEV-1131
- Added outline to state profile flags
> Feature Add Outline to State Profile Flags

- src/js/containers/state/StateTimeVisualizationSectionContainer.jsx
- src/js/helpers/fiscalYearHelper.js
Performance improvement for the state profile spending over time visualization. 
- Requests the end date of the current fiscal year instead of today's date
> Update State Spending Over Time

- api_contracts/contracts/state/StateProfile.md
- src/_scss/pages/stateLanding/_table.scss
- src/_scss/pages/stateLanding/stateLandingPage.scss
- src/js/components/stateLanding/table/StateLandingTable.jsx
- src/js/components/stateLanding/table/StateLinkCell.jsx
- src/js/containers/stateLanding/StateLandingContainer.jsx
- src/js/models/v2/state/BaseStateLandingItem.js
- tests/containers/state/mockData.js
- tests/containers/state/mockStateHelper.js
- tests/containers/stateLanding/StateLandingContainer-test.jsx
- tests/containers/stateLanding/mockStateSearch.js
https://federal-spending-transparency.atlassian.net/browse/DEV-1085
- Separates states and territories when sorting by name
- Adds no results messages
- Underlines matched substring of user input
> Update State Landing Page

- src/js/components/sharedComponents/Footer.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1149
- Updates the "Data Model" link in the footer to latest url
> Update Data Model link in footer

- src/_scss/elements/_titleSelector.scss
- src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1187   
- Disabled the Recipient button and added in the coming soon label
> Hotfix Spending by Category Dropdown

- api_contracts/contracts/downloads/CustomAccountDownload.md
- src/_scss/pages/bulkDownload/form/_federalPicker.scss
- src/_scss/pages/bulkDownload/form/_fyPicker.scss
- src/_scss/pages/bulkDownload/form/downloadForm.scss
- src/js/components/bulkDownload/accounts/AccountDataContent.jsx
- src/js/components/bulkDownload/accounts/UserSelections.jsx
- src/js/components/bulkDownload/accounts/filters/AccountLevelFilter.jsx
- src/js/components/bulkDownload/accounts/filters/AgencyFilter.jsx
- src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
- src/js/containers/bulkDownload/accounts/AccountDataContainer.jsx
- src/js/dataMapping/navigation/menuOptions.js
- src/js/helpers/bulkDownloadHelper.js
- src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js
- tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
- tests/containers/bulkDownload/accounts/AccountDataContainer-test.jsx
- tests/containers/bulkDownload/mockBulkDownloadHelper.js
- tests/containers/bulkDownload/mockData.js
https://federal-spending-transparency.atlassian.net/browse/DEV-1155
- Implemented Federal Account Grouping
> Feature Custom Account Filter

- src/js/components/bulkDownload/accounts/AccountDataContent.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1064
- Added in text and link to data dictionary
> Feature Custom Account Dictionary

- src/js/components/stateLanding/table/StateLinkCell.jsx
- tests/containers/state/StateContainer-test.jsx
- tests/containers/state/mockStateHelper.js
- Prevents a console error on the state landing page by correcting a prop type mismatch 
- Also fixes a state container unit test
> Fix state landing prop

- src/js/components/bulkDownload/archive/AwardDataArchiveContent.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1238
- Updated "Award Data Archive" second paragraph of the description to the latest version
> Update Description for Archive and Delta Files

- src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1261
> Hotfix re-enable spending by recipient

- src/js/components/about/DataQuality.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1290
- Updates link for "Federal Government Procurement Data Quality Summary" to latest link.
> Staging - Updated link for "Federal Government Procurement Data Quality Summary" as per hotfix request 

- src/js/dataMapping/navigation/menuOptions.js
- Temporarily reverts the new database download link in prod
> Revert database download link

- package.json
- Updates the a11y eslint plugin to fix an issue that was causing Travis checks to fail
> Update a11y plugin

- src/_scss/pages/explorer/detail/visualization/_breakdown.scss
- src/_scss/pages/explorer/detail/visualization/_dropdownItem.scss
- src/graphics/icons.svg
- src/js/components/explorer/detail/visualization/table/cells/LinkCell.jsx
- src/js/components/explorer/detail/visualization/toolbar/BreakdownDropdown.jsx
- src/js/components/explorer/detail/visualization/toolbar/DropdownItem.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1299
- Calling `parseInt` on a string (recipient's name used for `id`) was creating an invalid API request
- Fixes recipient icon not showing up in the dropdown
- Cleaned up dropdown Sass/ BEM
> Fix explorer table recipient links

- src/js/dataMapping/navigation/menuOptions.js
- Reverts Database Download Link
> Hotfix Revert Database Download Link

- src/js/dataMapping/navigation/menuOptions.js
>  Prod deploy: Staging -> Master

- src/_scss/pages/bulkDownload/form/downloadForm.scss
- src/js/components/bulkDownload/accounts/filters/FiscalYearFilter.jsx
- src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1302
- Added in language for custom accounts download
> Added in Language for Custom Accounts Download

- src/_scss/pages/bulkDownload/form/downloadForm.scss
- src/js/components/bulkDownload/accounts/filters/FiscalYearFilter.jsx
- src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx
- src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
- Minor update to Custom Accounts Download language
> Custom Account Downloads Language Update

- src/js/components/bulkDownload/accounts/AccountDataContent.jsx
- src/js/dataMapping/navigation/menuOptions.js
https://federal-spending-transparency.atlassian.net/browse/DEV-1284
Front end updates to enable navigation to custom account download and updated link text
> Custom Account Download 

- src/js/components/about/MoreInfo.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1312
> Updated About page dictionary link

- src/js/components/bulkDownload/archive/AwardDataArchiveContent.jsx
- src/js/components/bulkDownload/awards/filters/dateRange/TimePeriodFilter.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-873
- Updated text in "Custom Award Download" and "Award Data Archive" with instructions for downloading pre FY2009 Data
> Update text to clarify on downloading data before FY2009

- src/_scss/pages/search/_filterExpand.scss
- src/_scss/pages/search/filters/keyword/_keywordHover.scss
- src/js/components/search/filters/keyword/KeywordHover.jsx
- src/js/components/sharedComponents/filterSidebar/FilterExpandButton.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1281
- Updates the fields that keyword matches on
- Fixes a bug causing the tooltip not to show in Firefox and IE by moving the info icon outside of the button element (while nested in `<button>`, the hover events weren't triggered)
> Fix keyword hover

- src/js/components/recipientLanding/RecipientLandingSearchBar.jsx
- Updated the text for search bar
> Update Text for Recipient Landing Search

- src/js/components/bulkDownload/accounts/AccountDataContent.jsx
- src/js/components/bulkDownload/awards/AwardDataContent.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1304
- Fixed by clearing filters when leaving page and coming back
> Fix Custom Account Downloads Filters States

- src/js/models/v2/recipient/BaseRecipientOverview.js
- tests/models/recipient/BaseRecipientOverview-test.js
- tests/models/recipient/mockRecipientApi.js
- Incorrect mapping was causing an error on recipient profile pages with business types
> Fix recipient types mapping

- src/js/components/recipient/modal/RecipientModal.jsx
- src/js/components/recipient/modal/table/RecipientModalTable.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1379
- Fixed child recipient modal not closing after clicking a result
> Fixed bug in child recipient profile modal not closing

- api_contracts/contracts/recipient/RecipientProfile.md
- src/_scss/pages/recipientLanding/_recipientLabels.scss
- src/_scss/pages/recipientLanding/_table.scss
- src/_scss/pages/recipientLanding/recipientLandingPage.scss
- src/js/components/recipientLanding/RecipientLandingContent.jsx
- src/js/components/recipientLanding/RecipientLandingTabs.jsx
- src/js/containers/recipientLanding/RecipientLandingContainer.jsx
- tests/containers/recipientLanding/RecipientLandingContainer-test.jsx
- webpack/webpack.dev.config.js
https://federal-spending-transparency.atlassian.net/browse/DEV-1341
- Added in the ability to filter by different award types
> Recipient Landing Tabs

- src/js/components/homepage/features/PaneFeature.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1417
> Promoting custom account download

- src/_scss/pages/recipientLanding/recipientLandingPage.scss
- src/js/containers/recipientLanding/RecipientLandingContainer.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1448
- Fixes the pagination alignment and sets the page back to one when tabs changes.
> Hotfix Fixed Alignment and Tabs Issue on Recipient Landing

- api_contracts/contracts/accounts/FederalAccountsProfile.md
https://federal-spending-transparency.atlassian.net/browse/DEV-1428
- Creates a contract for the `/api/v2/federal_accounts/` endpoint for the landing page.
> Contract Federal Accounts Landing Page 

- src/_scss/layouts/landingPage/landingPage.scss
- src/js/components/recipientLanding/RecipientLandingContent.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1421
> Added disclaimer on recipient landing page

- src/js/components/recipientLanding/RecipientLandingContent.jsx
Quick page break update as per mock change:
https://federal-spending-transparency.atlassian.net/browse/DEV-1421
- Code Review
- Design Review
> Recipient Disclaimer additional update

- api_contracts/contracts/award/AwardProfile.md
- Removed the field fair_opportunity_sources
> Update V2 Awards Contract

- src/js/dataMapping/contracts/additionalDetails.js
https://federal-spending-transparency.atlassian.net/browse/DEV-1414
- Changes "Mutliple" to "Multiple"
> Fix contract summary typo

- api_contracts/contracts/downloads/CustomAccountDownload.md
https://federal-spending-transparency.atlassian.net/browse/DEV-1497
- Created the contract for Budget functions and subfunctions 
**Note:** Waiting on design mockup before merging to make sure the contract doesn't need any changes based on mockup.
> Contract Budget Function and Subfunction

- src/_scss/pages/search/_pagePositioning.scss
https://federal-spending-transparency.atlassian.net/browse/DEV-1265
> Fix for long recipient names being cut off in tooltips

- src/js/components/search/filters/contractFilters/ContractFilter.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1533
- Fix the off by one issue for the filter links in advanced search
> Fix Advanced Search Filter Links

- src/js/containers/recipient/modal/RecipientModalContainer.jsx
- tests/containers/recipient/modal/RecipientModalContainer-test.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1551
- Now sorting by amount in desc order
> Recipient Modal Sorting Change

- src/_scss/pages/recipientLanding/recipientLandingPage.scss
- Fixed the icons styling for Recipient Landing page
> Fixed Recipient Landing Icons

- src/js/components/state/RecipientFYPicker.jsx
- src/js/containers/explorer/detail/helpers/explorerQuarters.js
- src/js/helpers/fiscalYearHelper.js
- tests/containers/bulkDownload/archive/AwardDataArchiveContainer-test.jsx
- tests/containers/explorer/detail/helpers/explorerQuarters-test.js
- tests/helpers/fiscalYearHelper-test.js
https://federal-spending-transparency.atlassian.net/browse/DEV-1626
- Fixes fiscal year incident on the spending explorer and federal accounts page.
- 2 automated tests were created to prevent a similar incident in the future.
> Hotfix Fiscal Year Incident

- src/_scss/pages/bulkDownload/dictionary/_dictionaryTable.scss
https://federal-spending-transparency.atlassian.net/browse/DEV-1656
- Sets a maximum width for data dictionary columns
> Set a maximum width for data dictionary columns

- api_contracts/contracts/recipient/RecipientProfile.md
https://federal-spending-transparency.atlassian.net/browse/DEV-1659
> Update Recipient Profile Contract

- src/js/components/homepage/hero/Hero.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1654
- Updated the text on the homepage
> Hotfix Homepage Text Update

- src/js/components/bulkDownload/dictionary/DataDictionary.jsx
- src/js/containers/bulkDownload/dictionary/DataDictionaryContainer.jsx
- tests/containers/bulkDownload/dictionary/DataDictionaryContainer-test.jsx
- tests/containers/bulkDownload/mockData.js
- Updates the Data Dictionary download button to link to a url provided by the API instead of being hard-coded
> Fix dictionary link

- src/js/components/homepage/hero/Hero.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1654
- Updated Homepage Text
> Demote Hotfix to Dev

- src/js/containers/account/AccountContainer.jsx
- src/js/containers/account/filters/AccountObjectClassContainer.jsx
- src/js/containers/account/filters/AccountProgramActivityContainer.jsx
- src/js/containers/account/topFilterBar/AccountTopFilterBarContainer.jsx
- src/js/containers/agency/AgencyContainer.jsx
- src/js/containers/agency/visualizations/FederalAccountContainer.jsx
- src/js/containers/agency/visualizations/ObjectClassContainer.jsx
- src/js/containers/agency/visualizations/ObligatedContainer.jsx
- src/js/containers/agency/visualizations/RecipientContainer.jsx
- src/js/containers/award/AwardContainer.jsx
- src/js/containers/award/contracts/AwardDescriptionContainer.jsx
- src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
- src/js/containers/bulkDownload/modal/BulkDownloadBottomBarContainer.jsx
- src/js/containers/explorer/detail/ExplorerDetailPageContainer.jsx
- src/js/containers/glossary/GlossaryContainer.jsx
- src/js/containers/keyword/KeywordContainer.jsx
- src/js/containers/router/RouterContainer.jsx
- src/js/containers/search/SearchContainer.jsx
- src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx
- src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx
- src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
- tests/containers/account/filters/AccountObjectClassContainer-test.jsx
- tests/containers/account/filters/AccountProgramActivityContainer-test.jsx
- tests/containers/agency/AgencyContainer-test.jsx
- tests/containers/agency/visualizations/RecipientContainer-test.jsx
- tests/containers/award/AwardContainer-test.jsx
- tests/containers/explorer/detail/ExplorerDetailPageContainer-test.jsx
- tests/containers/search/SearchContainer-test.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-1138
- Updated the lifecycle of React containers
- Link to document can be found here: https://boozallen.sharepoint.com/:w:/r/sites/dataact/Shared%20Documents/UX%20UI%20Design/ReactLifeCycleUpdates.docx?d=wd633478144464a0ea225a41c00fa225c&csf=1&e=rOoPCO
> Update Container Lifecycle

- src/js/components/search/filters/awardType/AwardType.jsx
- src/js/containers/search/table/ResultsTableContainer.jsx
Updates Advanced search IDV tab Name and placement
[DEV-1799](https://federal-spending-transparency.atlassian.net/browse/DEV-1799)
> Updates idv tab name and placement

- src/_scss/pages/bulkDownload/dictionary/_dictionaryTable.scss
- src/_scss/pages/bulkDownload/dictionary/_searchBar.scss
- src/_scss/pages/bulkDownload/dictionary/dictionary.scss
- src/js/components/bulkDownload/dictionary/DataDictionary.jsx
- src/js/components/bulkDownload/dictionary/table/DataDictionaryTable.jsx
High level description:
Fixed the headers during scroll. Set a fixed height for the table and added in three scrollbars. Layout changes for the search bar and download icon.
JIRA Ticket:
[DEV-1788](https://federal-spending-transparency.atlassian.net/browse/DEV-1788)
> Update Data Dictionary Usability

- src/js/components/bulkDownload/dictionary/table/DataDictionaryTable.jsx
- Fixes console errors when scrolling to the left
> Fix Data Dictionary Scroll

- src/js/containers/award/contracts/AwardDescriptionContainer.jsx
- src/js/containers/award/table/TransactionsTableContainer.jsx
- src/js/helpers/searchHelper.js
High level description:
Updated the transaction table to use the /v2 transaction endpoint.
JIRA Ticket:
[DEV-1627](https://federal-spending-transparency.atlassian.net/browse/DEV-1627) 
> Update Transaction Endpoint

- src/js/components/award/visualizations/AwardLabelsPoly.jsx
- src/js/components/glossary/definition/GlossaryDefinition.jsx
- src/js/components/glossary/search/ResultItem.jsx
- src/js/components/search/filters/timePeriod/TimePeriod.jsx
- src/js/components/search/visualizations/geo/MapLegend.jsx
- src/js/components/search/visualizations/time/chart/BarChart.jsx
This fixes a stack limit issue on the awards and glossary page. This was caused by the React component Lifecycle update.
> Fix Stack Issue

- api_contracts/contracts/award/AwardProfile.md
Update the contract to reflect IDV changes. An IDVResponse has been added in. MiscResponse has been renamed FinancialAssistanceResponse to make the response more clear.
**Jira Ticket**
[DEV-1795](https://federal-spending-transparency.atlassian.net/browse/DEV-1795)
> Contract IDV

- src/js/components/about/MoreInfo.jsx
- src/js/components/about/legal/FOIAPage.jsx
- src/js/components/about/legal/PrivacyPage.jsx
- src/js/components/homepage/hero/HeroTooltip.jsx
- src/js/components/sharedComponents/Footer.jsx
Updates fiscal.treasury.gov links to new URLs.
[DEV-1975](https://federal-spending-transparency.atlassian.net/browse/DEV-1975)
> Hotfix treasury links

- api_contracts/contracts/award/AwardProfile.md
Adding in awards amounts for idv to contract.
Adding in awards amounts for idv to contract.
[DEV-1949](https://federal-spending-transparency.atlassian.net/browse/DEV-1949)
> Contract IDV Award Amounts

- src/_scss/pages/awardV2/awardIdv.scss
- src/_scss/pages/awardV2/awardPage.scss
- src/_scss/pages/awardV2/visualizations/overview/_agencyRecipient.scss
- src/_scss/pages/awardV2/visualizations/overview/_idvDates.scss
- src/_scss/pages/awardV2/visualizations/overview/overview.scss
- src/js/components/awardv2/AwardV2.jsx
- src/js/components/awardv2/contract/ContractContent.jsx
- src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx
- src/js/components/awardv2/idv/IdvContent.jsx
- src/js/components/awardv2/visualizations/overview/AgencyRecipient.jsx
- src/js/models/v2/awardsV2/CoreAwardAgency.js
- tests/models/awardsV2/CoreAwardAgency-test.js
- tests/models/awardsV2/mockAwardApi.js
Adds the Agency and Recipient section to IDV summary pages.
Also includes: 
- Overview section styling clean up -- improves mobile responsiveness and aligns the headings for each component
- Update to the CoreAwardAgency model to include a `formattedToptier` property, which displays the acronym in parentheses if it is available 
[DEV-1961](https://federal-spending-transparency.atlassian.net/browse/DEV-1961) & [DEV-1962](https://federal-spending-transparency.atlassian.net/browse/DEV-1962)
**Mockup:**
https://bahdigital.invisionapp.com/share/HEIA8W7U43G#/screens
> Feature IDV overview agency & recipient

- src/js/components/homepage/features/PaneFeature.jsx
Changes the Featured text on the homepage for Datalab with updated copy
[DEV-1957](https://federal-spending-transparency.atlassian.net/browse/DEV-1957)
> Update Featured Content Text with new Data Lab copy

- src/js/components/awardv2/idv/AwardHistory.jsx
Updated the text for the awardsV2 table section.
Updated the text for the awardsV2 table section.
[DEV-2099](https://federal-spending-transparency.atlassian.net/browse/DEV-2099)
> Update AwardV2 Table Section Text

- api_contracts/contracts/award/AwardProfile.md
API Contract for IDV Reference.
API Contract for IDV Reference.
[DEV-1935](https://federal-spending-transparency.atlassian.net/browse/DEV-1935)
**Mockup:**
https://bahdigital.invisionapp.com/share/HEIA8W7U43G#/screens
> Contract IDV Reference

- api_contracts/contracts/award/AwardProfile.md
This update fixes the sorting field in the request and adds a trailing slash to the request URL.
This update fixes the sorting field in the request and adds a trailing slash to the request URL.
[DEV-1935](https://federal-spending-transparency.atlassian.net/browse/DEV-1935)
> Update IDV Reference Contract

- src/_scss/components/visualizations/tooltip/_csstooltip.scss
- src/_scss/elements/_buttons.scss
- src/_scss/pages/recipient/_overview.scss
- src/js/components/recipient/RecipientMultiParentCollapse.jsx
- src/js/components/recipient/RecipientOverview.jsx
- src/js/models/v2/recipient/BaseRecipientOverview.js
Updates the frontend to display child recipient pages with multiple parents. They will now be in a collapsible accordion, along with links to each respective parent.
[DEV-1748](https://federal-spending-transparency.atlassian.net/browse/DEV-1748)
**Mockup:**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/295994920_Recipient_Summary_-Child-
> Multi Parent Relationship

- src/_scss/core/_defaults.scss
- src/_scss/layouts/default/header/_warning.scss
- src/js/components/sharedComponents/header/Header.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
- src/js/components/sharedComponents/header/WarningBanner.jsx
Adds a disclaimer to the top of the page for FY 19 delay in data
[DEV-2119](https://federal-spending-transparency.atlassian.net/browse/DEV-2119)
> Hotfix: Added disclaimer banner for FY 19 Delay

- .gitignore
Extremely trivial update to ignore the `.idea` hidden directory created by JetBrains IDEs.
See above.
No ticket.
**Mockup:**
You'll have to use your imagination here.  Envision a world where Git doesn't constantly beg you to add a hidden directory generated by your IDE.  Isn't that a sight to behold?
> Updated .gitignore to ignore JetBrains based IDEs' hidden directory

- src/js/components/search/filters/awardType/AwardType.jsx
- src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
- src/js/dataMapping/search/awardType.js
Enables Filtering on specific types within IDV subtype
Enables the dropdown, relabels some of the fields to be more readable.
[DEV-1837](https://federal-spending-transparency.atlassian.net/browse/DEV-1837)
- [NA ] Design review (if applicable)
- [NA] API contract approved by @backendDev (if applicable)
> IDV type filter

- src/_scss/pages/awardV2/idv/_infoTooltip.scss
- src/js/components/awardv2/idv/InfoTooltip.jsx
- src/js/components/awardv2/idv/InfoTooltipContent.jsx
Addresses miscellaneous styles change requests.
Mostly just basic css changes and a few mark up changes
[DEV-2289](https://federal-spending-transparency.atlassian.net/browse/DEV-2289)
**Mockup:**
> [DEV-2289] tooltip fixes

- src/_scss/pages/awardV2/awardPage.scss
- src/_scss/pages/awardV2/idv/_awardAmounts.scss
- src/_scss/pages/awardV2/idv/_awardFundingSummary.scss
- src/js/components/awardv2/idv/FundingSummary.jsx
- src/js/components/awardv2/idv/referencedAwards/ReferencedAwardsSection.jsx
Fixes a few design changes not merged in PR #1038.
* Removes border width in table
* Fixes sub-section header font size
* Changes some mark up / class names
* Changes title of Awards that Reference this IDV section to match the tool tip for that section
[DEV-2342](https://federal-spending-transparency.atlassian.net/browse/DEV-2342)
**Mockups (Requested changes from PR):**
** Screenshot:**
**Commits:**
d4c7692 -- fixes sub-section header size
a6828e8 -- fixes border styles and changes mark up
f8b4b2d -- fixes section title to match tooltip
> [coming-soon] Coming Soon section & federal account funding-summary table style fixes

- src/_scss/pages/awardV2/idv/_awardAmounts.scss
- src/js/components/awardv2/visualizations/amounts/AggregatedAwardAmounts.jsx
- src/js/components/awardv2/visualizations/amounts/charts/NormalChart.jsx
- src/js/helpers/aggregatedAmountsHelper.js
- src/js/models/v2/awardsV2/BaseAwardAmounts.js
- tests/helpers/aggregatedAmountsHelper-text.js
- tests/models/awardsV2/BaseAwardAmounts-test.js
Implements an "Insufficient Data" message for edge cases in the IDV aggregate Award Amounts visualization. 
- Refactored names used in the models to reflect updated terminology in the visualization
- Added a helper function that, given award amounts, determines whether they indicate
- Normal
- Overspend
- Extreme overspend
- Everything else
- Perform a check for the normal situation and implement the "Insufficient Data" message as the fallback. Subsequent PRs will check for "Overspend" and "Extreme overspend" and implement their corresponding visualizations.
- Award id for an example of the "Insufficient Data" message in dev: `68860659` (overspend)
[DEV-2356](https://federal-spending-transparency.atlassian.net/browse/DEV-2 …
> Normal scenario and insufficient data

- src/js/components/awardv2/idv/IdvContent.jsx
- src/js/containers/awardV2/idv/AwardMetaDataContainer.jsx
Clean up of IDV Activity and Federal Accounts section roll out.
Capitalized IDV and set values to N/A when they are 0 for Federal Account table section.
[DEV-2387](https://federal-spending-transparency.atlassian.net/browse/DEV-2387)
**Commits:**
c4b96a7 -- Capitalizing IDV
1f2b3ab -- Adding N/A when values are 0
- Design review N/A
> [DEV_2387] Capitalized IDV and set values to N/A when 0 for funding meta data

- src/js/components/keyword/table/ResultsTable.jsx
- src/js/components/search/table/ResultsTable.jsx
- src/js/components/search/table/cells/ResultsTableHeaderCell.jsx
- src/js/containers/keyword/KeywordContainer.jsx
- src/js/containers/keyword/table/ResultsTableContainer.jsx
- src/js/containers/search/table/ResultsTableContainer.jsx
- src/js/dataMapping/keyword/resultsTableColumns.js
- src/js/dataMapping/navigation/menuOptions.js
- src/js/dataMapping/search/awardTableColumns.js
- tests/containers/search/table/ResultsTableContainer-test.jsx
Add IDV table to Keyword Search Page.
- add idvs to table types
- add columns for idvs to keyword search data mapping
- add default column for idvs
- remove keyword search variable from route
[DEV-1807](https://federal-spending-transparency.atlassian.net/browse/DEV-1807)
**Mockup:**
TBD
> Add IDV Table to Keyword Search Page

- src/js/components/awardv2/visualizations/amounts/AggregatedAwardAmounts.jsx
- src/js/components/awardv2/visualizations/overview/RelatedAwards.jsx
Add commas to the counts for related awards section and the award amounts child table.
add `formatNumber` to those counts
[DEV-2541](https://federal-spending-transparency.atlassian.net/browse/DEV-2541)
> Dev-2541 Hotfix Add Commas

- src/js/components/awardv2/idv/FundingSummary.jsx
Changing text per mockup
Changing text per mockup
[DEV-2369](https://federal-spending-transparency.atlassian.net/browse/DEV-2369)
**Mockup:**
https://bahdigital.invisionapp.com/share/YJIAA9KVK4B#/screens
> [federal-funding-link-hotfix2] Changing link text per mockup to View federal funding submissions

- .travis.yml
Upgrade Travis to Node 10
Upgrade Travis to Node 10
> Update Travis to Node 10

- src/js/dataMapping/search/recipientType.js
On the Advanced Search page > Recipient Type filter > Special Designations dropdown, changes `Self-Certified Disadvantaged Business` to `Self-Certified Small Disadvantaged Business`.
[DEV-2382](https://federal-spending-transparency.atlassian.net/browse/DEV-2382)
**Mockup:**
N/A
> Fix Advanced Search Filter Typo

- .eslintrc
- babel.config.js
- package-lock.json
- package.json
- src/js/components/awardv2/idv/federalAccounts/FederalAccountsSection.jsx
- src/js/components/awardv2/idv/federalAccounts/FederalAccountsSummary.jsx
- src/js/components/awardv2/idv/federalAccounts/FederalAccountsTable.jsx
- src/js/components/awardv2/idv/federalAccounts/FederalAccountsTree.jsx
- src/js/containers/awardV2/idv/AwardMetaDataContainer.jsx
- tests/containers/awardV2/idv/AwardMetaDataContainer-test.jsx
TreeMap now displays all positive Federal Accounts.
* add for await to code base
* give fed account tree own no results, loading and error message
* give fed account table own no results, loading and error message
* new method to page through and get all fed accounts
* new method to parse all fed accounts
[DEV-1937](https://federal-spending-transparency.atlassian.net/browse/DEV-1937)
**Mockup:**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/screens/296001079
> HotFix Dev-1937 Show All Fed Accounts in TreeMap :)

- src/js/components/awardv2/idv/amounts/IDVAmounts.jsx
Update this IDV Award Amounts Tab Table Labels
N/A
[DEV-2644](https://federal-spending-transparency.atlassian.net/browse/DEV-2644)
> Dev-2644 Update this IDV Award Amounts Tab Table Labels

- src/js/components/awardv2/idv/federalAccounts/FederalAccountsTree.jsx
Update the way React shows the chart
get rid of uniqueId
[DEV-1937](https://federal-spending-transparency.atlassian.net/browse/DEV-1937)
> HotFix 1937 Fix React Keys TreeMap

- src/js/components/awardv2/idv/amounts/AggregatedAwardAmounts.jsx
Changes text value of div element per request.
Changing innerHTML value of the relevant DIV
[DEV-2619](https://federal-spending-transparency.atlassian.net/browse/DEV-2619)
**Mockup:**
https://bahdigital.invisionapp.com/share/GVIAAHOBER9#/296001079_Award_Summary_2-0_-_IDV_-future-
> [dev-2619] Count of Total Orders --> Count of Total Award Orders

- src/js/helpers/searchHelper.js
Removing code no longer used.
This code is no longer called anywhere, so we're removing it
[DEV-2558](https://federal-spending-transparency.atlassian.net/browse/DEV-2558)
> [dev-2558] removing dead code for v1/transactions that's no longer called

- src/js/containers/award/subawards/SubawardsContainer.jsx
- src/js/dataMapping/contracts/subawardTable.js
- src/js/helpers/searchHelper.js
Makes use of new v2 endpoint.
Altered shape of request object and `sort` parameters. Required an update to data map.
[DEV-2560](https://federal-spending-transparency.atlassian.net/browse/DEV-2560)
> [DEV-2560] v2 api migration, subawards endpoint

- src/js/components/awardv2/idv/IdvDates.jsx
- src/js/components/awardv2/idv/InfoTooltipContent.jsx
- src/js/dataMapping/awardsv2/additionalDetails.js
- src/js/dataMapping/awardsv2/referencedAwards.js
- src/js/dataMapping/search/awardTableColumns.js
Advanced Search IDV table column and the IDV Summary Page show Ordering Period End Date
[DEV-2700](https://federal-spending-transparency.atlassian.net/browse/DEV-2700)
> Dev-2700 Advanced Search IDV table column and the IDV Summary Page show Ordering Period End Date

- src/js/components/homepage/features/PaneFeature.jsx
Add Congressional Justification & Daily Treasury Statement Tracker Feature Content Box
N/A
[DEV-2699](https://federal-spending-transparency.atlassian.net/browse/DEV-2699)
[DEV-2486](https://federal-spending-transparency.atlassian.net/browse/DEV-2486)
**Mockup:**
https://bahdigital.invisionapp.com/share/8WIAAILTUDP
> Dev-2699 & Dev-2486 Add Congressional Justification & Daily Treasury Statement Tracker Feature Content Box

- src/_scss/pages/agencyLanding/table/table.scss
- src/js/app.jsx
- src/js/components/account/awards/LegacyTableHeaderCell.jsx
- src/js/components/agencyLanding/table/TableRow.jsx
- src/js/containers/agencyLanding/AgencyLandingContainer.jsx
- src/js/dataMapping/agencyLanding/agenciesTableFields.js
- tests/containers/agencyLanding/AgencyLandingContainer-test.jsx
- tests/containers/agencyLanding/mockToptierAgencies.js
Congressional Justification Link Column on Agency Landing Page
* update data mapping
* update legacy table header to allow for not sort
* add optional rendering for cj link in agency landing table
[DEV-2713](https://federal-spending-transparency.atlassian.net/browse/DEV-2713)
**Mockup:**
https://bahdigital.invisionapp.com/share/KDIAAI9YU8Q#/screens
> Dev-2713 Congressional Justification Link on Agency Landing Page

- src/_scss/pages/agency/_overview.scss
- src/js/app.jsx
- src/js/components/agency/overview/AgencyOverview.jsx
- src/js/components/awardv2/idv/federalAccounts/FederalAccountsSummary.jsx
- src/js/models/agency/AgencyOverviewModel.js
- tests/containers/agency/mockAgency.js
Add Congressional Justification Link to Agency Profile page.
* update agency overview css
* add external link icon to app
* add cj link to agency profile page
* add cj link to agency overview model
* logic in model to handle null links
* add cj link to mock data
[DEV-2058](https://federal-spending-transparency.atlassian.net/browse/DEV-2058)
[SubTask-DEV-2712](https://federal-spending-transparency.atlassian.net/browse/DEV-2712)
**Mockup:**
https://bahdigital.invisionapp.com/share/2WIA9QQMZ86
> Dev-2058 SubTask-Dev-2712 CJ Link Agency Profile Page

- .eslintrc
- package-lock.json
- package.json
React hooks are new and shouldn't be used w/o the linter.
The linter will bring attention to any use of react-hooks that are considered anti-patterns by the react community.
[DEV-976](https://federal-spending-transparency.atlassian.net/browse/DEV-976)
> [dev-976] adding linter for react-hooks

- src/js/components/agencyLanding/table/TableRow.jsx
On Agency Landing Page, CJ link opens new tab.
[DEV-2713](https://federal-spending-transparency.atlassian.net/browse/DEV-2713)
> HotFix Dev-2713 Agency Landing Page CJ opens new tab

- src/js/containers/search/filters/location/POPFilterContainer.jsx
- src/js/containers/search/filters/location/RecipientFilterContainer.jsx
Re-enables city search now that [backend updates](https://github.com/fedspendingtransparency/usaspending-api/pull/1866) are complete .
[DEV-2616](https://federal-spending-transparency.atlassian.net/browse/DEV-2616)
> Hotfix enable city search

- package.json
- src/_scss/pages/awardV2/idv/activity/idvActivity.scss
- src/js/components/awardv2/idv/activity/chart/ActivityChart.jsx
- src/js/components/awardv2/idv/activity/chart/ActivityChartBar.jsx
Add Obligated Amount Bar to IDV Activity Chart.
* add scale for obligated amount
* add obligated amount bar
* update styling
[DEV-2732](https://federal-spending-transparency.atlassian.net/browse/DEV-2732)
**Mockup:**
https://bahdigital.invisionapp.com/share/ACIAA6A938E#/screens/296010428
> Dev-2732 Obligated Amount Bar IDV Activity Chart

- src/js/components/awardv2/idv/activity/IdvActivityVisualization.jsx
- src/js/components/sharedComponents/Pagination.jsx
- src/js/helpers/idvHelper.js
Update Paging to match mock for the IDV Activity Chart
* update pagination component to take resultsText element
* add resultsText element to idvactivity visualization
[DEV-2647](https://federal-spending-transparency.atlassian.net/browse/DEV-2647)
**Mockup:**
https://bahdigital.invisionapp.com/share/ACIAA6A938E#/screens/296010428
> Hotfix Dev-2647 Update Paging to match mock for the IDV Activity Chart

- src/js/components/awardv2/idv/activity/IdvActivity.jsx
- src/js/components/awardv2/idv/activity/IdvActivityVisualization.jsx
- src/js/components/sharedComponents/Pagination.jsx
- src/js/helpers/paginationHelper.js
- tests/helpers/paginationHelper-test.js
Fixes a bug causing page ranges on the IDV Activity chart to display incorrectly.
- Created a helper function to calculate page ranges, which is now used in the shared Pagination component as well as the IDV Activity visualization.
- Added unit tests for the new helper function.
[DEV-2647](https://federal-spending-transparency.atlassian.net/browse/DEV-2647)
**Mockup:**
https://bahdigital.invisionapp.com/share/ACIAA6A938E#/screens/296010428
> Hotfix IDV Activity page ranges

- src/js/components/about/MoreInfo.jsx
- src/js/components/sharedComponents/Footer.jsx
Update links on the home and about pages.
* update data model link on home page
* add data dictionary link on home page
* update data dictionary link on about page
[DEV-2782](https://federal-spending-transparency.atlassian.net/browse/DEV-2782)
> Dev-2782 Update Home and About Pages Links

- src/_scss/components/visualizations/tooltip/_csstooltip.scss
- src/_scss/pages/awardV2/awardPage.scss
- src/_scss/pages/awardV2/idv/_infoTooltip.scss
- src/_scss/pages/awardV2/visualizations/_additionalInfo.scss
- src/js/app.jsx
- src/js/components/awardv2/idv/InfoTooltip.jsx
- src/js/components/awardv2/idv/InfoTooltipContent.jsx
- src/js/components/awardv2/shared/additionalInfo/Accordion.jsx
- src/js/components/awardv2/shared/additionalInfo/AdditionalInfo.jsx
- src/js/components/awardv2/shared/additionalInfo/IdvPeriodOfPerformance.jsx
- src/js/dataMapping/awardsv2/additionalDetailsIdv.js
- src/js/helpers/keyboardEventsHelper.js
- src/js/models/v2/awardsV2/BaseParentAwardDetails.js
- src/js/models/v2/awardsV2/additionalDetails/BaseContractAdditionalDetails.js
- tests/helpers/keyboardEventsHelper-test.js
- tests/models/awardsV2/additionalDetails/BaseContractAdditionalDetails-test.js
- Changes "Parent IDV Agency Identifier" to "Parent IDV Agency Name"
- Adds tooltips to the Period of Performance section explaining how the dates are calculated
- Removes fields from the Acquisition Details section (DOD Acquisition Program, Information Technology Commercial Item Category)
- Displays `false` instead of `no` for boolean values (Small Business Competitiveness Demonstration Program)
- Uses an existing, generic CSS tooltip
- Splits up Contracts and IDVs into separate mappings since there have become enough differences between the two
- Moves Period of Performance into its own component since the generic `Accordion` wouldn't handle tooltips
- Adds a helper for displaying Booleans that distinguishes between `true`, `false`, and …
> IDV Additional Information updates

- src/_scss/pages/search/filters/location/location.scss
- src/js/components/search/filters/location/LocationPicker.jsx
- src/js/components/search/filters/location/ZIPField.jsx
Disabling zip code field for foreign countries.
- Passing generateWarning to zip code field
- `ZIPField.jsx` now has `EntityWarning` component and local state to trigger showing the warning.
[DEV-2974](https://federal-spending-transparency.atlassian.net/browse/DEV-2947)
**Mockup:**
N/A
> Bug/dev 2947/disable foregin zipcodes

- src/_scss/pages/awardV2/idv/activity/idvActivity.scss
- src/js/components/awardv2/idv/activity/chart/ActivityXAxis.jsx
- src/js/containers/awardV2/idv/IdvActivityContainer.jsx
Add loading message when paging
set state to loading when paging
[DEV-2909](https://federal-spending-transparency.atlassian.net/browse/DEV-2909)
> Dev-2909 API Integration Add loading when paging

- src/js/containers/awardV2/idv/IdvActivityContainer.jsx
Add Param to Request to Filter Edge Cases.
* add flag to idv activity response
[DEV-3024](https://federal-spending-transparency.atlassian.net/browse/DEV-3024)
> Dev-3024 Add Param to Request to Filter Edge Cases.

- src/_scss/components/_Note.scss
- src/_scss/pages/awardV2/idv/_awardFundingSummary.scss
- src/_scss/pages/awardV2/idv/activity/idvActivity.scss
- src/js/components/awardv2/idv/activity/IdvActivityVisualization.jsx
- src/js/components/awardv2/idv/federalAccounts/FederalAccountsSection.jsx
- src/js/components/sharedComponents/Note.jsx
Add Note to IDV Activity Chart for Edge Cases
[DEV-3025](https://federal-spending-transparency.atlassian.net/browse/DEV-3025)
> Dev-3025 Add Note to IDV Activity Chart

- src/js/components/search/filters/location/EntityDropdown.jsx
Options in city drop down were not selectable.
Adds condition to `mouseOut` event handler to only update state when necessary.
[DEV-2878](https://federal-spending-transparency.atlassian.net/browse/DEV-2878)
> [DEV-2878] Follow up bug fix, Foreign City Selection prevented by mouseOut bug

- src/js/components/awardv2/idv/activity/chart/ActivityChart.jsx
Update Obligated Amount to show exact value.
Update Obligated Amount to show exact value.
[DEV-2732](https://federal-spending-transparency.atlassian.net/browse/DEV-2732)
> HotFix Dev-2732 Obligated Amount

- src/js/components/awardv2/idv/InfoTooltipContent.jsx
Update Text of IDV Activity Tooltip
[DEV-3085](https://federal-spending-transparency.atlassian.net/browse/DEV-3085)
> Dev-3085 IDV Activity Tooltip

- src/js/components/about/AboutContent.jsx
- src/js/components/about/Licensing.jsx
Add Licensing Content to the About Page.
[DEV-2352](https://federal-spending-transparency.atlassian.net/browse/DEV-2352)
> Dev-2352 About Page Licensing Content

- src/_scss/pages/awardV2/idv/awardAmounts/_awardAmounts.scss
- src/_scss/pages/awardV2/idv/awardAmounts/_charts.scss
- src/js/components/awardv2/idv/amounts/AggregatedAwardAmounts.jsx
- src/js/helpers/aggregatedAmountsHelper.js
- tests/helpers/aggregatedAmountsHelper-test.js
Add No Data Message to IDV Award Amounts.
* add logic to aggregated award amounts helper
* add no results table message
* update css
[DEV-2990](https://federal-spending-transparency.atlassian.net/browse/DEV-2990)
**Mockup:**
https://bahdigital.invisionapp.com/share/8KIAB29S5T6#/screens/296009664_combinedAwardsSection--unavailable
> DEV-2990 No Data Message IDV Award Amounts

- src/_scss/pages/awardV2/idv/awardAmounts/_awardAmounts.scss
Between mobile and tablet views, banner is not responsive.
Adds width property to banner.
[DEV-2330](https://federal-spending-transparency.atlassian.net/browse/DEV-2330)
> [dev-2330] Mobile Responsiveness for Banner on IDV Page

- sampleGlobalConstants_dev.js
- sampleGlobalConstants_prod.js
- src/_scss/layouts/default/header/nav/_logo.scss
- src/js/components/sharedComponents/header/NavBar.jsx
Removes the `IN_BETA` property from sample config and from the one instance it was referenced in the code base.
We were looking at this config property to determine whether or not to apply a class to the navigation component. This code has been removed.
[DEV-2968](https://federal-spending-transparency.atlassian.net/browse/DEV-2968)
> [DEV-2968] deprecate in beta config property 

- src/js/components/search/SearchSidebar.jsx
- src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
- Makes the program source filter available in staging and production
[DEV-3075](https://federal-spending-transparency.atlassian.net/browse/DEV-3075)
**Mockup:**
N/A
> Release Program Source (TAS) filter in all environments

- src/_scss/pages/search/filters/programSource/programSource.scss
- src/js/components/search/filters/programSource/ProgramSourceInfoTooltip.jsx
- src/js/containers/search/filters/programSource/ProgramSourceAutocompleteContainer.jsx
- src/js/dataMapping/search/programSourceInfoTooltipContent.js
Adds info tooltips to each of the Program Source (TAS) filter components. 
Uses a CSS-activated tooltip, which is compatible with collapsible sections. 
[DEV-2824](https://federal-spending-transparency.atlassian.net/browse/DEV-2824)
**Mockup:**
https://bahdigital.invisionapp.com/share/Z7IAB1I53Y4#/296002937_Advanced_Search_-_TAS (click the `i` icon next to ATA)
> TAS search tooltips

- __mocks__/fileMock.js
This PR mocks image files for testing purposes.
Add the __mocks__ folder with the mockFile.js file that jest sends images to.
> Mock Images Files for Testing

- src/js/dataMapping/search/programSourceInfoTooltipContent.js
Updates the description in the _Program Source_ filter > _Sub Account Code_ info tooltip
[DEV-3293](https://federal-spending-transparency.atlassian.net/browse/DEV-3293)
**Mockup:**
N/A
> Update Sub Account tooltip

- pull_request_template.md
Updates the PR template
N/A
**Mockup:**
N/A
> updating PR template to refactor

- src/js/components/awardv2/contract/ContractContent.jsx
- src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx
- src/js/components/awardv2/idv/amounts/AggregatedAwardAmounts.jsx
- src/js/components/awardv2/shared/awardAmountsSection/AwardAmountsSection.jsx
- src/js/components/awardv2/shared/awardAmountsSection/AwardAmountsTable.jsx
- src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx
- src/js/components/awardv2/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
- src/js/components/sharedComponents/TooltipWrapper.jsx
- src/js/models/v2/awardsV2/CoreAward.js
- src/js/propTypes/index.js
Adds tooltips to award amounts visualization chart and overspending row to award amounts table.
- Creates component `AwardAmountsChart` to reuse logic for rendering chart with tooltips.
- Improves `AwardAmountsTable` to handle overspending
- Updates CoreAward Model to include overspending and extreme overspending properties
[DEV-3279](https://federal-spending-transparency.atlassian.net/browse/DEV-3279)
**Mockup:**
https://bahdigital.invisionapp.com/share/KYIAAD5E57G#/screens
> [DEV-3279] as2.0 award amount tooltips & overspending row in Award Amounts Table

- src/js/components/awardv2/contract/ContractContent.jsx
- src/js/components/awardv2/shared/awardAmountsSection/AwardAmountsSection.jsx
- src/js/components/awardv2/shared/awardAmountsSection/AwardAmountsTable.jsx
- src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx
- src/js/components/awardv2/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
- src/js/components/awardv2/shared/awardAmountsSection/charts/ExceedsCurrentChart.jsx
- src/js/components/awardv2/shared/awardAmountsSection/charts/ExceedsPotentialChart.jsx
- src/js/components/awardv2/shared/awardAmountsSection/charts/GrantChart.jsx
- src/js/components/awardv2/shared/awardAmountsSection/charts/NormalChart.jsx
Implements tooltips for award type grant.
Reuses existing components with new props specific to grant spending categories and tooltip copies
[DEV-3451](https://federal-spending-transparency.atlassian.net/browse/DEV-3451)
**Mockup:**
> [DEV-3451] Award Amounts Section 2.0 -- implementing Grant Tooltips

- src/js/components/award/subawards/SubawardsTable.jsx
- src/js/components/award/table/TransactionsTable.jsx
- src/js/components/awardv2/table/FederalAccountTable.jsx
- src/js/containers/award/subawards/SubawardsContainer.jsx
- src/js/containers/awardV2/table/FederalAccountTableContainer.jsx
- src/js/containers/awardV2/table/TransactionsTableContainer.jsx
Adding logic / state / props to handle errors in award history table.
Implements same logic and approach as other tables that use this message.
[DEV-3100](https://federal-spending-transparency.atlassian.net/browse/DEV-3100)
> Handling error on Subawards/FederalAccounts/Transaction History Tabs in Award History v2 Component

- src/js/dataMapping/awardsv2/additionalDetailsContract.js
Updates the data mapping for Contract Parent IDV to use generated unique id.
Updates the data mapping for Contract Parent IDV to use generated unique id.
[DEV-3102](https://federal-spending-transparency.atlassian.net/browse/DEV-3102)
> Dev-3102 Add Parent IDV mapping to additional details

- src/js/components/awardv2/idv/IdvContent.jsx
Update IDV header to use `award` classnames
idv header uses award classnames
> Hotfix IDV Glossary Icon

- src/js/models/v2/awardsV2/BaseFinancialAssistance.js
- tests/models/awardsV2/CoreAwardAgency-test.js
Adds Funding Agency ID to to Financial Assistance Base Model to show Funding Agency Top-tier Link in Financial Assistance Pages Additional Information.
updates the Base Financial Assistance model to have the `id` property following the data structure for contracts.
[DEV-3103](https://federal-spending-transparency.atlassian.net/browse/DEV-3103)
> Hotfix Dev-3103 Update Financial Assistance Model Funding Data Structure

- src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx
- src/js/components/awardv2/shared/AwardPageWrapper.jsx
**High level description of the PR.**
Show Parenthesis in Title for Grant Pages
remove startCase
[DEV-3363](https://federal-spending-transparency.atlassian.net/browse/DEV-3633)
> Dev-3633 Award Titles show Parenthesis

- src/js/components/awardv2/shared/federalAccounts/FederalAccountsSummary.jsx
- src/js/containers/awardV2/shared/FederalAccountsSummaryContainer.jsx
Changes order of rows and title of table.
Very superficial changes.
[DEV-3587](https://federal-spending-transparency.atlassian.net/browse/DEV-3587)
> [DEV-3587] Changing Order of Rows and Title of Table in Federal Accounts Section

- src/js/components/awardv2/shared/additionalInfo/Accordion.jsx
- src/js/components/awardv2/shared/additionalInfo/AdditionalInfo.jsx
Fixes bug in IDV Additional Information Section
Adds `key` prop to `IDVPeriodOfPerformance` Accordion
> Bug IDVPeriodOfPerformance Accordion

- src/js/models/v2/awardsV2/BaseContract.js
- tests/models/awardsV2/BaseContract-test.js
Unhandled error was being thrown on page when the toptier.code was undefined. When this happens, it should always be treated as a PSC Type of `PRODUCTS`
> [DEV-1663] Handling case where psc.code is undefined.

- src/js/components/awardv2/shared/additionalInfo/AdditionalInfo.jsx
- src/js/dataMapping/awardsv2/additionalDetailsContract.js
- src/js/dataMapping/awardsv2/additionalDetailsFinancialAssistance.js
- src/js/dataMapping/awardsv2/additionalDetailsIdv.js
- src/js/models/v2/awardsV2/BaseContract.js
- src/js/models/v2/awardsV2/BaseFinancialAssistance.js
Updates to Additional Details in Contracts.
* update contract and financial assistance mapping to use id for funding agency
* update contract parent details mapping to not use parent_award as it does not exist in the response
* update data mapping for additional details for contracts
[DEV-3102](https://federal-spending-transparency.atlassian.net/browse/DEV-3102)
**Mockup:**
https://bahdigital.invisionapp.com/share/CZIAB1EVH75#/screens/296001046_Award_Summary_2-0_-_Contract_-_Expanded
> Hotfix Dev-3102 Additional Details Contract

- src/_scss/pages/awardV2/awardPage.scss
- src/js/components/awardv2/AwardV2.jsx
- src/js/components/awardv2/SummaryBarV2.jsx
- src/js/components/search/table/ResultsTable.jsx
- src/js/containers/awardV2/AwardV2Container.jsx
- src/js/containers/router/RouterRoutes.jsx
Adds generatedUniqueIds to Advanced Search Results table, removes dark logic release, handles invalid award IDs
43e73bb - adds unique id to advanced search results table
78d8b26 - removing dark release logic
06348b5 - sets `inFlight` false on error & removes `isV2` url
50c4ab1 - adds styles to invalid award id stuff
[DEV-3439](https://federal-spending-transparency.atlassian.net/browse/DEV-3439)
> [DEV-3439] First Iteration of Award Summary 2.0 Release

- src/js/components/search/filters/awardAmount/SpecificAwardAmountItem.jsx
Award Amount Filter in Advanced Search allows users to search negative ranges.
* updates the logic to separate empty input warning.
[DEV-2412](https://federal-spending-transparency.atlassian.net/browse/DEV-2412)
> Dev-2412 Award Amount Advanced Search Warning

- src/_scss/pages/awardV2/visualizations/overview/overview.scss
Quick follow up to #1314 to handle responsiveness for overview section.
> [as2.0-polish-overview-mobile] responsiveness for overview section on mobile/tablet

- src/js/components/awardv2/shared/InfoTooltipContent.jsx
- src/js/components/awardv2/shared/awardHistorySection/AwardHistory.jsx
- src/js/dataMapping/awardsv2/awardHistorySection.js
Updates to the Award History Section Tooltip
* move award history section tooltip to data mapping
[DEV-3678](https://federal-spending-transparency.atlassian.net/browse/DEV-3678)
> Dev-3678 Award History Tooltip

- src/js/components/awardv2/idv/amounts/AggregatedAwardAmounts.jsx
- src/js/components/awardv2/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
- src/js/dataMapping/awardsv2/awardAmountsSection.js
- src/js/helpers/awardAmountHelper.js
- tests/helpers/awardAmountHelper-test.js
Was rendering the grant award amounts chart for contracts due to error in conditional logic.
Improved conditional logic and tests.
[Bug was introduced in work associated with this ticket during this sprint](https://federal-spending-transparency.atlassian.net/browse/DEV-3447)
`N/A` Link to this PR in JIRA ticket
`N/A` Tagged Design, Testing, and Code Reviewers in `#us-ux-frontend` Slack Channel in the thread under the Post from Github for their SA
`N/A` Scheduled demo including Design/Testing/Front-end `if applicable`
`N/A` Provided instructions for testing in JIRA (for benefit of testing) and PR (for benefit of code reviewer) `if applicable`
`N/A` …
> [DEV-3447] Follow Up that Fixes Bug which Renders Grant Award Amounts Chart for Contracts

- src/_scss/pages/awardV2/visualizations/_awardFundingSummary.scss
Update CSS for IDV Federal Accounts section that would overflow the row.
Update CSS for IDV Federal Accounts section that would overflow the row.
[DEV-3697](https://federal-spending-transparency.atlassian.net/browse/DEV-3697)
**Testing**
1.  navigate to an idv page in one browser
2. navigate to a contract page in another browser
3. verify that the space between the additional information section and the section above between the two browsers are the same.
4. verify that the space between the award history section and the section above between the two browsers are the same.
> Dev-3697 update idv federal accounts css

- src/js/components/sharedComponents/header/Header.jsx
Rolling out new data for 2019, [we set initial state to default to true for the property governing if we show the info banner or not](https://github.com/fedspendingtransparency/usaspending-website/pull/1345/files?file-filters%5B%5D=.jsx#diff-09238ab91d6d456f29f7471e22f3cc55R23). The result of this is we always show the info banner, which is a change in behavior from how it was previously.
Reverting to previous behavior where we show the banner only if a cookie doesn't exist.
[DEV-3382](https://federal-spending-transparency.atlassian.net/browse/DEV-3382)
`N/A` Tagged Design, Testing, and Code Reviewers in `#us-ux-frontend` Slack Channel in the …
> [Hotfix] Use cookie for info banner

- src/_scss/pages/awardV2/awardPage.scss
- src/_scss/pages/awardV2/idv/_referencedAwards.scss
- src/_scss/pages/awardV2/shared/_awardHistorySection.scss
- src/_scss/pages/awardV2/shared/awardAmountsSection/_index.scss
- src/_scss/pages/awardV2/visualizations/_additionalInfo.scss
- src/_scss/pages/awardV2/visualizations/_awardFundingSummary.scss
- src/_scss/pages/search/results/table/_tableTypes.scss
- src/js/components/awardv2/idv/amounts/AwardAmounts.jsx
- src/js/components/awardv2/shared/AwardPageWrapper.jsx
- src/js/components/search/table/ResultsTableTabItem.jsx
- src/js/components/search/table/ResultsTableTabs.jsx
Adds a consistent margin between headers and content.
Gave hr a margin bottom and removed other padding-top from divs.
[DEV-3816](https://federal-spending-transparency.atlassian.net/browse/DEV-3816)
**Mockup:**
https://bahdigital.invisionapp.com/share/9EIABE5KQ24#/screens/296011639
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers …
> Dev-3816 Margins between Headers & Content

- src/_scss/pages/awardV2/idv/activity/idvActivity.scss
Remove margin top from IDV Activity Chart Title.
[DEV-3816](https://federal-spending-transparency.atlassian.net/browse/DEV-3816)
- [N/A] Added Unit Tests for methods in Container Components, reducers, and helper functions `if …
> Dev-3816 remove idv activity title margin top

- src/_scss/pages/awardV2/awardPage.scss
AwardExpandableSection Component had `css` rules that were scoped inside the wrapper `award__col__content` which is not always the parent for each section in which this component is used.
http://0.0.0.0:3000/#/award/CONT_IDV_NNK14MA75C_8000
Removed css rules from underneath parent, to the true universal parent of each award section: `award__col`.
N/A
**SS:**
`N/A` Link to this PR in JIRA ticket
`N/A` Tagged Design, Testing, and Code Reviewers in `#us-ux-frontend` Slack Channel in the thread under the Post from Github for their SA
`N/A` Scheduled demo including Design/Testing/Front-end `if applicable`
`N/A` Provided instructions for testing in JIRA …
> [Warm fix/expandable section/css] small update to styles

- src/_scss/pages/awardV2/shared/_expandableAwardSection.scss
- src/_scss/pages/awardV2/visualizations/description/_description.scss
Doubles the margin bottom of the description section paragraph
> Warmfix Add margin bottom

- src/js/dataMapping/awardsv2/additionalDetailsContract.js
- src/js/dataMapping/awardsv2/additionalDetailsIdv.js
- src/js/models/v2/awardsV2/BaseIdv.js
Removes the Links for Parent Award Agency Link & Add Links for Additional Details.
- [N/A] Link to this PR in JIRA ticket
- [N/A] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/d …
> Warm-Fix Unlink Parent Award Agency & Add Links Additional Details

- src/js/components/awardv2/shared/description/AwardDescription.jsx
Updates the the PSC title to use the same class as NAICS.
- [N/A] Link to this PR in JIRA ticket
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers …
> WarmFix Update Spacing for PSC Title

- src/js/components/awardv2/shared/InfoTooltipContent.jsx
- src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx
- src/js/dataMapping/awardsv2/tooltips.js
Non-Loan ASST type awards were displaying grant specific info
Now the tooltip content shows the correct tooltip copy data.
[DEV-3618](https://federal-spending-transparency.atlassian.net/browse/DEV-3618)
`N/A` Scheduled demo including Design/Testing/Front-end `if applicable`
`N/A` Provided instructions for testing in JIRA (for benefit of testing) and PR (for benefit of code reviewer) `if applicable`
`N/A` Design review complete `if applicable` …
> [warm-fix-awardamounts-asst-tooltips] Fixing Award Amounts Section & Chart tool tips

- src/_scss/pages/awardV2/awardFinancialAssistance.scss
- src/js/components/awardv2/shared/description/AwardDescription.jsx
- src/js/dataMapping/awardsv2/additionalDetailsContract.js
- src/js/dataMapping/awardsv2/additionalDetailsIdv.js
- src/js/models/v2/awardsV2/BaseIdv.js
1. Updates Award Amounts Tooltip to use Assistance & Update Assistance Content
2. Update Spacing Between Title and Content in Description Section
> Staging -> Dev

- src/js/helpers/searchHelper.js
Remove v1/accounts/awards/ Endpoint
Remove v1/accounts/awards/ Endpoint
[DEV-3867](https://federal-spending-transparency.atlassian.net/browse/DEV-3867)
- [N/A] Added Unit Tests for methods in Container …
> Dev-3867 Remove v1/accounts/awards/ Endpoint

- src/js/helpers/searchHelper.js
Remove v1/awards/[id] Endpoint
Remove v1/awards/[id] Endpoint
[DEV-3867](https://federal-spending-transparency.atlassian.net/browse/DEV-3867)
- [N/A] Added Unit Tests for methods in Container Components, …
> Dev-3867 Remove v1/awards/[id] Endpoint

- src/js/helpers/accountQuartersHelper.js
Remove v1/federal_accounts/[id] endpoint
Remove v1/federal_accounts/[id] endpoint
[DEV-3867](https://federal-spending-transparency.atlassian.net/browse/DEV-3867)
- [N/A] Added Unit Tests for methods in …
> Dev-3867 Remove v1/federal_accounts/[id] endpoint

- tests/containers/account/awards/mockResponses.js
- tests/containers/search/table/mockAwards.js
Updates mock responses to current response page metadata.
[DEV-3867](https://federal-spending-transparency.atlassian.net/browse/DEV-3867)
**Mockup:**
- [N/A] Added Unit Tests …
> Dev-3867 Update mock responses

- src/_scss/components/tooltips/_customTooltipContent.scss
Centers titles for award amount tool tips
> [DEV-3862] centering award amount tooltip titles

- src/js/dataMapping/awardsv2/additionalDetailsContract.js
- src/js/dataMapping/awardsv2/additionalDetailsIdv.js
Updates text label for PSC in Acquisition details in additional details for idv's and contracts.
N/A
[DEV-3916](https://federal-spending-transparency.atlassian.net/browse/DEV-3916)
**Mockup:**
N/A
- [N/A] [API …
> Dev-3916 PSC Label Change in Additional Details

- src/js/components/bulkDownload/accounts/filters/AgencyFilter.jsx
- src/js/containers/bulkDownload/accounts/AccountDataContainer.jsx
- src/js/helpers/bulkDownloadHelper.js
- tests/containers/bulkDownload/mockData.js
Dropdown using v1 end point moved to v2
Adjusting request object / caller function signature & updating parsing of response 
[DEV-1722](https://federal-spending-transparency.atlassian.net/browse/DEV-1722)
Author:
`N/A` All …
> [BUG-DEV-1722] Migration of Custom Account Download Dropdown to v2 Endpoint

- src/js/components/bulkDownload/awards/filters/FileFormatFilter.jsx
- src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
Enable TSV File Download for Custom Awards
[DEV-597](https://federal-spending-transparency.atlassian.net/browse/DEV-597)
Author:
Reviewer(s):
> Dev-597 Enable TSV File Download for Custom Awards

- src/_scss/components/tooltips/_index.scss
- src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx
> STAGING --> DEV

- src/_scss/pages/awardV2/visualizations/overview/_agencyRecipient.scss
- src/_scss/pages/awardV2/visualizations/overview/_awardDates.scss
- src/_scss/pages/awardV2/visualizations/overview/_awardOverviewLeftSection.scss
- src/_scss/pages/awardV2/visualizations/overview/_relatedAwards.scss
- src/_scss/pages/awardV2/visualizations/overview/overview.scss
- src/js/components/awardv2/contract/ContractContent.jsx
- src/js/components/awardv2/financialAssistance/CFDAOverview.jsx
- src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx
- src/js/components/awardv2/idv/IdvContent.jsx
- src/js/components/awardv2/shared/overview/AgencyRecipient.jsx
- src/js/components/awardv2/shared/overview/AwardDates.jsx
- src/js/components/awardv2/shared/overview/AwardOverviewLeftSection.jsx
- src/js/components/awardv2/shared/overview/AwardOverviewRightSection.jsx
- src/js/components/awardv2/shared/overview/AwardingAgency.jsx
- src/js/components/awardv2/shared/overview/Recipient.jsx
- src/js/components/awardv2/shared/overview/RecipientAddress.jsx
- src/js/components/awardv2/shared/overview/RelatedAwards.jsx
- src/js/dataMapping/awardsv2/awardOverview.js
- src/js/helpers/awardSummaryHelper.js
- src/js/models/v2/CoreLocation.js
- src/js/models/v2/awardsV2/BaseFinancialAssistance.js
- tests/helpers/awardSummaryHelper-test.js
- tests/models/CoreLocation-test.js
Updates the Aggregate Awards Section to include details about the Recipient.
* refactors the overview section for IDVs, Contracts, and Financial Assistance Awards
* refactors the overview section to two columns: left and right sections
* refactors the left overview section to two components: awarding agency and recipient
* refactors the right section to handle related awards and cfda logic
* add data mapping for financial assistance awards relating to glossary text, glossary links, recipient names, text, and address fields
* adds helper to handle logic for address, text, and name for non financial assistance, redacted due to pii and the three cases fro multiple recipients: aggregated by county, aggregated by state, and aggregated by …
> Dev-1976 Aggregate Awards Section v2

- src/index.html
- src/js/components/bulkDownload/archive/table/TableRow.jsx
- src/js/containers/bulkDownload/helpers/downloadAnalytics.js
- tests/containers/bulkDownload/helpers/downloadAnalytics-test.js
- webpack/webpack.dev.config.js
Logs more info around user download behavior.
Updates download helper.js, logs every field relevant to analysis.
[DEV-3981](https://federal-spending-transparency.atlassian.net/browse/DEV-3981)
**Mockup:** `N/A`
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) …
> [DEV-3981] Providing Analytics on Download Behavior 

- src/js/components/awardv2/AwardV2.jsx
- src/js/components/awardv2/contract/ContractContent.jsx
- src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx
- src/js/components/awardv2/shared/AwardPageWrapper.jsx
- src/js/components/search/table/ResultsTable.jsx
- src/js/components/search/table/ResultsTableSection.jsx
- src/js/components/search/table/cells/ResultsTableLinkCell.jsx
- src/js/containers/awardV2/AwardV2Container.jsx
- src/js/containers/awardV2/shared/AwardHistorySectionContainer.jsx
- src/js/containers/search/table/ResultsTableContainer.jsx
- src/js/propTypes/index.js
- src/js/redux/actions/search/searchSubAwardTableActions.js
- src/js/redux/reducers/index.js
- src/js/redux/reducers/search/searchSubAwardTableReducer.js
- tests/redux/reducers/search/searchSubAwardTableReducer-test.js
[DEV-1453](https://federal-spending-transparency.atlassian.net/browse/DEV-1453)
**Mockup:**
N/A
Author:
Reviewer(s):
- [N/A] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`
> Dev-1453 Sub Award Link To Sub Award Table

- src/js/components/awardv2/shared/overview/AwardOverviewRightSection.jsx
Fixes IDV Related Awards Links not scrolling.
pass set related awards tab to related awards component
**Mockup:**
Author:
- [N/A] Added Unit Tests for methods in Container Components, reducers, and helper functions `if …
> Dev-1976 IDV Related Awards Links

- src/js/components/award/shared/overview/AwardOverviewRightSection.jsx
- src/js/components/award/shared/overview/Recipient.jsx
> Sprint 97 fix dev staging conflicts

- src/js/components/award/Award.jsx
- src/js/containers/award/AwardContainer.jsx
Accidentally deleted some of Jon's Code #1417; restoring it.
> [DEV-1453] restoring deleted code in AwardContainer

- src/js/helpers/awardSummaryHelper.js
- tests/helpers/awardSummaryHelper-test.js
This PR cleans up the logic handling for the isBadDates Award Helper and add checks for non existing dates.
* Before we were just checking if the properties existed and even if they were bad dates the dates were already turned into moment objects so that check is not valid. This PR updates the bad dates helper to check if the moment values are NaN.
* This PR also cleans up some duplicate logic.
[DEV-4019](https://federal-spending-transparency.atlassian.net/browse/DEV-4019)
**Mockup:**
https://bahdigital.invisionapp.com/share/H4IAC8SREXU#/screens
Author:
Reviewer(s):
> Warm-Fix Dev-4019 Dates Section Null Dates

- src/js/components/award/idv/activity/ActivityChartTooltip.jsx
- src/js/models/v2/awardsV2/BaseIdvActivityBar.js
Updates link to new award id
Updates model, removes references to `.id`
[DEV-3967](https://federal-spending-transparency.atlassian.net/browse/DEV-3967)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
> [DEV-3967] Updating activity chart piid link in tooltip

- src/js/components/award/shared/overview/ProgressBar.jsx
Re-render component when dates or milestone change.
* verify date and milestone changes on component did update in the progress bar.
[DEV-4019](https://federal-spending-transparency.atlassian.net/browse/DEV-4019)
Author:
Reviewer(s):
> Warm Fix Dev-4019 Re-render component when dates or milestone change

- README.md
[DEV-3831](https://federal-spending-transparency.atlassian.net/browse/DEV-3831)
> [dev-3831] updating readme

- src/js/components/award/contract/ContractContent.jsx
- src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
- src/js/components/award/idv/IdvContent.jsx
- src/js/components/award/shared/overview/AwardOverviewLeftSection.jsx
- src/js/components/award/shared/overview/Recipient.jsx
- src/js/components/award/shared/overview/RecipientAddress.jsx
- src/js/dataMapping/awards/awardOverview.js
- src/js/helpers/awardSummaryHelper.js
- src/js/models/v2/CoreLocation.js
- src/js/models/v2/awardsV2/BaseAwardRecipient.js
- src/js/models/v2/awardsV2/BaseFinancialAssistance.js
- src/js/models/v2/awardsV2/BaseIdv.js
- tests/helpers/awardSummaryHelper-test.js
- tests/models/CoreLocation-test.js
Please see Ross's comments in the ticket for details.
* add properties to core location for recipient address
* adds properties passed to core location from base recipient
* adds properties to core location
**Mockup:**
N/A
**Testing**
>	- Contract
> 		- Domestic
> 			- Full Data (str1, str2, city, state, zip, congress, country)
> 				- CONT_AWD_DEAC5206NA25396_8900_-NONE-_-NONE-
> 				- CONT_AWD_HSCGG804CPFF012_7008_-NONE-_-NONE-
> 			- only country
> 				CONT_AWD_HHS03T09000201D_7555_-NONE-_-NONE-
> 			- only city and country
> 				CONT_AWD_HHS006_7555_HHSP23320052056RB_7555
> 			- address line 1 city and country …
> Dev 1976 Update Recipient Address

- src/js/components/sharedComponents/patterns/RectanglePattern.jsx
Fixes a bug in the Rectangle Pattern component when there is no data.
> Bug Rectangle Pattern Component No Data

- src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
Adds pstxt option, removes xml.
Updates data mapping files.
[DEV-4167](https://federal-spending-transparency.atlassian.net/browse/DEV-4167)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future …
> [DEV-4167] adding pstxt option, removing xml

- src/js/components/award/shared/description/AwardDescription.jsx
- src/js/dataMapping/awards/tooltips.js
Adds new tooltip content.
Updates tooltip.js and ensures tooltip is wide
[DEV-3724](https://federal-spending-transparency.atlassian.net/browse/DEV-3724)
Author: …
> [dev-3724] adding tooltip for new idv description section

- src/_scss/pages/award/awardPage.scss
> [DEV-4100] adds missing comma

- scripts/buildSitemap.js
Removes reference to unused variable.
> [DEV-4036] follow up sitemap pr

- src/js/dataMapping/awards/awardOverview.js
update data mapping properties for PII to domestic and foreign
Reviewer(s):
> Dev-1976 Bug PII FA DataMapping

- src/js/dataMapping/awards/awardOverview.js
- src/js/models/v2/CoreLocation.js
- tests/models/CoreLocation-test.js
* dev-1976 provide state for foreign contracts
* dev-1976 add test for contract and idv recipient address
> Staging -> Dev = Warm Fix Dev-1976 provide state for foreign contracts (#1472) 

- src/js/components/account/visualizations/sankey/SankeyVisualizationVertical.jsx
- src/js/components/account/visualizations/sankey/components/SankeyFlowVertical.jsx
- src/js/containers/account/filters/AccountProgramActivityContainer.jsx
Federal account page not displaying when view port changes
Updates the logic around didUpdate
[DEV-3694](https://federal-spending-transparency.atlassian.net/browse/DEV-3694)
Author:
`N/A` [Component …
> [dev-3694] handling didUpdate properly so component Displays on Mobile view

- src/js/components/award/contract/ContractContent.jsx
- src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
- src/js/containers/award/AwardContainer.jsx
- tests/containers/award/AwardContainer-test.jsx
- tests/containers/state/StateContainer-test.jsx
Resolves conflict from warm fixes to staging & new pushes to dev on the same file
> Staging --> DEV, w/ conflicts Resolved

- src/_scss/pages/homepage/features/_featurePane.scss
Max width property not working in ie11. Moving to width doesn't break anything.
max-width --> width
[DEV-4062](https://federal-spending-transparency.atlassian.net/browse/DEV-4062)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future …
> [DEV-4062] moving max-width to width

- src/js/components/glossary/Glossary.jsx
Allows user to have glossary open but focus elsewhere
removes method that was preventing focus from being changed
[DEV-2366](https://federal-spending-transparency.atlassian.net/browse/DEV-2366)
Author:
`N/A` All componentWillReceiveProps, …
> [DEV-2366] removing trapFocus method

- scripts/buildSitemap.js
- src/js/containers/state/StateContainer.jsx
- tests/containers/state/StateContainer-test.jsx
Fixes two bugs:
- `componentDidUpdate` logic updated to no longer default to '/latest'
- updates sitemap logic
Very small updates..
[DEV-3798](https://federal-spending-transparency.atlassian.net/browse/DEV-3798)
> [DEV-3798] Updates sitemap logic & default /latest

- src/_scss/pages/homepage/features/_featurePane.scss
- src/js/components/homepage/features/PaneFeature.jsx
Formatting and link was broken in IE for the featured content section of the home page
- For formatting: replaces max-width with width
- For Link: replaces button tag w/ div tag (adds role attribute to anchor tag that's a child of the div for accessibility, tabbing still works)
Fixing the link required applying additional padding to the wrapper and the button to maintain consistent styles.
[DEV-4062](https://federal-spending-transparency.atlassian.net/browse/DEV-4062)
**Mockup:**
Author: …
> [DEV-4062] Fixes formatting on Featured Content in IE & Allows for Click

- scripts/pages.js
Removes invalid value in <changefreq> xml tag.
> [DEV-4036] Changing change frequency value to monthly from invalid value of quarterly

- scripts/buildSitemap.js
Down merging the sitemap changes that were hotfixed to prod.
> Down Merge Sitemap Hotfixes

- src/js/models/v2/CoreLocation.js
When the state is missing, do not show '--'.
[DEV-4415](https://federal-spending-transparency.atlassian.net/browse/DEV-4415)
**Mockup:**
Author:
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate …
> Dev-4415 Recipient Address

- src/_scss/all.scss
> removing comment in all.scss

- src/js/components/sharedComponents/pickers/FYPicker.jsx
Fixes bug where download was starting when you clicked the fiscal year.
> [DEV-4329] FY event preventDefault

- src/_scss/pages/agency/v2/index.scss
> [DEV-4386] Adding max-width styles for users on 1200px =< viewport

- src/js/components/sharedComponents/pickers/FYPicker.jsx
FY selector should sort FY in descending order.
> [DEV-4373] Account FY Sort in Descending order

- src/js/helpers/apiRequest.js
updates params function to use if statements to decode award id parameter.
> HotFix - updates apiRequest params function

- src/js/helpers/apiRequest.js
> Down Merge Hotfix #2 for ensuring all award ids are not encoded

- src/js/components/sharedComponents/pickers/FYPicker.jsx
- src/js/helpers/apiRequest.js
Ensuring post requests have decoded award ids
> DOWNMERGE #2 Encoded Award IDs in Post Requests

- package-lock.json
- package.json
- src/_scss/all.scss
- src/_scss/pages/award/idv/activity/idvActivity.scss
- src/_scss/pages/explorer/detail/visualization/table/_table.scss
- src/_scss/pages/recipientLanding/recipientLandingPage.scss
- src/js/app.jsx
- src/js/components/accountLanding/AccountLandingContent.jsx
- src/js/components/award/idv/activity/IdvActivityVisualization.jsx
- src/js/components/award/idv/referencedAwards/ReferencedAwardsTable.jsx
- src/js/components/award/shared/federalAccounts/FederalAccountsTable.jsx
- src/js/components/explorer/detail/visualization/table/ExplorerTable.jsx
- src/js/components/recipientLanding/RecipientLandingContent.jsx
Pagination Component:
- now expects resultsText boolean as a prop, defaults to false
- the onChangePage prop name renamed to changePage
- pageNumber prop name renamed to currentPage
- classNames in pagination component updated to be prefixed with dt-usa
- Changes how we import the scss
> [DEV-4254] Integrating w/ DT-UI v1.0.0

- package-lock.json
- package.json
- src/_scss/layouts/default/footer/_footerCopyright.scss
- src/_scss/layouts/default/footer/footer.scss
- src/js/components/about/About.jsx
- src/js/components/about/DBInfo.jsx
- src/js/components/about/legal/common/LegalPage.jsx
- src/js/components/account/Account.jsx
- src/js/components/account/InvalidAccount.jsx
- src/js/components/account/LoadingAccount.jsx
- src/js/components/accountLanding/AccountLandingPage.jsx
- src/js/components/agency/AgencyPage.jsx
- src/js/components/agencyLanding/AgencyLandingPage.jsx
- src/js/components/award/Award.jsx
- src/js/components/bulkDownload/BulkDownloadPage.jsx
- src/js/components/errorPage/ErrorPage.jsx
- src/js/components/explorer/ExplorerWrapperPage.jsx
- src/js/components/homepage/Homepage.jsx
- src/js/components/keyword/KeywordPage.jsx
- src/js/components/recipient/RecipientPage.jsx
- src/js/components/recipientLanding/RecipientLandingPage.jsx
- src/js/components/search/SearchPage.jsx
- src/js/components/sharedComponents/Footer.jsx
- src/js/components/state/StatePage.jsx
- src/js/components/stateLanding/StateLandingPage.jsx
- src/js/components/testStyles/TestStylePage.jsx
- src/js/containers/Footer.jsx
- src/js/containers/agency/AgencyContainerV2.jsx
Adds new social links.
- Adjusts mark up 
- Adds new styles
- New Icons
- Converts component to a container
[DEV-3539](https://federal-spending-transparency.atlassian.net/browse/DEV-3539)
**Mockup:**
https://bahdigital.invisionapp.com/share/UQIACV5NVYZ#/screens
Author:
`N/A`All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …
> [DEV-3539] Adds links to Twitter, Facebook, Github, Linkedin on Footer

- src/js/models/v2/CoreLocation.js
- tests/models/CoreLocation-test.js
Foreign Address Recipient for IDVs & Contracts updates including using state name and using `--` when zip or state name are present.
• use state name for contract and idvs
• use -- if state name or zip exist
• update test
[DEV-4415](https://federal-spending-transparency.atlassian.net/browse/DEV-4415)
**Mockup:**
N/A
Author:
- [N/A] [API …
> Dev-4415 Foreign Address Recipient for IDVs & Contracts

- src/_scss/pages/bulkDownload/form/downloadForm.scss
- src/js/components/bulkDownload/awards/AwardDataContent.jsx
- src/js/components/bulkDownload/awards/DownloadTooltip.jsx
- src/js/components/bulkDownload/awards/UserSelections.jsx
- src/js/components/bulkDownload/awards/filters/AwardLevelAndTypeFilter.jsx
- src/js/components/bulkDownload/awards/filters/LocationFilter.jsx
- src/js/components/sharedComponents/checkbox/CollapsedCheckboxType.jsx
- src/js/components/sharedComponents/checkbox/PrimaryCheckboxType.jsx
- src/js/components/sharedComponents/checkbox/SecondaryCheckboxType.jsx
- src/js/components/sharedComponents/checkbox/SingleCheckboxType.jsx
- src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
- src/js/containers/bulkDownload/awards/AwardDataContainer.jsx
- src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
- src/js/redux/actions/bulkDownload/bulkDownloadActions.js
- src/js/redux/actions/search/searchFilterActions.js
- src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js
- tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
- tests/containers/bulkDownload/mockData.js
- tests/redux/reducers/bulkDownload/bulkDownloadReducer-test.js
Few changes were made to the Custom Award Download:
* split Prime and Sub Award Type selection
* added Place of Performance as an option
* adjusted the download preview box to display new selected options
* update on-screen text
The bulk of the work for this PR is messing with the Redux state to account for the changes to Prime and Sub Award state. The UI changes are shown in screenshots below.
Prime and Sub Award Type changes:
Place of Performance as an option:
Adjusted Download preview box:
Updated the on-screen text:
[DEV-4430](https://federal-spending-transparency.atlassian.net/browse/DEV-4430)
**Mockup:**
N/A
Author:
Reviewer(s):
> [DEV-4430] Improvements to Custom Award Download page

- src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
- src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
- tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
Fix the order of Award Types and break out `Insurance` into a separate checkbox.
With breaking out the `Insurance` option into a different checkbox the award types now return the specific Award Type Code instead of the Award Type. 
[DEV-4430](https://federal-spending-transparency.atlassian.net/browse/DEV-4430)
**Mockup:**
N/A
Author:
Reviewer(s):
> [DEV-4430] Correct order and add Insurance type

- src/js/components/award/shared/activity/ActivityYAxis.jsx
- src/js/containers/award/shared/ContractGrantActivityContainer.jsx
Updates Y-Axis for Activity Charts to format tick labels using all tick Values.
Grants Activity title -> Grant Activity
[DEV-3106](https://federal-spending-transparency.atlassian.net/browse/DEV-3106)
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if …
> Warm-Fix Dev-3106 Activity Chart Y-Labels

- src/js/components/sharedComponents/header/Header.jsx
Removes the AFG Launch Banner.
Comments out the logic in componentDidMount to show the banner.
[DEV-3805](https://federal-spending-transparency.atlassian.net/browse/DEV-3805)
**Mockup:**
N/A
Author:
- [N/A] [API …
> Dev-3805 Hide Banner

- src/js/components/search/filters/awardAmount/AwardAmountSearch.jsx
- src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
- src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
- tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
> Staging -> Dev Bulk Download Foreign Country Fix

- src/js/dataMapping/awards/additionalDetailsContract.js
- src/js/dataMapping/awards/additionalDetailsIdv.js
Adds "(Parent PIID)" to parent award section for Contracts and IDVs
[3839](https://federal-spending-transparency.atlassian.net/browse/DEV-3839)
**Mockup:**
https://bahdigital.invisionapp.com/share/3KIABNW4PGR#/screens/296008376
Author:
Reviewer(s):
> [DEV-3839] Add parent piid to parent award section

- src/js/components/award/shared/overview/RelatedAwards.jsx
Change text in related awards section from `Parent Award` to `Parent Award ID (Parent PIID)`
[DEV-3839](https://federal-spending-transparency.atlassian.net/browse/DEV-3839)
Author:
Reviewer(s):
- N/A Design review complete
> [DEV-3839] Change Related awards section text

- src/js/components/award/shared/overview/RelatedAwards.jsx
POs decided they didn't want the previous text change after all, so we're putting it back.
[DEV-3839](https://federal-spending-transparency.atlassian.net/browse/DEV-3839)
Author:
Reviewer(s):
> Revert previous warmfix

- package-lock.json
- package.json
- src/_scss/all.scss
- src/_scss/components/_baseModal.scss
- src/_scss/layouts/default/header/nav/_fullMenu.scss
- src/_scss/pages/glossary/_animations.scss
- src/_scss/pages/glossary/glossaryPage.scss
- src/js/app.jsx
- src/js/components/homepage/EmailSignUp.jsx
- src/js/components/sharedComponents/RedirectModal.jsx
- src/js/components/sharedComponents/header/NavBar.jsx
Scope of delivery is:
a. Dark Release
b. No actual API call
So, just styles w/ functioning modal.
Using `DEV` globalCont for dark release.
[DEV-4511](https://federal-spending-transparency.atlassian.net/browse/DEV-4511)
**Mockup:**
https://bahdigital.invisionapp.com/d/main#/console/14220692/296031033/inspect
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
> [DEV-4511] Sign Up for Newsletter Modal & Global Nav Item

- src/js/components/award/shared/overview/RelatedAwards.jsx
- src/js/components/bulkDownload/awards/UserSelections.jsx
> "All" User Selection in Download Cetner Warmfix Down merge

- src/js/components/award/financialAssistance/CFDASection.jsx
- src/js/components/award/financialAssistance/CFDATree.jsx
Moves the note to only the tree view for the CFDA section.
Updates text per design.
Moves the note to only the tree view for the CFDA section.
Updates text per design.
[DEV-4697](https://federal-spending-transparency.atlassian.net/browse/DEV-4697)
**Mockup:**
https://bahdigital.invisionapp.com/share/57IAC6CHK84#/screens/295998954
Author:
- [N/A] [Component Library Integration Status …
> dev-4697 move note to tree only

- src/js/components/award/financialAssistance/CFDATable.jsx
- src/js/components/award/financialAssistance/CFDATree.jsx
- src/js/components/award/financialAssistance/CFDATreeTooltip.jsx
- src/js/containers/award/financialAssistance/CFDAVizContainer.jsx
Implements new titles for the cfda tree and table including the cfda number. The title column in the table will now sort by cfda number.
N/A
[DEV-4696](https://federal-spending-transparency.atlassian.net/browse/DEV-4696)
[DEV-4697](https://federal-spending-transparency.atlassian.net/browse/DEV-4697)
**Mockup:**
https://bahdigital.invisionapp.com/share/57IAC6CHK84#/screens/295998954
Author:
- [N/A] [API …
> Warm Fix Dev-4696-4697 CFDA Tree/Table Titles

- src/js/dataMapping/awards/transactionHistoryTable/loanTransactionHistoryTable.js
- src/js/models/v2/awards/transactions/BaseLoanTransaction.js
- tests/models/awards/transactions/BaseTransactions-test.js
Adds CFDA column to the loan transaction table on the award summary page
[DEV-3478](https://federal-spending-transparency.atlassian.net/browse/DEV-3478)
Author:
Reviewer(s):
> [WARMFIX] Add cfda to loan transaction table

- src/js/components/award/financialAssistance/CFDATree.jsx
Testing QAT auto deploy jenkins job
> test qat auto deploy

- src/js/components/award/financialAssistance/CFDATree.jsx
> remove test code for qat deploy

- src/js/components/account/filters/programActivity/ProgramActivityFilter.jsx
- src/js/containers/account/filters/AccountObjectClassContainer.jsx
- tests/containers/account/filters/AccountObjectClassContainer-test.jsx
Fed Account Program Activity Object Class Filter Bug
[DEV-4833](https://federal-spending-transparency.atlassian.net/browse/DEV-4833)
Author:
Reviewer(s):
> HotFix Dev-4833 Fed Account Program Activity Object Class Filter Bug

- src/js/helpers/searchHelper.js
Moves calls to the base `spending_by_category` endpoint to the specific category endpoint.
[DEV-4372](https://federal-spending-transparency.atlassian.net/browse/DEV-4732)
Author:
Reviewer(s):
> [DEV-4372] move spending_by_category to individual endpoints

- src/_scss/pages/search/results/visualizations/geo/map/_legend.scss
- src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
- src/js/components/search/visualizations/geo/MapLegend.jsx
- src/js/components/search/visualizations/geo/MapLegendHeader.jsx
- src/js/components/search/visualizations/geo/MapLegendTooltip.jsx
- src/js/components/search/visualizations/geo/MapWrapper.jsx
- src/js/containers/search/SearchSidebarSubmitContainer.jsx
- src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
- src/js/redux/actions/search/mapLegendToggleActions.js
- src/js/redux/reducers/index.js
- src/js/redux/reducers/search/mapLegendToggleReducer.js
- tests/containers/search/SearchSidebarSubmitContainer-test.jsx
- tests/containers/search/mockSubmit.js
- tests/containers/search/visualizations/geo/GeoVisualizationSectionContainer-test.jsx
- tests/redux/reducers/search/MapLegendToggleReducer-test.js
Adds Per Capita toggle to Advanced Search Map.
N/A
[DEV-4671](https://federal-spending-transparency.atlassian.net/browse/DEV-4671)
**Mockup:**
https://bahdigital.invisionapp.com/share/JKIAD6VA9CQ#/screens/296033712
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`
Reviewer(s):
- [N/A] Design review complete
- [N/A] [API …
> Dev-4671 Advanced Search Per Capita Spending

- src/_scss/pages/search/filters/otherFilters/_tasCheckbox.scss
- src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
Just adds a tooltip. Contains all other TAS prs from this sprint
Reusing CSS based tooltip
[DEV-4281](https://federal-spending-transparency.atlassian.net/browse/DEV-4281)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339)
`N/A` [API …
> TAS Tooltip

- src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Update the height of the Bad Data message to height of vis 198px.
N/A
[DEV-4787](https://federal-spending-transparency.atlassian.net/browse/DEV-4787)
**Mockup:**
N/A
Author:
- [N/A] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR
- [N/A] All componentWillReceiveProps, componentWillMount, and …
> Warmfix Dev-4787 Amount CFDA Bad Data Height

- src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Adds z-index to the dropdown list.
N/A
[DEV-4787](https://federal-spending-transparency.atlassian.net/browse/DEV-4787)
**Mockup:**
N/A
Author:
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
> WarmFix Dev-4787 Dropdown List Z-Index

- src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Increase Z-Index for the Dropdown.
[DEV-4787](https://federal-spending-transparency.atlassian.net/browse/DEV-4787)
Author:
Reviewer(s):
> WarmFix Dev-4787 Add More Z-Index

- src/_scss/pages/award/visualizations/cfdaSectionViz.scss
Downmerge increase in z-index.
> Downmerge Dev-4787 Add More Z-Index

- src/js/components/search/SearchSidebar.jsx
TAS search is being refactored. In the dark release logic, I changed the title of search criteria. 
Updates the string value of the relevant variable to what it was [here](https://github.com/fedspendingtransparency/usaspending-website/commit/475aa8372952ed4893602ac612b48420887ff381#diff-09a23a0c96c144f8019c0aa93b6e13a2L49)
N/A
Author:
`N/A` Verified that this PR does not create any *new* accessibility …
> [bug-hotfix-TAS-search-component-title] Fixing the title for the search sidebar

- src/js/helpers/tasHelper.js
This `fn` takes an array of hierarchical nodes and a code and returns the node with the given code, from the given tree.
This `fn` was using `.forEach` to do this, which means it was continuing to iterate through the current node hierarchy level even after it found the correct node.
Now, we're using `.find` to get the node at the current level, then using `.reduce` to recursively look at the next level. The benefit of this is that `.find` breaks the iteration once we get the node. `.reduce`, though, I'm assuming has the same problem as `.forEach`.
Feedback on how to optimize this further is welcome and needed! Perhaps we could just use `.find` recursively or optimize this a bit better. …
> [DEV-4278] Optimizing getTasNodeFromTree for Performance

- src/js/components/search/SearchSidebar.jsx
Down-merges change from 4/29 hotfixed to prod; also includes conflict resolution
> Down Merge from Master w/ Conflicts resolved

- src/_scss/pages/award/visualizations/cfdaSectionViz.scss
> • Advanced Search Text Change
> Down Merge Qat -> Dev

- package-lock.json
- package.json
> • Fixes a bug when accessing the tooltip container reference.
> Bump Component Lib to V1.1.1

- src/js/components/award/shared/activity/ContractGrantActivityChart.jsx
> • update setting the y domain to a cleaner solution
> Y-Domain Bug Contract Grant Activity

- package-lock.json
> Add checkbox tree build files

- Dockerfile
> Docker File Use NPM CI

- src/js/dataMapping/accountLanding/accountsTableFields.js
- tests/containers/accountLanding/AccountLandingContainer-test.jsx
Changes 'Managing Agency' to 'Owning Agency' in the Federal Account landing page table header. 
[DEV-5003](https://federal-spending-transparency.atlassian.net/browse/DEV-5003)
Author:
Reviewer(s):
> DEV-5003 Fed Acct landing page 'Owning Agency'

- src/_scss/pages/agency/v2/index.scss
- src/js/components/sharedComponents/pickers/FYPicker.jsx
- src/js/containers/agency/AgencyContainerV2.jsx
Updates sort order and active selection styles for FY picker
[DEV-4856](https://federal-spending-transparency.atlassian.net/browse/DEV-4856)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339)
`N/A` [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api …
> [DEV-4856] FY selector styles

- src/js/components/award/contract/ContractContent.jsx
- src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
- src/js/containers/award/shared/ContractGrantActivityContainer.jsx
Add Transactions Table Button
N/A
[DEV-4562](https://federal-spending-transparency.atlassian.net/browse/DEV-4562)
**Mockup:**
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`
Reviewer(s):
- [N/A] [API …
> Dev-4562 Add Transactions Table Button

- src/js/components/award/shared/activity/ContractGrantActivityChart.jsx
- src/js/helpers/contractGrantActivityHelper.js
- tests/helpers/contractGrantActivityHelper-test.js
Handles bug in the yDomain, updates edge case for domain and adds edge case for xDomain.
[DEV-4886](https://federal-spending-transparency.atlassian.net/browse/DEV-4886)
**Mockup:**
N/A
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library …
> Dev-4886 Handle Edge Case Bugs 

- src/js/components/search/SearchSidebar.jsx
Removes Dark release logic. Very simple.
[DEV-4469](https://federal-spending-transparency.atlassian.net/browse/DEV-4469)
**Mockup:**
Author:
Reviewer(s):
> [DEV-4469] releasing NAICS Checkbox Tree

- src/_scss/components/_SVGLine.scss
- src/_scss/pages/award/shared/contractGrantsActivity.scss
- src/js/components/award/shared/activity/ContractGrantActivity.jsx
- src/js/components/award/shared/activity/ContractGrantActivityChart.jsx
- src/js/components/award/shared/activity/ContractGrantActivityChartAreaPaths.jsx
- src/js/components/award/shared/activity/ContractGrantActivityChartVerticalLines.jsx
- src/js/components/sharedComponents/SVGLine.jsx
- src/js/containers/award/shared/ContractGrantActivityContainer.jsx
Adds Rectangles to Text Elements.
Adds Rectangles to Text Elements.
[DEV-4915](https://federal-spending-transparency.atlassian.net/browse/DEV-4915)
**Mockup:**
https://bahdigital.invisionapp.com/share/7HIADD8Q53D#/screens/296034820
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-status.md) updated `if applicable`
Reviewer(s):
- …
> Dev-4915 Vertical Line Text Overlap

- src/js/components/sharedComponents/SVGLine.jsx
Updates the potential award amount line upper bound to be graph height.
Updates the potential award amount line upper bound to be graph height.
[DEV-4556](https://federal-spending-transparency.atlassian.net/browse/DEV-4556)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container Components, reducers, and helper …
> Warm-Fix Bug Dev-4556 Potential Award Amount Line Upper Bound

- src/_scss/pages/award/shared/contractGrantsActivity.scss
Allows for hovering over the tooltip pointer.
N/A
[DEV-5194](https://federal-spending-transparency.atlassian.net/browse/DEV-5194)
**Mockup:**
N/A
Author:
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.ht …
> Dev-5194 Pointer Existence

- src/js/helpers/contractGrantActivityHelper.js
Add shading when last transaction value changes.
N/A
[DEV-5193](https://federal-spending-transparency.atlassian.net/browse/DEV-5193)
**Mockup:**
N/A
Author:
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …
> Dev-5193 Shading Last Transaction Value Change

- src/js/components/award/shared/activity/ContractGrantActivity.jsx
- src/js/containers/award/shared/ContractGrantActivityContainer.jsx
Transactions Use Total Obligation in One Day.
• update transactions on the same day to use total obligation for that day
• update percentage for the tooltip
[DEV-5192](https://federal-spending-transparency.atlassian.net/browse/DEV-5192)
**Mockup:**
https://bahdigital.invisionapp.com/share/7HIADD8Q53D#/screens/296028849
Author:
- [N/A] All …
> Dev-5192 Transactions Use Total Obligation in One Day

- src/js/components/award/shared/activity/PaginatedTooltip.jsx
- src/js/components/award/shared/activity/PaginatedTooltipContainer.jsx
Update pagination to be continuous.
N/A
[DEV-5195](https://federal-spending-transparency.atlassian.net/browse/DEV-5195)
**Mockup:**
N/A
Author:
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …
> Dev-5195 Continuous Page Buttons

- src/js/components/award/shared/activity/ContractGrantActivity.jsx
- src/js/components/award/shared/activity/ContractGrantActivityChart.jsx
- src/js/components/award/shared/activity/ContractGrantActivityChartCircles.jsx
Allow for tabbing through transaction tooltips.
Add Focus and Blur Events for Transactions Circles
[DEV-5196](https://federal-spending-transparency.atlassian.net/browse/DEV-5196)
**Mockup:**
N/A
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-document …
> Dev-5196 Allow for tabbing through transaction tooltips.

- src/_scss/pages/bulkDownload/dictionary/_dictionaryTable.scss
- src/js/containers/bulkDownload/dictionary/DataDictionaryContainer.jsx
* added purple to dictionary colors
* removed trailing spaces
* dev-4176 initial sort column no longer dependent on raw names
* added default sort
* linter appeasement
* updated purble to be more readable
* re-changed shade of purple
> Mod/dev 4176 add data dict color (#1698)

- src/js/components/award/shared/activity/ContractGrantActivityChart.jsx
- src/js/components/award/shared/activity/ContractGrantActivityChartAreaPaths.jsx
- src/js/helpers/contractGrantActivityHelper.js
- tests/helpers/contractGrantActivityHelper-test.js
Handles a bug when the today line is outside the scope of the domain.
> • Handle the today line like the rest of the vertical lines.
> • Add domain check to line helper. 
> • this is the award that was extending outside the graph ASST_NON_693JJ21930000Z240FLD218113_6925
[DEV-4886](https://federal-spending-transparency.atlassian.net/browse/DEV-4886)
**Mockup:**
N/A
Author:
- [N/A] All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …
> Bug Dev-4886 Domain Edge Cases

- src/_scss/pages/award/shared/contractGrantsActivity.scss
Removes padding added to tooltip sections that causes a bug.
> Bug Remove padding to grant contract activity chart tooltip text sections

- src/js/components/search/SearchSidebar.jsx
Expands the time period filter in advanced search.
> Bug Expand Time Period Filter in Advanced Search

- src/js/components/award/shared/InfoTooltipContent.jsx
- src/js/dataMapping/shared/tableTabsTooltips.jsx
pack is now back.
[DEV-5166](https://federal-spending-transparency.atlassian.net/browse/DEV-5166)
> Bug Dev-5166 Typo pack -> back

- src/js/components/award/shared/InfoTooltipContent.jsx
- src/js/components/search/SearchSidebar.jsx
- src/js/dataMapping/shared/tableTabsTooltips.jsx
> Demote warmfix qat -> dev

- src/js/containers/router/RouterRoutes.js
[DEV-5285](https://federal-spending-transparency.atlassian.net/browse/DEV-5285)
Author:
Reviewer(s):
> Dev-5285 Update Covid-19 Route Name

- pull_request_template.md
- tests/testResources/mockComponent.js
Updates the PR checklist
- Specifies which browsers are expected to be verified by the author
- Adds data models to the list of types of files to write unit tests for
- Removes `componentWillUpdate` from the list of lifecycle methods to update since all instances are gone
- Links to a USASpending Jira ticket about deprecated lifecycle methods (instead of a Broker one)
Author:
Reviewer(s):
> Update PR checklist

- src/js/components/award/contract/ContractContent.jsx
- src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
- src/js/containers/award/shared/ContractGrantActivityContainer.jsx
Release the Contract Grant Activity Container.
> Warm Fix - Release The Contract Grant Activity Container

- src/js/containers/covid19/Covid19Container.jsx
- src/js/dataMapping/covid19/covid19.js
- src/js/helpers/disasterHelper.js
- src/js/redux/actions/covid19/covid19Actions.js
- src/js/redux/reducers/covid19/covid19Reducer.js
- src/js/redux/reducers/index.js
- tests/redux/reducers/covid19/covid19Reducer-test.js
- tests/redux/reducers/covid19/mockData.js
Covid-19 page will now have access to DEFC codes.
> • integrate defc route with covid container
> • add codes reducers and action
> • stores codes in redux
N/A
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and …
> Integrate DEFC Route to COVID-19 Page

- src/_scss/pages/covid19/index.scss
- src/js/components/covid19/AwardQuestions.jsx
- src/js/components/covid19/Covid19Section.jsx
- src/js/components/covid19/Heading.jsx
- src/js/containers/covid19/Covid19Container.jsx
- src/js/containers/covid19/helpers/covid19.jsx
- src/js/models/covid19/OverviewModel.js
- tests/models/covid19/mockData.js
- tests/models/covid19/overview-test.js
Covid Overview Model
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3277](https://federal-spending-transparency.atlassian.net/browse/DEV-3277)
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library …
> Covid Overview Model & Two Info Sections

- src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
Updating content of tooltip and title of TAS filter.
[DEV-5254](https://federal-spending-transparency.atlassian.net/browse/DEV-5254)
Author:
`N/A` All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …
> [DEV-5254] updating tooltip copy for Tas per A/C 3 and 3a

- src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
> Qat -> Dev Tooltip Copy

- src/_scss/pages/covid19/_overviewData.scss
- src/_scss/pages/covid19/index.scss
- src/js/components/covid19/Covid19Section.jsx
- src/js/components/covid19/OverviewData.jsx
- src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
- src/js/containers/covid19/helpers/covid19.jsx
- src/js/helpers/disasterHelper.js
- src/js/helpers/metaTagHelper.js
Adds re-usable component and styling for the overview data rows that are present in many COVID profile page sections.
- Temporarily using the mock API
Relates to [DEV-5459](https://federal-spending-transparency.atlassian.net/browse/DEV-5459), a subtask of [DEV-5299](https://federal-spending-transparency.atlassian.net/browse/DEV-5299)
**Mockup:**
https://bahdigital.invisionapp.com/share/NGIAE7D7H6S#/296040947_COVID-19_Profile_-_Tab_Rework
Author:
Reviewer(s):
> DEV-5459 overview data component

- src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
[DEV-5254](https://federal-spending-transparency.atlassian.net/browse/DEV-5254)
> Dev-5254 Update Text

- src/js/components/recipient/RecipientOverview.jsx
Updated recipient overview heading in recipient section
**Jira Ticket**
https://federal-spending-transparency.atlassian.net/browse/DEV-5165
> Bug Fix - updated recipient overview heading in recipient section

- src/js/components/award/shared/activity/ContractGrantActivity.jsx
- src/js/components/recipient/RecipientOverview.jsx
- src/js/components/sharedComponents/DatePicker.jsx
- src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
- src/js/helpers/contractGrantActivityHelper.js
- tests/helpers/contractGrantActivityHelper-test.js
https://github.com/fedspendingtransparency/usaspending-website/pull/1765
https://github.com/fedspendingtransparency/usaspending-website/pull/1763
> Qat -> Dev

- src/_scss/pages/covid19/_budgetCategoriesTable.scss
- src/_scss/pages/covid19/spendingOverTime/_awardSpendingOverTime.scss
- src/js/components/agency/v2/CountTab.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- Accounts for the API contract change from `pagination_metadata` --> `page_metadata`
- Fixes padding on the count tabs used in multiple sections
Author:
Reviewer(s):
> Adjustments for code-sharing and api contract change

- src/js/components/award/shared/activity/ContractGrantActivity.jsx
> update action type text in circle tooltip

- src/js/containers/covid19/helpers/covid19.jsx
> Remove Award Spending Over Time from Covid Page

- src/_scss/pages/covid19/index.scss
> Updates Padding for info sections and footer

- src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
- src/_scss/pages/covid19/index.scss
- src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
- src/js/dataMapping/covid19/covid19.js
- src/js/helpers/disasterHelper.js
- src/js/models/v2/covid19/BaseSpendingByCfdaRow.js
- tests/containers/covid19/SpendingByCFDAContainer-test.jsx
- tests/models/covid19/BaseSpendingByCfdaRow-test.js
- tests/models/covid19/mockData.js
Updates the CFDA columns when the Loans tab is active
- Some console errors related to the Table component fixed in [this Component Library PR](https://github.com/fedspendingtransparency/data-transparency-ui/pull/46)
[DEV-5512](https://federal-spending-transparency.atlassian.net/browse/DEV-5512) (subtask of [DEV-5509](https://federal-spending-transparency.atlassian.net/browse/DEV-5509))
**Mockup:**
https://bahdigital.invisionapp.com/share/HYIAECFJKEV#/296042256_COVID-_CFDA_Listing_-__Loans
Author:
- N/A Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR - will give a full demo of this table with API integration …
> DEV-5509 CFDA table loans tab

- src/_scss/components/_moreOptionsTabs.scss
- src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
- src/js/components/sharedComponents/moreOptionsTabs/MoreOptionsTabs.jsx
- src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
- src/js/dataMapping/covid19/awardSpendingAgency/awardSpendingAgencyTableTabs.js
- src/js/helpers/disasterHelper.js
- src/js/helpers/moreOptionsTabs/moreOptionsTabsHelper.js
Updates the spending by agency loan column text.
Updates the spending by agency column order.
Fixes a resizing bug with the MoreOptionsTabs.
Fixes another bug with overflowing text for MoreOptionsTabs button.
**TODO** - when api is ready, enable it. Removed `do not merge` so that we can merge this in. Will open another PR for the api integration.
[DEV-5518](https://federal-spending-transparency.atlassian.net/browse/DEV-5518)
**Mockup:**
https://bahdigital.invisionapp.com/share/KWIAE7IT4H2#/screens
Author:
Reviewer(s):
> DEV-5518 update spending by agency loan column

- src/_scss/pages/covid19/recipient/recipientContainer.scss
- src/js/components/covid19/recipient/AwardFilterButton.jsx
- src/js/components/covid19/recipient/AwardFilterButtons.jsx
- src/js/containers/covid19/recipient/RecipientContainer.jsx
- src/js/containers/covid19/recipient/map/MapContainer.jsx
- src/js/dataMapping/covid19/recipient/map/map.js
Implements Award Type Buttons for other devs to use.
N/A
[DEV-5297](https://federal-spending-transparency.atlassian.net/browse/DEV-5297)
**Mockup:**
https://bahdigital.invisionapp.com/share/36IAEAWYCM4#/296043830_COVID-19_Profile_-_V3
Author:
- …
> Dev-5297 Adds Award Type Buttons to Recipient Section

- src/js/components/award/shared/overview/AwardOverviewRightSection.jsx
Corrects spelling error in the prop during component invocation of `<CfdaOverview />`
Spelling is hard!!
[DEV-5572](https://federal-spending-transparency.atlassian.net/browse/DEV-5572)
Author:
`N/A` Added Unit Tests for methods in Container Components, reducers, helper functions, and models `if …
> [DEV-5572] cfdaPropgram --> cfdaProgram

- src/_scss/components/_moreOptionsTabs.scss
- src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
Updates the agency tab count api call for `All Awards` .
Fixes some css bugs with the more options dropdown.
For the `All Awards` tab count for the spending by agency section, we pass in all `award_type_codes`.
N/A
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and …
> Update Agency Tab Count Api Call

- src/js/components/homepage/features/PaneFeature.jsx
Removes `www` from the url
[DEV-5402](https://federal-spending-transparency.atlassian.net/browse/DEV-5402)
Author:
Reviewer(s):
> DEV-5402 Warmfix Fiscal Data site url

- src/js/components/homepage/features/PaneFeature.jsx
Down Merging [warmfix PR](#1806 )
> Warm Fix Down Merge: Fixed fiscal data site url (#1806)

- src/js/components/search/table/ResultsTableSection.jsx
- src/js/dataMapping/search/awardTableColumns.jsx
Ensuring we send the API the correct request object to sort the table by covid 19 obligations / outlays
Updates a data mapping file to have the correct `title` property
[DEV-5202](https://federal-spending-transparency.atlassian.net/browse/DEV-5202)
Author:
`N/A` Added Unit Tests for methods in …
> [DEV-5202] Sorting the Advanced Serach Table on COVID 19 Column

- src/js/models/v2/award/BaseFederalAccountFunding.js
- tests/models/award/BaseFederalAccountFunding-test.js
Very minor tweak to Federal Account Funding period labels.
> [DEV-5487] Minor correction to period labels

- src/js/GlobalConstants.js
Allows for testing CARES act things in QAT.
[This line](https://github.com/fedspendingtransparency/usaspending-config/blob/master/ci/usaspending-frontend-nonprod.groovy#L103) in our deploy script ensures that with these changes all CARES ACT features will be visible in QAT, but not production.
Reviewer(s):
> [cares-act-release-to-qat] updating CARES feature flag to TRUE in QAT

- src/js/components/homepage/features/PaneFeature.jsx
fixed bad link
fixed bad link 
[DEV-5403](https://federal-spending-transparency.atlassian.net/browse/DEV-5403)
**Mockup:**
https://bahdigital.invisionapp.com/share/3CIAED36DHE#/screens
Reviewer(s):
> Warmfix/dev 5403/fix broken feature pane link

- src/js/containers/covid19/Covid19Container.jsx
COVID-19 footer link to advanced search populates search with DEF codes.
> • keep def codes as full data in COVID container
[DEV-5308](https://federal-spending-transparency.atlassian.net/browse/DEV-5308)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container …
> Dev-5308 Bug COVID-19 Footer Advanced Search Link

- src/js/components/homepage/features/PaneFeature.jsx
remove www from https://fiscaldata.treasury.gov/
remove www from https://fiscaldata.treasury.gov/
[DEV-5402](https://federal-spending-transparency.atlassian.net/browse/DEV-5402)
Author:
Reviewer(s):
> Warmfix/dev 5402/fix feature pane link

- src/js/components/covid19/AmountsVisualization.jsx
Update Visualization to show text.
N/A
[DEV-5610](https://federal-spending-transparency.atlassian.net/browse/DEV-5610)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced …
> Dev-5610 Amounts Viz Errors

- src/_scss/pages/covid19/recipient/recipientContainer.scss
- src/js/components/covid19/recipient/map/RecipientMapTooltip.jsx
- src/js/containers/covid19/recipient/map/MapContainer.jsx
- src/js/dataMapping/covid19/recipient/map/map.js
Adds award count to recipient map tooltips.
> • Use a combo of Explorer tooltip and Geovisualization tooltip to create the recipient map tooltip.
> • update data passed to new tooltip
[DEV-5667](https://federal-spending-transparency.atlassian.net/browse/DEV-5667)
**Mockup:**
https://bahdigital.invisionapp.com/share/F5IAEIVY8MP#/screens/296045216
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent …
> Dev-5667 Recipient Map Tooltip Number of Awards

- src/_scss/components/_moreOptionsTabs.scss
- src/_scss/pages/search/results/table/_tableTypes.scss
- src/js/components/search/table/ResultsTableTabItem.jsx
- src/js/components/sharedComponents/moreOptionsTabs/MoreOptionsTabs.jsx
Fixes tab functionality when tab count is zero. It should disable the tab, and the user shouldn't be able to click into it.
N/A
[DEV-5347](https://federal-spending-transparency.atlassian.net/browse/DEV-5347)
See AC number 3.
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …
> DEV-5347 disable tab when count zero

- src/_scss/pages/covid19/recipient/recipientContainer.scss
- src/js/components/covid19/recipient/map/MapFilters.jsx
- src/js/dataMapping/covid19/covid19.js
- src/js/dataMapping/covid19/recipient/map/map.js
Styling tweaks
Tweaking styles like this 👇 
Adds sort fn to persist sort order.
Tweaking the 
[DEV-5631](https://federal-spending-transparency.atlassian.net/browse/DEV-5631)
[DEV-5644](https://federal-spending-transparency.atlassian.net/browse/DEV-5644)
Author:
`N/A` All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …
> [DEV-5631 & DEV-5644] Updates Order, Text, and Styles of Dropdown on Recipient Map 

- src/_scss/pages/covid19/_sidebar.scss
- src/_scss/pages/covid19/_sidebarFooter.scss
- src/_scss/pages/covid19/index.scss
- src/js/components/covid19/SidebarFooter.jsx
- src/js/components/sharedComponents/sidebar/Sidebar.jsx
- src/js/containers/covid19/Covid19Container.jsx
- src/js/containers/covid19/helpers/covid19.jsx
- src/js/helpers/covid19Helper.js
Adds option in `Sidebar` for `Data Sources and Methodology`.
Adds `SidebarFooter` component underneath sidebar which contains a link to `Data Lab`.
Fixes inconsistencies with active `Sidebar` section when scrolling if some table rows are expanded.
Fixes bug when clicking on `Overview` and then subsequently another tab, would add too much spacing on the top.
[DEV-5632](https://federal-spending-transparency.atlassian.net/browse/DEV-5632)
**Mockup:**
https://bahdigital.invisionapp.com/share/6NIAEAQCAM9#/screens
Author:
- [N/A] Verified that this PR does not create any …
> DEV-5632 navigation sidebar fixes

- src/js/models/v2/award/BaseFederalAccountFunding.js
- tests/models/award/BaseFederalAccountFunding-test.js
When zero, show --
Updates model and test
[DEV-5678](https://federal-spending-transparency.atlassian.net/browse/DEV-5678)
Author:
`N/A` All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …
> [DEV-5678] Award Summary, Award History Table, Federal Funding Tab, Funding Obligated Column

- src/_scss/pages/search/_tooltips.scss
- src/js/components/search/SearchSidebar.jsx
- src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
Ensures consistency of DEFC terminology and abbreviation. `Disaster Emergency Fund Code (DEFC)` rather than `Disaster Emergency Fund (DEF) Code` or `Disaster and Emergency Fund Code (DEFC)` etc...
Updates content
[DEV-5677](https://federal-spending-transparency.atlassian.net/browse/DEV-5677)
Author:
`N/A` Verified that this PR does not create any *new* accessibility issues (via Axe Chrome …
> [DEV-5677] Finalize DEFC Filter Tooltip and Nomenclature

- src/_scss/pages/covid19/_tableMessages.scss
- src/_scss/pages/covid19/index.scss
- src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
Fixes losing place bug with pagination when updating page size or changing current page.
Adds a static height for the table as well as the loading.
Sets overflow-y to scroll.
[DEV-5638](https://federal-spending-transparency.atlassian.net/browse/DEV-5638)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-render …
> DEV-5638 losing place css

- src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
- src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
- src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
- src/js/dataMapping/covid19/covid19.js
- src/js/models/v2/covid19/CoreSpendingTableRow.js
- tests/containers/covid19/SpendingByRecipientContainer-test.jsx
- tests/models/covid19/BaseBudgetCategoryRow-test.js
- tests/models/covid19/BaseSpendingByCfdaRow-test.js
- tests/models/covid19/BaseSpendingByRecipientRow-test.js
- tests/models/covid19/CoreSpendingTableRow-test.js
- tests/models/covid19/mockData.js
Updated count variable to award_count in `CoreSpendingTableRow`
Updated from count to awardCount in various tables.
[DEV-5626](https://federal-spending-transparency.atlassian.net/browse/DEV-5626)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container Components, reducers, helper functions, …
> DEV-5626 count -> award_count

- src/js/components/covid19/Covid19Section.jsx
- src/js/components/covid19/budgetCategories/BudgetCategories.jsx
- src/js/components/sharedComponents/sidebar/Sidebar.jsx
- src/js/containers/covid19/Covid19Container.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- src/js/helpers/covid19Helper.js
Expanded table rows will remain expanded while scrolling.
> • Sidebar manages own active state if no active state is passed.
> • Sidebar manages jumpToSection if no active state is passed.
[DEV-5637](https://federal-spending-transparency.atlassian.net/browse/DEV-5637)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container Components, reducers, helper functions, …
> Dev-5637 Chevron Persistence on Scroll

- src/js/components/covid19/SearchBar.jsx
Prevents a bug causing the COVID Profile page to reload the first time the recipient search bar was used.
[DEV-5737](https://federal-spending-transparency.atlassian.net/browse/DEV-5737)
Author:
Reviewer(s):
> DEV-5737 fix recipient search bar bug

- src/js/components/covid19/SidebarFooter.jsx
Fixes sidebar footer link location.
Fixes sidebar footer link to go to data lab in a new tab.
Fixes sidebar footer overlapping with sidebar content.
[DEV-5632](https://federal-spending-transparency.atlassian.net/browse/DEV-5632)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …
> DEV-5632 sidebar more fixes

- src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
- src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
- src/js/dataMapping/covid19/recipient/recipient.js
Recipient Table Note
N/A
[DEV-5642](https://federal-spending-transparency.atlassian.net/browse/DEV-5642)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3277](https://federal-spending-transparency.atlassian.net/browse/DEV-3277)
- …
> Dev-5642 Recipient Table Note

- src/js/components/award/table/DetailsTabItem.jsx
Restore Award History Table Tab Display to normal.
N/A
[DEV-5722](https://federal-spending-transparency.atlassian.net/browse/DEV-5722)
**Mockup:**
N/A
Author: …
> Bug-5722 Award History Table Tab Display

- src/_scss/pages/covid19/_dataSourcesAndMethodology.scss
- src/js/components/covid19/DataSourcesAndMethodology.jsx
- src/js/containers/covid19/helpers/covid19.jsx
Updated copy in DSM section of COVID profile page.
1. Added in updated copy
2. Added in link to new DSM page
3. Updated "Other Resources" and URLs
4. Updated styling for this section
5. Added ampersand to DSM label in sidenav
Edited DataSourcesAndMethodology.jsx and _dataSourcesAndMethodology.scss
[DEV-5552](https://federal-spending-transparency.atlassian.net/browse/DEV-5552)
**Mockup:**
https://bahdigital.invisionapp.com/share/FRIAEJZY7PH#/screens/296044312
Author:
- [`N/A`] All `componentWillReceiveProps` and `componentWillMount` in relevant …
> Ftr/dev 5552/updating content in dsm and other resources

- package-lock.json
- package.json
See v1.1.5 release notes: https://github.com/fedspendingtransparency/data-transparency-ui/releases/tag/v1.1.5
[DEV-5049](https://federal-spending-transparency.atlassian.net/browse/DEV-5049)
[DEV-5687](https://federal-spending-transparency.atlassian.net/browse/DEV-5687)
Author:
Reviewer(s):
> Update component library to v1.1.5

- src/_scss/pages/covid19/visualizations/_amounts.scss
- src/js/components/covid19/AmountsVisualization.jsx
- src/js/dataMapping/covid19/covid19.js
Updates chart to new mock.
[DEV-5646](https://federal-spending-transparency.atlassian.net/browse/DEV-5646)
**Mockup:**
https://bahdigital.invisionapp.com/share/BCIAEH6UVTR#/screens/296044453
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future …
> Dev-5646 Amount Chart Updates

- src/js/components/search/topFilterBar/filterGroups/DefCodesFilterGroup.jsx
Removed extra "COVID-19 - " from the chip that shows selected COVID-19 filters in Advanced Search.
removed "${value.value} - " from the title key on line 42 of DefCodesFilterGroup.jsx
[DEV-5757](https://federal-spending-transparency.atlassian.net/browse/DEV-5757)
**Mockup:**
Reference image linked in ticket above
Author:
- [`N/A] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- [`N/A] Verified mobile/tablet/desktop/monitor responsiveness
- [`N/A] Verified that this PR does not create any *new* …
> [DEV-5757] Adv Search selected filter chip update

- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
Fixes bug where changing the spendingCategory was not fetching results because it was not in the useEffect hook as a dependency.
[DEV-5763](https://federal-spending-transparency.atlassian.net/browse/DEV-5763)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container Components, reducers, helper …
> DEV-5763 SpendingCategory not in useEffect

- src/js/containers/covid19/CovidModalContainer.jsx
- src/js/containers/covid19/homepage/CovidHighlights.jsx
> STAGING -- [DEV-5536] Closing Modal on Link Click

- src/js/components/homepage/features/PaneFeature.jsx
> Fix dev 5403 feature pane links

- src/_scss/pages/covid19/_budgetCategoriesTable.scss
- src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
Fixes alignment of child rows in COVID-19 Profile tables. 
Removed styles that were overriding the component library `Table` default styles.
[DEV-5772](https://federal-spending-transparency.atlassian.net/browse/DEV-5772)
Author:
Reviewer(s):
> QAT DEV-5772 fix expandable table row bug

- src/_scss/pages/covid19/_budgetCategoriesTable.scss
- src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
> Staging DEV-5772 fix expandable table row bug

- src/js/containers/covid19/SummaryInsightsContainer.jsx
- src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx
Fixes infinite loading bug for summary insights when it is zero.
Cleans up logic in `BudgetCategoriesTableContainer` and `AwardySpendingAgencyTableContainer`.
We are still getting a cancelled request, we might be able to fix it later, but it isn't causing an issue right now.
[DEV-5775](https://federal-spending-transparency.atlassian.net/browse/DEV-5775)
**Mockup:**
N/A
Author:
- [N/A] Verified that this PR does …
> QAT Bug DEV-5775 request cancelled bug

- src/js/components/search/filters/defc/DEFCheckboxTreeLabel.jsx
- src/js/containers/search/filters/def/DEFCheckboxTree.jsx
DEFC Advanced Search change requests.
- Add sort for DEFC to display in alphabetic order
- Parse string P.L. to Public Law
[DEV-5738](https://federal-spending-transparency.atlassian.net/browse/DEV-5738)
Author:
`N/A` Added Unit Tests for methods in Container Components, reducers, helper …
> QAT -- [DEV-5738] Parsing P.L. Acronym (Public Law) and Alphabetic Sort for Codes

- src/js/components/search/filters/defc/DEFCheckboxTreeLabel.jsx
- src/js/containers/search/filters/def/DEFCheckboxTree.jsx
DEFC Advanced Search change requests.
- Add sort for DEFC to display in alphabetic order
- Parse string P.L. to Public Law
[DEV-5738](https://federal-spending-transparency.atlassian.net/browse/DEV-5738)
Author:
`N/A` Added Unit Tests for methods in Container Components, reducers, helper …
> STAGING -- [DEV-5738] Parsing P.L. Acronym (Public Law) and Alphabetic Sort for Codes

- src/_scss/pages/data-sources/index.scss
- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Addresses edits for the Data Sources & Methodology page from DEV-5765.
N/A.
[DEV-5765](https://federal-spending-transparency.atlassian.net/browse/DEV-5765)
**Mockup:**
Copy edits were taken from the document posted in the following Jira comment:
https://federal-spending-transparency.atlassian.net/browse/DEV-5765?focusedCommentId=57966
Author:
Reviewer(s):
> QAT Bug/DEV-5765 - Content fixes for Data Sources & Methodology page

- src/_scss/pages/covid19/_budgetCategoriesTable.scss
- src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
- src/_scss/pages/data-sources/index.scss
- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
- src/js/components/homepage/features/PaneFeature.jsx
- src/js/containers/search/filters/def/DEFCheckboxTree.jsx
- src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
Addresses edits for the Data Sources & Methodology page from DEV-5765.
N/A.
[DEV-5765](https://federal-spending-transparency.atlassian.net/browse/DEV-5765)
**Mockup:**
Copy edits were taken from the document posted in the following Jira comment:
https://federal-spending-transparency.atlassian.net/browse/DEV-5765?focusedCommentId=57966
Author:
Reviewer(s):
> STAGING Bug/DEV-5765 - Content fixes for Data Sources & Methodology page

- src/_scss/pages/covid19/_budgetCategoriesTable.scss
- src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
- src/js/components/homepage/features/PaneFeature.jsx
- src/js/containers/covid19/SummaryInsightsContainer.jsx
- src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx
- src/js/containers/search/filters/def/DEFCheckboxTree.jsx
- src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
- src/js/helpers/disasterHelper.js
> Staging DEV-5774 assistance award count

- src/js/components/covid19/SearchBar.jsx
> Staging DEV-5602 clear search min chars

- src/_scss/pages/covid19/index.scss
- src/js/components/sharedComponents/sidebar/Sidebar.jsx
- src/js/containers/covid19/Covid19Container.jsx
Removes the flickering due to width for side bar.  Removes sidebar footer at the end of the page.
> • handle case where we know the side bar is sticky and set the width
> • hide sidebar footer at the bottom of the page
[DEV-5632](https://federal-spending-transparency.atlassian.net/browse/DEV-5632)
**Mockup:**
N/A
Author:
- …
> QAT Dev-5362 Some Sidebar Fixes

- src/_scss/components/_newBadge.scss
- src/_scss/layouts/default/header/nav/_dropdownMenu.scss
> QAT -- ie style changes

- src/_scss/pages/covid19/index.scss
- src/js/components/sharedComponents/sidebar/Sidebar.jsx
- src/js/containers/covid19/Covid19Container.jsx
> Staging Dev-5362 Some Sidebar Fixes 

- src/js/components/covid19/AmountsVisualization.jsx
- src/js/components/covid19/AwardQuestions.jsx
- src/js/components/covid19/Heading.jsx
- src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
- src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
- src/js/containers/covid19/CovidModalContainer.jsx
- src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
- src/js/containers/covid19/recipient/RecipientContainer.jsx
- src/js/dataMapping/covid19/recipient/map/map.js
Content edits based on 07.30 document linked in ticket below
Edited various files for homepage, COVID modal / banner, and COVID spending profile.
[DEV-5765](https://federal-spending-transparency.atlassian.net/browse/DEV-5765)
**Mockup:**
N/A - content updates in linked ticket above
Author:
- [`N/A`] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome …
> QAT -- Bug/dev 5765/updating latest mac content

- src/js/components/covid19/AmountsVisualization.jsx
- src/js/components/covid19/AwardQuestions.jsx
- src/js/components/covid19/Heading.jsx
- src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
- src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
- src/js/containers/covid19/CovidModalContainer.jsx
- src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
- src/js/containers/covid19/recipient/RecipientContainer.jsx
- src/js/dataMapping/covid19/recipient/map/map.js
Content edits based on 07.30 document linked in ticket below
Edited various files for homepage, COVID modal / banner, and COVID spending profile.
[DEV-5765](https://federal-spending-transparency.atlassian.net/browse/DEV-5765)
**Mockup:**
N/A - content updates in linked ticket above
Author:
- [`N/A`] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome …
> Staging -- Bug/dev 5765/updating latest mac content

- src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
Fixes and issue with the loans tab in the CFDA table making a request to spending and loans. It should only request to loans when clicking on the loans tab. 
[DEV-5786](https://federal-spending-transparency.atlassian.net/browse/DEV-5786)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container …
> QAT -- DEV-5786 cfda api bug

- src/_scss/components/tooltips/_customTooltipContent.scss
- src/_scss/pages/homepage/hero/_covid-hero.scss
- src/js/components/homepage/hero/CovidTooltip.jsx
Adding tooltip content to the homepage hero image tooltip
Edited `CovidTooltip.jsx` and changed font sizes in `_customTooltipContent.scss` to match other tooltips (16px heading and 14px body copy)
[DEV-5785](https://federal-spending-transparency.atlassian.net/browse/DEV-5785)
**Mockup:**
N/A - applicable text is noted in the above ticket
Author:
- [`N/A`] Verified that this PR does …
> QAT -- [DEV-5785] Adding tooltip content to homepage hero

- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Add copy edits from DEV-5787
N/A
[DEV-5787](https://federal-spending-transparency.atlassian.net/browse/DEV-5787)
**Mockup:**
N/A
Author:
Reviewer(s):
> QAT -- Bug/dev 5787/DSnM page content edits

- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Add copy edits from DEV-5787
N/A
[DEV-5787](https://federal-spending-transparency.atlassian.net/browse/DEV-5787)
**Mockup:**
N/A
Author:
Reviewer(s):
> STAGING -- Bug/dev 5787/DSnM page content edits

- package-lock.json
- package.json
- src/_scss/pages/covid19/_budgetCategoriesTable.scss
- src/js/components/covid19/SidebarFooter.jsx
- src/js/components/covid19/recipient/map/MapFilters.jsx
- src/js/components/glossary/GlossaryHeader.jsx
- src/js/components/sharedComponents/pickers/FYPicker.jsx
- src/js/components/sharedComponents/stickyHeader/StickyHeader.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js
- src/js/helpers/covid19Helper.js
Drop down styling tweaks for covid profile page
- Update to component library fixes issue with the share drop down being misaligned
- Updated props and styling for consistent dropdown behavior on the BudgetCategory section dropdown selector
[DEV-5697](https://federal-spending-transparency.atlassian.net/browse/DEV-5697)
[DEV-5631](https://federal-spending-transparency.atlassian.net/browse/DEV-5631)
Author:
`N/A` Added Unit Tests for methods in …
> STAGING -- [DEV-5697 & 5631] Share Dropdown Position fix & Budget Categories Dropdown Fix 

- src/js/containers/covid19/CovidModalContainer.jsx
No ticket for this one -- close modal on link click for DSM page.
> QAT -- Close COVID Modal on DSM Page Link Click 

- src/js/containers/covid19/CovidModalContainer.jsx
No ticket for this one -- close modal on link click for DSM page.
> STAGING -- Close COVID Modal on DSM Page Link Click 

- src/js/components/homepage/Homepage.jsx
Hiding the hero image.
Using the new phase 2 env var
[DEV-5809](https://federal-spending-transparency.atlassian.net/browse/DEV-5809)
Author:
`N/A` All `componentWillReceiveProps` …
> [DEV-5809] Hide Hero Image for Phase I Release of PROD

- src/_scss/pages/covid19/index.scss
- src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
- src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
- src/js/containers/covid19/recipient/RecipientContainer.jsx
Sets the award sections to coming soon.
**Mockup:**
N/A
Author:
Reviewer(s):
> [DEV-5807] Award Sections Coming Soon

- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Removes award spending section and sidebar link on the data sources page.
Author:
Reviewer(s):
> Dev-5807 Data Sources Page Remove Award Spending

- src/js/components/homepage/features/PaneFeature.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
- src/js/containers/covid19/CovidModalContainer.jsx
Homepage Pane Feature & Global Banner & Global Modal
Author:
Reviewer(s):
> Dev-5807 Homepage Pane Feature & Global Banner & Global Modal

- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
- src/js/containers/covid19/CovidModalContainer.jsx
> Dev-5807 DS&M Page Changes

- src/_scss/layouts/default/header/_warning.scss
- src/_scss/pages/covid19/index.scss
- src/_scss/pages/modals/covid19/_covid19.scss
- src/js/components/covid19/InterimDataDisclaimerModal.jsx
- src/js/containers/covid19/Covid19Container.jsx
- src/js/containers/globalModal/GlobalModalContainer.jsx
- src/js/propTypes/index.js
Introduces banner and modal to give info about preliminary release
- Adds Banner and modal. 
- Banner is currently not sticky or dismissable
**Mockup:**
Author:
`N/A` All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …
> [DEV-5807] COVID Profile Page Banner and Modal to indicate Preliminary release 

- src/_scss/layouts/default/header/_warning.scss
- src/_scss/pages/covid19/index.scss
- src/_scss/pages/modals/covid19/_covid19.scss
- src/js/GlobalConstants.js
- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
- src/js/components/covid19/DataSourcesAndMethodology.jsx
- src/js/components/covid19/InterimDataDisclaimerModal.jsx
- src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
- src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
- src/js/components/covid19/budgetCategories/BudgetCategories.jsx
- src/js/components/homepage/Homepage.jsx
- src/js/components/homepage/features/Features.jsx
- src/js/components/homepage/features/PaneFeature.jsx
- src/js/components/sharedComponents/header/Dropdown.jsx
- src/js/components/sharedComponents/header/InfoBanner.jsx
- src/js/components/sharedComponents/header/mobile/MobileDropdown.jsx
- src/js/containers/covid19/Covid19Container.jsx
- src/js/containers/covid19/CovidModalContainer.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- src/js/containers/covid19/recipient/RecipientContainer.jsx
- src/js/containers/globalModal/GlobalModalContainer.jsx
- src/js/propTypes/index.js
1. Branched off of `staging` to create the branch `resolve-conflicts`
2. Merged `qat` into `resolve-conflicts`
3. This PR will merge `resolve-conflicts` into `staging` and effectively promote the changes in QAT to Staging for the demo
> QAT -> staging resolve conflicts

- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
- src/js/components/covid19/InterimDataDisclaimerModal.jsx
- src/js/containers/covid19/Covid19Container.jsx
- Removed remaining references to linked data in the Data Sources & Methodology Download Instructions section
- Changed "many" to "some" in the COVID banner
- Removed bullets from the COVID modal and updated copy under "Preliminary Data"
Author:
- N/A (text changes only) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (text changes only) Verified mobile/tablet/desktop/monitor responsiveness
- N/A (text changes only) Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
Reviewer(s):
> final CARES Act Phase 1 edits

- src/_scss/pages/covid19/index.scss
- src/js/GlobalConstants.js
- src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
- src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
- src/js/containers/covid19/recipient/RecipientContainer.jsx
Revert Award Sections COVID-19 Page
[DEV-5808](https://federal-spending-transparency.atlassian.net/browse/DEV-5808)
Author:
Reviewer(s):
> QAT Revert Award Sections COVID-19 Page

- src/js/components/homepage/features/PaneFeature.jsx
Revert Feature Pane on homepage to GSA Link
[DEV-5808](https://federal-spending-transparency.atlassian.net/browse/DEV-5808)
> QAT Dev-5808 Revert Feature Pane on homepage to GSA Link

- src/js/components/homepage/features/PaneFeature.jsx
> STAGING Dev-5808 Revert Feature Pane on homepage to GSA Link 

- src/js/helpers/disasterHelper.js
- tests/helpers/disasterHelper-test.js
Disaster emergency fund codes ordered alphabetically
defCodeQueryString sorted and tests updated 
[DEV-5815](https://federal-spending-transparency.atlassian.net/browse/DEV-5815)
Author:
Reviewer(s):
> codes sorted, tests updated

- src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
Fixes sorting bug on recipient name and removes duplicate requests.
> • update recipient loan column mapping
> • update the way we are setting request
[DEV-5825](https://federal-spending-transparency.atlassian.net/browse/DEV-5825)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for …
> Dev-5825 Recipient Loan Sort & API Request Bug

- src/_scss/pages/covid19/_sidebar.scss
- src/_scss/pages/covid19/_stickyHeader.scss
- src/_scss/pages/covid19/index.scss
- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
- src/js/components/sharedComponents/sidebar/Sidebar.jsx
- src/js/containers/covid19/Covid19Container.jsx
- src/js/dataMapping/covid19/covid19.js
- src/js/helpers/covid19Helper.js
Makes the COVID banner in yellow dismissible and sticky.
- Updates conditional logic for scrolling behavior.
- Uses hook for sticky class
N/A
Author:
`N/A` All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …
> [DEV-5832] Make the Covid Banner Sticky and Dismissible

- src/js/components/search/visualizations/geo/MapWrapper.jsx
Advanced Search No Zoom for Congressional Districts and Counties
Advanced Search No Zoom for Congressional Districts and Counties
N/A
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in …
> Advanced Search No Zoom for Congressional Districts and Counties

- src/js/components/covid19/recipient/map/MapWrapper.jsx
> update to only call new exponential function only

- src/js/containers/covid19/recipient/RecipientContainer.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-5831?focusedCommentId=58880
[DEV-5831](https://federal-spending-transparency.atlassian.net/browse/DEV-5831)
Author:
`N/A` All …
> [DEV-5831] updating copy content for link to PDF

- src/_scss/components/_checkboxTree.scss
Removes grayed out scroll bar in covid-19 spending filters.
Changes `overflow-y` property to `auto` rather than `scroll`.
[DEV-5721](https://federal-spending-transparency.atlassian.net/browse/DEV-5721)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` …
> Fix DEV-5721 remove IE grayed out scrollbar

- package-lock.json
- package.json
- scripts/buildSitemap.js
- scripts/package-lock.json
- scripts/package.json
- scripts/pages.js
Adjusting sitemap script to be able to run behind a corp. proxy
axios tried to automatically configure a proxy if the HTTPS_PROXY environment variable is set. However, there is a known issue with HTTP -> HTTPS proxies where axios will attempt to connect on the incorrect port.
The solution to this issue is to manually configure the agent to use a proxy.
This PR includes:
- adding the tunnel package dependency
- configuring a tunnel agent
- configuring axios to use the tunnel agent
- defaulting to no agent if the PROXY_* environment variables are not set
- updating the URLs referenced to be explicit about the port used as to not confuse axios.
[OPS-1430](https://federal-spending-transparency.atlassian.net/browse/OPS-1430) …
> Adjusting sitemap script to be able to run behind a corp. proxy

- README.md
- webpack/webpack.dev.config.js
> Updates README and Default API ENV VAR

- src/js/containers/Footer.jsx
Update ordering of resources section to move Data Dictionary to the top
Reorder links in footer.jsx
[DEV-5405](https://federal-spending-transparency.atlassian.net/browse/DEV-5405)
**Mockup:**
https://federal-spending-transparency.atlassian.net/browse/DEV-5405
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …
> [DEV-5405] warmfix - reorder resources links

- src/_scss/pages/search/results/_tables.scss
- src/_scss/pages/search/results/searchResults.scss
- src/_scss/pages/state/_contentWrap.scss
- src/_scss/pages/state/_tables.scss
- src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
- src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
Adds WebGL error messages to state profile and advanced search maps.
[DEV-5776](https://federal-spending-transparency.atlassian.net/browse/DEV-5776)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …
> DEV-5776 [Warm-fix] added WebGL error messages to state profile and advanced search maps

- src/_scss/pages/search/results/_tables.scss
- src/_scss/pages/search/results/searchResults.scss
- src/_scss/pages/state/_contentWrap.scss
- src/_scss/pages/state/_tables.scss
- src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
- src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
> QAT -> Dev MapBoxGL

- src/_scss/pages/covid19/visualizations/_amounts.scss
- src/js/components/covid19/AmountsVisualization.jsx
- src/js/dataMapping/covid19/covid19.js
Amounts Chart Tooltips.
[DEV-5878](https://federal-spending-transparency.atlassian.net/browse/DEV-5878)
**Mockup:**
N/A
Author:
Reviewer(s):
> Dev-5878 amounts chart tooltips

- src/js/components/covid19/recipient/AwardFilterButtons.jsx
- src/js/components/covid19/recipient/SpendingByRecipient.jsx
- src/js/containers/covid19/recipient/map/MapContainer.jsx
https://federal-spending-transparency.atlassian.net/browse/DEV-5745 AC #1
> HotFix Dev-5745 Recipient Map Loan Filter Bug

- src/_scss/pages/data-sources/index.scss
- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
Fixes casing on back to link.
Adds css to fix location of copy confirmation message.
[DEV-5791](https://federal-spending-transparency.atlassian.net/browse/DEV-5791)
**Mockup:**
N/A
Author:
- …
> DEV-5791 fix casing and css for copy-confirmation

- src/_scss/pages/data-sources/index.scss
- src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
- src/js/components/search/filters/timePeriod/TimePeriod.jsx
https://github.com/fedspendingtransparency/usaspending-website/pull/2040
> Qat -> Dev Text Change

- src/index.ejs
> • add announcement in header per googles structured data spec https://developers.google.com/search/docs/data-types/special-announcements#structured-data-type-definitions
[DEV-5586](https://federal-spending-transparency.atlassian.net/browse/DEV-5586)
**Mockup:**
N/A
Author:
Reviewer(s):
> Dev-5586 Add COVID-19 Spending Data Announcement

- src/js/components/covid19/OtherResources.jsx
Updates link.
Updates link url.
[DEV-5883](https://federal-spending-transparency.atlassian.net/browse/DEV-5883)
Author:
`N/A` All `componentWillReceiveProps` and …
> [DEV-5883] Updates link for. DOL on COVID Profile Page per Request of Website owner

- src/index.ejs
https://github.com/fedspendingtransparency/usaspending-website/pull/2050
> DownMerge [DEV-5586] Add announcement for COVID-19 (PR #2050)

- src/js/containers/search/SearchSidebarSubmitContainer.jsx
- tests/containers/search/SearchSidebarSubmitContainer-test.jsx
https://github.com/fedspendingtransparency/usaspending-website/pull/2050
Hold up I got one two -Max
> Down Merge Qat -> Dev COVID-19 Announcement

- src/index.ejs
Remove Hashes from Google Announcement Links
Remove Hashes from Google Announcement Links
[DEV-5586](https://federal-spending-transparency.atlassian.net/browse/DEV-5586)
Author:
> Dev-5586 Remove Hashes from Google Announcement Links

- src/js/components/account/Account.jsx
- src/js/components/agency/AgencyPage.jsx
- src/js/components/award/Award.jsx
- src/js/components/recipient/RecipientPage.jsx
- src/js/components/state/StatePage.jsx
- src/js/helpers/metaTagHelper.js
Updates site titles and descriptions.
Changes helper data and converts some of them to be a fn for dynamic data.
[DEV-5971](https://federal-spending-transparency.atlassian.net/browse/DEV-5971)
Author:
`N/A` Added Unit Tests for methods in Container Components, reducers, helper functions, and …
> [DEV-5971] Updating Site Titles and Descriptions

- src/js/components/covid19/budgetCategories/BudgetCategories.jsx
Updates text.
[DEV-6062](https://federal-spending-transparency.atlassian.net/browse/DEV-6062)
Author:
`N/A` All …
> [DEV-6062] Updating text on COVID Profile Page per request from SBA 

- src/js/scripts/buildSitemap.js
Static.xml still had hashes in the url
> [sitemap-hash] removing hash from static.xml sitemap

- src/index.ejs
Adds `spatialCoverage`, `category` and `expires` fields to the Google Announcement.
[DEV-5586](https://federal-spending-transparency.atlassian.net/browse/DEV-5586)
**Mockup:**
Author:
Reviewer(s):
> Dev-5586 Google Announcement Additional Fields

- src/js/components/about/DataQuality.jsx
Updates link on the About pg.
[DEV-6081](https://federal-spending-transparency.atlassian.net/browse/DEV-6081)
Author:
> [DEV-6081] Fixing Link per request on the About Page

- src/js/containers/covid19/homepage/CovidHighlights.jsx
> [DEV-6076] updating hard-coded text on home page from June to July

- src/_scss/pages/covid19/_dataSourcesAndMethodology.scss
- src/_scss/pages/covid19/recipient/recipientContainer.scss
- src/js/components/covid19/AmountsVisualization.jsx
- src/js/components/covid19/DataSourcesAndMethodology.jsx
- src/js/components/covid19/OtherResources.jsx
- src/js/components/covid19/recipient/map/MapWrapper.jsx
- src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
- src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
- src/js/containers/covid19/helpers/covid19.jsx
- src/js/containers/covid19/recipient/map/MapContainer.jsx
Fixes mobile view of the COVID-19 profile page.
> • Update to css and html throughout the covid page.  Updates to the overview chart, recipient map loading, tables, and other resources sections.
[DEV-6079](https://federal-spending-transparency.atlassian.net/browse/DEV-6079)
**Mockup:**
N/A
Author:
- [ N/A] Added Unit Tests for methods in Container Components, reducers, helper functions, and models `if applicable` …
> Dev-6079 COVID-19 Profile Page Mobile Bugs

- src/js/components/about/DataQuality.jsx
- src/js/containers/covid19/homepage/CovidHighlights.jsx
https://github.com/fedspendingtransparency/usaspending-website/pull/2080
> Prod -> QAT #2080

- src/js/components/covid19/Covid19Tooltips.jsx
- src/js/containers/covid19/homepage/CovidHighlights.jsx
[#2085 ](https://github.com/fedspendingtransparency/usaspending-website/pull/2085)
> Down Merge qat -> dev 

- .github/ISSUE_TEMPLATE/question.md
> Issue Template for Questions

- .github/ISSUE_TEMPLATE/bug_report.md
> Bug Report Issue Template

- .github/ISSUE_TEMPLATE/feature_request.md
> Feature Request Issue Template

- src/_scss/pages/modals/covid19/_cfdaTable.scss
CFDA Modal URL Wrap
> • adds `break-all` to keep IE11 happy.
[DEV-5962](https://federal-spending-transparency.atlassian.net/browse/DEV-5962)
**Mockup:**
N/A
Author: …
> Dev-5962 CFDA Modal URL Wrap

- src/_scss/pages/award/awardFinancialAssistance.scss
- src/js/components/award/financialAssistance/SingleCFDA.jsx
Adds grants gov aspect to award summary assistance pages.
Reuses covid19 grants gov modal.
[DEV-6006](https://federal-spending-transparency.atlassian.net/browse/DEV-6006)
**Mockup:**
See Jira Ticket
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent …
> DEV-6006 adds grants gov aspect to award summary assistance pages

- src/_scss/pages/modals/covid19/_cfdaTable.scss
Updates the width of the modal on large screens to make the modal look correct on IE
Updates the width of the modal on large screens to make the modal look correct on IE
[DEV-5962](https://federal-spending-transparency.atlassian.net/browse/DEV-5962)
Author:
- [N/A] …
> Dev-5962 update min width for the modal on large screens

- src/js/helpers/metaTagHelper.js
> removing .gov from all site titles

- src/js/components/covid19/recipient/map/MapWrapper.jsx
- src/js/containers/covid19/Covid19Container.jsx
> [DEV-6128] updating url

- src/_scss/pages/covid19/_sidebar.scss
- src/js/components/covid19/SidebarFooter.jsx
- src/js/components/sharedComponents/sidebar/Sidebar.jsx
- src/js/containers/covid19/Covid19Container.jsx
Fixes sidebar footer flickering issue.
Migrates sidebar footer to be child of sidebar to avoid flickering issue.
[DEV-5764](https://federal-spending-transparency.atlassian.net/browse/DEV-5764)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3277](https://federal-spending-transparency.atlassian.net/browse/DEV-3277)
- [N/A] [API …
> DEV-5764 fix siderbar footer flickering issue

- src/js/components/covid19/recipient/map/MapWrapper.jsx
Update the ranges for mapping to avoid values outside of the range of the Array.
Scale was slightly off due to needed a sorted array for linear scale. Fix is to simply supply a min and max value since it is linear.
[DEV-6070](https://federal-spending-transparency.atlassian.net/browse/DEV-6070)
**Mockup:**
N/A
Author:
Reviewer(s):
> [DEV-6070] Update range for mapping scale

- src/js/components/covid19/recipient/map/MapWrapper.jsx
> [DEV-5819] COVID-Map Warm Fix PR #2114

- package-lock.json
- package.json
- src/_scss/components/tooltips/_customTooltipContent.scss
- src/_scss/components/tooltips/_index.scss
- src/_scss/components/visualizations/tooltip/_arrow.scss
- src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
- src/_scss/pages/award/shared/contractGrantsActivity.scss
- src/_scss/pages/homepage/hero/_covid-hero.scss
- src/js/components/homepage/hero/CovidTooltip.jsx
- Use new component library tooltip that keeps the tooltip visible when you mouse over the tooltip.
- Adds link to tooltip on homepage.
- Cleans up the Contract Activity tooltip that was using bottom positioning (touch up styles)
- Cleans up pointer styles
[DEV-2698](https://federal-spending-transparency.atlassian.net/browse/DEV-2698)
[DEV-6109](https://federal-spending-transparency.atlassian.net/browse/DEV-6109)
Author:
`N/A`Added Unit Tests for …
> [DEV-2698 & DEV-6109] Hoverable Tooltip

- package-lock.json
- package.json
> updating semver for component lib

- src/js/components/search/table/ResultsTable.jsx
- src/js/dataMapping/search/awardTableColumns.jsx
DEFC Column now allows sorting without displaying an error.
Differentiating title and displayName so that the API receives the accurate field name to sort
[DEV-5766](https://federal-spending-transparency.atlassian.net/browse/DEV-5766)
**Mockup:**
https://bahdigital.invisionapp.com/share/KCIAE86MRBA#/screens/296039704
Author:
- [`N/A`] Verified that this PR does not create any *new* …
> [DEV-5766] warmfix - fix sorting error for new DEFC column

- src/js/components/explorer/detail/visualization/toolbar/BreakdownDropdown.jsx
- src/js/components/sharedComponents/TreemapCell.jsx
- src/js/components/sharedComponents/filterSidebar/FilterOption.jsx
- src/js/components/sharedComponents/header/Header.jsx
- src/js/containers/explorer/detail/ExplorerDetailPageContainer.jsx
This PR updates all instances of componentWillMount to componentDidMount (5 instances).
Updating method signatures & removing setState instances in componentDidMount
[DEV-3266](https://federal-spending-transparency.atlassian.net/browse/DEV-3266)
**Mockup:**
N/A
Author:
- [`N/A`] Added Unit Tests for methods in Container Components, reducers, helper functions, and models `if …
> [DEV-3266] Remove instances of componentWillMount lifecycle method
