fedspendingtransparency/usaspending-website

src/_scss/components/_checkboxTree.scss
src/_scss/elements/inputs/_checkbox.scss
src/_scss/elements/inputs/_radio.scss
src/_scss/pages/bulkDownload/form/downloadForm.scss

Standardizes checkbox and radio btn colors to $color-primary.
Purely css to replace default checkboxes and radio buttons with custom css. 
Note: Styles don't apply to IE11 and Safari.
[DEV-6160](https://federal-spending-transparency.atlassian.net/browse/DEV-6160)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent …

DEV-6160 standardize checkbox and radio btn colors ($color-primary)

---

src/js/containers/AppContainer.jsx
src/js/helpers/analytics/Analytics.js

Down merge Hotfix

---

pull_request_template.md
src/js/components/account/visualizations/sankey/SankeyVisualizationHorizontal.jsx
src/js/components/account/visualizations/sankey/components/SankeyFlow.jsx
src/js/components/agency/visualizations/objectClass/MajorObjectClasses.jsx
src/js/components/agency/visualizations/objectClass/MinorObjectClasses.jsx
src/js/components/agency/visualizations/objectClass/ObjectClassCell.jsx
src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/visualization/toolbar/BreakdownDropdown.jsx
src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
src/js/components/glossary/definition/GlossaryDefinition.jsx
src/js/components/glossary/search/ResultItem.jsx
src/js/components/search/filters/timePeriod/TimePeriod.jsx
src/js/components/search/visualizations/rank/chart/ChartGroup.jsx
src/js/components/search/visualizations/rank/chart/HorizontalChart.jsx
src/js/components/search/visualizations/rank/chart/HorizontalXAxis.jsx
src/js/components/search/visualizations/time/chart/BarChart.jsx
src/js/components/sharedComponents/TreemapCell.jsx
src/js/components/state/visualizations/awardBreakdown/AwardBreakdownTreeMap.jsx
src/js/components/state/visualizations/awardBreakdown/AwardTypeCell.jsx
src/js/containers/account/visualizations/AccountTimeVisualizationContainer.jsx
src/js/containers/agency/visualizations/FederalAccountContainer.jsx
src/js/containers/agency/visualizations/RecipientContainer.jsx
src/js/containers/explorer/detail/ExplorerDetailPageContainer.jsx
src/js/containers/search/filters/TimePeriodContainer.jsx

Remove all instances of 'componentWillReceiveProps' and update to 'componentDidUpdate'
Renamed all componentWillReceiveProps instances and added helper methods to fix setState errors
[DEV-3277](https://federal-spending-transparency.atlassian.net/browse/DEV-3277)
**Mockup:**
N/A
Author:
- [`N/A`] [API contract](https://github.com/fedspendingtransparency/usaspendin …

[DEV-3277] Remove instances of componentWillReceiveProps lifecycle method (React v17)

---

src/js/components/sharedComponents/stickyHeader/ShareIcon.jsx

Add aria label to share input to update accessibility.
Author:
Reviewer(s):

Dev-6045 Aria Label Share Input

---

src/js/components/keyword/KeywordSearchBar.jsx
src/js/components/search/header/DownloadButton.jsx
src/js/components/sharedComponents/stickyHeader/StickyHeader.jsx

Removes critical accessibility issues from keyword search page.
Author:
Reviewer(s):

dev-6045 Keyword Search Accessibility

---

src/js/components/accountLanding/AccountLandingSearchBar.jsx
src/js/components/agencyLanding/AgencyLandingSearchBar.jsx
src/js/components/recipientLanding/RecipientLandingSearchBar.jsx

Update aria-label for Account, Agency, Recipient and State Landing Pages.
Author:
Reviewer(s):

Dev-6045 Profile Landing Pages Accessibility

---

src/js/components/bulkDownload/dictionary/DataDictionarySearchBar.jsx

adds aria label for input on data dictionary page.
Author:
Reviewer(s):

Dev-6045 Download Data Dictionary Aria Label

---

src/js/components/bulkDownload/accounts/filters/AccountLevelFilter.jsx
src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx

Adds aria labels for account download page.
Author:
Reviewer(s):

Dev-6045 Account Download Aria Labels

---

src/js/components/bulkDownload/awards/filters/AgencyFilter.jsx
src/js/components/bulkDownload/awards/filters/DateTypeFilter.jsx
src/js/components/bulkDownload/awards/filters/FileFormatFilter.jsx
src/js/components/bulkDownload/awards/filters/LocationFilter.jsx
src/js/components/search/filters/location/EntityDropdown.jsx

Ensure unique id's and adds aria labels to radio buttons.
Author:
Reviewer(s):

Dev-6045 Award Download Aria Labels & Unique Ids

---

src/js/helpers/searchHelper.js

Move endpoints to V2 because V1 is depreciated.
Most changes in backend. Front-end just needs URLs updated
[DEV-3991](https://federal-spending-transparency.atlassian.net/browse/DEV-3991)
[DEV-3992](https://federal-spending-transparency.atlassian.net/browse/DEV-3992)
Author:
Reviewer(s):

[ DEV-3991/ DEV-3992] refactor api/v1/references/hash and filter endpoints

---

src/js/components/award/idv/activity/chart/ActivityChart.jsx

Adds fill color to IDV Activity Chart
[DEV-6199](https://federal-spending-transparency.atlassian.net/browse/DEV-6199)
Author:
Reviewer(s):

Dev-6199 IE IDV Activity Chart Bug

---

src/js/components/award/idv/activity/chart/ActivityChart.jsx

[DEV-6199] Down Merge (PR #2153)

---

src/js/components/sharedComponents/filterSidebar/FilterOption.jsx
src/js/containers/covid19/homepage/CovidHighlights.jsx
src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/containers/search/filters/location/LocationPickerContainer.jsx
src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx

Addresses errors on home page and advanced search. Follow up pr to come from @afnazu addressing errors on advanced search during submit search.
- Adding componentWillunmount
- Adding `.catch` to a request on home page
[DEV-6046](https://federal-spending-transparency.atlassian.net/browse/DEV-6046)
Author:
`N/A` Verified that this PR does not create any *new* accessibility issues (via Axe Chrome …

[DEV-6046] Removing Console Errors (Pt 1)

---

package-lock.json
package.json

Bump DTUI to new version to include accessibility solutions.
Author:
Reviewer(s):

Dev-6045 bump DTUI

---

src/js/dataMapping/contracts/transactionTable.js

This PR changes the table label from "Reason for Modification" -> "Action Type"  to match Contract Activity Chart, Download, DAIMS, and the same column on the IDV page.
[DEV-4975](https://federal-spending-transparency.atlassian.net/browse/DEV-4975)
**Mockup:**
https://federal-spending-transparency.atlassian.net/browse/DEV-6248
Author:
- [`N/A`] Verified mobile/tablet/desktop/monitor …

[DEV-4975] Contract Award Summary: Reason for Modification -> Action Type

---

src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx
src/js/helpers/covid19Helper.js

Duplicate network requests were being made in these sections.
In each container, the same bug is present within the `addUnlinkedData` method, which is invoked in every case within the network request to populate the table. 
The solution of this bug was to create a new useEffect that invoked the method when a third param w/in the function (formerly not defined as a param) was defined. We listen for this change in the new useEffect which only calls `addUnlinkedData`, rather thank listening for it in the useEffect that calls the network request.
[DEV-6202](https://federal-spending-transparency.atlassian.net/browse/DEV-6202)
Author:
`N/A` Scheduled demo including …

[DEV-6202] Preventing Duplicate API Calls on Covid Profile PG Award Sections (CFDA, Recipient, Agency) 

---

package-lock.json
package.json
src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx

Fix Merge Conflicts Master to QAT

---

package-lock.json
package.json
src/js/components/award/idv/activity/IdvActivityVisualization.jsx
src/js/containers/award/idv/IdvActivityContainer.jsx
src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
tests/containers/award/idv/IdvActivityContainer-test.jsx

Fix Merge Commits I Blew Up

---

src/index.ejs
src/js/containers/AppContainer.jsx
src/js/helpers/analytics/Analytics.js

This PR replaces our current Google Analytics pageview tracking implementation with Google Tag Manager. 
Added timeout function to LogPageView in AppContainer to resolve page title delay issue; Changed pageview function in Analytics.js to push to dataLayer for GTM access
[DEV-6193](https://federal-spending-transparency.atlassian.net/browse/DEV-6193)
**Mockup:**
N/A
Author:
- [`N/A`] …

[DEV-6193] Track pageviews in Google Tag Manager

---

src/_scss/pages/aboutTheData/agenciesPage.scss
src/js/containers/AppContainer.jsx
src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/router/RouterRoutes.js

Skeleton of About the Data Agencies Page
N/A
[DEV-6292](https://federal-spending-transparency.atlassian.net/browse/DEV-6292)
**Mockup:**
https://bahdigital.invisionapp.com/d/main#/console/14220692/296049079/preview
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/d …

Dev-6292 About the Data Agencies Page

---

src/js/components/covid19/Covid19Tooltips.jsx
src/js/containers/covid19/helpers/covid19.jsx

Updating the title of the ‘Award Spending by Agency ’section to ‘Award Spending by Sub-Agency’. Also updates the tooltip!
Updates data mapping.
[DEV-6009](https://federal-spending-transparency.atlassian.net/browse/DEV-6009)
Author:
`N/A`Added Unit Tests for helper functions, reducers, models and …

[DEV-6009] COVID Profile PG Section title Update

---

src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx

Removing the duplicate request.
45e4012 - De-dupe fetchAwardAmounts request This request -- when for all awards -- is already made in
the Covid19Container. The intent of this commit is to use
that response when the active tab is for AllAwards
[DEV-6270](https://federal-spending-transparency.atlassian.net/browse/DEV-6270)
Author:
`N/A` Verified that this PR does not create any *new* accessibility …

[DEV-6270] Duplicate COVID Profile Page Network Requests

---

src/js/containers/router/RouterRoutes.js

Show about the data pages in dev and qat

---

src/js/containers/covid19/CovidModalContainer.jsx
src/js/containers/covid19/LinkToAdvancedSearchContainer.jsx
src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
src/js/containers/search/SearchContainer.jsx

There are a few high-priority (?) bugs in production that are being considered for a hotfix. This PR fixes them.
3a9f194 : (a) [fixing populating previous search when selecting adv search link](https://federal-spending-transparency.atlassian.net/browse/DEV-6338) (b) [fetching download availability](https://federal-spending-transparency.atlassian.net/browse/DEV-6399)
9137845 : fixing links to pre-populated advanced search stuff
[DEV-6399](https://federal-spending-transparency.atlassian.net/browse/DEV-6399)
[DEV-6338](https://federal-spending-transparency.atlassian.net/browse/DEV-6338)
**Mockup:**
Author:
`N/A` …

Advanced Search Bug Fixes & Spending Explorer 2020 Period Selection fix

---

src/_scss/pages/aboutTheData/agenciesDetailPage.scss
src/js/containers/aboutTheData/AgenciesDetailContainer.jsx
src/js/containers/router/RouterRoutes.js

Creates new URL route and implements agency detail page skeleton
added AgenciesDetailContainer
[DEV-6405](https://federal-spending-transparency.atlassian.net/browse/DEV-6405)
**Mockup:**
https://bahdigital.invisionapp.com/share/2FIAF0VV7UD#/screens
Author:
- [`N/A`] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [`N/A`] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [`N/A`] [Component Library Integration Status …

[DEV-6405] About the Data Agency Detail Page

---

package-lock.json
package.json
src/_scss/pages/aboutTheData/agenciesPage.scss
src/js/components/sharedComponents/stickyHeader/StickyHeader.jsx
src/js/containers/aboutTheData/AgenciesContainer.jsx

Implements the About the Data table w/ scrolling behavior included.
Applies sticky positioning on scroll
[DEV-6381](https://federal-spending-transparency.atlassian.net/browse/DEV-6381)
**Mockup:**
Author:
`N/A`Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
`N/A`[API contract](https://github.com/fedspendingtransparency/usaspending-api/ …

[DEV-6381] About the Data Table Mock Data & Scrolling UX

---

src/_scss/pages/aboutTheData/agenciesDetailPage.scss

Warmfix to add underline styling to external agency link on about the data agency detail page
[DEV-6405](https://federal-spending-transparency.atlassian.net/browse/DEV-6405)
**Mockup:**
https://bahdigital.invisionapp.com/share/85IAFKWZSEA#/screens/296052484
Author:
- [`N/A`] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [`N/A`] [API …

[DEV-6405] fix agency detail page external link underline

---

src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx

Issue with styling on table columns. They weren't wrapping like before 👇 (bad)
good 👇 
Adds mark up to table column title so that it has a single parent:
[DEV-6380](https://federal-spending-transparency.atlassian.net/browse/DEV-6380)
Author:
`N/A` [API …

[DEV-6380] Adds markup to Column Title

---

src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx

Removes extraneous `isUnlinkedRow` value in the last row of "Unknown Recipient (Unlinked Data)"
`isUnlinkedRow` was originally added to the row to prevent and infinite loop because `useEffect` was watching for changes to `results`. These changes create a new state variable, `parsedRows`, to store the finalized table data (including the Unlinked Row). This issue recently surfaced because the component library was updated to allow more items in each row than there are columns w/ the introduction of sub-columns.
[DEV-6475](https://federal-spending-transparency.atlassian.net/browse/DEV-6475)
Author:
Reviewer(s):

DEV-6475 Warmfix Recipient Unlinked Data row

---

package-lock.json
package.json

Bumps DTUI library to 1.3.2 to use new class names for tabs.

Dev-6379 Bumps DTUI to use 1.3.2

---

src/js/containers/router/RouterRoutes.js

Bug Show About The Data Agencies in QAT

---

src/js/components/search/visualizations/time/TimeVisualization.jsx

Hotfix Semicolon

---

src/_scss/pages/about/_section.scss
src/js/components/about/AboutContent.jsx
src/js/components/about/Careers.jsx

Add Careers section to the About Page.
> • add careers component
[DEV-6423](https://federal-spending-transparency.atlassian.net/browse/DEV-6423)
**Mockup:**
https://bahdigital.invisionapp.com/share/QWIAFPN83JC#/296052517_About
Author:
- [N/A] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR (Going to complete a design review with this ticket https://federal-spending-transparency.atlassian.net/browse/DEV-6454)
- [N/A] [API …

Dev-6423 Careers Section to About Page

---

src/_scss/pages/about/_section.scss
src/js/components/about/AboutContent.jsx
src/js/components/about/Careers.jsx
src/js/containers/Footer.jsx

Implements careers footer link.
> • refactor about page to component.
> • add link with state to footer link
> • contains https://github.com/fedspendingtransparency/usaspending-website/pull/2261
[DEV-6454](https://federal-spending-transparency.atlassian.net/browse/DEV-6454)
**Mockup:**
https://bahdigital.invisionapp.com/share/CBIAFJSDXP4#/screens/296052507
Author:
- [N/A] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) …

Dev-6454 Careers Footer Link

---

src/js/dataMapping/award/additionalDetailsContract.js
src/js/dataMapping/award/additionalDetailsIdv.js

Text Update Additional Details Contracts & IDVs
[DEV-6484](https://federal-spending-transparency.atlassian.net/browse/DEV-6484)
Author:
Reviewer(s):

Dev-6484 Text Update Additional Details Contracts & IDVs

---

package-lock.json

update 10 of the 20 low vulnerabilities.

NPM Audit Update 10 Packages

---

src/js/containers/search/SearchContainer.jsx
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/helpers/searchHelper.js
tests/containers/search/SearchContainer-test.jsx
tests/containers/search/filters/searchHelper.js
tests/containers/search/mockSearchHashes.js
tests/containers/search/table/ResultsTableContainer-test.jsx
tests/helpers/searchHelper-test.js

Currently we dont show a loading indicator until `/filter` resolves. Now, we show the indicator before we initiate the request for `/filter`.
Also does small refactoring to deduplicate network requests.
04fe3a0 - show indicator
8a32932 - deduplicate network request refactor
[DEV-6489](https://federal-spending-transparency.atlassian.net/browse/DEV-489)
Author:
`N/A` [API …

[DEV-6489] Advanced Search UX Degradation Fix

---

react-testing-library.md

Updating react testing library markdown

---

package-lock.json
package.json
src/js/components/search/visualizations/geo/MapWrapper.jsx
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/helpers/mapHelper.js
tests/components/sharedComponents/InfoBanner-test.jsx
tests/helpers/mapHelper-test.js

Resolves the merge conflict in #2293 by branching `qat` into `resolve-package-conflict`. Merged `master` into this branch and resolved the conflict. Merging `resolve-package-conflict` into `qat` down-merges the latest hotfixes, #2291 and #2292 .

Resolve master -> qat conflict

---

package-lock.json
package.json

removes Server-Side Request Forgery from axios dependency

upgrades axios to 21.1 to remove security vulnerability of SSRF

---

src/js/dataMapping/award/additionalDetailsIdv.js

Updates completed to competed in the competition details of the additional details section on the IDV Summary page.
completed to competed
[DEV-6484](https://federal-spending-transparency.atlassian.net/browse/DEV-6484)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for helper functions, …

Dev-6484 IDV Additional Details Text Update

---

scripts/sitemaps/package-lock.json
scripts/sitemaps/package.json

bump axios for security vulnerability in sitemaps code

---

package-lock.json
package.json

Updating component library version.

[increment-component-lib] v1.3.5

---

src/js/components/about/legal/common/LegalContent.jsx

update legal content side bar links
[DEV-6623](https://federal-spending-transparency.atlassian.net/browse/DEV-6623)
Author:
Reviewer(s):

update legal content side bar links

---

README.md

[update-readme] ENV VAR dox: API > USASPENDING_API

---

src/js/containers/aboutTheData/AgencyTableMapping.jsx

[DEV-6449] updating sort string for 2 columns on all agencies overview table

---

package-lock.json
package.json

Bump DTUI 1.3.6

---

src/js/containers/aboutTheData/AgencyTableMapping.jsx
src/js/models/v2/aboutTheData/PublicationOverviewRow.js
tests/models/aboutTheData/PublicationOverviewRow-test.js

Mockup: https://bahdigital.invisionapp.com/d/main#/console/14222399/296054007/preview

[DEV-6536] Period 1 and Period 2 are combined, actually

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyTableMapping.jsx
src/js/models/v2/aboutTheData/PublicationOverviewRow.js

Quick fixes for QAT described above ☝️
21941a8 -- Drilldown UX
120dc47 -- Associate period with proper quarter
[DEV-6536](https://federal-spending-transparency.atlassian.net/browse/DEV-6536)
Author:
`N/A` Added Unit Tests for helper functions, reducers, models and Container/Component …

[DEV-6536] Agency Details Page Drill down and Updating P07 to be under Q3

---

package-lock.json
package.json

Updates the website to use DTUI 1.3.7
N/A
[DEV-6539](https://federal-spending-transparency.atlassian.net/browse/DEV-6539)
**Mockup:**
N/A
Author:
Reviewer(s):

Dev-6539 Bump DTUI

---

src/js/containers/aboutTheData/AgencyTableMapping.jsx

Demo feedback: left-align the Agency Comments column
[DEV-6501](https://federal-spending-transparency.atlassian.net/browse/DEV-6501)
**Mockup:**
https://bahdigital.invisionapp.com/share/YUIAG2SZGE2
Author:
Reviewer(s):

DEV-6501 left-align Agency Comments column

---

src/js/containers/Footer.jsx
src/js/dataMapping/navigation/menuOptions.jsx

556d660 Only show updates to footer in QAT / DEV
6487a10 API Tutorial link opens in new tab

[DEV-6291] Dark Release Footer Updates & Open API Tutorial in new tab 

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyTableMapping.jsx

Incorrect:
Correct: 
- showing published date for periods
- showing `--` for not submitted

[About-The-Data] P4 should be in Q2, not Q1

---

src/js/components/aboutTheData/AboutTheDataPage.jsx

Mockup: https://bahdigital.invisionapp.com/share/5BIAFVV7KUX#/296054005_Default-View__Statistics-By-Reporting-Period

[DEV-6464] Updating copy content of Tab on About the data Page

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Adds spaces after the comma:
**Before:**
**After**:
Author:
`N/A` [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspendi …

[DEV-6721] Dynamic DEFC value list used inside <p> --> adding a space after comma

---

src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
tests/containers/aboutTheData/AgencyDetailsContainer-test.jsx

Seeking to offer greater validation in our tests we are not making duplicate requests.
See commit and message
Author:
`N/A` …

[tests-agency-details] About the Data Agency Details Pg Tests Refactor

---

src/js/containers/homepage/CovidHighlights.jsx

Bug when dates only load on first mount.
on mount -- if we have the submissionPeriods to parse the as of date, we set loading to false.
**JIRA Ticket**
[DEV-6871](https://federal-spending-transparency.atlassian.net/browse/DEV-6871)
Author:
`N/A` Added Unit Tests for helper functions, reducers, models and …

[DEV-6871] Home Page Data as of Bug (perpetual loading after refresh)

---

src/js/helpers/checkboxTreeHelper.js
tests/containers/search/filters/psc/mockPSC.js
tests/helpers/checkboxTreeHelper-test.js

Adds new condition to `addChildrenAndPossiblyPlaceholder` function + tests
See commit message
[DEV-6817](https://federal-spending-transparency.atlassian.net/browse/DEV-6817)
Author:
`N/A` [Component Library Integration Status …

[DEV-6871] PSC Search Loading Bug: addChildrenAndPossiblyPlaceholder Refactor

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/AgencyDetailsPage.jsx
src/js/components/aboutTheData/dataMapping/tooltipContentMapping.jsx

Copy updates to the Agency Submission Statistics page.
- Also fixes a bug with the tooltip mapping for the "Statistics by Submission Period" tab
- Includes some changes from running a code formatter (sorry)
[DEV-6770](https://federal-spending-transparency.atlassian.net/browse/DEV-6770)
Author:
Reviewer(s):

[DEV-6770] Submission Statistics copy

---

src/_scss/pages/aboutTheData/_agenciesPage.scss
src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/AgencyDetailsPage.jsx
src/js/components/sharedComponents/header/DropdownItem.jsx
src/js/dataMapping/navigation/menuOptions.jsx
tests/components/aboutTheData/AboutTheDataPage-test.jsx

Capturing the active table tab in the url; handling undefined url param
See commit msg
[DEV-6782](https://federal-spending-transparency.atlassian.net/browse/DEV-6782)
Author:
`N/A`  Verified mobile/tablet/desktop/monitor responsiveness
`N/A` [Component Library Integration Status …

[DEV-6782] capture active tab in URL on AboutTheDataPage

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/containers/aboutTheData/modals/UnlinkedDataContainer.jsx
src/js/helpers/aboutTheDataHelper.js
tests/containers/aboutTheData/UnlinkedDataContainer-test.jsx

Unlinked Modals API Integration
N/A
[DEV-6698](https://federal-spending-transparency.atlassian.net/browse/DEV-6698)
**Mockup:**
https://bahdigital.invisionapp.com/share/HTIAFWRXBYQ
Author:
- [N/A] Added Unit Tests for helper functions, reducers, models and Container/Component …

Dev-6698 Unlinked Modals API Integration

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
src/js/components/aboutTheData/DrilldownCell.jsx
src/js/containers/router/RouterRoutes.js

DS&M Page for about the data in the same styles 
see commits
[DEV-6749](https://federal-spending-transparency.atlassian.net/browse/DEV-6749)
Author:
`N/A` [Component Library Integration …

[DEV-6749] About the Data DS&M Page

---

src/js/GlobalConstants.js
src/js/components/sharedComponents/header/NavBar.jsx
src/js/components/sharedComponents/header/mobile/MobileNav.jsx
src/js/containers/Footer.jsx
src/js/containers/router/RouterRoutes.js

Un "dark-release" Agency Submission statistics URLs and navigation updates in the staging environment (for testing purposes).
* Adds a new Global Constants variable for staging
N/A
Reviewer(s):

Release Submission Statistics pages in Staging

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Updates copy on the COVID-19 Data Sources & Methodology page
Also removes some phased Covid release logic.
[DEV-6914](https://federal-spending-transparency.atlassian.net/browse/DEV-6914)
Author:
Reviewer(s):

[DEV-6914] Hotfix COVID Data Sources & Methodology copy

---

src/_scss/pages/data-sources/index.scss
src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Very minor updates to DS&M Pg
Removing extra characters, adding a space, and using the external link icon (w/o prompting redirect modal b/c it's a fiscal link)
[DEV-6749](https://federal-spending-transparency.atlassian.net/browse/DEV-6749)
Author:
Reviewer(s):

[DEV-6749] Copy Edits to DS&M PG

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/TimeFilters.jsx
src/js/components/sharedComponents/QuarterPickerWithFY.jsx
src/js/containers/account/WithLatestFy.jsx
src/js/helpers/aboutTheDataHelper.js
tests/components/aboutTheData/AboutTheDataPage-test.jsx
tests/components/aboutTheData/TimeFilters-test.jsx
tests/containers/account/WithLatestFy-test.js

Refactoring about the data page so logic/functionality can be reused in agency v2
See commit msg.
[DEV-4521](https://federal-spending-transparency.atlassian.net/browse/DEV-4521)
Author:
Reviewer(s):

[DEV-4521] Extracting Query Param FY/Period validation into new hook: useValideTimeBasedQueryParams

---

src/_scss/pages/agencyV2/_sidebar.scss
src/_scss/pages/agencyV2/index.scss
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/AgencySection.jsx
src/js/components/sharedComponents/sidebar/Sidebar.jsx
src/js/components/sharedComponents/sidebar/SidebarLink.jsx

Updates the Agency v2 sidebar to match latest mockup
[DEV-6356](https://federal-spending-transparency.atlassian.net/browse/DEV-6356)
**Mockup:**
https://bahdigital.invisionapp.com/share/WUIAG3CQ4JG#/296056413_agency-Profile-Mvp
Author:
Reviewer(s):

[DEV-6356] Agency v2 sidebar

---

src/js/containers/account/WithLatestFy.jsx
src/js/containers/agencyV2/AgencyContainerV2.jsx
tests/containers/account/WithLatestFy-test.js
tests/containers/agencyV2/AgencyContainerV2-test.jsx

Using hook for valid fy in query param of url.
See commit msg.
[DEV-4521](https://federal-spending-transparency.atlassian.net/browse/DEV-4521)
Author:
Reviewer(s):

[DEV-4521] using useValidTimeBasedQueryParams in Agency V2 pt II (Contains pt I)

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Minor update to the COVID-19 Data Sources & Methodology page
[DEV-6973](https://federal-spending-transparency.atlassian.net/browse/DEV-6973)
Author:
Reviewer(s):

Warmfix COVID Data Sources & Methodology copy

---

package-lock.json
package.json

Bump DTUI for https://github.com/fedspendingtransparency/usaspending-website/pull/2428 and https://github.com/fedspendingtransparency/usaspending-website/pull/2429

dev-6810 bump dtui

---

src/_scss/pages/covid19/_overviewData.scss
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx
src/js/components/covid19/recipient/SpendingByRecipient.jsx
src/js/containers/covid19/recipient/RecipientContainer.jsx
src/js/containers/covid19/recipient/map/MapContainer.jsx

Updates the covid-19 page to use tabs from component library.
[DEV-6810](https://federal-spending-transparency.atlassian.net/browse/DEV-6810)
**Mockup:**
https://bahdigital.invisionapp.com/d/main#/console/14222472/296055984/preview
Author:
Reviewer(s):
- [N/A] Design review complete `if …

Dev-6810 COVID-19 Page Tabs

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/AgencySection.jsx
src/js/containers/account/WithLatestFy.jsx
src/js/containers/agencyV2/AgencyContainerV2.jsx
src/js/helpers/queryParams.js
tests/components/aboutTheData/AboutTheDataPage-test.jsx
tests/containers/account/WithLatestFy-test.js
tests/containers/agencyV2/AgencyContainerV2-test.jsx
tests/helpers/queryParams-test.js

Removing page level loading indicator behavior to a section level loading indicator.
Also moving some props from highest level that dont need to be there.
see commit message.
[DEV-4521](https://federal-spending-transparency.atlassian.net/browse/DEV-4521)
Author:
Reviewer(s):

[DEV-4521] Agency v2 FY Picker pt III (Contains pt I and pt II

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Promote warmfix qat -> staging

---

scripts/sitemaps/buildSitemap.js
scripts/sitemaps/pages.js
src/js/components/award/shared/overview/Recipient.jsx
src/js/components/recipient/RecipientMultiParentCollapse.jsx
src/js/components/sharedComponents/metaTags/MetaTags.jsx
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
src/js/helpers/metaTagHelper.js
tests/containers/covid19/SpendingByRecipientContainer-test.jsx
tests/helpers/aboutTheDataHelper-test.js
tests/helpers/metaTagHelper-test.js

Updates Robots.txt, fixes broken links, and implements the canonical tag.
see commits
[DEV-6937](https://federal-spending-transparency.atlassian.net/browse/DEV-6937)
Author:
Reviewer(s):

[DEV-6937] Changes from SEO Audit pt I

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Restoring changes from https://github.com/fedspendingtransparency/usaspending-website/pull/2437

Restoring DS&M copy

---

package-lock.json
package.json

updating dtui

---

src/_scss/components/_stickyTable.scss
src/_scss/pages/aboutTheData/_agenciesPage.scss
src/_scss/pages/aboutTheData/_agencyDetailsPage.scss
src/_scss/pages/covid19/_budgetCategoriesTable.scss
src/_scss/pages/covid19/_tables.scss
src/_scss/pages/covid19/_unlinkedData.scss
src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
src/_scss/pages/covid19/awardSpendingAgency/_awardSpendingAgency.scss
src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyDetailsContainer.jsx

A couple of adjustments to our table styles to go with https://github.com/fedspendingtransparency/data-transparency-ui/pull/81
[DEV-6887](https://federal-spending-transparency.atlassian.net/browse/DEV-6887)
Author:
Reviewer(s):

DEV-6887 table styling updates

---

src/js/components/account/visualizations/sankey/SankeyVisualizationHorizontal.jsx
src/js/components/account/visualizations/sankey/SankeyVisualizationVertical.jsx

[DEV-6970] Federal Accounts Sankey Copy Edit:

---

src/_scss/pages/agencyV2/index.scss
src/_scss/pages/covid19/index.scss
src/js/components/agencyV2/AgencySection.jsx
src/js/components/covid19/Covid19Section.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/containers/covid19/helpers/covid19.jsx

Updating COVID Profile PG and Agency V2 to use new component
Erasing a couple styles, invoking component
[DEV-6590](https://federal-spending-transparency.atlassian.net/browse/DEV-6590)
Author:
Reviewer(s):

[DEV-6590] Using new Section Title Component from DTUI

---

src/js/components/agencyV2/accountSpending/AccountSpending.jsx
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
src/js/containers/agencyV2/accountSpending/TableContainer.jsx
tests/components/agency/AccountSpending-test.jsx

Down Merge Warmfix to QAT #2453

---

src/js/components/agencyV2/accountSpending/AccountSpending.jsx
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
src/js/containers/agencyV2/accountSpending/TableContainer.jsx
tests/components/agency/AccountSpending-test.jsx

QAT --> Staging

---

src/js/components/explorer/detail/UnreportedErrorScreen.jsx

[DEV-7079] Updating copy for unreported data

---

src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx

Copy update, per GAO
none
[DEV-7035](https://federal-spending-transparency.atlassian.net/browse/DEV-7035)
Author:
Reviewer(s):

dev 7035 update wording

---

src/js/components/aboutTheData/AboutTheDataPage.jsx

Updates link to DTM on the Agency Statistics page.

update link to DTM

---

package-lock.json
package.json

Bump DTUI to 2.2.0

---

src/_scss/components/_picker.scss
src/_scss/layouts/default/stickyHeader/_toolbar.scss
src/_scss/pages/agencyV2/index.scss
src/_scss/pages/recipient/recipientPage.scss
src/_scss/pages/state/statePage.scss
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/recipient/RecipientPage.jsx
src/js/components/sharedComponents/stickyHeader/DownloadIconButton.jsx
src/js/components/sharedComponents/stickyHeader/ShareIcon.jsx
src/js/components/sharedComponents/stickyHeader/StickyHeader.jsx
src/js/components/state/StatePage.jsx
src/js/helpers/apiRequest.js
src/js/helpers/socialShare.jsx
src/js/helpers/stickyHeaderHelper.js

New header on 3 pages
See commits
[DEV-6889](https://federal-spending-transparency.atlassian.net/browse/DEV-6889)
**Mockup:**
Author:
Reviewer(s):
`N/A` [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`

[DEV-6889] Implements new Page Header on Agency V2, State & Recipient Page

---

package-lock.json
package.json
src/_scss/layouts/default/header/header.scss
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/recipient/RecipientContent.jsx
src/js/components/recipient/RecipientPage.jsx
src/js/components/state/StateContent.jsx
src/js/components/state/StatePage.jsx
src/js/helpers/fiscalYearHelper.js

Didn't realize adding the FY was in the A/C of this ticket. Small change to include it and decoupled from #2494 which implements the header everywhere on the application.
see commits
[DEV-6889](https://federal-spending-transparency.atlassian.net/browse/DEV-6889)
Author:
Reviewer(s):
`N/A`[API …

[DEV-6889] AC #6 -- Adding FY to Page Header on State / Recipient Page Header

---

src/_scss/pages/search/results/visualizations/geo/geoVisualization.scss
src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
src/js/dataMapping/search/geoVisualizationSection.jsx

Adds a note to the advanced search results below the map.
> • data mapping file for geo-visualization section.
> • add note and css to geo-visualization section.
[DEV-1958](https://federal-spending-transparency.atlassian.net/browse/DEV-1958)
**Mockup:**
N/A
Author:
- [N/A] [Component Library Integration Status …

Dev-1958 Advanced Search Results Map Note

---

src/_scss/pages/agencyV2/index.scss
src/_scss/pages/agencyV2/overview/_fySummary.scss
src/_scss/pages/agencyV2/overview/_overview.scss
src/_scss/pages/agencyV2/overview/_visualizationSection.scss
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/overview/AgencyOverview.jsx
src/js/components/agencyV2/overview/FySummary.jsx
src/js/components/agencyV2/overview/VisualizationSection.jsx
tests/components/agency/AgencyOverview-test.jsx

Implements the layout of the Agency v2 FY Summary section.
- Using mock data to avoid duplicate data fetching while the visualizations are also in progress
[DEV-6358](https://federal-spending-transparency.atlassian.net/browse/DEV-6358)
**Mockup:**
Mobile: https://bahdigital.invisionapp.com/share/Z9IAG5XBJQY
Desktop: https://bahdigital.invisionapp.com/share/WUIAG3CQ4JG#/296056413_agency-Profile-Mvp
Author:
- N/A Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` - LMK if you disagree!
Reviewer(s):

DEV-6358 agency v2 FY Summary section scaffolding

---

package-lock.json

Fix NPM Audit

---

package-lock.json

NPM Audit Fix (cherrypicking commit from dev)

---

src/js/GlobalConstants.js
src/js/components/award/financialAssistance/RectanglePercentViz.jsx
src/js/components/award/shared/awardAmountsSection/AwardAmountsSection.jsx
src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx
src/js/components/homepage/features/Features.jsx
src/js/components/homepage/features/PaneFeature.jsx
src/js/components/search/SearchSidebar.jsx
src/js/containers/award/idv/IdvAwardAmountsSectionContainer.jsx
src/js/containers/covid19/CovidModalContainer.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
src/js/dataMapping/search/awardTableColumns.jsx
tests/testResources/mockGlobalConstants.js

Adds a constant variable that can be used to control whether the Public Law filter and corresponding copy updates are visible in specific environments.
- Also removes the CARES Act phased release variables and corresponding logic
- Cleans up some other unused / outdated global constant variables
- Removes obsolete dti migration logic
[DEV-7229](https://federal-spending-transparency.atlassian.net/browse/DEV-7229)
Author:
Reviewer(s):

DEV-7229 ARP release global constant

---

src/js/components/aboutTheData/componentMapping/tooltipContentMapping.jsx

Update table's tooltips per ticket
none
[DEV-7058](https://federal-spending-transparency.atlassian.net/browse/DEV-7058)
**Mockup:**
none
Author:
- na Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- na Verified mobile/tablet/desktop/monitor responsiveness
- na Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- na Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- na [API …

7058 copy updates

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyTableMapping.jsx
src/js/models/v2/aboutTheData/PublicationOverviewRow.js
tests/models/aboutTheData/PublicationOverviewRow-test.js

No difference to user experience
> • API response is handling periods, therefore we remove our logic for periods from the api.
[DEV-7180](https://federal-spending-transparency.atlassian.net/browse/DEV-7180)
**Mockup:**
N/A
Author:
Reviewer(s):

Dev-7180 remove fake periods added

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/AgencyDetailsPage.jsx
src/js/components/covid19/AwardQuestions.jsx
src/js/components/covid19/Heading.jsx
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx
src/js/components/sharedComponents/GlossaryLink.jsx
src/js/components/sharedComponents/header/NavBar.jsx
src/js/components/sharedComponents/header/mobile/MobileNav.jsx
src/js/containers/Footer.jsx
src/js/containers/glossary/GlossaryListener.jsx
src/js/containers/router/RouterRoutes.js
src/js/helpers/glossaryHelper.js
src/js/helpers/metaTagHelper.js
tests/helpers/glossaryHelper-test.js

- Showing the new navigation menu
- Releasing the page itself to the router
See commits
[DEV-6691](https://federal-spending-transparency.atlassian.net/browse/DEV-6691)
Author:
`N/A` Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if …

[DEV-6691] release agency stats pg

---

src/js/components/sharedComponents/metaTags/MetaTags.jsx

> • adds keys to a few more meta tags.

Meta Tag Keys

---

src/_scss/pages/covid19/recipient/_spendingByRecipient.scss

Updates the Recipient Search Bar to work like other sections on the page and removes the download button on mobile.
> • Updates the Recipient Search Bar to work like other sections on the page and removes the download button on mobile.
[DEV-6282](https://federal-spending-transparency.atlassian.net/browse/DEV-6282)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity …

Dev-6282 Recipient Search Bar Bug

---

src/js/components/covid19/amountsVisualization/AmountsVisualization.jsx
src/js/components/covid19/amountsVisualization/amounts/remainingBalance/LinesAndText.jsx
src/js/components/covid19/amountsVisualization/amounts/remainingBalance/RemainingBalance.jsx
src/js/components/covid19/amountsVisualization/amounts/totalObligations/LineAndText.jsx
src/js/components/covid19/amountsVisualization/amounts/totalObligations/TotalObligations.jsx

COVID-19 Progress Chart Obligation Line Three Overlap
[DEV-7207](https://federal-spending-transparency.atlassian.net/browse/DEV-7207)
**Mockup:**
[DEV-7207](https://federal-spending-transparency.atlassian.net/browse/DEV-7207)
Author:
- [N/A] Added Unit Tests for helper functions, reducers, models and …

COVID-19 Progress Chart Obligation Line Three Overlap

---

src/_scss/pages/agencyV2/overview/_overview.scss

Hides tooltip on mobile and ensures responsiveness throughout tablet/desktop.
Hides on mobile, adjusts width for responsiveness.
[DEV-6622](https://federal-spending-transparency.atlassian.net/browse/DEV-6622)
Author:
`N/A`  Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
`N/A` Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React …

[DEV-6622] Updating styles to hide on mobile

---

src/js/components/homepage/hero/TotalAmount.jsx
src/js/helpers/browser.js

Used for conditonal rendering on home page to disable animation and just show the total spending number.

[DEV-7086] using isDynamicRenderer property on window to skip animation of total amount on home pg

---

src/_scss/pages/agencyV2/overview/_overview.scss
src/js/components/homepage/hero/TotalAmount.jsx
src/js/helpers/browser.js

Down Merge: Disable COVID Home PG Animation & Agency v2 Covid Tooltip

---

src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/axis/AxisLabel.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/axis/XAxis.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/axis/YAxis.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/AreaPath.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/Path.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/Paths.jsx

Adds Accessibility Tab and Text for Axis and Paths
Adds Accessibility Tab and Text for Axis and Paths
[DEV-7349](https://federal-spending-transparency.atlassian.net/browse/DEV-7349)
**Mockup:**
N/A
Author:
- …

Dev-7349 Accessibility Tab and Text for Axis and Paths

---

scripts/sitemaps/package-lock.json
scripts/sitemaps/package.json

> • bump babel node and core to remove security vulnerability in lodash in our sitemap module.

Sitemaps Security Vulnerability

---

src/_scss/pages/homepage/hero/_covid-hero.scss
src/js/containers/homepage/CovidHighlights.jsx

Styling changes and new button link to Covid profile added to homepage
[DEV-7225](https://federal-spending-transparency.atlassian.net/browse/DEV-7225)
**Mockup:**
See ticket link
Author:
[n/a] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
[n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
[n/a] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library-integration-s …

Implement new Covid branding - Homepage

---

README.md
src/js/GlobalConstants.js
src/js/components/sharedComponents/header/NavBar.jsx
src/js/containers/AppContainer.jsx
src/js/helpers/analytics/Analytics.js
tests/testResources/mockGlobalConstants.js
webpack/webpack.common.js

Removes references to the `dev` environment (and in some places replaces them with `qat`) to reflect our new deployment cycle.
Author:
Reviewer(s):

Remove references to dev env

---

src/_scss/pages/homepage/hero/_covid-hero.scss
src/js/containers/homepage/CovidHighlights.jsx

Fixes bug where tooltip is hidden in Safari
Remove overflow set to hidden
[DEV-7161](https://federal-spending-transparency.atlassian.net/browse/DEV-7161)
Author:
- [n/a] [Component Library Integration Status …

[DEV-7161] Fix safari tooltip bug

---

src/js/components/covid19/OtherResources.jsx

Update copy for other resources section on covid profile page
[DEV-7402](https://federal-spending-transparency.atlassian.net/browse/DEV-7402)
**Mockup:**
[copy document](https://pmeonpremise.bah.com/sites/data-transparency/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fdata%2Dtransparency%2FShared%20Documents%2F01%20Data%20Transparency%2F09%20USAspending%2FCares%20Act%2FCopy)
Author: …

[DEV-7402] Copy updates - Other Resources

---

src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/containers/covid19/helpers/covid19.jsx

Implement copy edits for award spending by subagency & award spending by CFDA program
[DEV-7401](https://federal-spending-transparency.atlassian.net/browse/DEV-7401)
**Mockup:**
[copy document](https://pmeonpremise.bah.com/sites/data-transparency/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fdata%2Dtransparency%2FShared%20Documents%2F01%20Data%20Transparency%2F09%20USAspending%2FCares%20Act%2FCopy)
Author: …

[DEV-7401] Copy updates - Award spending by subagency and CFDA

---

src/js/components/covid19/Heading.jsx

Implement covid profile page heading copy edits
[DEV-7223](https://federal-spending-transparency.atlassian.net/browse/DEV-7223)
**Mockup:**
[copy document](https://pmeonpremise.bah.com/sites/data-transparency/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fdata%2Dtransparency%2FShared%20Documents%2F01%20Data%20Transparency%2F09%20USAspending%2FCares%20Act%2FCopy)
Author:
- [n/a] [API …

[DEV-7223] Copy updates - Covid profile Introduction

---

src/js/components/covid19/Covid19Tooltips.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx

Implement copy edits - COVID Profile Page - Total Spending by Budget Category
[DEV-7399](https://federal-spending-transparency.atlassian.net/browse/DEV-7399)
**Mockup:**
[copy document](https://pmeonpremise.bah.com/sites/data-transparency/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fdata%2Dtransparency%2FShared%20Documents%2F01%20Data%20Transparency%2F09%20USAspending%2FCares%20Act%2FCopy)
Author: …

[DEV-7399] Copy updates - Total spending by budget category

---

src/_scss/pages/homepage/features/_carousel.scss
src/_scss/pages/homepage/features/_covidFeature.scss
src/js/components/homepage/features/ImageCarousel.jsx
src/js/components/homepage/features/SpendingExplorerFeature.jsx
src/js/containers/homepage/CovidFeatureContainer.jsx

DEV-7432 Hotfix --> qat

---

.gitignore
package-lock.json
package.json

Website will now use the v3 of the component library.

bump dtui v3

---

src/js/components/covid19/Covid19Tooltips.jsx
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx

https://github.com/fedspendingtransparency/usaspending-website/pull/2624

DEV-7401 Warmfix downmerge to qat

---

src/_scss/pages/agencyV2/overview/_visualizationSection.scss
src/js/apis/agencyV2.js
src/js/components/agencyV2/overview/FySummary.jsx
src/js/containers/agencyV2/visualizations/ObligationsByAwardTypeContainer.jsx
src/js/containers/agencyV2/visualizations/RecipientDistributionContainer.jsx
src/js/helpers/moneyFormatter.js
src/js/models/v2/agency/BaseAgencyRecipients.js
src/js/redux/actions/agencyV2/agencyV2Actions.js
src/js/redux/reducers/agencyV2/agencyV2Reducer.js
tests/components/agency/AgencyOverview-test.jsx
tests/components/agency/overview/FYSummary-test.jsx
tests/containers/agencyV2/visualizations/ObligationsByAwardTypeContainer-test.jsx
tests/containers/agencyV2/visualizations/RecipientDistributionContainer-test.jsx
tests/helpers/moneyFormatter-test.js
tests/models/agency/BaseAgencyRecipients-test.js
tests/redux/reducers/agencyV2/agencyV2Reducer-test.js

API integration for the "Award Obligations by Type" and "Recipient Award Amount Distribution" summary insights (replaces mock data).
- Stores the agency's award obligations and recipient distribution data in Redux
- Adds a new data model, `BaseAgencyRecipients`, and API request for the recipient distribution and implements a container to make the request. The container and model can be added to as we build out the box & whiskers visualization.
[DEV-7134](https://federal-spending-transparency.atlassian.net/browse/DEV-7134)
**Mockup:**
https://bahdigital.invisionapp.com/share/CZIAH1ZQGPF#/296056413_agency-Profile-Mvp
Author:
Reviewer(s):

DEV-7134 Agency v2 FY Summary API integration - part 2

---

src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx

Add note under table in recipients tab as discussed in [comments](https://federal-spending-transparency.atlassian.net/browse/DEV-7400)
[DEV-7400](https://federal-spending-transparency.atlassian.net/browse/DEV-7400)
Author:
- [n/a] [Component …

[DEV-7400] Add note under recipients tab covid profile page

---

src/index.ejs

Removes expired structured data announcement.

remove expired structured data

---

src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx

NAICS filter displaying "No Results" for a search filter upon collapsing the tree
During a search, when all subtree nodes are collapsed and then the main nodes are also collapsed, faulty logic shows "No Results" instead of search matches.
[DEV-6816](https://federal-spending-transparency.atlassian.net/browse/DEV-6816)
**Mockup:**
na, but example in ticket; another example: search "sheep", collapse subnode, then collapse main node
Author:
- [na] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [na] Verified mobile/tablet/desktop/monitor responsiveness
- [na] Verified that this PR does not create any …

DEV-6816 remove unneeded logic causing problem

---

src/js/components/award/shared/InfoTooltipContent.jsx

award profile--hovering on covid badge shows codes in arbitrary order, should be alphabetical
add sort to code array before displaying
[DEV-6897](https://federal-spending-transparency.atlassian.net/browse/DEV-6897)
**Mockup:**
na
Author:
- [na] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [na] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- [na] Verified mobile/tablet/desktop/monitor responsiveness
- [na] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [na] Added Unit Tests for helper functions, …

DEV-6897 sort codes before displaying

---

src/_scss/layouts/default/footer/_footerCopyright.scss
src/_scss/layouts/default/footer/_footerLinks.scss
src/_scss/layouts/default/footer/_footerLogo.scss
src/_scss/layouts/default/footer/footer.scss
src/js/containers/Footer.jsx

Adjusted footer spacing on social links so they remain in a row on mobile to save space (DEV-7605). Adjusted link margins and padding to pass Google Lighthouse mobile audit for tap target sizes (see https://web.dev/tap-targets/)
[DEV-7605](https://federal-spending-transparency.atlassian.net/browse/DEV-7605)
[DEV-7609](https://federal-spending-transparency.atlassian.net/browse/DEV-7609)
**Mockup:**
https://bahdigital.invisionapp.com/share/4CIAFVTX9KE#/296054099_footer-Mobile
Author:
- [n/a] [API …

[DEV-7605, DEV-7609] Mobile Footer Link Spacing and Tap Target Adjustment

---

src/_scss/pages/homepage/features/_covidFeature.scss

Fix image ratios on homepage to pass Google Lighthouse Audit (see https://web.dev/image-aspect-ratio/)
Before
After
Testing
1.  Navigate to the homepage url path (ie. / ) in Chrome
3. Right click the page, and select “Inspect”
5. In the development console, click on the “Lighthouse” tab
7. Make sure the “Best Practices” category is selected and the “Mobile” device is selected, then click “Generate Report”
9. Wait for the audit to run, then scroll to the “Best Practices” section, then scroll to the “User Experience” sub-section. 
11. Ensure there is no error that states “Displays images with incorrect aspect ratio” (see screenshot)
[DEV-7606](https://federal-spending-transparency.atlassian.net/browse/DEV-7606)
**Mockup:** …

[DEV-7606] Homepage Image Aspect Ratio

---

src/_scss/pages/homepage/features/_featurePane.scss
src/js/components/homepage/features/PaneFeature.jsx

Remove the "COVID-19 Related Contract Visualization" content block from the Featured Pane on the homepage.
[DEV-7668](https://federal-spending-transparency.atlassian.net/browse/DEV-7668)
Author:
- [N/A] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/frontend_apps/component-library …

[DEV-7668] Remove the "COVID-19 Related Contract Visualization" content block

---

package-lock.json
package.json

Website will now use v3.1.0 of the component library.
> • install new version of DTUI
N/A
**Mockup:**
N/A

Bump DTUI to v3.1.0

---

src/js/components/about/DataQuality.jsx
src/js/dataMapping/navigation/menuOptions.jsx

[DEV-7794](https://federal-spending-transparency.atlassian.net/browse/DEV-7794)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for helper functions, reducers, models and Container/Component …

Dev-7794 remove agency submission navigation links

---

src/js/apis/agencyV2.js
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
src/js/containers/agencyV2/awardSpending/SubAgencySummaryContainer.jsx
src/js/models/v2/agency/BaseAgencySubagencyCount.js
src/js/redux/actions/agencyV2/agencyV2Actions.js
src/js/redux/reducers/agencyV2/agencyV2Reducer.js
tests/containers/agencyV2/awardSpending/SubAgencySummaryContainer-test.jsx
tests/models/agency/BaseAgencySubagencyCount-test.js
tests/redux/reducers/agencyV2/agencyV2Reducer-test.js

Adds summary insights information boxes and tabs functionality 
Adds summary insights section & api integration
[DEV-4566](https://federal-spending-transparency.atlassian.net/browse/DEV-4566)
[DEV-4567](https://federal-spending-transparency.atlassian.net/browse/DEV-4567)
[DEV-4568](https://federal-spending-transparency.atlassian.net/browse/DEV-4568)
[DEV-7447](https://federal-spending-transparency.atlassian.net/browse/DEV-7447)
**Mockup:**
https://bahdigital.invisionapp.com/share/CZIAH1ZQGPF#/screens/296056413_agency-Profile-Mvp
Author:
- [n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated …

Subagency summary insights section

---

src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
src/js/containers/agencyV2/awardSpending/SubAgencySummaryContainer.jsx
tests/containers/agencyV2/awardSpending/SubAgencySummaryContainer-test.jsx

Address design updates reflected in new [mock](https://bahdigital.invisionapp.com/share/QXIAHL4H6E5#/screens)
-Remove first box with subagencies count and use 3 box layout
-Remove subtitles
[DEV-4566](https://federal-spending-transparency.atlassian.net/browse/DEV-4566)
[DEV-4567](https://federal-spending-transparency.atlassian.net/browse/DEV-4567)
[DEV-4568](https://federal-spending-transparency.atlassian.net/browse/DEV-4568)
[DEV-7447](https://federal-spending-transparency.atlassian.net/browse/DEV-7447)
**Mockup:**
https://bahdigital.invisionapp.com/share/QXIAHL4H6E5#/screens
Author:
- [n/a] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity …

Subagency summary insights design update

---

src/js/containers/agencyV2/visualizations/TotalObligationsOverTimeContainer.jsx

under certain conditions, error message shows above loading message on Total Obligations Over Time
add check for error to logic showing loading message
[DEV-7853](https://federal-spending-transparency.atlassian.net/browse/DEV-7853)
**Mockup:**
na
Author:
Reviewer(s):

dev7853 check for error when showing loading

---

src/_scss/components/_stickyTable.scss

when filtered, table doesn't show bottom border of last row
just added a CSS rule for this one case
[DEV-7095](https://federal-spending-transparency.atlassian.net/browse/DEV-7095)
**Mockup:**
none
Author:
Reviewer(s):

7095 add bottom border to table

---

src/js/components/agencyV2/overview/BarChart.jsx

Ensures more consistent error messages across the agency v2 FY Summary visualizations
* The component library [Error Message](https://fedspendingtransparency.github.io/data-transparency-ui/?path=/story/messages--error-message) defaults to "Something went wrong while gathering your data."
N/A
Reviewer(s):

Fix Agency v2 error message

---

src/_scss/pages/covid19/index.scss
src/_scss/pages/covid19/recipient/recipientContainer.scss

Minor code style change request that didn't make #2719 
Reviewer(s):

DEV-7252 move scss block

---

package-lock.json
package.json

Update site to use v3.2.0 of component library
n/a

update dtui to v3.2.0

---

.travis.yml
lighthouserc.js

Includes Lighthouse scores for the Homepage and Covid-19 profile in our CI process.
https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md
[DEV-7611](https://federal-spending-transparency.atlassian.net/browse/DEV-7611)
Author:
Reviewer(s):

DEV-7611 Lighthouse scores

---

src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx

“Wire up” the Covid-19 profile page such that the url parameter affects the data in the Award Spending by CFDA Program section.
Updated filters in SpendingByCFDA.jsx and SpendingByCFDAContainer.jsx to use data from Redux
[DEV-7839](https://federal-spending-transparency.atlassian.net/browse/DEV-7839)
**Mockup:**
n/a
Author:
Reviewer(s):

7839 arp api integration

---

src/js/components/covid19/OtherResources.jsx

[DEV-6095](https://federal-spending-transparency.atlassian.net/browse/DEV-1234)
**Mockup:**
n/a
Author:
- [ x] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
Reviewer(s):

6095 update prac link

---

package-lock.json
package.json

Update repo to use v3.2.1 of component library

Bump DTUI to version 3.2.1

---

package-lock.json

post-audit fix push, trying to fix intermittent build errors

Ftr/bump dtui 3.2.1

---

src/_scss/pages/homepage/covid-vaccine-link.scss
src/_scss/pages/homepage/homePage.scss
src/js/components/homepage/CovidVaccineLink.jsx
src/js/components/homepage/Homepage.jsx

Put the vaccine banner back on the homepage.
Added the .jsx and scss files for the banner itself, and put back the references to them in the homepage code.
[DEV-8082](https://federal-spending-transparency.atlassian.net/browse/DEV-8082)
**Mockup:**
N/A
Author:
Reviewer(s):

8082 add vaccine banner

---

src/_scss/pages/homepage/hero/_covid-hero.scss

Friendly PR from ole pal max
Two styling changes:
(1) Add a a min width to the second span
in the covid banner to account for when the page
is loading.
(2) Add margin and positioning to horizontally and
vertically center the dots within the parent.
Before:
https://user-images.githubusercontent.com/12897813/139948363-37a760e2-bc27-4c4a-a7be-08b57db9c614.mp4
After:
https://user-images.githubusercontent.com/12897813/139948452-69408b07-34f1-4e30-897f-252dd548367d.mp4
Author:
- `N/A` Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
`N/A` Added Unit Tests for helper functions, …

[COVID-HOME-PG] ✨✨ Polish Loading Dots ✨✨

---

src/_scss/pages/agencyV2/index.scss
src/_scss/pages/agencyV2/statusOfFunds/_drilldownSidebar.scss
src/_scss/pages/agencyV2/statusOfFunds/_statusOfFunds.scss
src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/statusOfFunds/DrilldownSidebar.jsx
src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
src/js/containers/agencyV2/awardSpending/SubagencyTableContainer.jsx

Basic setup for the Status of Funds section to prevent conflicts.
[DEV-8048](https://federal-spending-transparency.atlassian.net/browse/DEV-8048)
Author:
Reviewer(s):

DEV-8048 Status of Funds scaffolding

---

src/_scss/pages/agencyV2/_awardSpendingNotes.scss
src/_scss/pages/agencyV2/index.scss
src/_scss/pages/agencyV2/statusOfFunds/_statusOfFunds.scss
src/_scss/pages/agencyV2/statusOfFunds/_statusOfFundsNotes.scss
src/js/components/agencyV2/awardSpending/AwardSpendingNotes.jsx
src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
src/js/components/agencyV2/statusOfFunds/StatusOfFundsNotes.jsx

Add the notes copy to the Status of Funds and Award Spending sections of the AgencyV2 page.
I made new components and css for each Notes section and added them to the page section.
[DEV-8104](https://federal-spending-transparency.atlassian.net/browse/DEV-8104)
**Mockup:**
https://bahdigital.invisionapp.com/share/BSIAHSLA9PE#/screens/296067036
Author:
- [ x] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- …

8104 agency page notes

---

src/js/GlobalConstants.js

add global constant to update internal links prior to agency v2 release
n/a
[DEV-8123](https://federal-spending-transparency.atlassian.net/browse/DEV-8123)
**Mockup:**
n/a
Author:
- [ n/a] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [n/a ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity …

dev8123 create global constant for agency links

---

package-lock.json
package.json

Upgrades the component library to fix the text-alignment of expandable table rows on the Covid Profile at smaller screen sizes.
[DEV-8065](https://federal-spending-transparency.atlassian.net/browse/DEV-8065)
Author:
Reviewer(s):

DEV-8065 component library upgrade

---

src/js/components/search/header/NoDownloadHover.jsx
src/js/containers/covid19/SummaryInsightsContainer.jsx
src/js/containers/covid19/recipient/RecipientTableContainer.jsx
src/js/helpers/index.js
tests/containers/covid19/SummaryInsightsContainer-test.jsx
tests/containers/covid19/recipient/RecipientTableContainer-test.jsx

Demote hotfixes to QAT

---

src/js/components/search/header/NoDownloadHover.jsx

Small change to notify users that the download limit has been increased to 250k.

Increase download limit to 250k

---

src/js/components/agencyV2/statusOfFunds/StatusOfFundsNotes.jsx

Copy change from Jessica, with a request to change it as soon as possible, in a comment on the ticket.
Copy change.
[DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-8104)
**Mockup:**
https://bahdigital.invisionapp.com/share/BSIAHSLA9PE#/screens
Author:
- [x ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x ] Verified that this PR does not create any *new* accessibility issues …

8104 - copy change, per instructions from jessica

---

src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx

Update pagination to match mock by removing the limit selector prop. Pagination functionality will be implemented in API integration ticket.
[DEV-8049](https://federal-spending-transparency.atlassian.net/browse/DEV-8049)
**Mockup:**
https://bahdigital.invisionapp.com/share/BSIAHSLA9PE#/screens/296067034
Author:
- [n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-a …

dev-8049 testing feedback remove limit selector from pagination

---

src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
src/js/components/search/header/NoDownloadHover.jsx

- Fixes pagination for Agency V2 Status of Funds chart

Qat -> Staging

---

src/_scss/pages/agencyV2/overview/_pageTitle.scss

AV2 chart(s) overlaps COVID badge tip (chart tips overlap each other as expected)
removes errant z-indexes causing the problem
[DEV-8113](https://federal-spending-transparency.atlassian.net/browse/DEV-8113)
**Mockup:**
n/a
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [n/a ] [API …

8113 un-raise the covid badge

---

src/js/components/covid19/DateNote.jsx

change COVID "Data through" date format to be consistent with Agency Profile page
make it M/D/YYYY
[DEV-8273](https://federal-spending-transparency.atlassian.net/browse/DEV-8273)
**Mockup:**
n/a
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and …

8273 update covid date format

---

src/js/components/recipient/RecipientMultiParentCollapse.jsx
src/js/components/recipient/modal/table/ChildRecipientModalTable.jsx
src/js/components/recipientLanding/RecipientLandingResultsSection.jsx
src/js/components/recipientLanding/RecipientLandingSearchBar.jsx
src/js/components/recipientLanding/table/RecipientLandingTable.jsx
src/js/components/search/filters/recipient/RecipientName.jsx
src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
src/js/dataMapping/award/additionalDetailsContract.js
src/js/models/v2/recipient/BaseChildRecipient.js
src/js/models/v2/recipient/BaseRecipientLandingRow.js

Added DUNS back to the UI for the following locations: 
Page |  
-- | --
Advanced Search | Keyword Tooltip, Recipient Filter
Recipient Profile |  Child recipients modal 
Recipient Landing | Search bar placeholder text, Table column
n/a
[DEV-8267](https://federal-spending-transparency.atlassian.net/browse/DEV-8267)
Author:
Reviewer(s):

8267 - Added DUNS back to several locations

---

package-lock.json
src/js/containers/agencyV2/visualizations/TotalObligationsOverTimeContainer.jsx

show message in summary chart if no data available
data detection logic never canceled the loading flag if no data returned; also add custom message
[DEV-8302](https://federal-spending-transparency.atlassian.net/browse/DEV-8302)
**Mockup:**
in ticket
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if …

8302 show message in summary chart if no data available

---

src/js/GlobalConstants.js
src/js/containers/router/RouterRoutes.js

Re-add Dark Release Flag for Agency v2 page
Broker needs to deploy before 1/18 so USAS frontend and backend are deploying as well to be in sync.  Will need to deploy a hotfix to undark release again on 1/18
[DEV-8068](https://federal-spending-transparency.atlassian.net/browse/DEV-8068)
Author:
Reviewer(s):

HOTFIX - Re-add Dark Release Flag for Agency v2 page

---

src/js/GlobalConstants.js
src/js/containers/router/RouterRoutes.js

Add code to remove the dark release flag
[DEV-8068](https://federal-spending-transparency.atlassian.net/browse/DEV-8068)
Author:
Reviewer(s):

HOTFIX - Add code to remove the dark release flag

---

package-lock.json
package.json

Currently IE is showing as a blank screen in the QAT environment (though it works locally).  The issue is in the vendors bundle so we suspect the problem is related to one of the package updates.  In this PR I reverted the node-sass version increase.

Revert node-sass version update

---

src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

Styling adjustments to Status of Funds chart.
**Technical Details:**
Used .nice(2) to create consistent number of ticks and ensure first and last tick is always present. Mobile should usually have 3 divisions with one tick but there are some cases we will have 2 ticks (4 divisions) depending on the data ranges
[DEV-8293](https://federal-spending-transparency.atlassian.net/browse/DEV-8293)
**Mockup:**
https://bahdigital.invisionapp.com/share/BSIAHSLA9PE#/screens
Author:
- [n/a] [API …

dev-8293 agency profile status of funds adjustments

---

src/_scss/pages/search/results/table/_tableStyle.scss
src/js/components/search/table/cells/ResultsTableHeaderCell.jsx

allow ascending sorts for award search columns
sorting efficiencies were worked out in API, this just allows them in front end; code was mostly there, just commented-out
[DEV-8303](https://federal-spending-transparency.atlassian.net/browse/DEV-8303)
**Mockup:**
n/a
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity …

8303 unhide up arrow, re-add sort logic

---

src/js/components/search/filters/recipient/RecipientName.jsx

Remove 'search by' from placeholder to prevent text from being cut off.
[DEV-8240](https://federal-spending-transparency.atlassian.net/browse/DEV-8240)
Author:
Reviewer(s):

dev 8240 add UEI adv search recipient filter - testing update

---

src/_scss/pages/modals/covid19/_covid19.scss

The text in the modal was cut off at smaller mobile sizes.
I increased the max-height for the modal class for < 500px.
[DEV-8489](https://federal-spending-transparency.atlassian.net/browse/DEV-8489)
**Mockup:**
N/A, but picture of the problem attached to the ticket
Author:
Reviewer(s):

8489 - increased max-height at < 500px

---

package-lock.json
package.json
src/_scss/pages/recipient/_recipientInfoBanner.scss
src/_scss/pages/recipient/recipientPage.scss
src/js/components/recipient/RecipientInfoBanner.jsx
src/js/components/recipient/RecipientPage.jsx
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/components/sharedComponents/header/UEIInfoBanner.jsx
src/js/dataMapping/stickyHeader/stickyHeader.js

8480 - Hotfix Add UEI recipient banner

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Hotfix/8548 Remove Infrastructure DEFC from COVID DS&M

---

src/index.ejs
src/js/components/recipient/RecipientPage.jsx

Environment Promotion
Reviewer(s):

8577 - Hotfix - Re-enable UEI recipient banner

---

src/js/components/search/visualizations/rank/sections/SpendingByRecipientSection.jsx
src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
src/js/containers/state/topFive/TopFiveContainer.jsx
src/js/dataMapping/search/spendingByCategory.js
src/js/dataMapping/state/topCategories.js
src/js/helpers/recipientLandingHelper.js

The backend updated endpoints to remove the word "duns".  Updated those endpoints on the frontend.
[DEV-8580](https://federal-spending-transparency.atlassian.net/browse/DEV-8580)
**Mockup:**
Author:
Reviewer(s):

8580 - Update recipient duns endpoints to remove the word "duns"

---

scripts/buildRedirectConfig.js

Fixed homepage redirect

---

package-lock.json
package.json
src/_scss/mixins/profilePage.scss
src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
src/js/components/agencyV2/awardSpending/AwardSpendingIntro.jsx

There was a bug reported that the pagination for the Agency Profile page Status of Funds chart was styled incorrectly.  Thi s seems to be caused by DEV-8583.
https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1647878384201939
[DEV-8583](https://federal-spending-transparency.atlassian.net/browse/DEV-8583)
Author:
Reviewer(s):

8583 - Changed how scss files are included to fix Status of Funds pagination styles

---

package.json
src/_scss/pages/agencyV2/index.scss
src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
src/js/components/agencyV2/awardSpending/AwardSpendingIntro.jsx
src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx

Before the Fix on the Award Profile V2 page, Award Spending section
After the Fix

8583 - Style fix for 8583

---

src/_scss/pages/homepageUpdate/homepageUpdate.scss
src/js/components/homepageUpdate/gettingStarted/GettingStarted.jsx

Implement Getting Started section layout as part of homepage update
[DEV-8516](https://federal-spending-transparency.atlassian.net/browse/DEV-8516)
**Mockup:**
See ticket for link
Author:
Reviewer(s):

Dev-8516 homepage 'Getting Started' Section Layout

---

package-lock.json
package.json
src/js/helpers/stickyHeaderHelper.js
webpack/webpack.common.js
webpack/webpack.dev.config.js

One of webpack dev server dependencies, node-forge, has a high security vulnerability.  Upgrade to latest to mitigate.  
n/a
Reviewer(s):

Upgrade webpack dev server to latest version

---

src/js/components/aboutTheData/TimeFilters.jsx

Fixing issue where the background color was incorrect due to changes in data-transparency-ui
added backgroundColor prop
n/a
Reviewer(s):

fixed background color

---

src/js/components/covid19/recipient/map/MapFilters.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx

Fixed additional backgroundColor issues
Fixed additional backgroundColor issues for Picker
**Mockup:**
Reviewer(s):

missed a few the first time

---

package.json
src/js/components/agencyLanding/AgencyLandingContent.jsx

[DEV-8647](https://federal-spending-transparency.atlassian.net/browse/DEV-8647)
Author:
Reviewer(s):

8647 - Agency Landing Page CJ Link Env Promotion

---

src/js/GlobalConstants.js
src/js/components/analystGuide/AnalystGuideIntro.jsx
src/js/components/analystGuide/AnalystGuideQuestions.jsx

Fixed links to FAQ, Community Page, and typo
[DEV-8366](https://federal-spending-transparency.atlassian.net/browse/DEV-8366)
Author:
Reviewer(s):

Fix analyst guide links and set the release flag to true

---

src/js/components/sharedComponents/header/UEIInfoBanner.jsx

Fix an issue where focus was stuck on the info banner
Change the onkeydown function to only work in the case of enter
[DEV-8652](https://federal-spending-transparency.atlassian.net/browse/DEV-8652)
Reviewer(s):

DEV-8652 - changed key down behavior

---

src/js/dataMapping/navigation/menuOptions.jsx

Removed is new flag from COVID menu item
Removed 'isNewTab' from object
[DEV-8692](https://federal-spending-transparency.atlassian.net/browse/DEV-8692)
Author:
Reviewer(s):

8692 - Removed is new flag from COVID menu item

---

src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx

Fixed note on the bottom of the status of funds page
Updated the text in the note on the bottom of the status of funds page
[DEV-8411](https://federal-spending-transparency.atlassian.net/browse/DEV-8411)
Reviewer(s):

DEV-8411 updated status of funds note

---

package-lock.json
package.json

Increased ui library version for fiscal year picker update
Increased ui library version for fiscal year picker update
n/a
Reviewer(s):

Increased ui library version for fiscal year picker update

---

src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx

Somehow missed some words when copying/pasting for the status of funds note
Made sure additional words weren't forgotten this time 
[DEV-8411](https://federal-spending-transparency.atlassian.net/browse/DEV-8411)
Reviewer(s):

DEV-8411 - somehow missed words when copying/pasting

---

src/js/components/covid19/PublicLawPicker.jsx

Background color of Picker on covid 19 page 
Added backgroundColor prop to component
[DEV-8700](https://federal-spending-transparency.atlassian.net/browse/DEV-8700)
**Mockup:**
Author:
Reviewer(s):

DEV-8700 - Fix/8700 dropdown

---

src/js/components/analystGuide/AnalystGuideQuestions.jsx

**Mockup:**
Author:
Reviewer(s):

8669 - Remove params from submission-statistics link (Env promotion)

---

src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
src/_scss/pages/agencyV2/visualizations/_statusOfFundsChart.scss
src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

Adds hovers to the Status of Funds bar chart that show users the actual Obligation and Total Budgetary Resource (TBR) amounts for each row of the existing sub-component and Federal Account layers in the drilldown.
[DEV-8678](https://federal-spending-transparency.atlassian.net/browse/DEV-8678)
Author:
Reviewer(s):

[DEV-8678] Status of Funds bar chart hover state

---

src/_scss/pages/homepageUpdate/hero/_animatedHeading.scss
src/js/components/homepageUpdate/hero/AnimatedHeading.jsx

Fixed the hero text alignment on mobile.
Refactored some css for mobile to fix issues with text alignment.  Also addressed issue with text alignment of Safari and Firefox.
[DEV-8664](https://federal-spending-transparency.atlassian.net/browse/DEV-8664)
Author:
Reviewer(s):
`

Fix test for 8664 hero replay

---

src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

Address feedback in ticket comments - capitalize 'Federal Accounts' and hide instruction note on Federal Accounts level
[DEV-8678](https://federal-spending-transparency.atlassian.net/browse/DEV-8678)
Author:
Reviewer(s):

DEV 8678 Bar chart hover tooltip fixes

---

package-lock.json
package.json

Updated the version of the async page to mitigate security vulneraibility
The async package is a dependency of a package in package.json

Updated package dependency version

---

src/js/dataMapping/navigation/menuOptions.jsx

Fixed the analyst guide link on mobile
https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1652723859943109
Remove reference to global variable
[DEV-8067](https://federal-spending-transparency.atlassian.net/browse/DEV-8067)
Author:
Reviewer(s):

8067 - Fixed the analyst guide link on mobile

---

src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Fix tooltip disappearing, add outlay amount to tooltip, move tooltip closer to cursor
added listener on svg to remove tooltip
added outlay amount to the hover
changed the transform to move the tooltip closer
[DEV-8767](https://federal-spending-transparency.atlassian.net/browse/DEV-8767)
**Mockup:**
Author:
Reviewer(s):

DEV-8767 hover modifications

---

src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
src/_scss/pages/award/shared/awardAmountsSection/_index.scss
src/js/components/award/idv/amounts/AggregatedAwardAmountsSection.jsx
src/js/components/award/shared/awardAmounts/AwardAmountsChart.jsx
src/js/components/award/shared/awardAmounts/AwardAmountsSection.jsx
src/js/components/award/shared/awardAmounts/AwardAmountsTable.jsx
src/js/components/award/shared/awardAmounts/HorizontalSingleStackedBarViz.jsx
src/js/dataMapping/award/awardAmountsSection.js

Added Infrastructure spending to contract awards
Examples to test -
[DEV-8670](https://federal-spending-transparency.atlassian.net/browse/DEV-8670)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/628d365558d7ebb99a65f0e0
Author:
Reviewer(s):

8670 - Added Infrastructure spending to contract awards

---

src/_scss/pages/agency/index.scss
src/_scss/pages/agency/statusOfFunds/_visualizationSection.scss
src/js/components/agency/overview/VisualizationSection.jsx
src/js/components/agency/statusOfFunds/VisualizationSection.jsx
src/js/components/agency/visualizations/StatusOfFundsChart.jsx
src/js/components/sharedComponents/accordion/Accordion.jsx

Final adjustments to get the hover working correctly and also included the hotfix for touch devices
Link to ticket:
https://federal-spending-transparency.atlassian.net/browse/DEV-8858
Touchend events implemented for the bars, also added a listener on the g element for mouseleave so that the hover will disappear properly
Author:
Reviewer(s):

DEV-8858 Drilldown fix

---

src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
src/js/components/award/idv/amounts/AggregatedAwardAmountsSection.jsx
src/js/components/award/shared/awardAmounts/AwardAmountsSection.jsx
src/js/dataMapping/award/awardAmountsSection.js
src/js/helpers/awardAmountHelper.js
src/js/models/v2/award/BaseAwardAmounts.js

Fixing AC #5 for DEV-8670
[DEV-8670](https://federal-spending-transparency.atlassian.net/browse/DEV-8670)

Fix/8670 - chart not available

---

src/js/components/award/shared/awardAmounts/AwardAmountsSection.jsx
src/js/components/award/shared/awardAmounts/HorizontalSingleStackedBarViz.jsx

Please the following:
http://localhost:3000/award/CONT_AWD_12046W20P0067_12C2_-NONE-_-NONE-/
http://localhost:3000/award/CONT_AWD_693JJ922F000007_6940_HTC71117DC003_9700
http://localhost:3000/award/146848104
[DEV-8670](https://federal-spending-transparency.atlassian.net/browse/DEV-8670)
Reviewer(s):

Fix/8670 - Fixed issue where infrastructure tab not showing and stem for total funding not showing

---

src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Forgot to add touchend check when at the subcomponent level
added check for the above issue
Author:
Reviewer(s):

HOTFIX fix for mobile drilldown

---

src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
src/js/components/award/shared/awardAmounts/AwardAmountsTable.jsx

Legend row was not aligned properly
Applied classname to the required divs
use for testing: http://localhost:3000/award/CONT_AWD_WCO00200110D68R80201_6800_-NONE-_-NONE-
[DEV-8654](https://federal-spending-transparency.atlassian.net/browse/DEV-8654)
Author:
Reviewer(s):

DEV-8654 align legend

---

src/_scss/pages/award/awardPage.scss
src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
src/js/components/award/idv/IdvContent.jsx

Based on pr feedback
[DEV-8913](https://federal-spending-transparency.atlassian.net/browse/DEV-8913)
Author:
Reviewer(s):

DEV-8913 fix triangle and prop passing

---

src/js/components/search/table/cells/ResultsTableLinkCell.jsx
src/js/components/search/visualizations/rank/chart/ChartGroup.jsx

Open table links in new tab
[DEV-8547](https://federal-spending-transparency.atlassian.net/browse/DEV-8547)
Author:
Reviewer(s):

DEV-8547 new tabs for table links

---

src/js/dataMapping/search/geoVisualizationSection.jsx

Open about page on new tab per melissa's note
[DEV-8547](https://federal-spending-transparency.atlassian.net/browse/DEV-8547)
Author:
Reviewer(s):

DEV-8547 about page new tab

---

package-lock.json
src/_scss/pages/homepage/_summaryStats.scss

Additional spacing adjustments at the following viewports - 
1425
1406 - 1401
1236 - 1229
1200
[DEV-8959](https://federal-spending-transparency.atlassian.net/browse/DEV-8959)
Author:
Reviewer(s):

8959 - For HOTFIX - Additional spacing adjustments

---

src/js/components/sharedComponents/UnlinkedAwardWarning.jsx

update verbiage per AC
[DEV-9009](https://federal-spending-transparency.atlassian.net/browse/DEV-9009)
Author:
Reviewer(s):

HOTFIX DEV-9009 verbiage update

---

src/_scss/pages/state/_contentWrap.scss
src/js/components/state/overview/StateOverview.jsx

link to awards from state overview pages
based on work done for recipient pages
[DEV-9026](https://federal-spending-transparency.atlassian.net/browse/DEV-9026)
Author:
Reviewer(s):

DEV-9026 state awards link

---

package.json

**Mockup:**
Author:
Reviewer(s):

add commander

---

__mocks__/tabbable.js
tests/components/aboutTheData/AboutTheDataModal-test.jsx

fixed test, function needed to be mocked
[DEV-8972](https://federal-spending-transparency.atlassian.net/browse/DEV-8972)
Author:
Reviewer(s):

DEV-8972 mocking window scroll fn

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

COpy changes to Covid DSM page, bc changes are being made to calculations by backend
Just copy changes outlined in the ticket.
Because my IDE made a bunch of whitespace changes to this file - the relevant changes are at lines 521, 527, 546, 561, 567
[DEV-9072](https://federal-spending-transparency.atlassian.net/browse/DEV-9072)
**Mockup:**
n/a
Author:
Reviewer(s):

9072 - copy changes to covid dsm page

---

src/js/components/sharedComponents/commonCards/CardButton.jsx
src/js/components/sharedComponents/commonCards/CardContainer.jsx
src/js/components/sharedComponents/commonCards/CardHero.jsx

Fix 8978 - Removed default props and used default arg values

---

package-lock.json

attempt to fix postcss
Author:
Reviewer(s):

postcss fix

---

src/_scss/components/_externalLink.scss
src/_scss/pages/homepage/_featuredContent.scss
src/_scss/pages/homepage/homepageUpdate.scss
src/js/components/homepageUpdate/FeaturedContent/FeaturedContent.jsx
src/js/components/sharedComponents/ExternalLink.jsx

Fixed tabbing through featured cards
[DEV-8978](https://federal-spending-transparency.atlassian.net/browse/DEV-8978)
Author:
Reviewer(s):

8978 - Fixed tabbing through featured cards

---

package-lock.json
src/js/components/homepage/AwardSearch/AwardSearch.jsx

addition to 9149, toString
[DEV-9149](https://federal-spending-transparency.atlassian.net/browse/DEV-9149)
Author:
Reviewer(s):

DEV-9149 Fix carousel links

---

package-lock.json
src/_scss/pages/homepage/_awardSearch.scss
src/_scss/pages/homepage/homepageUpdate.scss
src/js/components/homepage/AwardSearch/AwardSearch.jsx
src/js/components/sharedComponents/commonCards/CardContainer.jsx

Did remaining things in the fit and finish ticket 
mostly scss changes
[DEV-9153](https://federal-spending-transparency.atlassian.net/browse/DEV-9153)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/62fa717312f2d01095f906aa
Author:
Reviewer(s):

DEV-9153 carousel fit and finish

---

package-lock.json
src/js/components/homepageUpdate/WordOfTheDay/WordOfTheDay.jsx

adjust what is displayed for terms that are 3 lines
just added another string that displays instead of the term if it's not empty
[DEV-9135](https://federal-spending-transparency.atlassian.net/browse/DEV-9135)
Author:
Reviewer(s):

DEV-9135 3 line word of the day terms

---

package-lock.json
src/js/components/interactiveDataSources/lottieAnimation/LottieAnimation.jsx
src/js/components/interactiveDataSources/scroller/scrollerOverlay/ScrollerOverlayCard.jsx
src/js/components/interactiveDataSources/scrollerSections/AccountData.jsx
src/js/components/interactiveDataSources/scrollerSections/AdditionalData.jsx
src/js/components/interactiveDataSources/scrollerSections/AwardData.jsx
src/js/components/interactiveDataSources/scrollerSections/DataAvailable.jsx
src/js/components/interactiveDataSources/scrollerSections/DataFeatures.jsx
src/js/components/interactiveDataSources/scrollerSections/DataSourceSystems.jsx
src/js/components/interactiveDataSources/scrollerSections/DataSubmissionExtraction.jsx
src/js/components/interactiveDataSources/scrollerSections/DataTypes.jsx
src/js/components/interactiveDataSources/scrollerSections/DataUseCases.jsx
src/js/components/interactiveDataSources/scrollerSections/DataValidation.jsx
src/js/components/interactiveDataSources/scrollerSections/FederalSpendingOverview.jsx
src/js/components/interactiveDataSources/scrollerSections/Frequency.jsx
src/js/components/interactiveDataSources/sections/IntroSection.jsx

links open in new tabs and add tab stops
just add tabIndex and add target="_blank" to appropriate spots
[DEV-9125](https://federal-spending-transparency.atlassian.net/browse/DEV-9125)
Author:
Reviewer(s):

DEV-9125 links open in new tabs and add tab stops

---

package-lock.json
src/_scss/components/_pageLoading.scss
src/_scss/pages/homepageUpdate/_wordOfTheDay.scss

Fix the min height of the loading wrapper at the page level 
Add min height styling back in and unset the min height in the case of the word of the day card
[DEV-9179](https://federal-spending-transparency.atlassian.net/browse/DEV-9179)
Author:
Reviewer(s):

DEV-9179 loading

---

package-lock.json
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx

Adjustments to text labels and addition of paragraph
[DEV-8964](https://federal-spending-transparency.atlassian.net/browse/DEV-8964)
Author:
Reviewer(s):

DEV-8964 table label and covid dsm paragraph

---

src/js/dataMapping/navigation/menuOptions.jsx

Changed MenuOption newTab to false
Changed online of code
[DEV-9180](https://federal-spending-transparency.atlassian.net/browse/DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-9180 )
**Mockup:**
Author:
Reviewer(s):

Mod 9180 update data source page fix

---

src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx
src/js/components/interactiveDataSources/scrollerSections/AccountData.jsx
src/js/components/interactiveDataSources/scrollerSections/AdditionalData.jsx
src/js/components/interactiveDataSources/scrollerSections/AwardData.jsx
src/js/components/interactiveDataSources/scrollerSections/DataAvailable.jsx
src/js/components/interactiveDataSources/scrollerSections/DataFeatures.jsx
src/js/components/interactiveDataSources/scrollerSections/DataSourceSystems.jsx
src/js/components/interactiveDataSources/scrollerSections/DataSubmissionExtraction.jsx
src/js/components/interactiveDataSources/scrollerSections/DataTypes.jsx
src/js/components/interactiveDataSources/scrollerSections/DataUseCases.jsx
src/js/components/interactiveDataSources/scrollerSections/DataValidation.jsx
src/js/components/interactiveDataSources/scrollerSections/Frequency.jsx
src/js/components/interactiveDataSources/sections/AboutSection.jsx
src/js/components/interactiveDataSources/sections/IntroSection.jsx

lots of small updates to copy
[DEV-9186](https://federal-spending-transparency.atlassian.net/browse/DEV-9186)
Author:
Reviewer(s):

DEV-9186 copy updates

---

src/js/components/interactiveDataSources/scrollerSections/Frequency.jsx

missed .gov
[DEV-9186](https://federal-spending-transparency.atlassian.net/browse/DEV-9186)
Author:
Reviewer(s):

DEV-9186 missing gov

---

package-lock.json

Updated the color of the fy buttons background color
changed a color
[DEV-9204](https://federal-spending-transparency.atlassian.net/browse/DEV-9204)
**Mockup:**
Author:
Reviewer(s):

Mod 9204-Updated color of the FY buttons background 

---

src/js/components/homepageUpdate/HomepageResources/HomepageResources.jsx

This one word keep getting overwritten when we merge and I don't know why, so I'm changing it again
text change
andrew's comment on
[DEV-9180](https://federal-spending-transparency.atlassian.net/browse/DEV-9180)
**Mockup:**
Author:
Reviewer(s):

no tkt number yet - changed this text in Resources section, again

---

package-lock.json
package.json
src/_scss/components/_atdButton.scss
src/js/components/sharedComponents/aboutTheData/ATDButton.jsx

change for ATD icon for mobile/tablet so it doesn't go down to a second toolbar
[DEV-9203](https://federal-spending-transparency.atlassian.net/browse/DEV-9203)
**Mockup:**
https://bahdigital.invisionapp.com/console/share/327RPD5NUJM/959667049/play
Author:
Reviewer(s):

Atd changes

---

package-lock.json
package.json

update loader-utils version and increased security level to critical

Temporary fix to loader-utils security vulnerability

---

src/js/components/aboutTheDataSidebar/AboutTheData.jsx
src/js/containers/router/RouterRoutes.js

Fixed issue reported by QA - https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1669063835182819
[DEV-9232](https://federal-spending-transparency.atlassian.net/browse/DEV-9232)

9232 - Fixed data sources page and about the data scroll to top functionality

---

src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1669139664945819

Fix - 8535 update cfda program labels, added missing letter per testing feedback

---

package-lock.json
src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx

fix based on testing feedback
[DEV-9233](https://federal-spending-transparency.atlassian.net/browse/DEV-9233)
Author:
Reviewer(s):

DEV-9233 fix for scroll to on data-sources

---

src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx

testing adjustment for scroll to on data-sources
Author:
Reviewer(s):

DEV-9233 testing adjustment scroll to

---

package-lock.json
src/js/components/homepageUpdate/ReadyToGetStarted/ReadyToGetStarted.jsx

fixed link on homepage
[DEV-9340](https://federal-spending-transparency.atlassian.net/browse/DEV-9340)
Author:
Reviewer(s):

DEV-9340 fixed homepage link

---

src/js/dataMapping/search/spendingByCategory.js

Prod bug in this api call
reverted recent change
[DEV-9345](https://federal-spending-transparency.atlassian.net/browse/DEV-9345)
**Mockup:**
n/a
Author:
Reviewer(s):

9345 - reverted change in spendingByCategory.js to fix api call

---

src/js/containers/Footer.jsx

Added the youtube icon and link
Changed the linkedin link
Changed the footer componenet to include a Youtube icon and link.
Changed the linked in link
[DEV-9266](https://federal-spending-transparency.atlassian.net/browse/DEV-9266)
**Mockup:**
No mock but IMG are on the ticket
Author:
Reviewer(s):

Updated Social Media Links

---

package-lock.json
src/js/components/about/AboutContent.jsx

sidebar fix when clicking on sections on about page
[DEV-9347](https://federal-spending-transparency.atlassian.net/browse/DEV-9347)

Sidebar fix for about page

---

src/_scss/components/aboutTheDataSidebar/aboutTheData.scss
src/_scss/pages/glossary/glossaryPage.scss
src/js/components/aboutTheDataSidebar/AboutTheData.jsx
src/js/components/aboutTheDataSidebar/AboutTheDataDrilldown.jsx
src/js/components/aboutTheDataSidebar/AboutTheDataHeader.jsx
src/js/components/aboutTheDataSidebar/AboutTheDataListView.jsx
src/js/components/aboutTheDataSidebar/AboutTheDataNoResults.jsx
src/js/components/aboutTheDataSidebar/AboutTheDataSearchBar.jsx
src/js/components/glossary/definition/GlossaryDefinition.jsx
src/js/dataMapping/navigation/menuOptions.jsx
src/js/helpers/aboutTheDataSidebarHelper.js

See ticket AC
[DEV-9303](https://federal-spending-transparency.atlassian.net/browse/DEV-9303)
Author:
Reviewer(s):

9303 - About the Data Fit and Finish

---

src/js/components/aboutTheDataSidebar/AboutTheDataDrilldown.jsx

the ampersand in the file b title was breaking the email share option specifically - only file b
Author:
Reviewer(s):

atd share file b fix

---

src/_scss/pages/covid19/_budgetCategoriesTable.scss

made gray match the other grays in the table
[DEV-9393](https://federal-spending-transparency.atlassian.net/browse/DEV-9393)
Author:
Reviewer(s):

DEV-9393 covid page dropdown text fix

---

src/_scss/pages/search/_tooltips.scss
src/js/components/search/SearchSidebar.jsx
src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx

add tooltip to location filter
[DEV-9055](https://federal-spending-transparency.atlassian.net/browse/DEV-9055)
Author:
Reviewer(s):

DEV-9055 location tooltip

---

src/_scss/pages/trainingVideos/_highlightedVideo.scss
src/_scss/pages/trainingVideos/_listOfVideos.scss
src/_scss/pages/trainingVideos/_trainingVideosFilters.scss
src/js/components/trainingVideos/trainingVideosHeading/TrainingVideosHeading.jsx
src/js/helpers/metaTagHelper.js

change meta tags for training videos page
[DEV-9371](https://federal-spending-transparency.atlassian.net/browse/DEV-9371)
Author:
Reviewer(s):

DEV-9371 change meta tags for training videos page

---

src/_scss/pages/search/results/_tabs.scss

QA feedback, change icon color to match text color
Color names are in the AC on the ticket; and Allie left a comment about it too
[DEV-8546](https://federal-spending-transparency.atlassian.net/browse/DEV-8546)
Author:
Reviewer(s):

8546 - icon color change

---

package-lock.json
package.json
src/_scss/pages/trainingVideos/_listOfVideos.scss
src/js/components/sharedComponents/commonCards/CardContainer.jsx
src/js/components/trainingVideos/listOfVideos/ListOfVideos.jsx
src/js/components/trainingVideos/videoCard/VideoCard.jsx
src/js/containers/trainingVideos/TrainingVideosContainer.jsx

video list section, responsive columns for cards
[DEV-9375](https://federal-spending-transparency.atlassian.net/browse/DEV-9375)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/screen/6373f6160e9d708e1d9a0c8d
Author:
Reviewer(s):

DEV-9375 video list section

---

src/_scss/pages/trainingVideos/_videoThumbnail.scss

Design listed the css changes they wanted in the ticket
Made the changes
[DEV-9429](https://federal-spending-transparency.atlassian.net/browse/DEV-9429)
Author:
Reviewer(s):

9429 - very specific css changes, as dictated by design

---

package-lock.json
src/js/components/interactiveDataSources/scrollerSections/AccountData.jsx
src/js/components/interactiveDataSources/scrollerSections/AwardData.jsx
src/js/components/interactiveDataSources/scrollerSections/DataSubmissionExtraction.jsx

fixing missed copy corrections
[DEV-9383](https://federal-spending-transparency.atlassian.net/browse/DEV-9383)
Author:
Reviewer(s):

DEV-9383 testing feedback for copy corrections

---

src/_scss/pages/trainingVideos/_videoSort.scss
src/js/components/trainingVideos/listOfVideos/ListOfVideos.jsx

[DEV-9381](https://federal-spending-transparency.atlassian.net/browse/DEV-9381)
Author:
Reviewer(s):

DEV-9381 - Address testing feedback

---

src/js/components/homepageUpdate/WordOfTheDay/WordOfTheDay.jsx

Hotfix - Fix word of the day definition not appearing for the term "Redacted Due to PII"
[DEV-9463](https://federal-spending-transparency.atlassian.net/browse/DEV-9463)

Hotfix - Fix word of the day definition not appearing for the term "Redacted Due to PII"

---

src/_scss/pages/trainingVideos/_videoSort.scss

[DEV-9381](https://federal-spending-transparency.atlassian.net/browse/DEV-9381)

9381 - Reverted change to the dropdown list width and placement per testing feedback

---

src/_scss/pages/modals/video/_trainingVideoModal.scss
src/_scss/pages/trainingVideos/_videoThumbnail.scss
src/js/components/trainingVideos/featuredVideo/FeaturedVideo.jsx

add cursor and modal launch for featured video
[DEV-9432](https://federal-spending-transparency.atlassian.net/browse/DEV-9432)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/dashboard?sid=63c18f078d24b2b5edd142a5
Author:
Reviewer(s):

DEV-9432 pointer and launch modal for featured video

---

src/js/components/homepageUpdate/FeaturedContent/FeaturedContent.jsx

tab+enter for homepage youtube feature card
[DEV-9450](https://federal-spending-transparency.atlassian.net/browse/DEV-9450)
Author:
Reviewer(s):

DEV-9450 tab+enter with youtube feature card

---

src/js/components/homepageUpdate/FeaturedContent/FeaturedContent.jsx
src/js/components/homepageUpdate/WordOfTheDay/WordOfTheDay.jsx
src/js/dataMapping/navigation/menuOptions.jsx

Tweaks for Training Video Deploy
[DEV-9489](https://federal-spending-transparency.atlassian.net/browse/DEV-9489)
Author:
Reviewer(s):

9489 - Tweaks for Training Video Deploy

---

src/js/components/homepageUpdate/WordOfTheDay/WordOfTheDay.jsx

Fix word of the day break.  The fix is in the branch for DEV-9489 so it can be tested in that branch too once that's merged to QAT
Restarted loop through glossaryTerms
n/a
Reviewer(s):

Hotfix - Fix word of the day break 

---

src/_scss/pages/covid19/recipient/recipientContainer.scss

change font color
[DEV-9468](https://federal-spending-transparency.atlassian.net/browse/DEV-9468)
Author:
Reviewer(s):

DEV-9468 dropdown font

---

src/js/models/v2/agency/BaseAgencySubcomponentsList.js

**Mockup:**
Author:
Reviewer(s):

Hotfix/9511 Environment Promotion

---

src/js/dataMapping/trainingVideos/playListMetadata.js
tests/models/trainingVideo/VideoMetadata-test.js

Added latest video to YouTube static data 
[DEV-9510](https://federal-spending-transparency.atlassian.net/browse/DEV-9510)
Author:
Reviewer(s):

9510 - Added latest video to YouTube static data 

---

src/_scss/pages/homepageUpdate/_wordOfTheDay.scss

min height fix
[DEV-9512](https://federal-spending-transparency.atlassian.net/browse/DEV-9512)
Author:
Reviewer(s):

DEV-9512 min height fix

---

src/js/dataMapping/trainingVideos/playListMetadata.js
src/js/dataMapping/trainingVideos/playlist.js

Added a new video to the training video page. 
Add new JSON file for training video page
[DEV-9522](https://federal-spending-transparency.atlassian.net/browse/DEV-9522)
**Mockup:**
/
Author:
Reviewer(s):

Mod 9522 add recipient video to training videos page

---

src/_scss/components/_buttons.scss

small changes from testing
[DEV-9502](https://federal-spending-transparency.atlassian.net/browse/DEV-9502)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/6259c2b382e531929b63118a
Author:
Reviewer(s):

testing feedback

---

src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
src/js/components/aboutTheData/AboutTheDataModal.jsx
src/js/components/aboutTheData/AboutTheDataPage.jsx

give an id to a modal to fix the width
[DEV-9469](https://federal-spending-transparency.atlassian.net/browse/DEV-9469)
Author:
Reviewer(s):

DEV-9469- Fix modals on submission stats page

---

src/js/components/trainingVideos/featuredVideo/FeaturedVideo.jsx
src/js/components/trainingVideos/listOfVideos/ListOfVideos.jsx

fix keyboard modal launch on training videos page for featured video and list of videos
[DEV-9477](https://federal-spending-transparency.atlassian.net/browse/DEV-9477)
Author:
Reviewer(s):

DEV-9477 keyboard modal launch for training videos page

---

src/js/components/homepageUpdate/WordOfTheDay/WordOfTheDay.jsx

fix outline on wod card
[DEV-9451](https://federal-spending-transparency.atlassian.net/browse/DEV-9451)
Author:
Reviewer(s):

DEV-9451 fix outline on word of the day card

---

src/content/about-the-data/changes-in-reporting-requirements.mdx

Read the entries in the Legal
and Policy Documentation section for information about relevant OMB memos.
ADDED sentence to the end of first paragraph
ADD
Read the entries in the Legal
and Policy Documentation section for information about relevant OMB memos.
[DEV-9547](https://federal-spending-transparency.atlassian.net/browse/DEV-9547)
Author:
Reviewer(s):

Added sentence to the end of first paragraph

---

src/_scss/pages/modals/redirect/_redirect.scss
src/js/components/sharedComponents/RedirectModal.jsx

basically same fix as 9469 PR
[DEV-9470](https://federal-spending-transparency.atlassian.net/browse/DEV-9470)
Author:
Reviewer(s):

DEV-9470 external link modal space

---

src/_scss/pages/modals/redirect/_redirect.scss

fix longer links on mobile - they were running over off the screen
Author:
Reviewer(s):

DEV-9470 testing feedback, fix longer links

---

src/_scss/layouts/default/header/_warning.scss
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx

https://data-transparency-bfs.slack.com/archives/C0155EL4AU9/p1678122935442969

Hotfix:  Download banner

---

package.json

**Mockup:**
Author:
Reviewer(s):

Increase DTUI version number to 5.2.7

---

src/_scss/pages/search/results/visualizations/geo/_topSection.scss
src/_scss/pages/search/results/visualizations/rank/_topSection.scss
src/_scss/pages/search/results/visualizations/time/_topSection.scss
src/js/components/search/table/ResultsTableSection.jsx
src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx

testing feedback from allie, didn't realize some sentences were missing as the MAC changed while I was doing the ticket
[DEV-9542](https://federal-spending-transparency.atlassian.net/browse/DEV-9542)
Author:
Reviewer(s):

DEV-9542 explainer feedback

---

src/js/components/sharedComponents/header/Header.jsx

Remove the sitewide banner to notify users about download issue.

Hotfix - Remove sitewide banner

---

src/js/components/aboutTheData/AgencyDetailsPage.jsx

fix whitespace on drilldown
Author:
Reviewer(s):

DEV-9469 add id to fix whitespace on drilldown

---

src/_scss/pages/search/results/visualizations/rank/_topSection.scss
src/js/components/search/table/ResultsTableSection.jsx

last small comments from allie 
Author:
Reviewer(s):

final small comments for 9542

---

src/js/components/search/filters/awardID/AwardIDSearch.jsx

award id search wouldn't work with lowercase, so I forced uppercase
[DEV-9593](https://federal-spending-transparency.atlassian.net/browse/DEV-9593)
Author:
Reviewer(s):

DEV-9593 fixing case sensitive award id search

---

src/js/components/aboutTheDataSidebar/AboutTheDataDrilldown.jsx
src/js/components/aboutTheDataSidebar/AboutTheDataListView.jsx
src/js/components/agency/statusOfFunds/StatusOfFunds.jsx
src/js/components/agency/visualizations/StatusOfFundsChart.jsx
src/js/components/award/shared/AwardPageWrapper.jsx
src/js/components/award/shared/InfoTooltipContent.jsx
src/js/components/search/filters/location/EntityDropdown.jsx
src/js/components/sharedComponents/DatePicker.jsx
src/js/components/sharedComponents/TrainingVideoModal.jsx
src/js/components/sharedComponents/accordion/Accordion.jsx
src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/components/trainingVideos/featuredVideo/FeaturedVideo.jsx
src/js/components/trainingVideos/listOfVideos/ListOfVideos.jsx

replace .keyCode because it is deprecated
[DEV-9594](https://federal-spending-transparency.atlassian.net/browse/DEV-9594)
Author:
Reviewer(s):

DEV-9594 exchange keycode for key

---

package-lock.json
package.json

update dtui version with force resolutions 
[DEV-9585](https://federal-spending-transparency.atlassian.net/browse/DEV-9585)
Author:
Reviewer(s):

DEV-9585 update dtui version

---

src/js/components/search/filters/awardID/AwardIDSearch.jsx

changed how i did it, same end result minus the weird cursor jumping bug that allie found
[DEV-9593](https://federal-spending-transparency.atlassian.net/browse/DEV-9593)
Author:
Reviewer(s):

DEV-9593 fix from qa

---

src/js/components/agencyLanding/AgencyLandingContent.jsx

Update text on agency landing page
[DEV-9532](https://federal-spending-transparency.atlassian.net/browse/DEV-9532)
Author:
Reviewer(s):

9532 - Update text on agency landing page

---

src/_scss/layouts/default/header/_warning.scss
src/_scss/layouts/default/header/nav/headerNav.scss
src/js/GlobalConstants.js
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx

Add sitewide banner advertising the marketing campaign
No, this one was pretty straight forward
[DEV-9526](https://federal-spending-transparency.atlassian.net/browse/DEV-9526)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/screen/6414a872ee0f8d1021d9a78d
Author:
Reviewer(s):

9526 - Add sitewide banner advertising the marketing campaign

---

src/_scss/pages/state/topFive/_table.scss

translation off, this fixes it

DEV-9603 fix translation issue at 768px

---

src/_scss/layouts/default/header/_warning.scss

[DEV-9526](https://federal-spending-transparency.atlassian.net/browse/DEV-9526)
Author:
Reviewer(s):

9526 - Marketing banner color update

---

src/_scss/layouts/default/header/_warning.scss
src/js/components/sharedComponents/header/Header.jsx

[DEV-9526](https://federal-spending-transparency.atlassian.net/browse/DEV-9526)
Author:
Reviewer(s):

9526 - Fixed line break on mobile in marketing banner

---

src/js/helpers/awardAmountHelper.js

While reviewing PR to merge staging to master, noticed the check for negative numbers in the grant, loans, and insurance award amount chart was incorrect.  I don't have an example of this condition being exercised.
[DEV-8906](https://federal-spending-transparency.atlassian.net/browse/DEV-8906)
Author:
Reviewer(s):

8906 - Hotfix award chart

---

src/js/components/aboutTheDataSidebar/AboutTheDataHeader.jsx

Added an ID to the only h1 instead of about the data component
[DEV-9658](https://federal-spending-transparency.atlassian.net/browse/DEV-9658)
**Mockup:**
Author:
Reviewer(s):

In AboutTheDataHeader component,  added an id to the h1 element.

---

src/js/components/sharedComponents/StayInTouch.jsx

different implementation of learn more functionality
[DEV-9630](https://federal-spending-transparency.atlassian.net/browse/DEV-9630)
Author:
Reviewer(s):

DEV-9630 fix learn more footer

---

src/_scss/components/_roundedtoggle.scss
src/js/components/search/visualizations/SubawardToggle.jsx

fix tab for rounded toggle
[DEV-9636](https://federal-spending-transparency.atlassian.net/browse/DEV-9636)
Author:
Reviewer(s):

DEV-9636 toggles weren't tabbable properly

---

src/_scss/pages/award/visualizations/_additionalInfo.scss
src/js/components/award/shared/additionalInfo/Accordion.jsx

fixed tabbing when accordions closed
[DEV-9655](https://federal-spending-transparency.atlassian.net/browse/DEV-9655)
Author:
Reviewer(s):

DEV-9655 tabbing when accordions closed

---

src/_scss/pages/bulkDownload/form/_locationFilter.scss
src/_scss/pages/search/filters/location/location.scss
src/js/components/search/filters/location/EntityDropdown.jsx

add tooltip to CD text on Location filter - advanced search page
[DEV-9665](https://federal-spending-transparency.atlassian.net/browse/DEV-9665)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/screen/63ee57406477be6bea8852d1
Author:
Reviewer(s):

DEV-9665 CD Tooltip on Location filter (advanced search page)

---

src/_scss/components/search/_keywordSearchLink.scss
src/_scss/pages/search/_pagePositioning.scss
src/_scss/pages/search/searchSidebar.scss
src/js/components/search/KeywordSearchLink.jsx
src/js/components/search/SearchPage.jsx
src/js/components/search/SearchSidebar.jsx

link to keyword search on advanced search page
new component that goes under the sidebar on desktop and in the filter sidebar on mobile
[DEV-9691](https://federal-spending-transparency.atlassian.net/browse/DEV-9691)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/screen/642efd320fe96c686b40e264
Author:
Reviewer(s):

DEV-9691 keyword search link on advanced search page

---

src/js/components/analystGuide/AnalystGuidePage.jsx

This issue was flagged in our latest 508 scan
added aria-label to analyst guide download link
[DEV-9770](https://federal-spending-transparency.atlassian.net/browse/DEV-9770)
Author:
Reviewer(s):

9770 - added aria-label to analyst guide download link

---

src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx

Update Custom Account Data Download note for File C filter
[DEV-9788](https://federal-spending-transparency.atlassian.net/browse/DEV-9788)
Author:
Reviewer(s):

Hotfix: 9788 Update Custom Account Data Download note for File C filter

---

src/_scss/layouts/default/header/_officialSite.scss

Alignment fix from design review - https://data-transparency-bfs.slack.com/archives/GGRP4UMAT/p1684184028010769
[DEV-9671](https://federal-spending-transparency.atlassian.net/browse/DEV-9671)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/screen/640a4fb8661e2f7b24040ea0
Author:
Reviewer(s):

hotfix - 9671 Final tophat fix

---

src/_scss/layouts/default/header/nav/_megaMenu.scss
src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
src/js/dataMapping/navigation/menuOptions.jsx

bug fixes with nav
fixes atd issue
spacing on first dropdown
space between columns
16px left and right padding on top items in second and third dropdowns
api title change
Author:
Reviewer(s):

DEV-9700 fixes

---

src/js/components/glossary/definition/GlossaryDefinition.jsx

fix glossary copy function
[DEV-9872](https://federal-spending-transparency.atlassian.net/browse/DEV-9872)
Author:
Reviewer(s):

DEV-9872 fix glossary copy function

---

src/_scss/layouts/default/header/nav/_megaMenu.scss
src/_scss/pages/analystGuide/analystGuide.scss
src/js/components/sharedComponents/header/megaMenu/DropdownContainer.jsx
src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx

fit and finish for megamenu
[DEV-9847](https://federal-spending-transparency.atlassian.net/browse/DEV-9847)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/640fad0874ea6c39404e356d
Author:
Reviewer(s):

DEV-9847 remaining fixes

---

src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx

Fixed megamenu keyboard accessibility
Removed uniqueId from the navbar key.  
[DEV-9869](https://federal-spending-transparency.atlassian.net/browse/DEV-9869)
**Mockup:**
Author:
Reviewer(s):

9869 - Fixed megamenu keyboard accessibility

---

src/_scss/layouts/default/header/nav/_megaMenu.scss
src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
src/js/components/sharedComponents/header/megaMenu/DropdownContainer.jsx
src/js/components/sharedComponents/header/megaMenu/FadeContents.jsx

[DEV-9871](https://federal-spending-transparency.atlassian.net/browse/DEV-9871)
**Mockup:**
Author:
Reviewer(s):

9871 - Fix the mega menu animation when moving between dropdowns

---

src/js/components/trainingVideos/videoCard/VideoCard.jsx
src/js/dataMapping/trainingVideos/playListMetadata.js

Changing title of a video on the training page per Andrews request
https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1685543162981879
[DEV-9786](https://federal-spending-transparency.atlassian.net/browse/DEV-9786)
Author:
Reviewer(s):

Mod 9786 training video title change

---

src/_scss/layouts/default/header/nav/_megaMenu.scss
src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
src/js/components/sharedComponents/header/megaMenu/DropdownContainer.jsx
src/js/components/sharedComponents/header/megaMenu/FadeContents.jsx
src/js/components/sharedComponents/header/megaMenu/MegaMenu.jsx
src/js/components/sharedComponents/header/megaMenu/Navbar.jsx
src/js/components/sharedComponents/header/megaMenu/NavbarItem.jsx

DEV-9871 broke keyboard accessibility.  Updated fix for DEV-9871 to fix keyboard accessibility
[DEV-9871](https://federal-spending-transparency.atlassian.net/browse/DEV-9871
Author:
Reviewer(s):

DEV-9869 fixed keyboard accessibility

---

package-lock.json
package.json

increase dtui v to 5.6.1

---

src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx

fixing 404 issue
for testing it's specifically any of the second or third dropdown links in the gray section - if you click them when you're not on the homepage the url is appended to the base url when it shouldn't be

fixing 404 issue

---

src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Updated the status of fund chart tooltip hover state for level 4. can easily be changed for when level 5 is implemented. 
[DEV-9830](https://federal-spending-transparency.atlassian.net/browse/DEV-9830)
**Mockup:**
Author:
Reviewer(s):

Mod 9830 status of fund chart tooltip

---

src/js/components/search/filters/location/EntityDropdown.jsx

fix for marshall islands click bug

HOTFIX fixed marshall islands bug

---

src/_scss/layouts/default/footer/_stayInTouch.scss
src/_scss/layouts/default/header/_warning.scss
src/js/components/sharedComponents/StayInTouch.jsx
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx

Reverting adding congressional districts sitewide banner
[DEV-9934](https://federal-spending-transparency.atlassian.net/browse/DEV-9934)
Author:
Reviewer(s):

Revert 9934 - Adding congressional districts sitewide banner

---

src/js/dataMapping/aboutTheDataSchema.js

Revert 9936 - Removed the congressional district about the data entry
[DEV-9936](https://federal-spending-transparency.atlassian.net/browse/DEV-9936)
Author:
Reviewer(s):

Revert 9936 - Removed the congressional district about the data entry

---

src/_scss/components/aboutTheDataSidebar/_header.scss

fix atd close button size
[DEV-9436](https://federal-spending-transparency.atlassian.net/browse/DEV-9436)
Author:
Reviewer(s):

DEV-9436 fix atd close button size

---

src/js/components/award/shared/InfoTooltipContent.jsx

added some verbiage to match the mac
[DEV-9405](https://federal-spending-transparency.atlassian.net/browse/DEV-9405)
Author:
Reviewer(s):

Added outlayed amount

---

src/_scss/pages/explorer/detail/header/header.scss
src/js/components/explorer/detail/ExplorerInfoTooltip.jsx
src/js/components/explorer/detail/header/RootHeader.jsx

[DEV-9968](https://federal-spending-transparency.atlassian.net/browse/DEV-9968)
**Mockup:**
Author:
Reviewer(s):

Mod 9968 tooltip doesn't open on mouse click

---

src/js/components/explorer/detail/ExplorerInfoTooltip.jsx
src/js/components/explorer/detail/header/RootHeader.jsx

Reverts fedspendingtransparency/usaspending-website#3687

Revert "Mod 9968 tooltip doesn't open on mouse click"

---

src/_scss/pages/award/visualizations/_additionalInfo.scss

fix this problem in mobile
Author:
Reviewer(s):

DEV-10000 fix for mobile alignment

---

package.json

fix change that was accidentally committed

fix test in package.json

---

src/js/components/award/shared/InfoTooltipContent.jsx

update one sentence in tooltip 
[DEV-9911](https://federal-spending-transparency.atlassian.net/browse/DEV-9911)
Author:
Reviewer(s):

DEV-9911 update one section

---

src/js/components/award/shared/additionalInfo/AdditionalInfo.jsx

idvs don't have a place of performance so it was crashing, had to adjust my logic

fix for idvs when POP is not there

---

src/js/components/award/shared/overview/RecipientAddress.jsx

missed a feature flag
[DEV-9911](https://federal-spending-transparency.atlassian.net/browse/DEV-9911)
Author:
Reviewer(s):

missed feature flag

---

src/js/components/search/header/NoDownloadHover.jsx

fix link
[DEV-9833](https://federal-spending-transparency.atlassian.net/browse/DEV-9833)
Author:
Reviewer(s):

DEV-9833 update link

---

src/js/components/covid19/recipient/map/MapFilters.jsx
src/js/dataMapping/covid19/recipient/map/map.js

Unhid COVID Page CD tooltip and updated CD version of the map
[DEV-10051](https://federal-spending-transparency.atlassian.net/browse/DEV-10051)
Author:
Reviewer(s):

10051 - Added COVID CD work

---

src/js/components/about/AboutContent.jsx

forgot to remove training _facepalm_
Author:
Reviewer(s):

DEV-10066 forgot to remove training

---

src/js/components/award/shared/awardAmounts/AwardAmountsTable.jsx

Added back the $0.00 amount to display. 
[DEV-10079](https://federal-spending-transparency.atlassian.net/browse/DEV-10079)
Author:
Reviewer(s):

Mod 10079 bug fix zero diplay

---

src/_scss/pages/state/topFive/_table.scss

correct the top five section for mobile so that it stacks on recipient page
[DEV-7690](https://federal-spending-transparency.atlassian.net/browse/DEV-7690)
Author:
Reviewer(s):

DEV-7690 stack recipient top 5 mobile

---

src/_scss/components/datePicker/_datePicker.scss
src/_scss/pages/search/filters/timePeriod/timePeriod.scss

make some adjustments to fix date picker <992 and 1200-1335px
[DEV-9893](https://federal-spending-transparency.atlassian.net/browse/DEV-9893)
Author:
Reviewer(s):

DEV-9893 fix date dropdown for various screen sizes

---

src/_scss/components/datePicker/_datePicker.scss

from testing, making the date filters the same width so that I can overcome the issue with width: auto and width: 100%

DEV-9893 width auto wasn't making them the same size

---

src/_scss/layouts/default/header/nav/_megaMenu.scss

[DEV-10110](https://federal-spending-transparency.atlassian.net/browse/DEV-10110)
Author:
Reviewer(s):

Hotfix - 10110 Fixed issue with transitioning between menu items

---

src/_scss/layouts/default/header/nav/_megaMenu.scss

[DEV-10110](https://federal-spending-transparency.atlassian.net/browse/DEV-10110)
Author:
Reviewer(s):

10110 - Fix for issue in Edge and Safari

---

src/_scss/layouts/default/header/nav/_megaMenu.scss
src/js/models/v1/search/SearchAwardsOperation.js

Staging to Master
**Mockup:**
Author:
Reviewer(s):

Staging to Prod

---

src/js/components/covid19/OtherResources.jsx
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/recipient/RecipientSection.jsx

Update some bad links on covid page
We were using beta.sam... links for some reason; and one other one just needed to be updated to a new page
[DEV-9471](https://federal-spending-transparency.atlassian.net/browse/DEV-9471)
**Mockup:**
n/a
Author:
Reviewer(s):

9471 - updated bad links

---

src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx

https://data-transparency-bfs.slack.com/archives/C0155EL4AU9/p1691694008928159

Hotfix - Warning to alert users of api failures

---

src/js/components/sharedComponents/header/Header.jsx

**Mockup:**
Author:
Reviewer(s):

Removed api outage warning banner

---

src/js/components/sharedComponents/FilterModal.jsx

Updated some wordage on the tooltip on the advance search page. 
Time Tooltip on the filter section
and
The Learn how active filters work tooltip. 
[DEV-9622](https://federal-spending-transparency.atlassian.net/browse/DEV-9622)
**Mockup:**
Author:
Reviewer(s):

Fix 9622 advanced searchand/or logic fix

---

src/js/components/about/AboutContent.jsx
src/js/components/agency/AgencyPage.jsx
src/js/components/covid19/Covid19Page.jsx
src/js/components/glossary/definition/GlossaryDefinition.jsx
src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx
src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx
src/js/components/state/StateContent.jsx
src/js/containers/glossary/GlossaryListener.jsx

covering edge cases for glossary/atd
less use of ? hardcoded and need to use history.replace less
[DEV-10162](https://federal-spending-transparency.atlassian.net/browse/DEV-10162)
Author:
Reviewer(s):

DEV-10162 atd/glossary edge cases

---

package-lock.json
src/_scss/layouts/default/stickyHeader/_inpagenav.scss
src/_scss/layouts/default/stickyHeader/header.scss
src/js/components/about/navTest/About.jsx
src/js/components/about/navTest/AboutContent.jsx
src/js/components/inPageNav/InPageNav.jsx
src/js/components/sharedComponents/PageWrapper.jsx
src/js/containers/router/RouterRoutes.jsx

In-page nav left scroll and resize behavior
[DEV-10167](https://federal-spending-transparency.atlassian.net/browse/DEV-10167)
Author:
Reviewer(s):

10167 - In-page nav left scroll and resize behavior

---

package-lock.json

fix issue with social share sticking

fixing package lock/social share

---

src/js/components/award/idv/activity/IdvActivity.jsx

HOTFIX fix idv problem

---

src/js/components/explorer/detail/ExplorerDetailPage.jsx
src/js/containers/explorer/detail/ExplorerDetailPageContainer.jsx

[DEV-10216](https://federal-spending-transparency.atlassian.net/browse/DEV-10216)
Author:
Reviewer(s):

10216 Removed WithRouter and converted components from class to function

---

src/js/containers/recipient/RecipientContainer.jsx

Convert RecipientContainer class component to function component
Converted class component to function component by changing the format of the component, converting the methods to functions, removing references to this, replacing the constructor with useState, and refactoring lifecycle methods with useEffects. Also, replaced withRouter dependency with useHistory. 
[DEV-10213](https://federal-spending-transparency.atlassian.net/browse/DEV-10213)
**Mockup:**
N/A
Author:
Reviewer(s):

Mod/10213 convert RecipientContainer to function component

---

package-lock.json
src/js/containers/award/AwardContainer.jsx

change to functional component
[DEV-10209](https://federal-spending-transparency.atlassian.net/browse/DEV-10209)
Author:
Reviewer(s):

DEV-10209 AwardContainer functional component

---

src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx

functional component
[DEV-10210](https://federal-spending-transparency.atlassian.net/browse/DEV-10210)
Author:
Reviewer(s):

DEV-10210 BulkDownloadPageContainer functional component

---

src/js/components/bulkDownload/awards/filters/dateRange/TimePeriodFilter.jsx
src/js/components/search/filters/timePeriod/TimePeriod.jsx

allie found a bug from the moment ticket, quick fix for it
[DEV-10224](https://federal-spending-transparency.atlassian.net/browse/DEV-10224)
Author:
Reviewer(s):

DEV-10224 fix small bug allie found

---

package-lock.json

package lock fix

---

package-lock.json
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
src/js/models/v1/search/SearchAwardsOperation.js

fix bug allie found in 10214
[DEV-10214](https://federal-spending-transparency.atlassian.net/browse/DEV-10214)
Author:
Reviewer(s):

fix bug with subaward table in search

---

src/js/containers/search/table/ResultsTableContainer.jsx

undo 10214

---

package-lock.json
src/js/components/sharedComponents/checkbox/PrimaryCheckboxType.jsx
src/js/components/sharedComponents/checkbox/SecondaryCheckboxType.jsx
src/js/components/sharedComponents/checkbox/SingleCheckboxType.jsx

change event names
[DEV-10343](https://federal-spending-transparency.atlassian.net/browse/DEV-10343)
Author:
Reviewer(s):

DEV-10343 change event types ac2

---

src/_scss/pages/search/filters/recipient/_recipientType.scss

issue found by testing
**Mockup:**
Author:
Reviewer(s):

DEV-10299 - addressed testing feedback, fixed the width for recipient type filter checkboxes

---

package-lock.json

fix yargs issue

---

package-lock.json
src/js/components/search/filters/recipient/RecipientTypeAccordion.jsx
src/js/dataMapping/search/recipientType.js

fix issues mentioned here https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1700596326299819

HOTFIX - issues mentioned https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1700596326299819

---

src/js/components/about/navTest/About.jsx
src/js/components/inPageNav/InPageNav.jsx
src/js/components/sharedComponents/PageWrapper.jsx

In-page nav highlight active section on scroll
re-used code from Sidebar.jsx to detect active section in side bar
[DEV-10420](https://federal-spending-transparency.atlassian.net/browse/DEV-10420)
Author:
Reviewer(s):

10420 - In-page nav highlight active section on scroll

---

package-lock.json
package.json
src/_scss/layouts/default/stickyHeader/_inpagenav.scss
src/js/components/about/navTest/About.jsx
src/js/components/inPageNav/InPageNav.jsx
src/js/components/sharedComponents/PageWrapper.jsx

Added the inpage nav to dtui
Removed the in-page nav component from the PageWrapper component and added it to the DTUI Page Header component. 
When adding the in-page nav to a new page please add the inPageNav prop to the PageWrapper component to enable the in-page nav
[DEV-10425](https://federal-spending-transparency.atlassian.net/browse/DEV-10425)
Author:
Reviewer(s):

10425 - Added the inpage nav to dtui

---

package-lock.json
package.json

n/a
n/a
n/a
Author:
n/a
Reviewer(s):

Added adobe-css dependency 4.3.2 to resolutions to address security vulnerability

---

src/_scss/pages/state/_positioning.scss
src/js/components/state/StateContent.jsx
src/js/components/state/StatePage.jsx

inpagenav on state profile
[DEV-10387](https://federal-spending-transparency.atlassian.net/browse/DEV-10387)
Author:
Reviewer(s):

DEV-10387 inpagenav state profile

---

package-lock.json
package.json
src/js/components/aboutTheDataSidebar/AboutTheData.jsx
src/js/components/glossary/Glossary.jsx
src/js/components/search/filters/location/EntityDropdown.jsx

mousetrap doesn't like react 18, remove and replace with event listener js
[DEV-10421](https://federal-spending-transparency.atlassian.net/browse/DEV-10421)
Author:
Reviewer(s):

DEV-10421 remove mousetrap, fix esc 

---

package-lock.json
src/_scss/pages/search/results/visualizations/geo/map/_toggle.scss
src/_scss/pages/state/visualizations/geo/geoVisualization.scss

because we removed the sidebar and/or added another option to the map for congressional districts, the tooltip spacer had to be translated a different number of pixels
[DEV-10010](https://federal-spending-transparency.atlassian.net/browse/DEV-10010)
Author:
Reviewer(s):

DEV-10010 issue with translate of tooltip spacer

---

src/js/containers/search/filters/recipient/RecipientNameDUNSContainer.jsx
src/js/containers/search/filters/recipient/RecipientSearchContainer.jsx
src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx

recipient/name/duns container search filter - class to functional component
[DEV-10469](https://federal-spending-transparency.atlassian.net/browse/DEV-10469)
Author:
Reviewer(s):

DEV-10469 class to functional component

---

src/_scss/pages/interactiveDataSources/_lottieAnimation.scss
src/_scss/pages/interactiveDataSources/index.scss
src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx
src/js/components/interactiveDataSources/InteractiveDataSourcesSection.jsx

inpagenav on interactive data sources page
[DEV-9848](https://federal-spending-transparency.atlassian.net/browse/DEV-9848)
Author:
Reviewer(s):

DEV-9848 in page nav on interactive data sources

---

src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
src/js/components/covid19/recipient/map/MapWrapper.jsx
src/js/components/search/visualizations/geo/map/MapBox.jsx

fix for 10459 covid and search maps
worked with @jagu65 
[DEV-10459](https://federal-spending-transparency.atlassian.net/browse/DEV-10459)
Author:
Reviewer(s):

fix for 10459 covid and search maps

---

src/_scss/layouts/default/header/nav/mobile/_animations.scss
src/js/components/sharedComponents/header/NavbarWrapper.jsx
src/js/components/sharedComponents/header/mobile/MobileNav.jsx

Fix to mobile nav close transition not working in Safari 
[DEV-10426](https://federal-spending-transparency.atlassian.net/browse/DEV-10426)
Author:
Reviewer(s):

10426 - Fix to mobile nav close transition not working in Safari 

---

package-lock.json
package.json

a package had a vulnerability according to travis, fixing that issue

fixing travis failure

---

.travis.yml
package-lock.json
package.json

**Mockup:**
Author:
Reviewer(s):

Fix package lock

---

package-lock.json
src/_scss/pages/award/visualizations/description/_description.scss
src/js/components/award/shared/description/AwardDescription.jsx

use this as an example: http://localhost:3000/award/CONT_AWD_HSFE0907J0099_7022_-NONE-_-NONE-
[DEV-10279](https://federal-spending-transparency.atlassian.net/browse/DEV-10279)
Author:
Reviewer(s):

DEV-10279 align psc and naics boxes when there are no codes

---

src/js/components/agency/AgencyPage.jsx

make history replace smarter
[DEV-10510](https://federal-spending-transparency.atlassian.net/browse/DEV-10510)
Author:
Reviewer(s):

DEV-10510 make the history.replace smarter

---

src/_scss/pages/agency/visualizations/_obligationsByAwardType.scss
src/js/components/agency/AgencyPage.jsx

align donut tooltip horizontally 
[DEV-10511](https://federal-spending-transparency.atlassian.net/browse/DEV-10511)
Author:
Reviewer(s):

DEV-10511 horizontally align tooltip under donut

---

package-lock.json
src/js/components/search/SearchPage.jsx

Need to get package-lock changes into Staging bc it's out of sync with Prod
**Mockup:**
Author:
Reviewer(s):

qat - comment for new build

---

src/js/helpers/searchHelper.js

https://data-transparency-bfs.slack.com/archives/CE892FN21/p1706793558127479
Author:
Reviewer(s):

HOTFIX trailing slash issue

---

package-lock.json
src/_scss/layouts/default/stickyHeader/header.scss
src/_scss/pages/interactiveDataSources/index.scss
src/js/components/sharedComponents/DownloadStaticFile.jsx

align share and download icons on data sources page
[DEV-10557](https://federal-spending-transparency.atlassian.net/browse/DEV-10557)
Author:
Reviewer(s):

DEV-10557 align icons on data sources page

---

src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx

inpage nav on https://www.usaspending.gov/submission-statistics/data-sources (use localhost obviously)
[DEV-10565](https://federal-spending-transparency.atlassian.net/browse/DEV-10565)
Author:
Reviewer(s):

DEV-10565 add inpagenav to submission stats dsm

---

src/_scss/core/_base.scss
src/_scss/pages/search/searchPage.scss

remove gray border from body except search page
[DEV-10580](https://federal-spending-transparency.atlassian.net/browse/DEV-10580)
Author:
Reviewer(s):

DEV-10580 remove gray border from pages

---

package-lock.json
package.json

Strnage little bug with inPageNav, only seen on the Data Sources page, which has the longest list of sections, at screens > 1640px. When scrolling right, to the last section, the right chevron doesn't disappear like it should. The chevron should disappear when the user gets to the end of the list of sections, and it always does at smaller screen sizes.
Made a new rule for calculating the isOverflowRight for screens > 1640px; also refactored the handleResize function, and got rid of the useEffect with windowWidth as a dependency, since we have a listener on 'resize'
[DEV-10408](https://federal-spending-transparency.atlassian.net/browse/DEV-10408)
**Mockup:**
n/a …

10408 - new dtui version

---

package-lock.json
package.json

[DEV-10516](https://federal-spending-transparency.atlassian.net/browse/DEV-10516)
Author:
Reviewer(s):

Mod/10516 increase dtui version for in-page nav unit tests

---

src/js/containers/search/table/ResultsTableContainer.jsx

**Mockup:**
Author:
Reviewer(s):

backing out 10646 fix because it broken 10513

---

src/js/components/search/visualizations/geo/map/MapBox.jsx

Fixed COVID-19 page not loading in Staging before prod deploy
Regression from DEV-10520

Hotfix - fix covid page not loading

---

src/js/components/search/visualizations/geo/map/MapBox.jsx
src/js/models/v1/search/SearchAwardsOperation.js

Staging to qat downmerge

---

src/_scss/layouts/summary/summary.scss
src/_scss/mixins/background.scss
src/_scss/pages/aboutTheData/aboutTheData.scss
src/_scss/pages/account/accountPage.scss
src/_scss/pages/account/overview/overview.scss
src/_scss/pages/agency/index.scss
src/_scss/pages/bulkDownload/bulkDownloadPage.scss
src/_scss/pages/covid19/index.scss
src/_scss/pages/dataDictionary/dataDictionaryPage.scss
src/_scss/pages/interactiveDataSources/index.scss
src/_scss/pages/recipient/_contentWrap.scss
src/_scss/pages/recipient/recipientPage.scss
src/_scss/pages/state/_contentWrap.scss
src/_scss/pages/state/statePage.scss

more deleting than originally thought, it was not all in one place
[DEV-10653](https://federal-spending-transparency.atlassian.net/browse/DEV-10653)
[DEV-10655](https://federal-spending-transparency.atlassian.net/browse/DEV-10655)
Author:
Reviewer(s):

DEV-10653 and DEV-10655 extra margin and pointless gray border/box shadow

---

src/_scss/components/_titleBarFilter.scss

additional feedback, added comments where we'll have to add additional styling when we have a practical example
[DEV-10647](https://federal-spending-transparency.atlassian.net/browse/DEV-10647)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/65ba9e3c5ee8df1046ce0ae2
Author:
Reviewer(s):

DEV-10647 additional designer feedback

---

src/js/components/search/visualizations/geo/map/MapBox.jsx

[DEV-10650](https://federal-spending-transparency.atlassian.net/browse/DEV-10650)
Author:
Reviewer(s):

Fix/10650: Increase zoom levels for cds and counties

---

src/js/components/search/visualizations/time/TimeVisualizationChart.jsx

Need to figure out what the designers want to show when data isn't available for this chart.
[DEV-10649](https://federal-spending-transparency.atlassian.net/browse/DEV-10649)
Author:
Reviewer(s):

Fix for 10649 - Fixed crash when no data is available

---

src/js/components/search/filters/location/EntityDropdown.jsx

location filter fix
[DEV-10743](https://federal-spending-transparency.atlassian.net/browse/DEV-10743)
Author:
Reviewer(s):

DEV-10743 fix location filter dropdown on advanced search

---

src/js/components/search/visualizations/time/TimeVisualizationChart.jsx

[DEV-10744](https://federal-spending-transparency.atlassian.net/browse/DEV-10744)
**Mockup:**
Author:
Reviewer(s):

10744 - Spending over Time time jump update

---

package-lock.json
package.json
src/js/helpers/analytics/Analytics.js

[DEV-10803](https://federal-spending-transparency.atlassian.net/browse/DEV-10803)
Author:
Reviewer(s):

Hotfix 10803 - Revert GA4 DAP change to fix DAP UA 

---

src/_scss/components/_titleBarFilter.scss
src/_scss/pages/search/searchPage.scss

fix this
[DEV-10729](https://federal-spending-transparency.atlassian.net/browse/DEV-10729)
Author:
Reviewer(s):

DEV-10729 fix minor problem where dropdowns on advanced search were unnecessarily translated

---

package-lock.json
src/js/components/search/visualizations/time/TimeVisualizationSection.jsx

[DEV-10727](https://federal-spending-transparency.atlassian.net/browse/DEV-10727)
[DEV-10728](https://federal-spending-transparency.atlassian.net/browse/DEV-10728)
Author:
Reviewer(s):

Spending Over Time feature - Removed the QAT only flag for spending over time chart

---

src/_scss/layouts/default/default.scss
src/_scss/layouts/default/header/_warning.scss
src/_scss/pages/search/searchPage.scss
src/js/components/search/SearchPage.jsx

Banner for search page problems. 
Had to make some css adjustments bc it looked weird.
no ticket
**Mockup:**
Author:
Reviewer(s):

Search results banner

---

src/_scss/layouts/default/header/_warning.scss
src/js/components/search/SearchPage.jsx

**Mockup:**
Author:
Reviewer(s):

no ticket number - removed banner

---

src/js/dataMapping/trainingVideos/playListMetadata.js
src/js/dataMapping/trainingVideos/playlist.js

Added new video
[DEV-10447](https://federal-spending-transparency.atlassian.net/browse/DEV-10447)
Author:
Reviewer(s):

10447 - Added new video

---

src/_scss/components/_titleBarFilter.scss
src/_scss/pages/search/results/visualizations/geo/geoVisualization.scss
src/_scss/pages/search/searchPage.scss
src/js/components/sharedComponents/dropdowns/NewPicker.jsx
src/js/components/sharedComponents/dropdowns/NumericPickerWrapper.jsx

The new dropdown component how has items that are now fully clickable.
The entire li element now has onClick and onKeyUp functionality for clicking/selection.
[DEV-10866](https://federal-spending-transparency.atlassian.net/browse/DEV-10866)
**Mockup:**
n/a
Author:
Reviewer(s):

10866 - fix for click

---

src/_scss/layouts/landingPage/landingPage.scss

Updated the landing pages font to match profile pages.
The h2 element on the landing pages was changed to match the h2 on the profile pages.
[DEV-10879](https://federal-spending-transparency.atlassian.net/browse/DEV-10879)
**Mockup:**
n/a
Author:
Reviewer(s):

10879 - updated the h4 tag font style on the landing pages

---

src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

hotfix for downloads
https://data-transparency-bfs.slack.com/archives/CE892FN21/p1713979864024549
Author:
Reviewer(s):

fix null checks for download

---

src/_scss/layouts/default/default.scss
src/_scss/layouts/default/header/_warning.scss
src/js/components/search/SearchPage.jsx

**Mockup:**
Author:
Reviewer(s):

removed unused code

---

package-lock.json
src/js/GlobalConstants.js
src/js/components/sharedComponents/header/Header.jsx

Added warning banner to covid page only
Updated banner code so that we can just change the globalconstants to turn on and off the banner.
[DEV-10952](https://federal-spending-transparency.atlassian.net/browse/DEV-10952)
Author:
Reviewer(s):

Hotfix 10952 - Added warning banner to covid page only

---

src/js/components/search/newResultsView/SectionDataTable.jsx

Resolving issue found during testing
[DEV-10884](https://federal-spending-transparency.atlassian.net/browse/DEV-10884)
**Mockup:**
Author:
Reviewer(s):

10884 - Fixed results by time section table pagination

---

src/_scss/pages/search/searchPage.scss

hiding button, very straightforward
[DEV-10994](https://federal-spending-transparency.atlassian.net/browse/DEV-10994)
Author:
Reviewer(s):

DEV-10994 hide See Spending from last year button

---

src/_scss/pages/search/results/visualizations/time/timeVisualization.scss

update a couple styles for spending over time tooltip 
[DEV-10963](https://federal-spending-transparency.atlassian.net/browse/DEV-10963)
**Mockup:**
picture in ticket above
Author:
Reviewer(s):

DEV-10963 formatting spending over time tooltips

---

package-lock.json
package.json
src/_scss/elements/_table.scss
src/js/components/search/newResultsView/SectionDataTable.jsx
src/js/components/search/newResultsView/categories/CategoriesTable.jsx

[DEV-10929](https://federal-spending-transparency.atlassian.net/browse/DEV-10929)
Author:
Reviewer(s):

Updated categories and spending over time table classname to adopt dtui changes

---

package.json

Add right border back to dtui Table
Removed the line that removed that border
[DEV-11021](https://federal-spending-transparency.atlassian.net/browse/DEV-11021)
**Mockup:**
Author:
Reviewer(s):

11021 - new dtui version number

---

package-lock.json

**Mockup:**
Author:
Reviewer(s):

Generated new package-lock

---

src/_scss/pages/keyword/keywordPage.scss

fix keyword search

---

package-lock.json
src/_scss/pages/account/results/table/awardTable.scss
src/js/components/account/SearchResults.jsx
src/js/containers/account/awards/AccountAwardsContainer.jsx

fix federal account table, missing styles and updated the container used for the federal account so it is now a functional component
search table styles look correct still

fix federal account table

---

package-lock.json
src/js/containers/search/newResultsView/ResultsTableContainer.jsx

we were missing a useeffect dependency
[DEV-11029](https://federal-spending-transparency.atlassian.net/browse/DEV-11029)
Author:
Reviewer(s):

DEV-11029 fix subaward toggle problem on new search page

---

src/js/containers/search/newResultsView/CategoriesVisualizationWrapperContainer.jsx

Fixed issue with Results by Categories, Recipient chart links in labels
[DEV-11033](https://federal-spending-transparency.atlassian.net/browse/DEV-11033)
Author:
Reviewer(s):

11033 - Fixed issue with Results by Categories, Recipient chart links in labels

---

src/_scss/pages/about/_contentWrap.scss
src/_scss/pages/search/searchPage.scss
src/js/components/search/newResultsView/SectionsContent.jsx

[DEV-10906](https://federal-spending-transparency.atlassian.net/browse/DEV-10906)
Author:
Reviewer(s):

10906 - Missed removing gray background and adding GA event for visualization sections

---

src/js/components/search/newResultsView/ResultsView.jsx

**Mockup:**
Author:
Reviewer(s):

removed page feature flag from result view component

---

src/_scss/pages/agency/statusOfFunds/_statusOfFunds.scss

added back in

---

src/_scss/pages/search/results/searchResults.scss
src/js/LocalConstants.js
src/js/components/search/newResultsView/SectionDataTable.jsx
src/js/components/search/newResultsView/categories/CategoriesTable.jsx

ISSUE:  https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1718916631689779?thread_ts=1718907499.882299&cid=CE5P5AWE8
Please test the tables in the sections - Results by Geography, Results by Categories, and Results Over Time at mobile and very small px widths.  The table should be visible in the container (ie. not outside of the section container as in the slack post), the table should be horizontally scrollable (ie. contain the left sticky column and ability to scroll to the left and right)
Reviewer(s):

Fixed issue found during testing with section tables

---

src/_scss/pages/search/resultsView/_resultsView.scss

remove dsm scrollbar
**Mockup:**
Author:
Reviewer(s):

remove scroll bar in dsm

---

src/js/components/search/visualizations/rank/spendingByCategoriesChart/SpendingByCategoriesChart.jsx

capital letters are different widths so i had to adjust the one line logic a bit more 
https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1719931932863159?thread_ts=1719919128.042749&cid=CE5P5AWE8
[DEV-11089](https://federal-spending-transparency.atlassian.net/browse/DEV-11089)
Author:
Reviewer(s):

DEV-11089 fix alignment for caps on results by category -> recipients

---

src/js/components/covid19/recipient/map/MapFiltersToggle.jsx
src/js/components/covid19/recipient/map/MapWrapper.jsx
src/js/components/search/visualizations/geo/MapWrapper.jsx

fix map toggle on enter
[DEV-11193](https://federal-spending-transparency.atlassian.net/browse/DEV-11193)
Author:
Reviewer(s):

DEV-11193 fix map toggle

---

src/js/components/about/legal/PrivacyPage.jsx

Added 'Making A Privacy Request' to the Privacy Page.
Added the text and link to PrivacyPage.jsx
[DEV-11172](https://federal-spending-transparency.atlassian.net/browse/DEV-11172)
**Mockup:**
n/a
Author:
Reviewer(s):

11172 - added 'Making A Privacy Request'

---

src/_scss/elements/_table.scss

**Mockup:**
Author:
Reviewer(s):

hotfix - added css to make table row hover work correctly

---

.travis.yml
src/_scss/elements/_table.scss

**Mockup:**
Author:
Reviewer(s):

Staging to Master

---

package-lock.json
src/js/containers/search/filters/AgencyListContainer.jsx

issue where if you typed chars on page load it would error, the problem was that setState was not finishing before it was being used to query the api
this was a simple solution for the problem
[DEV-11192](https://federal-spending-transparency.atlassian.net/browse/DEV-11192)
Author:
Reviewer(s):

DEV-11192 agency input box issue in advanced search

---

package-lock.json

package-lock
n/a
**Mockup:**
n/a
Author:
Reviewer(s):

11227 - package-lock

---

src/js/dataMapping/trainingVideos/playListMetadata.js

Added new YouTube video to testimonials section.
Added meta data for new YouTube video. 
[DEV-11164](https://federal-spending-transparency.atlassian.net/browse/DEV-11164)
**Mockup:**
N/A
Author:
Reviewer(s):

11164 - Added new YouTube video to training section

---

Dockerfile

**Mockup:**
Author:
Reviewer(s):

add maxsockets 1

---

src/js/GlobalConstants.js

[DEV-11363](https://federal-spending-transparency.atlassian.net/browse/DEV-11363)
**Mockup:**
Author:
Reviewer(s):

Toggle off banner from GlobalConstants

---

src/js/components/search/newResultsView/SearchSectionWrapper.jsx
src/js/components/search/newResultsView/SectionsContent.jsx
src/js/components/search/newResultsView/map/MapSection.jsx
src/js/components/search/newResultsView/table/TableSection.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1723724473481859?thread_ts=1723657841.782449&cid=CE5P5AWE8

11292 - Adjusted the homepage jump to location for the map

---

src/js/containers/search/filters/location/NewLocationSectionContainer.jsx

removing console log
Author:
Reviewer(s):

remove console

---

src/js/components/search/SearchPage.jsx

escape key functionality <992px for filter overlay
[DEV-11386](https://federal-spending-transparency.atlassian.net/browse/DEV-11386)
Author:
Reviewer(s):

DEV-11386 escape <992px

---

src/_scss/pages/state/overview/_overview.scss
src/js/components/state/overview/StateOverview.jsx

Replaced existing copy of the "What is this?" accordion/panel with the new copy and added bottom margin.
[DEV-11281](https://federal-spending-transparency.atlassian.net/browse/DEV-11281)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/667c5f77d0da3162e016d3be
Author:
Reviewer(s):

11281 - update content of outlays panel on state profile page

---

package-lock.json
src/_scss/pages/search/filters/timePeriod/timePeriodNew.scss
src/js/components/search/filters/timePeriod/DateRange.jsx
src/js/components/search/filters/timePeriod/DateRangeError.jsx
src/js/components/search/filters/timePeriod/TimePeriod.jsx
src/js/components/sharedComponents/DatePicker.jsx

change error message style on date range
[DEV-11396](https://federal-spending-transparency.atlassian.net/browse/DEV-11396)
Author:
Reviewer(s):

DEV-11396 new error message for date range

---

src/js/components/sharedComponents/autocomplete/Autocomplete.jsx

fixes this problem https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1726081909623479?thread_ts=1726000737.164129&cid=CE5P5AWE8
Author:
Reviewer(s):

fix null reference in cfda dropdown

---

src/js/LocalConstants.js
src/js/components/sharedComponents/autocomplete/Autocomplete.jsx

**Mockup:**
Author:
Reviewer(s):

11490 - additional tweak, fixed font color in autocomplete

---

package-lock.json
src/js/containers/state/StateContainer.jsx

class to functional state page container, should be merged after the hotfix is done so that the page can properly be tested
[DEV-11474](https://federal-spending-transparency.atlassian.net/browse/DEV-11474)
Author:
Reviewer(s):

DEV-11474 state page container class to functional

---

package-lock.json
src/js/components/search/filters/timePeriod/DateRange.jsx
src/js/components/search/filters/timePeriod/DateRangeError.jsx
src/js/components/search/filters/timePeriod/TimePeriod.jsx

fix for date range error when you enter characters not expected for mm/dd/yyyy
[DEV-11504](https://federal-spending-transparency.atlassian.net/browse/DEV-11504)
Author:
Reviewer(s):

DEV-11504 fix for date range error (advanced search filter)

---

src/_scss/layouts/default/footer/_downloadBottomBar.scss
src/js/components/search/modals/fullDownload/DownloadBottomBar.jsx
src/js/containers/bulkDownload/modal/BulkDownloadBottomBarContainer.jsx
src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx

Updated the download bottom bar message to inform users about the expiration of the download link.
[DEV-11375](https://federal-spending-transparency.atlassian.net/browse/DEV-11375)
**Mockup:**
N/A
Author:
Reviewer(s):

11375 - update message on download bar

---

src/js/containers/state/topFive/TopFiveContainer.jsx

i believe this was just a typo that i fixed
[DEV-11434](https://federal-spending-transparency.atlassian.net/browse/DEV-11434)
Author:
Reviewer(s):

DEV-11434 fix states so that it uses loading: true

---

src/_scss/pages/state/visualizations/geo/geoVisualization.scss

added missing import
[DEV-11471](https://federal-spending-transparency.atlassian.net/browse/DEV-11471)
Author:
Reviewer(s):

DEV-11471 add loading class

---

package-lock.json
src/js/components/state/StatePage.jsx
src/js/components/state/topFive/TopFive.jsx
src/js/components/stateLanding/table/StateLandingTable.jsx
src/js/containers/state/StateContainer.jsx

new fy changes
[DEV-11526](https://federal-spending-transparency.atlassian.net/browse/DEV-11526)
Author:
Reviewer(s):

DEV-11526 fixed issues caused by new FY

---

package-lock.json
src/js/dataMapping/navigation/menuOptions.jsx

external link change for download data
[DEV-11394](https://federal-spending-transparency.atlassian.net/browse/DEV-11394)
Author:
Reviewer(s):

DEV-11394 external link change

---

package-lock.json

fix staging lock

---

src/js/dataMapping/navigation/menuOptions.jsx

removing leaving government site popup for database download
[DEV-11535](https://federal-spending-transparency.atlassian.net/browse/DEV-11535)
Author:
Reviewer(s):

DEV-11535 remove leaving gov't site popup

---

src/js/GlobalConstants.js
src/js/components/sharedComponents/header/Header.jsx

[DEV-11565](https://federal-spending-transparency.atlassian.net/browse/DEV-11565)
Author:
Reviewer(s):

Hotfix: 11565 Add Banner to notify users about data download issues

---

src/_scss/pages/aboutTheData/_agenciesPage.scss

more borders added than needed
[DEV-11302](https://federal-spending-transparency.atlassian.net/browse/DEV-11302)
Author:
Reviewer(s):

DEV-11302 fix double borders

---

src/_scss/pages/search/filters/awardAmount/_awardAmountItem.scss

add focus visible outline color for award amount checkboxes
[DEV-11524](https://federal-spending-transparency.atlassian.net/browse/DEV-11524)
Author:
Reviewer(s):

DEV-11524 focus visible outline color on award amount

---

src/js/containers/search/filters/location/LocationAutocompleteContainer.jsx

Fix for issue mentioned in Slack - https://data-transparency-bfs.slack.com/archives/C0155EL4AU9/p1729714969023459

use effect error causing infinite calls to countries.json

---

src/js/GlobalConstants.js

The download issue will be fixed with today's backend prod deploy so we can remove the banner with our frontend prod deploy.
[DEV-11598](https://federal-spending-transparency.atlassian.net/browse/DEV-11598)
Author:
Reviewer(s):

11598 - remove banner about download issue from Adv Search

---

src/_scss/pages/homepageUpdate/_awardSearch.scss

removing this fixes desktop and seems to preserve tablet and mobile
Author:
Reviewer(s):

fix carousel

---

src/js/containers/recipient/topFive/TopFiveContainer.jsx

Converted recipient TopFiveContainer.jsx to functional.
No change to behavior expected..
[DEV-11344](https://federal-spending-transparency.atlassian.net/browse/DEV-11344)
**Mockup:**
n/a
Author:
Reviewer(s):

11344 - converted TopFiveContainter to functional

---

src/_scss/core/_variables.scss
src/_scss/layouts/default/header/_warning.scss
src/_scss/pages/trainingVideos/_trainingVideosHeading.scss
src/js/GlobalConstants.js
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/components/trainingVideos/trainingVideosHeading/TrainingVideosHeading.jsx

banner on training videos page
[DEV-11505](https://federal-spending-transparency.atlassian.net/browse/DEV-11505)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/672411ac10dae1c627b50256
Author:
Reviewer(s):

DEV-11505 banner on training videos page

---

src/js/components/sharedComponents/checkbox/ListCheckbox.jsx
src/js/containers/search/filters/ExtentCompetedContainer.jsx

Refactored to have the search bar within the ListCheckbox.jsx component.
[DEV-11627](https://federal-spending-transparency.atlassian.net/browse/DEV-11627)
**Mockup:**
n/a
Author:
Reviewer(s):

11627 - moved search bar to list checkbox component

---

src/_scss/pages/covid19/index.scss
src/js/components/covid19/Covid19Page.jsx

Added grid and new page margins.
[DEV-10896](https://federal-spending-transparency.atlassian.net/browse/DEV-10896)
**Mockup:**
n/a
Author:
Reviewer(s):

10896 - COVID page new margins and grid

---

src/_scss/elements/filters/_typeahead.scss
src/js/components/search/filters/location/LocationAutocomplete.jsx
src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
src/js/components/sharedComponents/autocomplete/SuggestionHolder.jsx
src/js/containers/search/filters/location/LocationAutocompleteContainer.jsx

there was no loading state so had to add the loading state and the indicator and then style it
[DEV-11618](https://federal-spending-transparency.atlassian.net/browse/DEV-11618)
Author:
Reviewer(s):

DEV-11618 add loading indicator for location filter

---

src/js/containers/search/filters/TimePeriodContainer.jsx

Added back in commented out line for FY search filters
[DEV-11637](https://federal-spending-transparency.atlassian.net/browse/DEV-11637)
**Mockup:**
n/a
Author:
Reviewer(s):

11637 - added back in FY search

---

src/js/components/search/SearchPage.jsx
src/js/components/search/collapsibleSidebar/SearchPagev2.jsx

Adv Search page not loading in mobile 
[DEV-11752](https://federal-spending-transparency.atlassian.net/browse/DEV-11752)
Author:
Reviewer(s):

11752:  Adv Search page not loading in mobile 

---

src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/dataMapping/search/searchFilterCategories.jsx

Reverts fedspendingtransparency/usaspending-website#4391

Revert "DEV-11723 agency and tas filter on searchv2 page"

---

src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/dataMapping/search/searchFilterCategories.jsx

tas and agency filters on search v2
[DEV-11723](https://federal-spending-transparency.atlassian.net/browse/DEV-11723)
Author:
Reviewer(s):

DEV-11723 redoing 11723

---

src/js/components/search/collapsibleSidebar/CollapsibleSidebar.jsx
src/js/containers/search/SearchSidebarSubmitContainer.jsx

Fixed side filter panel 2.0 submit button to work like 1.0 version
There was so weirdness with the components reloading.  Fixed the importing the submitsidebarcontainer component.  Also,  converted that component to functional
[DEV-11718 ](https://federal-spending-transparency.atlassian.net/browse/DEV-11718 )
**Mockup:**
n/a
Author:
Reviewer(s):

11718 - Fixed side filter panel 2.0 submit button to work like 1.0 version

---

package-lock.json
src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1733331655364469
change back to =

fix fy chips

---

package-lock.json

fix staging package lock for broken build

fix staging build

---

package-lock.json
src/js/components/search/filters/timePeriod/DateRange.jsx

https://staging.usaspending.gov/federal_account/075-0512 
use above as an example, if you go to custom dates, the page crashes
this PR fixes that bug
Author:
Reviewer(s):

fix bug on fed acct page

---

tests/redux/reducers/search/searchFiltersReducer-test.js

removing consoles in test

---

package-lock.json
src/_scss/pages/analystGuide/analystGuide.scss

update federal spending guide for mobile margins, was already using grid
[DEV-10902](https://federal-spending-transparency.atlassian.net/browse/DEV-10902)
Author:
Reviewer(s):

DEV-10902 federal spending guide, seems like it just needed to be updated for mobile

---

package-lock.json
src/_scss/pages/interactiveDataSources/_dataSourcesTitles.scss
src/_scss/pages/interactiveDataSources/index.scss
src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx

adjust max width, margins for data sources page, replace with flex grid components
[DEV-10903](https://federal-spending-transparency.atlassian.net/browse/DEV-10903)
Author:
Reviewer(s):

DEV-10903 grid for data sources page

---

package-lock.json
src/_scss/pages/bulkDownload/bulkDownloadPage.scss
src/_scss/pages/bulkDownload/downloadData.scss
src/_scss/pages/bulkDownload/form/downloadForm.scss
src/js/components/bulkDownload/BulkDownloadPage.jsx

download center grid
[DEV-10900](https://federal-spending-transparency.atlassian.net/browse/DEV-10900)
Author:
Reviewer(s):

DEV-10900 bulk download grid

---

src/js/models/v1/search/SearchAwardsOperation.js

fix crash in master

---

package-lock.json
src/_scss/pages/search/_collapsibleSidebar.scss
src/_scss/pages/search/filters/timePeriod/timePeriod.scss
src/js/components/search/collapsibleSidebar/CategoryFilter.jsx
src/js/components/search/collapsibleSidebar/CateogriesList.jsx
src/js/components/search/collapsibleSidebar/CollapsibleSidebar.jsx
src/js/components/search/collapsibleSidebar/SearchSidebarDrilldown.jsx
src/js/components/search/collapsibleSidebar/SearchSidebarMainMenu.jsx
src/js/components/search/filters/location/LocationSection.jsx
src/js/components/search/filters/timePeriod/TimePeriod.jsx

Fix sidepanel back button from level 3 to level 2
Fix the filter level margins to 32px left and right
[DEV-11720](https://federal-spending-transparency.atlassian.net/browse/DEV-11720)
[DEV-11725](https://federal-spending-transparency.atlassian.net/browse/DEV-11725)
**Mockup:**
Margins:
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/6639417eb322e8126ef4528b
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/660372c8cca0278f64d8ef42
Author:
- [n/a] Added Unit …

11720/11725 - Fix sidepanel back button and filter level margins

---

src/js/components/search/newResultsView/categories/SpendingByCategoriesChart.jsx

had to make domain 15% larger in order to fit the label
use http://localhost:3000/search/?hash=39fc101c1f0eecdf23d8e822336f17c5 to test and adjust the screen size smaller so you can verify it does not overlap at any point before the graph stacks for mobile
[DEV-11600](https://federal-spending-transparency.atlassian.net/browse/DEV-11600)
Author:
Reviewer(s):

DEV-11600 5% was not large enough

---

package-lock.json
package.json
src/_scss/pages/search/results/table/resultsTable.scss
src/js/components/search/table/ResultsTable.jsx
src/js/containers/award/table/AwardHistoryTableContainer.jsx

remove right fade code, fixes read more so that when you open the read more and scroll either direction that it does not close the read more that you had open
depends on merging https://github.com/fedspendingtransparency/data-transparency-ui/pull/220/files first
[DEV-11712](https://federal-spending-transparency.atlassian.net/browse/DEV-11712)
Author:
Reviewer(s):

DEV-11712 remove right fade, fix read more

---

src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

fix bug found here https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1734982008095339

Fix extent competed bug

---

src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
src/js/containers/search/filters/AgencyContainer.jsx
src/js/containers/search/filters/AgencyListContainer.jsx

Autocomplete onselect was firing multiple times, fix that
[DEV-11854 ](https://federal-spending-transparency.atlassian.net/browse/DEV-11854 )
Author:
Reviewer(s):

Hotfix: 11854 - Agency autocomplete timing issue; couldn't select multiple agencies from the autocomplete

---

package-lock.json
src/js/components/search/filters/timePeriod/DateRange.jsx
src/js/redux/reducers/search/filters/timePeriodFilterFunctions.js

fix issue with clicking x area on time period chips
[DEV-11595](https://federal-spending-transparency.atlassian.net/browse/DEV-11595)
Author:
Reviewer(s):

fix x problem and keyup bug

---

src/js/components/search/visualizations/geo/MapWrapper.jsx
src/js/components/search/visualizations/geo/map/MapBox.jsx
src/js/components/sharedComponents/checkbox/AccordionCheckboxSecondary.jsx

Added additional error checking and fixed issue causing the map to crash
[DEV-11871](https://federal-spending-transparency.atlassian.net/browse/DEV-11871)
Author:
Reviewer(s):

11871 - Added additional error checking and fixed issue causing the map to crash

---

src/js/components/sharedComponents/checkbox/SingleCheckboxType.jsx

there was an assignment bug that caused the award amount filter to be misleading
[DEV-11874](https://federal-spending-transparency.atlassian.net/browse/DEV-11874)
Author:
Reviewer(s):

DEV-11874 award amount bug

---

src/js/components/search/filters/awardType/ContractAwardType.jsx
src/js/components/search/filters/awardType/FinancialAssistanceAwardType.jsx
src/js/containers/search/filters/AwardTypeContainerV2.jsx
src/js/dataMapping/search/searchFilterCategories.jsx

separate contract and financial assistance award types, didn't delete any of the old code files but once we deploy search 2.0 we can and should delete the older files
[DEV-11867](https://federal-spending-transparency.atlassian.net/browse/DEV-11867)
Author:
Reviewer(s):

DEV-11867 separate award types

---

src/_scss/pages/search/mobile/mobileFilterButton.scss

sticky mobile button, minimal changes required
[DEV-11934](https://federal-spending-transparency.atlassian.net/browse/DEV-11934)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/677d5bf0ab13afbbbaa8b833
Author:
Reviewer(s):

DEV-11934 sticky mobile button

---

package-lock.json
src/js/dataMapping/trainingVideos/playListMetadata.js

changed title name
changed value in title property 
[[DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-1234)
](https://federal-spending-transparency.atlassian.net/jira/software/c/projects/DEV/boards/25?quickFilter=279&selectedIssue=DEV-11493)
**Mockup:**
n/a
Author:
Reviewer(s):

11493 - added testiominal video

---

src/_scss/elements/filters/_selectedFilterBtn.scss
src/js/components/search/filters/otherFilters/ShownValue.jsx

refactored shownValue component and changed onClick behavior to icon and not whole chip. 
refactored shownValue component from class to functional. moved the onClick to the icon and not the whole button.  Changed button to button from dtui repo and created class so the styling of button would be consistent as before
https://federal-spending-transparency.atlassian.net/browse/DEV-11869
**Mockup:**
n/a
Author:
- [] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
Reviewer(s):

refactored shownValue and changed onClick function

---

src/_scss/pages/search/filters/otherFilters/_extentCompeted.scss

fixed x icon in search bar
[DEV-11955](https://federal-spending-transparency.atlassian.net/browse/DEV-11955)
**Mockup:**
n/a
Author:
Reviewer(s):

11955 - fixed x icon in search bar

---

src/_scss/components/_checkboxTree.scss
src/_scss/pages/search/_collapsibleSidebar.scss
src/_scss/pages/search/_newNaicsStyles.scss
src/_scss/pages/search/_newPscStyles.scss
src/_scss/pages/search/_newTasStyles.scss
src/_scss/pages/search/_searchFilter.scss
src/_scss/pages/search/filters/naics/naics.scss
src/js/components/search/collapsibleSidebar/CategoryHeader.jsx
src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx

changes to checkbox tree for naics/tas/psc - keep in mind we are going to replace the component, the bulk of this ticket was primarily to fix the margins for those three filters to make them 32px wide
i didn't want to overlap the existing checkbox tree code fully so i tried to separate out most of the changes for the three filters in a legible fasion
also the mocks don't account for there being an icon now and we'll need to go back and fix the margin when there are selected elements
[DEV-11954](https://federal-spending-transparency.atlassian.net/browse/DEV-11954)
**Mockup:**
https://zpl.io/XKY0MZg
https://zpl.io/WQ4ZYvK
https://zpl.io/ezwZYBY
Author:
Reviewer(s):

DEV-11954 changes to checkbox tree for naics/tas/psc

---

src/_scss/pages/search/_collapsibleSidebar.scss
src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx
src/js/helpers/search/collapsiblesidebarHelper.js

Added the intersection observer to check for the presence of the top sticky bar and footer elements and update the ui accordingly
[DEV-11933 ](https://federal-spending-transparency.atlassian.net/browse/DEV-11933 )
[DEV-11724 ](https://federal-spending-transparency.atlassian.net/browse/DEV-11724 )
Author:
Reviewer(s):

11933 &11724 - Sidebar open and close animation and adjust sidebar for top hat banner open and close

---

src/js/components/sharedComponents/checkbox/AccordionCheckbox.jsx
src/js/components/sharedComponents/checkbox/ListCheckbox.jsx
src/js/containers/search/filters/recipient/RecipientSearchContainer.jsx

add null checks to fix console errors
[DEV-11960](https://federal-spending-transparency.atlassian.net/browse/DEV-11960)
Author:
Reviewer(s):

fix console errors

---

src/js/models/v1/search/SearchAwardsOperation.js
src/js/redux/reducers/search/searchFiltersReducer.js

null protections and removing a state that didn't need to be there, it was causing a download problem
http://localhost:3000/search/?hash=9e6a7b35c84d2a90db8a0289e1dd2e20 for testing
[DEV-12087](https://federal-spending-transparency.atlassian.net/browse/DEV-12087)
Author:
Reviewer(s):

DEV-12087 removed data type that was screwing up fromState

---

package-lock.json
src/js/components/search/visualizations/geo/map/MapBox.jsx

staging to qat downmerge, fixed package lock conflict with qat

Staging qat conflict

---

package-lock.json
src/content/search/characteristics-panel.mdx
src/content/search/location-filter-panel.mdx
src/content/search/sources-panel.mdx

Made changes to the text
[DEV-12199](https://federal-spending-transparency.atlassian.net/browse/DEV-12199)
**Mockup:**
Author:
Reviewer(s):

12199-edit-dsm-copy

---

src/js/components/agencySubmissionStats/DataSourcesAndMethodologiesPage.jsx

Copy update
[DEV-12265](https://federal-spending-transparency.atlassian.net/browse/DEV-12265)
**Mockup:**
n/a
Author:
Reviewer(s):

12265 - copy update

---

src/js/containers/search/filters/recipient/RecipientSearchContainer.jsx

fix https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1742415091936559 while still preserving highlighting

Fix recipient issue

---

package-lock.json
package.json

Update dtui version to 6.4.0 which includes the updates for focus
[DEV-9589](https://federal-spending-transparency.atlassian.net/browse/DEV-9589)
Author:

update dtui version

---

src/js/components/search/filters/location/LocationSection.jsx
src/js/containers/search/filters/location/LocationAutocompleteContainer.jsx
src/js/models/v2/search/LocationEntity.js

update to location response
[DEV-12291](https://federal-spending-transparency.atlassian.net/browse/DEV-12291)
Author:

DEV-12291 update to location filter format

---

package-lock.json
package.json

dtui fix for table border
[DEV-12339](https://federal-spending-transparency.atlassian.net/browse/DEV-12339)
Author:

DEV-12339 update dtui

---

src/js/helpers/checkboxTreeHelper.js
src/js/helpers/naicsHelper.js
src/js/helpers/pscHelper.js
src/js/helpers/searchHelper.js
src/js/helpers/tasHelper.js
src/js/redux/reducers/search/naicsReducer.js
src/js/redux/reducers/search/pscReducer.js
src/js/redux/reducers/search/tasReducer.js
tests/helpers/checkboxTreeHelper-test.js

undid change to fix tas/naics/psc filters

Fix tas filter

---

src/js/containers/search/SearchContainer.jsx
src/js/containers/search/SearchContainerv2.jsx
tests/containers/search/SearchContainer-test.jsx

Fixing issue found with the original fix for DEV-12347.  Please test submitting a filter and verify the correct page is displayed afterwards. 
[DEV-12347 ](https://federal-spending-transparency.atlassian.net/browse/DEV-12347 )
**Mockup:**
n/a
Author:

DEV-12347 - Fixed redirect when submitting filter

---

src/js/ActiveBanners.jsx
src/js/GlobalConstants.js
src/js/components/sharedComponents/header/Header.jsx

Add advanced search banner.  I had to move the banner array with banner content out of GlobalConstants to ActiveBanners.jsx because the design required an external link.
[DEV-12418](https://federal-spending-transparency.atlassian.net/browse/DEV-12418)
**Mockup:**
https://figma-gov.com/design/65wzQ5SvVnMKGs0YgEzVAQ/USAS---Search-2.0?node-id=10648-14&t=3UOC1dHK06fgyCAr-4
Author:

Dev12418 - Add advanced search banner

---

package-lock.json
src/js/components/state/StatePage.jsx

make change per design and hakan, not originally part of the ticket
[DEV-11540](https://federal-spending-transparency.atlassian.net/browse/DEV-11540)
Author:

DEV-11540 change to tab label on state page

---

src/js/components/search/filters/location/LocationSection.jsx

it was not obvious that I also had to remove this
Author:

remove old location filter section

---

src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx

Fixed bug introduced with the original fix
[DEV-12433 ](https://federal-spending-transparency.atlassian.net/browse/DEV-12433 )
**Mockup:**
n/a
Author:

12433 - Fixed crash when closing the Adv Search 2.0 page mobile sidepanel

---

src/js/components/search/newResultsView/table/TableDsm.jsx
src/js/components/search/newResultsView/table/TableSection.jsx

added missing copy
[DEV-12318](https://federal-spending-transparency.atlassian.net/browse/DEV-12318)
**Mockup:**
n/a
Author:

12318 - added transactions copy

---

src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/models/v1/search/SearchAwardsOperation.js

Fix covid and infrastructure advanced search 2.0 filters 
[DEV-12521](https://federal-spending-transparency.atlassian.net/browse/DEV-12521)
**Mockup:**
n/a
Author:

12521: Fix covid and infrastructure advanced search 2.0 filters 

---

src/content/search/time-filter-panel.mdx
src/js/components/search/newResultsView/time/TimeDsm.jsx

see https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1745275408671179
[DEV-12526](https://federal-spending-transparency.atlassian.net/browse/DEV-12526)
Author:

DEV-12526 additional changes

---

src/_scss/components/_titleBarFilter.scss
src/_scss/core/_variables.scss
src/js/components/search/SubawardDropdown.jsx
src/js/components/search/collapsibleSidebar/SearchPagev2.jsx
src/js/components/sharedComponents/dropdowns/NewPicker.jsx

info for pagewide filter
[DEV-12543](https://federal-spending-transparency.atlassian.net/browse/DEV-12543)
**Mockup:**
https://figma-gov.com/design/65wzQ5SvVnMKGs0YgEzVAQ/USAS---Search-2.0?node-id=11034-28275&m=dev
Author:

DEV-12543 pagewide filter info

---

package.json
src/js/helpers/searchHelper.js

Fixing issue with search by county in the search-legacy location filter.
[DEV-12547](https://federal-spending-transparency.atlassian.net/browse/DEV-12547)
**Mockup:**
n/a
Author:

Fixing issue with search by county in the search-legacy location filter

---

package-lock.json
src/js/ActiveBanners.jsx
src/js/GlobalConstants.js
src/js/components/search/SubawardDropdown.jsx
src/js/components/search/filters/location/LocationSection.jsx
src/js/components/search/newResultsView/categories/CategoriesDsm.jsx
src/js/components/search/newResultsView/map/MapDsm.jsx
src/js/components/search/newResultsView/table/TableDsm.jsx
src/js/components/search/newResultsView/time/TimeDsm.jsx
src/js/containers/router/RouterRoutes.jsx
src/js/containers/search/SearchContainer.jsx
src/js/containers/search/SearchContainerv2.jsx
tests/containers/search/SearchContainer-test.jsx

High level description of the PR.  Please include technical details for the knowledge of other developers.
[DEV-12550](https://federal-spending-transparency.atlassian.net/browse/DEV-12550)
**Mockup:**
n/a
Author:

12550 -  Revert search v2

---

src/js/components/search/SearchPage.jsx
src/js/components/search/SubawardDropdown.jsx

fixed issue found by testing - https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1745613394220849?thread_ts=1745612182.953669&cid=CE5P5AWE8
[DEV-12550](https://federal-spending-transparency.atlassian.net/browse/DEV-12550)
**Mockup:**
n/a
Author:

12550: fixed "filter by" options in legacy search page

---

src/index.ejs

new version of survey
it's the survey in the bottom right hand corner on the homepage, you can verify it works by clicking it and seeing a test banner on the page it takes you to
[DEV-12469](https://federal-spending-transparency.atlassian.net/browse/DEV-12469)
Author:

DEV-12469 new verint (foresee) survey

---

package-lock.json

update usas storybook version - also fixes vulnerabilities
[DEV-12454](https://federal-spending-transparency.atlassian.net/browse/DEV-12454)
Author:

Update usas sb

---

package.json

change audit level back to high

fix audit level

---

src/js/components/agencySubmissionStats/AboutTheDataPage.jsx
src/js/components/search/newResultsView/table/TableDsm.jsx
src/js/components/sharedComponents/GlossaryLink.jsx

Fixed issue found by testing - https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1746817936005339
[DEV-11589 ](https://federal-spending-transparency.atlassian.net/browse/DEV-11589 )
**Mockup:**
n/a
Author:

11589 - Fixed issue found by testing ( glossary links issue) and exhaustive deps issue

---

src/js/ActiveBanners.jsx
src/js/GlobalConstants.js
src/js/components/homepageUpdate/AwardSearch/AwardSearch.jsx
src/js/components/homepageUpdate/ReadyToGetStarted/ReadyToGetStarted.jsx
src/js/components/homepageUpdate/heroUpdate/HeroUpdate.jsx
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
src/js/components/sharedComponents/header/mobile/MobileNav.jsx

navigate to the correct search on mobile
https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1746737729561469?thread_ts=1746730519.109299&cid=CE5P5AWE8
qat and staging go to v2
prod goes to legacy search
[DEV-12604](https://federal-spending-transparency.atlassian.net/browse/DEV-12604)
Author:

DEV-12604 fix mobile navigate to search

---

src/js/components/search/newResultsView/SearchSectionWrapper.jsx

Add GA Event to DSM open close for V2 results view.
[DEV-12570](https://federal-spending-transparency.atlassian.net/browse/DEV-12570)
Author:

DEV-12570 - Advanced Search: Add GA tracking to Advanced Search Results View DS&Ms

---

src/content/about-the-data/daims.mdx
src/content/about-the-data/frequency-of-updates-to-agency-account-data.mdx
src/content/about-the-data/gsdm.mdx
src/content/about-the-data/limited-data-for-unlinked-prime-awards.mdx
src/js/components/agencySubmissionStats/componentMapping/tooltipContentMapping.jsx
src/js/components/analystGuide/AnalystGuideQuestions.jsx
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
src/js/dataMapping/aboutTheDataSchema.js

Text updates.  Testing doc added to JIRA ticket
[DEV-12536](https://federal-spending-transparency.atlassian.net/browse/DEV-12536)
Author:

DEV/12536 - About the Data - DATA Act Information Model Schema"/"DAIMS" text update

---

src/js/GlobalConstants.js
src/js/containers/account/AccountContainer.jsx
src/js/containers/search/newResultsView/CategoriesVisualizationWrapperContainer.jsx
src/js/containers/search/newResultsView/MapSectionWrapper.jsx
src/js/containers/search/newResultsView/TimeVisualizationSectionContainer.jsx
src/js/dataMapping/search/awardTableColumns.jsx

Had to create a separate branch to merge staging to qat

Downmerge staging to qat

---

src/js/containers/search/SearchContainerv2.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1748356100583149?thread_ts=1748010214.613709&cid=CE5P5AWE8
n/a
**Mockup:**
n/a
Author:

fixed v2 submit redirect

---

src/js/containers/search/SearchContainerv2.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1748356100583149?thread_ts=1748010214.613709&cid=CE5P5AWE8
n/a
**Mockup:**
n/a
Author:

Fixing v2 submit redirect again

---

src/_scss/pages/bulkDownload/_datePicker.scss
src/_scss/pages/search/_pagePositioning.scss
src/_scss/pages/search/filters/timePeriod/timePeriodNew.scss
src/js/components/search/SearchPage.jsx

basically the search sidebar wasn't wide enough for several of the filters, had to adjust width between 992 and ~1368px
Author:

fix for search sidebar on search legacy page

---

src/js/LocalConstants.js
src/js/components/search/visualizations/geo/MapWrapper.jsx

[High level description of the PR.  Please include technical details for the knowledge of other developers.
](https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1749163230268469)
n/a
Author:

Fix map tooltips

---

src/js/containers/account/awards/AccountAwardsContainer.jsx

Fixed api call cancelling on Federal Account Profile Page, results table. Please see the "Grants to States for Medicaid, Centers for Medicare and Medicaid Services, Health and Human Services" profile page below for testing:
[Local Environment](http://localhost:3000/federal_account/075-0512)
[QAT](https://qat.usaspending.gov/federal_account/075-0512)
[DEV-12701](https://federal-spending-transparency.atlassian.net/browse/DEV-12701)
**Mockup:**
n/a
Author:
[DEV-12701]: https://federal-spending-transparency.atlassian.net/browse/DEV-12701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12701 - proper cancelling of duplicate api calls

---

package-lock.json
package.json

merge to qat for dtui upgrade for JD's ticket
[DEV-12718](https://federal-spending-transparency.atlassian.net/browse/DEV-12718)
Author:
[DEV-12718]: https://federal-spending-transparency.atlassian.net/browse/DEV-12718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12718 update dtui

---

src/js/components/bulkDownload/awards/filters/dateRange/DownloadDateRange.jsx
src/js/components/search/filters/timePeriod/DateRange.jsx
src/js/components/sharedComponents/DatePicker.jsx

Fixed bulk downloads custom awards
[DEV-12818](https://federal-spending-transparency.atlassian.net/browse/DEV-12818)
**Mockup:**
n/a
Author:
[DEV-12818]: https://federal-spending-transparency.atlassian.net/browse/DEV-12818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12818 - fixed start date for custom award data bulk download

---

package-lock.json
package.json

update package for vulnerability

---

src/content/about-the-data/subaward-data-quality.mdx

Update to the subaward data quality copy
[DEV-12747](https://federal-spending-transparency.atlassian.net/browse/DEV-12747)
**Mockup:**
n/a
Author:
[DEV-12747]: https://federal-spending-transparency.atlassian.net/browse/DEV-12747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12747 - subaward data quality copy update

---

src/js/components/recipient/InfoTooltipContent.jsx

Fixed missing punctuation and removed random editing objects that were not supposed to be in document.
[DEV-12040](https://federal-spending-transparency.atlassian.net/browse/DEV-12040)
Author:
[DEV-12040]: https://federal-spending-transparency.atlassian.net/browse/DEV-12040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV - 12040 - Fix minor text/formatting issues

---

src/js/components/search/mobile/MobileSortDirectionToggle.jsx

misunderstood the sort order mock, swapped them per testing
[DEV-12444](https://federal-spending-transparency.atlassian.net/browse/DEV-12444)
Author:
[DEV-12444]: https://federal-spending-transparency.atlassian.net/browse/DEV-12444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12444 Fix mobile sort order per testing

---

.github/workflows/broken-link-check.yaml
.github/workflows/pull-request-checks.yaml
README.md

testing broken link checker
[DEV-11167](https://federal-spending-transparency.atlassian.net/browse/DEV-11167)
Author:
[DEV-11167]: https://federal-spending-transparency.atlassian.net/browse/DEV-11167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-11167 testing broken link checker

---

src/js/containers/search/helpers/searchAnalytics.js
tests/containers/search/helpers/searchAnalytics-test.js

Custom dates came to analytics helper as a set.  Added type to differentiate and then used convertReducibleValue helper to build analytic event.
[DEV-12926](https://federal-spending-transparency.atlassian.net/browse/DEV-12926)
Author:
[DEV-12926]: https://federal-spending-transparency.atlassian.net/browse/DEV-12926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV - 12926: Time Period filter tracking for Custom date

---

package-lock.json
package.json
scripts/sitemaps/package-lock.json

scripts update to fix vulnerability

---

src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx

See thread in Slack
[High level description of the PR.  Please include technical details for the knowledge of other developers.
](https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1753473202634789?thread_ts=1753472401.465469&cid=CE5P5AWE8)
n/a
**Mockup:**
n/a
Author:

Nested tree fix based on QA finding

---

src/js/components/glossary/Glossary.jsx

Fix glossary problem

---

src/js/containers/agencySubmissionStats/AgenciesContainer.jsx

mistakenly changed setTableData params
https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1754423811332639
[DEV-12734](https://federal-spending-transparency.atlassian.net/browse/DEV-12734)
Author:
[DEV-12734]: https://federal-spending-transparency.atlassian.net/browse/DEV-12734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12734 mistakenly changed

---

src/js/dataMapping/award/additionalDetailsFinancialAssistance.js

Updated the 'Awarding Sub-Agency Code' label to be 'Awarding Agency Code' for financial assistance awards.
[DEV-12932](https://federal-spending-transparency.atlassian.net/browse/DEV-12932)
**Mockup:**
n/a
Author:
[DEV-12932]: https://federal-spending-transparency.atlassian.net/browse/DEV-12932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12932 - awarding agency code label updated for assistance awards

---

src/js/components/search/table/ResultsTable.jsx

class to functional for ResultsTable.jsx
testing: click on different tabs, sort options, choose different spending levels, etc
[DEV-13018](https://federal-spending-transparency.atlassian.net/browse/DEV-13018)
Author:
[DEV-13018]: https://federal-spending-transparency.atlassian.net/browse/DEV-13018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-13018 class to functional

---

package-lock.json
src/index.ejs

verint code update
[DEV-13125](https://federal-spending-transparency.atlassian.net/browse/DEV-13125)
**Mockup:**
n/a
Author:
[DEV-13125]: https://federal-spending-transparency.atlassian.net/browse/DEV-13125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

13125 - verint code update

---

src/js/components/homepageUpdate/SummaryStats.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1755102454923159
[DEV-12937](https://federal-spending-transparency.atlassian.net/browse/DEV-12937)
Author:
[DEV-12937]: https://federal-spending-transparency.atlassian.net/browse/DEV-12937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12937 - fixed link to advanced search

---

src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx
src/js/helpers/search/collapsiblesidebarHelper.js

Increased search sidebar width by 20px for both desktop and desktop XL
[DEV-13110](https://federal-spending-transparency.atlassian.net/browse/DEV-13110)
**Mockup:**
[Figma](https://figma-gov.com/design/s8rgQ5B6Rd3snAgGATNvXl/Design-Tickets?node-id=133-609&m=dev)
Author:
[DEV-13110]: https://federal-spending-transparency.atlassian.net/browse/DEV-13110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

13110 - increased search sidebar width

---

package-lock.json
package.json
src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1756399717799839
n/a
**Mockup:**
n/a
Author:

adv search filter crash

---

src/_scss/components/checkboxTree/_checkboxTree.scss

add missing highlight className for searched psc children.
Author:

add highlight style

---

src/js/ActiveBanners.jsx

High level description of the PR.  Please include technical details for the knowledge of other developers.
[DEV-12276](https://federal-spending-transparency.atlassian.net/browse/DEV-12276)
Author:
[DEV-12276]: https://federal-spending-transparency.atlassian.net/browse/DEV-12276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12276 - Adding govt shutdown banner

---

src/js/ActiveBanners.jsx

[DEV-12276](https://federal-spending-transparency.atlassian.net/browse/DEV-12276)
Author:
[DEV-12276]: https://federal-spending-transparency.atlassian.net/browse/DEV-12276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12276 - updated the color

---

src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx

Add null checks for the elements and style properties.  Fixing the null errors allows the the correct styling.
[DEV-13331](https://federal-spending-transparency.atlassian.net/browse/DEV-13331)
Author:
[DEV-13331]: https://federal-spending-transparency.atlassian.net/browse/DEV-13331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV - 13331:Adv Search 2.0: Collapsible Sidebar line covers Footer when closed on Desktop

---

src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx

Adjust collapsible sidebar height so "Learn more about Filter Categories" component is closer and more aligned with "Submit" filters component.
[DEV-13524](https://federal-spending-transparency.atlassian.net/browse/DEV-13524)
Author:
[DEV-13524]: https://federal-spending-transparency.atlassian.net/browse/DEV-13524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV - 13524: Advanced Search 2.0: Fix sidebar height so the Learn more about Filter Categories is bottom aligned
