fedspendingtransparency/usaspending-website

src/js/components/search/table/ResultsTable.jsx
src/js/components/sharedComponents/IBTable/components/TableBody.jsx

* Results table data hash is now a concatenated string of the results batch ID and the award type name
* This addresses a bug where the table would fail to update if the table's award type tabs did not change, but a sidebar filter was applied that that returned no results, then the sidebar filter was changed to something that returned multiple results.
* This also addresses a bug where the table would fail to update if the table's award type tabs did not change and a set of sidebar filters were applied that returned a non-zero number of results, then the sidebar filters were changed again to return different data but the same amount of results.

Bug fix: Improved Results Table Data Hash

---

src/_scss/pages/search/topFilterBar/_clearAllButton.scss
src/_scss/pages/search/topFilterBar/_tag.scss
src/js/components/search/topFilterBar/TopFilterBar.jsx
src/js/components/search/topFilterBar/TopFilterItem.jsx
src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

* Fixes a bug where scrolling JS would break because the close icon was previously replaced in the SVG file with a different name.
* Adds functionality to automatically display/populate the top filter bar when filters are pre-selected, either by pressing the back button to the search page or via future URL parameter functionality.

Hotfix: Top Filter Bar

---

src/js/components/search/filters/location/SelectedLocations.jsx
src/js/redux/reducers/search/filters/locationFilterFunctions.js
src/js/redux/reducers/search/searchFiltersReducer.js

* Refactored Redux store for location filter to be an OrderedMap instead of a Set
* This allows us to stop comparing full location objects for each filter add/remove, which may or may not always equal
* This also guarantees return order of location tags is the order in which they were added
* This also allows the Redux actions to pass their future tests
👇

Location Filter Redux Refactor

---

src/_scss/pages/search/results/table/_tableStyle.scss
src/js/components/search/table/ResultsTable.jsx
src/js/components/search/table/cells/ResultsTableGenericCell.jsx
src/js/components/search/table/cells/ResultsTableHeaderCell.jsx
src/js/dataMapping/search/tableSearchFields.js
src/js/models/results/award/AwardSummary.js

* Adds awarding sub-agency, funding agency, and funding sub-agency columns to the search results table
* Updates the results table styling to be able to dynamically apply correct final column styling to any arbitrary final column
* Awards JS model updated to reflect new fields
* Results table/awards JS model now populates Award Type value using the `type_description` server value instead of mapping it client-side. This also ensures correct alphabetical sorting of the Type column in the results table

Add Sub-Agency and Funding Agency/Sub-Agency to Results Table

---

src/js/models/search/queryBuilders/AwardTypeQuery.js

* No longer adds separate filters for `procurement_set` sub-values, all award types are now filtered by the `type` value in the main award object.
* Update required by current API after fedspendingtransparency/usaspending-api#114

Fix: Award type API field change

---

gulpfile.babel.js
package.json
src/js/components/search/visualizations/time/TimeVisualizationTooltip.jsx
src/js/components/search/visualizations/time/chart/BarChart.jsx
src/js/components/search/visualizations/time/chart/BarItem.jsx
src/js/components/search/visualizations/time/chart/BarYAxis.jsx
src/js/helpers/moneyFormatter.js

* Y axis now displays labels when only one data point is shown and it is negative or zero
* No longer errors out when data points are exactly $0
* Now displays N/A as the percent of total spending for $0 data points instead of NaN
* Centralized all money formatting to the MoneyFormatter helper

Spending Over Time Fixes

---

src/js/components/search/topFilterBar/filterGroups/LocationFilterGroup.jsx
src/js/containers/search/filters/location/LocationListContainer.jsx
src/js/containers/search/filters/recipient/RecipientLocationContainer.jsx
src/js/helpers/locationFormatter.js

Removed parent label from all location Autocompletes and Selections when the `place_type` is a country

Fix - Hide Country Acronym in PoP/Recipient Locations when Place itself is a Country

---

src/js/containers/search/filters/AgencyListContainer.jsx
src/js/containers/search/filters/location/LocationListContainer.jsx
src/js/containers/search/filters/recipient/RecipientLocationContainer.jsx

Fixes an issue on showing the Autocomplete error on the Agency filter when it shouldn't be there / when it should be there. We're checking for previously-selected agencies in this class' `parseAutocomplete` function and not `queryAutocomplete` function, like in the others, so we need to check if all the agencies that match the search term have been selected in the `parseAutocomplete` function in addition to `queryAutocomplete`.

Hotfix - Autocomplete error incorrectly showing / not showing in Agency Filter

---

src/js/components/homepage/Homepage.jsx

Fixing issue of undefined `children` array within `categories` prop of `TreeMap`

Hotfix - Undefined Homepage Prop

---

src/js/components/search/visualizations/geo/map/MapBox.jsx

* Fixes a bug where unmounting a map component before its Mapbox API calls were complete would trigger a JS error

Fix: Safely handle setState in Mapbox callbacks

---

src/_scss/pages/account/filters/filters.scss
src/_scss/pages/account/filters/objectClass/objectClass.scss
src/_scss/pages/account/filters/programActivity/programActivity.scss
src/_scss/pages/account/results/searchResults.scss
src/_scss/pages/search/filters/awardType/_sharedAwardStyle.scss
src/js/components/account/SearchSidebar.jsx
src/js/components/account/filters/programActivity/ProgramActivityFilter.jsx
src/js/components/account/filters/programActivity/ProgramActivityItem.jsx
src/js/components/account/topFilterBar/filterGroups/AccountTopFilterGroupGenerator.jsx
src/js/components/account/topFilterBar/filterGroups/ProgramActivityFilterGroup.jsx
src/js/containers/account/filters/AccountProgramActivityContainer.jsx
src/js/containers/account/topFilterBar/AccountTopFilterBarContainer.jsx
src/js/helpers/accountHelper.js
src/js/models/account/queries/AccountAwardSearchOperation.js
src/js/models/account/queries/AccountSearchBalanceOperation.js
src/js/models/account/queries/AccountSearchOperation.js
src/js/models/account/queries/queryBuilders/ObjectClassQuery.js
src/js/models/account/queries/queryBuilders/ProgramActivityQuery.js
src/js/redux/actions/account/accountFilterActions.js
src/js/redux/reducers/account/accountReducer.js
src/js/redux/reducers/account/filters/accountProgramActivityFunctions.js
tests/containers/account/defaultFilters.js
tests/containers/account/filters/AccountProgramActivityContainer-test.jsx
tests/containers/account/topFilterBar/AccountTopFilterBarContainer-test.jsx
tests/redux/reducers/account/accountReducer-test.js

- User is able to filter data by Program Activity on Federal Account page
- Program Activities are populated when filter is expanded
- Program Activity list shows up to 10 Program Activities by default
- Program Activity list gives the option to show all remaining Program Activities, as well as hide the subsequently expanded list

Program Activity filter on Federal Account page

---

src/_scss/pages/award/_recipientInfo.scss
src/js/components/award/RecipientInfo.jsx
src/js/models/results/award/AwardSummary.js

- Not displaying address/parent/duns InfoSnippets for a Multiple Recipients award, displaying explanatory text instead
- Adding SCSS class to handle display of single InfoSnippet
- Converting name and snippet builds to functions to keep them out of render
- Displaying `Multiple Recipients in [County], [State/Province]` in name field, but only showing `in [County], [State/Province]` if both are available

[DS-1147] Multiple Recipients

---

src/js/containers/search/filters/AgencyListContainer.jsx
src/js/models/search/SearchOperation.js

- User will see toptier agencies listed before subtier agencies in both Agency Filter autocompletes
- Flag in API request will prioritize agency objects in which subtier agency name matches toptier agency name to ensure that no toptier agencies are being left out of the `limit`ed response (currently 10)

Agency Filter Sorting

---

src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx
src/js/components/search/visualizations/rank/sections/SpendingByAgencySection.jsx
src/js/containers/search/visualizations/rank/SpendingByFundingAgencyVisualizationContainer.jsx
tests/containers/search/visualizations/rank/SpendingByFundingAgencyVisualizationContainer-test.jsx

"Spending by Funding Agency" rank visualization will always use `/accounts/awards/total/` endpoint

Spending by Funding Agency Endpoint Fix

---

src/js/components/award/RecipientInfo.jsx

Update to check for multiple recipients with case insensitivity.
IDs to verify:
78304 on dev ("Multiple Recipients")
946692 on staging ("MULTIPLE RECIPIENTS")

[DS-1147] multiple recipients (new branch)

---

src/js/containers/search/filters/AgencyListContainer.jsx

Within the Agency Filter:
- Removes the ability to filter on subtier **Funding** Agencies, only showing toptier Funding Agencies
- Leaves intact the ability to filter on subtier **Awarding** Agencies, showing both subtier and toptier Awarding Agencies

Remove Subtier Funding Agency Filtering

---

src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx
src/js/containers/search/visualizations/rank/SpendingByFundingAgencyVisualizationContainer.jsx

Re-enables option to view Spending By Funding Agency visualization using updated queries that group by the new `treasury_account__funding_toptier_agency__name` foreign key, linking TAS and Agency.

Spending By Funding Agency Visualization

---

src/js/components/award/financialAssistance/FinancialAssistanceDetails.jsx
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/dataMapping/search/filterFields.js
tests/containers/search/visualizations/rank/SpendingByCFDAVisualizationContainer-test.jsx

* Changes references to the API's `cfda_number` and `cfda_title` to `cfda__program_number` and `cfda__program_title`
* Adds in CFDA program description to the federal assistance page and allows the description to overflow as necessary

Update: CFDA key change

---

sampleGlobalConstants_dev.js
sampleGlobalConstants_prod.js
src/js/helpers/accountHelper.js
src/js/helpers/accountQuartersHelper.js
src/js/helpers/downloadHelper.js
src/js/helpers/guideHelper.js
src/js/helpers/searchHelper.js

* Moved API version number to the helper routes, so different routes can use different API versions while they are migrated to v2
* Update the sample configs with an empty mapbox token entry
* 🚨 YOU MUST update your config files to remove `v1/` from the API endpoint, it should still end with a slash though🚨

Update: API Route-Specific Versioning

---

src/_scss/pages/search/results/visualizations/rank/rankVisualization.scss
src/js/components/search/visualizations/rank/chart/ChartGroup.jsx

Fixes Safari SVG issue by adding a redirect when clicking/tapping the SVG text element, and not just the contents of that element. Will require adding `v1/` to `/federal_accounts/${id}/` and `tas/categories/total/` endpoints to test.

Hotfix - Federal Account links in Safari behave as expected

---

src/_scss/pages/search/results/visualizations/geo/map/map.scss
src/js/components/search/visualizations/geo/map/MapBox.jsx

- Map cannot be panned on viewports smaller than 768px, allowing user to scroll down the entire page
- In viewports smaller than 768px, buttons appear at the bottom right of the map that allow user to navigate up, down, left, and right 100px at a time

Fix Map Scrolling on Mobile

---

src/js/components/search/visualizations/geo/map/MapBox.jsx

- Homepage map should center and zoom out to be fully visible on mobile load/resize

Fix - Mobile Map Zoom/Center

---

src/_scss/elements/_titleSelector.scss

- Aligns dropdown elements under the dropdown selector
- Doesn't break other areas where this class is used

Fix - Budget Category dropdown alignment

---

src/_scss/pages/award/table/detailsTable.scss
src/js/components/award/details/DetailsSection.jsx

* Resolves React `key` errors on award page and associated memory leak.
* This was caused by `tabs` array being moved to a scope outside of the component instance, which caused the Additional tab to be appended to the retained array on each render pass rather than re-instantiated each time
* Fixed a styling issue where the responsive mobile tabs floated behind the data tables, which prevented them from being clickable

Fix: Award Page React Errors

---

src/js/components/agency/overview/AgencyOverview.jsx

* Agency overview would revert to clean `state` when the component was re-mounted; data parsing now occurs on both `componentWillReceiveProps` and `componentDidMount`

Fix: Agency overview not broken

---

src/js/components/agency/visualizations/recipient/ScopeList.jsx
src/js/components/award/AwardAmounts.jsx
src/js/components/search/filters/awardType/AwardType.jsx
src/js/components/search/topFilterBar/filterGroups/AwardTypeFilterGroup.jsx
src/js/containers/account/awards/AccountAwardsContainer.jsx
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/dataMapping/search/awardType.js
src/js/dataMapping/search/tableSearchFields.js
src/js/helpers/summaryPageHelper.js
src/js/redux/reducers/search/columnVisibilityReducerInitialState.js
tests/redux/reducers/search/columnVisibilityReducer-test.js

- User can see "Other" is a top-level option in the Award Type filter, with "Insurance" and "Other Financial Assistance" as children (https://projects.invisionapp.com/share/XHB29AYB3#/screens/205404741_USA_Spending_Search)
- User can see "Other" as an option in the tabs above the award table on the Search/Download and Federal Account pages, replacing "Insurance"
- User can see "Other" as a future option in the Agency Page Rank Visualization, replacing "Insurance"

Other Award Types

---

src/_scss/elements/filters/_selectedFilterBtn.scss
src/_scss/pages/search/topFilterBar/_tag.scss
src/js/components/search/topFilterBar/TopFilterItem.jsx

* Also standardizes behavior of the filter badges between top filter bar and sidebar (previously, top bar required clicking the X to remove while the entire badge removed the filter in the sidebar; both now will remove if the badge is clicked due to the small size of the X)

Fix filter removal icons on IE

---

src/js/components/search/SearchPage.jsx
src/js/components/search/SearchSidebar.jsx
src/js/components/sharedComponents/filterSidebar/FilterOption.jsx
src/js/containers/search/SearchContainer.jsx
src/js/helpers/sidebarHelper.js

- Sidebar filters are now collapsed by default on *both* desktop and mobile
- Removed Budget Categories sidebar filter, reclassifying Funding Agency and Fiscal Year as Award-type filters, leaving only Award-type filters in the Sidebar
- Reorders the Sidebar filters in the order of most-used:
- Keywords
- Time Period
- Award Types
- Agencies
- Recipients
- Place of Performance
- Award Amount
- Award ID
- [Other Awards Items]
- Other Award Items will be broken out into individual top-level sidebar containers in a following PR from @ejgullo

Sidebar Remix

---

src/js/components/award/table/FinancialSystemTable.jsx
src/js/components/award/table/cells/FinSysAccountCell.jsx
src/js/dataMapping/contracts/financialSystem.js
src/js/models/results/other/FinancialSystemItem.js

* Financial System Details table on individual award pages now has a federal account column
* Federal account column shows the name of the column and links to the federal account page

Add federal account column to award detail pages

---

src/_scss/pages/award/_recipientInfo.scss
src/js/components/award/RecipientInfo.jsx
src/js/helpers/businessTypesHelper.js

- Show a list of applicable business types on the Contract Summary page, instead of `Unknown Types`
- If there are more than two types, hide the overflow by default and give users the option to see more

Update Contract Summary Business Types

---

src/_scss/pages/agency/_section.scss
src/_scss/pages/agency/visualizations/_obligated.scss
src/_scss/pages/agency/visualizations/federalAccount/federalAccount.scss
src/_scss/pages/agency/visualizations/recipient/recipient.scss
src/js/components/agency/AgencyContent.jsx
src/js/components/agency/AgencyPage.jsx
src/js/components/agency/visualizations/federalAccount/FederalAccountChart.jsx
src/js/components/agency/visualizations/federalAccount/FederalAccountVisualization.jsx
src/js/components/agency/visualizations/objectClass/ObjectClassTreeMap.jsx
src/js/components/agency/visualizations/obligated/ObligatedGraph.jsx
src/js/components/agency/visualizations/obligated/ObligatedVisualization.jsx
src/js/components/agency/visualizations/recipient/RecipientChart.jsx
src/js/components/agency/visualizations/recipient/RecipientVisualization.jsx
src/js/containers/agency/AgencyContainer.jsx
src/js/containers/agency/visualizations/FederalAccountContainer.jsx
src/js/containers/agency/visualizations/ObjectClassContainer.jsx
src/js/containers/agency/visualizations/ObligatedContainer.jsx
src/js/containers/agency/visualizations/RecipientContainer.jsx

- "Data as of X" is added to all sections according to the mock (Date is the same for all visualizations except recipients, which shows the date awards were last uploaded)
- Labels added to each visualization so the users know they are looking at obligated amounts
- Asterisk is removed from obligations section and previous "data as of" note is removed

Agency Page design updates

---

src/_scss/pages/search/results/visualizations/rank/chart/_item.scss

- All links to summary/profile pages should be blue links rather than underlined

Update profile links

---

package.json

* Ever have just 1 linter error buried in the middle of 280 warnings?
* Now you can run `npm run errors` to only display linter errors without warnings

NPM command to display only linting errors

---

src/_scss/pages/search/results/visualizations/rank/chart/_item.scss

- Visited profile links in rank charts are blue instead of black

Visited links color fix

---

package.json
src/js/containers/agencyLanding/AgencyLandingContainer.jsx
tests/containers/agencyLanding/mockToptierAgencies.js

- Temporarily hard-codes the total budget authority amount to calculate accurate percentages on the agency landing page

Agency Landing Total Budget Authority

---

package.json
src/js/containers/search/table/ResultsTableContainer.jsx

- Fixes the API parameter generation when switching tabs in the Awards Table if the Award Type filter is populated when the new tab is selected

Fix - Award Type filter in Awards Table

---

src/_scss/pages/agency/visualizations/federalAccount/federalAccount.scss
src/js/components/agency/visualizations/federalAccount/FederalAccountChart.jsx
src/js/components/agency/visualizations/federalAccount/FederalAccountVisualization.jsx
src/js/containers/agency/visualizations/FederalAccountContainer.jsx
src/js/containers/agency/visualizations/RecipientContainer.jsx
tests/containers/agency/agencyHelper.js
tests/containers/agency/visualizations/FederalAccountContainer-test.jsx

- Adds pagination to the Federal Accounts visualization on the Agency Profile Page so that users can see more than just the top 10 accounts
- Updated tests

Hotfix agency accounts pagination

---

src/_scss/pages/explorer/detail/_noAwardsScreen.scss
src/_scss/pages/explorer/detail/explorerDetail.scss
src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/NoAwardsScreen.jsx
src/js/components/explorer/detail/visualization/toolbar/BreakdownDropdown.jsx
src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
src/js/containers/explorer/detail/DetailContentContainer.jsx

- Prevents treemap cells from getting cut off when there are negative obligations
- Shows a message when a user clicks on an option and there are no associated awards at the next step/ total is $0
- Closes the dropdown when user clicks outside it

Spending Explorer Updates

---

src/js/components/account/AccountOverview.jsx
src/js/components/explorer/detail/sidebar/FYPicker.jsx
src/js/components/explorer/landing/ExplorerLanding.jsx
src/js/containers/account/AccountContainer.jsx
src/js/containers/account/filters/AccountTimePeriodContainer.jsx
src/js/containers/search/filters/TimePeriodContainer.jsx
src/js/helpers/fiscalYearHelper.js
src/js/redux/reducers/explorer/explorerReducer.js
src/js/redux/reducers/search/searchFiltersReducer.js
tests/containers/search/SearchContainer-test.jsx
tests/containers/search/filters/fiscalYearHelper.js
tests/helpers/fiscalYearHelper-test.js
tests/redux/reducers/explorer/mockCurrentFiscalYear.js

* Current FY will not appear as award search and spending explorer filter options until 2/1
* Use previous FY prior to 2/1 for federal account sankey and spending explorer
* Updated tests

Hotfix: Hold off using the new FY until 2/1

---

src/js/components/agency/AgencyContent.jsx
src/js/components/agency/visualizations/objectClass/ObjectClassTreeMap.jsx
src/js/containers/agency/visualizations/ObjectClassContainer.jsx

* Get the total obligated amount in the object class narrative from File A (via the redux agency overview object)

Hotfix: Updated obligated amount narrative in agency object class treemap

---

src/js/containers/search/table/ResultsTableContainer.jsx

* Trigger a "no results" message when there is no intersection between the user-applied award type filter and the table tab filter

Hotfix: Award Table Award Type Intersection

---

src/js/components/account/topFilterBar/filterGroups/TimePeriodFYFilterGroup.jsx
src/js/components/search/topFilterBar/filterGroups/TimePeriodFYFilterGroup.jsx

* Show "All Fiscal Years" option when all fiscal year filter options are selected on search and federal account pages
* Bases "all" calculation on new `defaultFiscalYear` instead of `currentFiscalYear` as the current FY will no longer appear as a filter option until 2/1 of the new year

Hotfix: All Fiscal Years tag

---

src/js/components/agency/overview/AgencyOverview.jsx
src/js/containers/agencyLanding/AgencyLandingContainer.jsx
tests/containers/agencyLanding/mockToptierAgencies.js

Removes hard coded total budget from:
- Agency landing page
- Agency overview visualization 
- Tests

Revert hard coded total budget authority amount

---

package.json

* A bug in moment 2.19 (released today) will cause builds to fail. Our `package.json` will auto-upgrade to this version on new installs. This change locks the version to 2.18.1, the last known stable version.

Hotfix: Lock moment version

---

src/js/components/sharedComponents/filterSidebar/FilterOption.jsx

* Mark filters as dirty when they are expanded or pre-populated from the search hash
* Don't collapse dirty filters when their values are cleared

Don't close dirty filters

---

src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx

* Unregister page navigation event listener before triggering browser download because of Firefox

Firefox Download

---

src/js/containers/explorer/detail/DetailContentContainer.jsx
src/js/redux/actions/explorer/explorerActions.js
src/js/redux/reducers/explorer/explorerReducer.js
tests/containers/explorer/detail/mockData.js
tests/redux/reducers/explorer/explorerReducer-test.js

- Resets the table to page 1 and the default sort order in Redux when changing level or subdivision

Reset the sort order when the subdivision type changes

---

src/js/components/award/contract/ContractDetails.jsx
src/js/components/award/financialAssistance/FinancialAssistanceDetails.jsx
src/js/components/search/filters/psc/SelectedPSC.jsx
src/js/dataMapping/contracts/additionalDetails.js

- Shows Award Type as "Not Available" if it doesn't exist
- Rename "Awarding Sub-Tier Agency" to "Awarding Sub-Agency"
- Rename "Funding Sub-Tier Agency" to "Funding Sub-Agency"
- Surface Awarding Office name from contract details in latest transaction
- Surface Funding Office name from contract details in latest transaction
- Show description (or code, if description does not exist) instead of both items for Solicitation Procedures, Extent Competed, Commercial Item Acquisition Procedures, and Subcontracting Plan fields
- Use correct description field for Set-Aside Type and Commercial Item Test Program
- Note a future fix for Financial Assistance Type once the data is available from the Broker

Fixing Data Mappings on Award Page

---

src/_scss/pages/award/_agencyInfo.scss
src/js/components/award/AgencyInfo.jsx
src/js/models/results/award/AwardSummary.js

* Adds awarding and funding office names for contracts and codes for assistance awards in the award detail page header bar 
https://federal-spending-transparency.atlassian.net/browse/DS-1785
https://projects.invisionapp.com/d/main#/console/8586929/260271850/comments/88635986
* Contract example: 52276483
* Assistance example: 8623108

Show offices in award detail page header

---

src/js/components/search/filters/psc/SelectedPSC.jsx
src/js/components/search/topFilterBar/filterGroups/PSCFilterGroup.jsx
src/js/containers/search/filters/psc/PSCListContainer.jsx

- Surfacing PSC description in the PSC autocomplete results, PSC selection, and PSC section of the top filter bar
[Subtask DS-1870](https://federal-spending-transparency.atlassian.net/browse/DS-1870) of [DS-1757](https://federal-spending-transparency.atlassian.net/browse/DS-1757), as the updated autocomplete endpoint now returns the PSC description, in addition to the code itself, for the first time

Show PSC Description in PSC Filter

---

src/js/components/search/filters/agency/SelectedAgencies.jsx
src/js/components/search/topFilterBar/filterGroups/AgencyFilterGroup.jsx
src/js/containers/search/filters/AgencyListContainer.jsx
src/js/models/search/SearchAwardsOperation.js

- Remove the restriction of Funding Agencies to be toptier-only
- This returns Funding Agency to an "Award Type" filter from the deprecated "Budget Type" filter construct
- Remove the ability to view or select subtier options of toptier Agencies
- ex. "Treasury" will now return a single option, instead of a toptier and subtier option
- Update queries to reflect Funding Agencies can now be subtier
[Subtask DS-1873](https://federal-spending-transparency.atlassian.net/browse/DS-1873) of [DS-1757](https://federal-spending-transparency.atlassian.net/browse/DS-1757)

Agency Filter Updates

---

src/js/components/agency/AgencyContent.jsx
src/js/components/agency/visualizations/recipient/RecipientVisualization.jsx
src/js/containers/agency/visualizations/RecipientContainer.jsx

- Recipient Visualization now shows date from response of `lastUpdate` API call, the last date that awards were pulled, instead of the end date of the last submission period
Corrects a bug in [DS-1777](https://federal-spending-transparency.atlassian.net/browse/DS-1777)

Reverting Agency Page - Recipient Visualization Date

---

src/js/components/award/details/DetailsSection.jsx

https://federal-spending-transparency.atlassian.net/browse/DS-1896

Re-enable subawards tab

---

src/js/redux/reducers/award/awardReducer.js
tests/redux/reducers/award/awardReducer-test.js

* Change transactions table default sort to action date descending
https://federal-spending-transparency.atlassian.net/browse/DS-1789

Fix: Default transactions table sorting

---

src/js/components/search/filters/recipient/RecipientType.jsx
src/js/components/search/topFilterBar/filterGroups/RecipientTypeFilterGroup.jsx
src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx
src/js/dataMapping/search/recipientType.js
src/js/redux/reducers/search/searchFiltersReducer.js
tests/containers/search/filters/recipientFilter/RecipientTypeContainer-test.jsx
tests/containers/search/filters/recipientFilter/mockRecipients.js
tests/containers/search/mockSearchHashes.js

* Passes a single filter value when an entire group of recipient types is selected
* **Note:** This will invalidate any existing search hash URLs once deployed.

Fix: Parent Recipient Type Filter API Integration

---

src/js/components/award/SummaryBar.jsx

* Removes award status section from header bar on individual award page
https://federal-spending-transparency.atlassian.net/browse/DS-1956

Remove award status label

---

src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx

* In DEV only
* Requires fedspendingtransparency/usaspending-api#740 to operate correctly

Restore county and congressional district layers

---

package.json
src/_scss/all.scss
src/_scss/components/datePicker/_datePicker.scss
src/js/components/search/filters/timePeriod/DateRange.jsx
src/js/components/sharedComponents/DatePicker.jsx
src/js/models/search/SearchAwardsOperation.js

* When a set of FYs are intended but no FYs are selected, request the period of start of FY 2008 to end of current FY from API
* When a date range date is intended but no date is specified, request the period of start of FY 2008 to end of current FY from API
* When an open-ended date range is sent to the API, fill in the missing start or end date with the start of FY 2008 or end of current FY respectively
* Disable dates in date picker before FY 2008 or the populated start date value (whichever is later)
* Upgrade react-day-picker so date picker automatically goes to the pre-populated date
* Style changes to actually disable selection of disabled dates in date picker

Time Period Filter Improvements

---

src/js/components/search/topFilterBar/filterGroups/TimePeriodFYFilterGroup.jsx

* Use a single "All Fiscal Years" tag in the top filter bar(s) when all fiscal years are selected

Fix All Fiscal Years Top Filter Bar Tag

---

src/_scss/pages/search/results/table/resultsTable.scss
src/js/components/search/visualizations/geo/MapWrapper.jsx
src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
src/js/helpers/mapBroadcaster.js

* Recipient Location/Place of Performance toggle works on map visualization again
* Restored vertical spacing between award search table's type tabs and header in the table's loading state

Fix: Allow forced overrides of map measurement diff

---

src/_scss/pages/homepage/_searchSectionDropdown.scss
src/_scss/pages/homepage/_searchSectionItems.scss

- Removed the gap between the dropdown button and its options so that it doesn't close when the user mouses out from the button
- IE11 users should now be able to select the Agencies option in the dropdown at the bottom of the homepage
Bug: https://federal-spending-transparency.atlassian.net/browse/DS-1972

Fix - Homepage Dropdowns on IE11

---

src/js/components/bulkDownload/awards/filters/AgencyFilter.jsx
src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
tests/containers/bulkDownload/mockData.js

- Removes the `subtier_agency_id` field, which will no longer be returned by the `/list_agencies` endpoint
- Passes the subtier agency name as a string instead of its id to the `/bulk_download/awards` endpoint
https://federal-spending-transparency.atlassian.net/browse/DS-2065

Update Subtiers Based on Names

---

src/js/components/award/contract/ContractDetails.jsx
src/js/components/award/financialAssistance/FinancialAssistanceDetails.jsx

https://federal-spending-transparency.atlassian.net/browse/DS-2076
* Promote to dev-stable with staging (not prod) as target
* Fixes a bug where financial assistance awards would not initially populate Award Details and, if the URL changed to another financial assistance award, would then populate with the previous award

Mild Fix: Show Financial Assistance Award Details

---

src/js/components/about/DataQuality.jsx

* Changes about page text from `quarterly assistance` to `quarterly assurance`

Fix: Quarterly Assurance Typo

---

src/js/components/sharedComponents/IBTable/components/TableBody.jsx

* Fixes a bug in the table library where sometimes scrolling to the bottom of the table would not trigger pagination requests on OSes and browsers with persistent scrollbars enabled
* Fixes a bug in the table library where allowing vertical overscrolling events to trigger pagination requests would, on reset, skip straight to the second page of requests (hiding the first page of results) due to batched DOM writes that indirectly triggered additional scroll events

Fix table pagination

---

src/js/components/account/awards/LegacyResultsTable.jsx
src/js/containers/account/awards/AccountAwardsContainer.jsx
src/js/dataMapping/search/accountTableSearchFields.js
src/js/models/v2/BaseFederalAccountAwardRow.js
src/js/models/v2/utils.js
tests/containers/account/awards/AccountAwardsContainer-test.jsx
tests/containers/account/awards/mockSearchFields.js

Does not need to go in this deploy.
- Columns in the Federal Account table now match those in the Award Search table for each Award Type
Bug: https://federal-spending-transparency.atlassian.net/browse/DEV-116
Note: For full testing, @michaeldhess is looking into finding a Federal Account in the dev database that has corresponding awards to display in the table. However, even without result data in the table (which allows the user to scroll through the column headers), the visible column headers can be seen updating on each tab change.
Use 2421

Fix - Federal Account Table Columns

---

src/_scss/pages/explorer/detail/visualization/treemap/_cell.scss
src/js/components/agency/overview/AgencyOverview.jsx
src/js/components/award/AwardAmounts.jsx
src/js/components/bulkDownload/awards/AwardDataContent.jsx
src/js/components/explorer/detail/visualization/table/ExplorerTable.jsx
src/js/components/explorer/detail/visualization/table/TableRow.jsx
src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
src/js/components/explorer/detail/visualization/treemap/TreemapCell.jsx

- When an Award ID is `null` due to a missing File C/D linkage, the Spending Explorer table will show a generic table cell that does not attempt to link to the Award page with that `null` ID
- Also fixes React key issues in the Spending Explorer table when encountering `null` Award IDs
Bug: https://federal-spending-transparency.atlassian.net/browse/DEV-284
To test, in the Spending Explorer, select Agency -> DOL -> Click the Table Icon -> Award

Fix - Spending Explorer Table with null Award IDs

---

src/_scss/pages/explorer/detail/visualization/table/_table.scss

- Removes unnecessary scroll bars on the Spending Explorer in Chrome + IE on Windows
- Increases line height of table rows in the Spending Explorer to avoid cutting off the bottom of letters that descend below the baseline in Safari on Mac
Bug: https://federal-spending-transparency.atlassian.net/browse/DEV-91

Fix - Spending Explorer Styles

---

src/js/components/sharedComponents/IBTable/components/Table.jsx

* Fixes a bug where IBTable may respond to a reload method after the table has been scheduled for unmounting, resulting in a JS error

Fix IBTable Reload after Unmount

---

src/js/helpers/fiscalYearHelper.js
tests/containers/account/filters/AccountTimePeriodContainer-test.jsx
tests/helpers/fiscalYearHelper-test.js

**This PR is going directly to master**
- Extends the FY rollover date by 15 days
- Adds configuration to allow for complete override of default fiscal year via global constants
- Adds configuration to dynamically change the number of days of delay between the end of Q1 close and the date we rollover to the new FY

Hottest Fix - Change FY Rollover Date from 1/31 to 2/15

---

src/js/components/award/RecipientInfo.jsx
src/js/helpers/businessTypesHelper.js

Updating business type checks to look for booleans and ignoring unknown business type check for contracts

Update Award profile page business type checks

---

src/js/components/search/SearchPage.jsx
src/js/components/search/header/DownloadButton.jsx
src/js/components/search/header/NoDownloadHover.jsx

- Updates text and link within the hover on the Advanced Search page Download button when it's in a disabled state
- Only shows the hover if the user has applied filters and there are more than 500,000 results
Issue: https://federal-spending-transparency.atlassian.net/browse/DEV-431
As there are fewer than 500,000 records within the Skinny Dev database, test the hover functionality by changing [this line](https://github.com/fedspendingtransparency/usaspending-website/blob/dev/src/js/containers/search/SearchContainer.jsx#L380) to `downloadAvailable: false`.

Update - Advanced Search Hover

---

src/js/components/account/AccountOverview.jsx
src/js/containers/account/AccountContainer.jsx
src/js/containers/account/visualizations/AccountTimeVisualizationContainer.jsx
src/js/models/account/FederalAccount.js
src/js/redux/reducers/account/accountReducer.js
tests/containers/account/AccountContainer-test.jsx
tests/containers/account/mockAccount.js

https://federal-spending-transparency.atlassian.net/browse/DEV-528
* More robust logic in the federal account sankey to determine if there is data for the current FY which to build the sankey and summary
* Support for showing multiple FYs at the same time in federal account Spending Over Time visualization
* Reversed the order of bars in Spending Over Time so later periods appear going left-to-right, matching Advanced Search's Spending Over Time
* Refactored federal account container test's function mocking to be in line with our standard approach

Fixes: Federal Account - Sankey Error Handling & Multiple FYs in Spending Over Time 

---

src/js/components/award/RecipientInfo.jsx
src/js/components/award/financialAssistance/FinancialAssistanceDetails.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-454
https://federal-spending-transparency.atlassian.net/browse/DEV-514
* Treat IDVs as contracts in the recipient section on the award profile page, allowing correct business types and parent DUNS to appear.
* Implement logic from contract profile to truncate financial assistance award descriptions to be truncated to 160 characters.

IDV Business Types/Parent DUNS + Truncated Financial Assistance Descriptions

---

src/js/components/homepage/Homepage.jsx

* Homepage included a duplicate instance of the glossary, which caused irreconcilable conflicts between the instances

Fix: Homepage Glossary

---

src/js/components/explorer/detail/visualization/table/ExplorerTable.jsx
src/js/helpers/moneyFormatter.js

- Fixes Spending Explorer table unique key issue with duplicate names
- Fixes bug in showing cents in treemap tooltips for awards in the THOUSANDS range

Fix - Spending Explorer Table Key Names

---

src/_scss/pages/account/results/visualizations/rank/rank.scss
src/_scss/pages/search/results/visualizations/rank/rankVisualization.scss
src/js/components/search/visualizations/rank/RankVisualization.jsx
src/js/components/search/visualizations/rank/RankVisualizationTooltip.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-545
* Adds a legend to Spending by Category on federal account profile page
* Updates tooltip to use "Obligation Incurred" instead of "Total Spending"

Federal Account Spending by Category Legend

---

src/js/containers/account/filters/AccountProgramActivityContainer.jsx
src/js/models/account/queries/queryBuilders/ProgramActivityQuery.js
src/js/models/account/queries/queryBuilders/_programActivityTranslator.js
tests/containers/account/filters/AccountProgramActivityContainer-test.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-540
* Temporary patch to combine program activity filters on the federal account profile page that have the same code and name into a single option

Fix Duplicate Program Activity Filters on Federal Account Profile

---

src/_scss/layouts/default/header/nav/_glossaryLink.scss
src/_scss/pages/account/header/_options.scss
src/_scss/pages/award/_summaryStatus.scss
src/_scss/pages/homepage/hero/_heroTooltip.scss
src/_scss/pages/homepage/hero/hero.scss
src/js/components/homepage/hero/Hero.jsx
src/js/components/homepage/hero/HeroTooltip.jsx

- Adds an information icon to the homepage
- Adds a tooltip to the information icon that activates on hover or tap
- Tooltip can be closed through clicking/tapping an X button at the top right of the tooltip
- Fixes the Header bar CSS for Firefox
Issue: https://federal-spending-transparency.atlassian.net/browse/DEV-553

Homepage Information Icon

---

src/js/components/award/visualizations/AwardLabels.jsx

* Remove parenthicals from labels in the Award Amount visualization on Award profile page

Remove Award Amount Parenthicals

---

src/_scss/pages/explorer/detail/header/_truncation.scss
src/_scss/pages/explorer/detail/header/header.scss
src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/header/DetailHeader.jsx
src/js/components/explorer/detail/header/TruncationWarning.jsx
src/js/containers/explorer/detail/DetailContentContainer.jsx
tests/containers/explorer/detail/DetailContentContainer-test.jsx
tests/containers/explorer/detail/mockData.js

* Adds a truncation warning at the award level of the spending explorer when results have limited due to response size

Spending Explorer Limits

---

src/js/models/results/award/AwardSummary.js

* Fixes a bug where page rendering would break on award profile pages with `null` recipient names due to Award Amounts performing a `.toLowerCase()` operation.
Test on award 6797869

Fix: Handle null recipient names

---

src/_scss/pages/explorer/detail/visualization/_breakdown.scss

- Enables automatic wrapping of elements in the Spending Explorer breakdown bar
- Adds vertical spacing between items on smaller screens
No bug for this one

Fix - Spending Explorer Responsiveness

---

src/_scss/core/_variables.scss
src/_scss/elements/filters/_typeahead.scss
src/_scss/pages/explorer/detail/visualization/treemap/_cell.scss
src/_scss/pages/keyword/_searchBar.scss
src/_scss/pages/search/filters/awardAmount/_specificAwardAmount.scss
src/_scss/pages/search/filters/awardID/awardID.scss
src/_scss/pages/search/filters/keyword/keyword.scss
src/_scss/pages/search/filters/location/_dropdown.scss
src/_scss/pages/search/filters/location/location.scss
src/js/components/agency/visualizations/objectClass/MajorObjectClasses.jsx
src/js/components/agency/visualizations/objectClass/MinorObjectClasses.jsx
src/js/components/explorer/detail/visualization/treemap/TreemapCell.jsx
src/js/helpers/colorHelper.js
tests/helpers/colorHelper-test.js

https://federal-spending-transparency.atlassian.net/browse/DEV-568
https://federal-spending-transparency.atlassian.net/browse/DEV-575
* Improve contrast of text field placeholders on advanced search page
* Implement a color generator to programmatically generate treemap label colors so treemap labels will always have 508-compliant contrast for any given cell background color

Additional 508 Color Contrast Fixes

---

src/_scss/pages/search/filters/recipient/recipient.scss

* Design review caught a field that didn't have the updated placeholder contrast applied to it

Update contrast for recipient field

---

src/js/components/search/filters/recipient/RecipientType.jsx
src/js/containers/search/filters/recipient/RecipientTypeContainer.jsx
src/js/dataMapping/search/recipientType.js
tests/containers/search/filters/recipientFilter/RecipientTypeContainer-test.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-624
*  Use `category_business` instead of `business` for recipient type in Advanced Search
* When a parent recipient type is selected, any previously selected child recipient type is overwritten with the parent recipient type to prevent duplicates in the API call and the top filter bar

Fix: Business Recipient Type Filter

---

src/js/models/v2/awards/BaseContract.js
src/js/models/v2/awards/BaseFinancialAssistance.js
src/js/models/v2/awards/CoreAwardAgency.js
tests/models/awards/BaseContract-test.js
tests/models/awards/BaseFinancialAssistance-test.js
tests/models/awards/CoreAwardAgency-test.js

* Handle null awarding/funding agencies in the new award models so they don't break the agency toggle on the profile pages

Handle null awarding/funding agencies

---

src/js/components/award/LoanAmounts.jsx

* Hide percentage of face value amount on loans profile when the face value is 0

Fix: Hide percentage on loans with $0 face value

---

src/js/components/award/AwardAmounts.jsx
src/js/dataMapping/contracts/additionalDetails.js
src/js/models/v2/awards/additionalDetails/BaseContractAdditionalDetails.js

https://federal-spending-transparency.atlassian.net/browse/DEV-628
- Shows the field `other_than_full_and_o_desc` for "Not Competed Reason"
- Groups "Fair Opportunity Limited Sources" under "Competition Details" instead of "Additional Details"
- Replaces "ceiling" with "potential award amount" in the Award Amount visualization

Contract Summary Updates

---

src/js/containers/account/visualizations/AccountTimeVisualizationContainer.jsx
tests/containers/account/mockAccount.js
tests/containers/account/visualizations/AccountTimeVisualizationContainer-test.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-541
- Sorts the list of quarters/years before iterating to create bar graphs
- Updates variable names for clarity
Test with staging API: 
- `/#/federal_account/404` by quarter, Other/Unknown Program Activity filters
- `/#/federal_account/388` by quarter, Above 185 of Poverty Program Activity filters

Fix Account Spending Over Time order

---

src/js/components/sharedComponents/header/Header.jsx

- Prevent GA events for Data Lab & usaspending.gov links being logged when the page loads

Fix Header Analytics

---

src/js/dataMapping/bulkDownload/bulkDownloadOptions.js

https://federal-spending-transparency.atlassian.net/browse/DEV-802
- Removed _today_ from the list of predefined data ranges on the Custom Award Data page.

Fix Custom Award Data Date Range

---

src/js/components/about/DataQuality.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-933
* Adds a link to the raw agency submissions on the About page

Hotfix: Add link to raw files on About page

---

src/js/containers/keyword/KeywordContainer.jsx
tests/containers/bulkDownload/mockBulkDownloadHelper.js
tests/containers/keyword/KeywordContainer-test.jsx

* Updates KeywordContainer to use the correct bulkDownloadHelper function resulting from a helper function refactor

Hotfix: Keyword download

---

src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
tests/containers/search/visualizations/rank/RankVisualizationWrapperContainer-test.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1182
- Updates Redux state to indicate applied filter completion as a spending by category request is being made

Hotfix Spending by Category disabled filters

---

src/js/containers/explorer/detail/DetailContentContainer.jsx
tests/containers/explorer/detail/DetailContentContainer-test.jsx
tests/containers/explorer/detail/mockData.js

https://federal-spending-transparency.atlassian.net/browse/DEV-1172
- Fixed the rewind feature to use the currently selected quarter and added in a test to reflect that.

Fix Spending Explorer Rewind Feature

---

api_contracts/contracts/downloads/CustomAccountDownload.md
src/js/components/bulkDownload/accounts/AccountDataContent.jsx
src/js/components/bulkDownload/accounts/UserSelections.jsx
src/js/components/bulkDownload/accounts/filters/AccountLevelFilter.jsx
src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx
src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
src/js/containers/bulkDownload/accounts/AccountDataContainer.jsx
src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
src/js/dataMapping/navigation/menuOptions.js
src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js

https://federal-spending-transparency.atlassian.net/browse/DEV-1059, https://federal-spending-transparency.atlassian.net/browse/DEV-1156
- Implemented the option to group by File C
- Implemented the option to group by Federal accounts
- Created API contract for Custom Accounts

Feature Custom Accounts Grouping

---

src/js/components/search/modals/fullDownload/FullDownloadModal.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1139
- Modal is now properly hidden after downloading results from advanced search
- Modal also resets when reopened to allow the user to request a new download

Close advanced search when complete

---

src/js/components/bulkDownload/archive/AwardDataArchiveContent.jsx
src/js/containers/bulkDownload/archive/AwardDataArchiveContainer.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1238
- Updated "Award Data Archive" second paragraph of the description with newer langauge
- As per newer language, updated the title of the last column in the table to "Data as of" instead of "Date as of"

Update Description for Archive and Delta Files with newer language

---

src/js/containers/search/helpers/searchAnalytics.js
src/js/helpers/analytics/Analytics.js
tests/containers/search/helpers/searchAnalytics-test.js

- Updates analytics event parser to be compatible with multiple keywords
- Prevents a bug causing empty keyword events to be logged as "(not set)"

Fix keyword analytics

---

api_contracts/contracts/recipient/RecipientProfile.md

- Uses real `duns` & `recipient_id` values to allow testing against dev API
- Makes location fields required & nullable

Update recipient overview contract

---

src/js/components/recipient/RecipientOverview.jsx
src/js/models/v2/CoreLocation.js
tests/models/CoreLocation-test.js

- Fixes a bug causing just `Congressional District:` to display when there was no location data
- Shows `Address not provided in source system` when no location data is available 
- Shows `Not provided in source system` when there are no business types

Update recipient no location data

---

src/js/components/recipient/spendingOverTime/RecipientTimeVisualizationSection.jsx
src/js/components/search/visualizations/time/chart/BarXAxis.jsx
src/js/components/state/spendingovertime/StateTimeVisualization.jsx
src/js/components/state/spendingovertime/StateTimeVisualizationSection.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1399
- Hides the trendline + its axis & label by re-using state profile's time visualization component
- Keeps the x-axis labels static on hover per Recipient Profile design review
- Adds a prop for the color of the bars (can be removed later)

Update hide trendline

---

api_contracts/contracts/award/AwardProfile.md

https://federal-spending-transparency.atlassian.net/browse/DEV-1410
- Makes `award_id` a required request param and updates it from type `string` to `number`

Update Transactions Contract

---

src/js/components/recipient/RecipientOverview.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1479
Temporarily disabling parent recipient glossary link as per service desk request

Temporarily disabling glossary link on parent recipient label

---

src/js/models/v2/awards/subawards/BaseSubawardRow.js
tests/models/awards/BaseSubawardRow-test.js

Changes the Award Summary Sub-award table Recipient column to display the top-level API field `recipient_name` instead of nested `recipient__recipient_name`
• [ ] Frontend code review
• [ ] Merge concurrently with backend updates (@tony-sappe)

Hotfix sub-award recipient name

---

src/js/containers/search/filters/AgencyListContainer.jsx
tests/containers/search/filters/agencyFilter/AgencyListContainer-test.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1543
- On Advanced Search Awarding Agency & Funding Agency filters, move FEMA's toptier entry to the end of the autocomplete list

Move FEMA's toptier entry to the end of the autocomplete list

---

src/_scss/layouts/tabbedSearch/header/_downloadButton.scss
src/js/components/search/SearchPage.jsx
src/js/components/search/header/DownloadButton.jsx
src/js/containers/search/SearchContainer.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1089
- While the advanced search page determines whether download is available for the current filter set, the button displays `Preparing Download...`  and does not show the tooltip on hover
Mockup: https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/screens/295996700_Advanced_Search_-_Awards_Level-_Prime_Awards_-_Download_Prep

Fix download button loading state

---

src/js/containers/search/filters/AgencyListContainer.jsx
tests/containers/search/filters/agencyFilter/AgencyListContainer-test.jsx
tests/containers/search/filters/agencyFilter/mockLocalSearch.js

https://federal-spending-transparency.atlassian.net/browse/DEV-1543
First PR (#895) only moved the toptier entry to the end of the list. This version retains the order of results in the API response when searching for FEMA, so that older subagencies of top-tier FEMA will also be at the end of the list.

Update Fema Autocomplete v2

---

src/js/containers/search/filters/AgencyListContainer.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1543
- Using the JS Search library was changing the order of the results returned from the API, which we want to preserve when searching for FEMA

Don't use JS Search library for FEMA

---

api_contracts/contracts/award/AwardProfile.md
api_contracts/contracts/downloadCenter/DownloadCenter.md
api_contracts/contracts/recipient/RecipientProfile.md
api_contracts/contracts/search/AdvancedSearch.md
api_contracts/contracts/spendingExplorer/SpendingExplorer.md
src/js/components/explorer/detail/visualization/table/cells/LinkCell.jsx
tests/containers/explorer/detail/DetailContentContainer-test.jsx
tests/containers/explorer/detail/mockData.js

Fixes some formatting issues in existing API contracts.
-  Ensures that [compliance tests](https://github.com/fedspendingtransparency/usaspending-website/tree/dev/api_contracts#automated-dev-api-compliance-testing) will not fail because of formatting issues in the contract. Compliance tests may still fail because:
a) the endpoint doesn't exist yet
b) the endpoint does not match the contract 
- Improves generated [API Documentation](https://github.com/fedspendingtransparency/usaspending-website/tree/dev/api_contracts#generating-api-documentation)
- Changes `v2/spending` results' `id` to a string in preparation for [DEV-1549](https://federal-spending-transparency.atlassian.net/browse/DEV-1549)
**Link to JIRA Ticket:**
N/A, preparation for …

Cleanup API Contracts

---

src/_scss/pages/state/spendingovertime/_stateTimeVisualization.scss
src/js/components/state/StateContent.jsx
src/js/components/state/spendingovertime/StateTimeVisualization.jsx
src/js/components/state/spendingovertime/StateTimeVisualizationSection.jsx
src/js/components/state/spendingovertime/StateTimeVisualizationTooltip.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-1523
- Changes State Profile sidebar label from "Awards Over Time" to "Transactions Over Time"
- Changes State & Recipient Profile tooltips from "Awarded Amount" to "Amount Obligated"

Hotfix state profile copy

---

src/js/components/about/DataQuality.jsx
src/js/components/bulkDownload/accounts/AccountDataContent.jsx
src/js/dataMapping/navigation/menuOptions.js
src/js/models/v2/state/BaseStateProfile.js
tests/models/state/BaseStateProfile-test.js

Changes s3 links to new .gov urls in the following places: 
- Custom Account Data Dictionary link (Custom Account page)
- Raw quarterly submission files link (About page, Data Quality section)
- State flag images (State Profile pages)
- Agency Submission Files & Database Download (Download menu)
- Determines whether the url should use `files.usaspending.gov` or `files-nonprod.usaspending.gov` based on the global constants variable
- There was no need to update download file urls because they come directly from the `v2/bulk_download/` API
[DEV-1546](https://federal-spending-transparency.atlassian.net/browse/DEV-1546)

Update s3 links

---

api_contracts/contracts/award/AwardProfile.md

Adds the `v2/accounts/awards` endpoint to the Award Profile API contract 
- `v2/accounts/awards` is used to populate the Financial System Details table on Award Profile pages
- Also refactored the `Data Structures` into separate sections for each `Group` 
[DEV-1598](https://federal-spending-transparency.atlassian.net/browse/DEV-1598)

Contract v2/accounts/awards

---

src/_scss/pages/bulkDownload/downloadData.scss
src/js/components/bulkDownload/accounts/AccountDataContent.jsx
src/js/components/bulkDownload/accounts/filters/BudgetFunctionFilter.jsx

- Switches order of title and code
- Removes `BETA` flag from custom account download page
[DEV-1446](https://federal-spending-transparency.atlassian.net/browse/DEV-1446) failed testing because the results were not listed in alphabetical order. Now that the results are alphabetized, it makes more sense to display the budget sub-function title before the code.

Hotfix Budget Sub-function dropdown

---

api_contracts/contracts/recipient/RecipientProfile.md
api_contracts/contracts/search/AdvancedSearch.md

(@dtrinh50 Help with PR description)
Minor edits to SpendingOverTime API endpoint (`/api/v2/search/spending_over_time')
Making the `TimePeriodGroup` response object types consistent.
Link to https://github.com/fedspendingtransparency/usaspending-api/pull/1576

Update time period in contracts

---

src/js/components/awardv2/contract/Accordion.jsx
src/js/components/awardv2/contract/Recipient.jsx

High level description:
Non-matching api response causing `view more` buttons to break. 
Technical details:
API response(`api/v2/awards`) in dev for `recipient` is showing a value called `business_categories` which unfortunately, isn't matching the value specified in the API contract `business_categories_name`. 
This PR handles this issue by checking to see if the field exists before attempting to use it.
JIRA Ticket:
[DEV-1563](https://federal-spending-transparency.atlassian.net/browse/DEV-1563)

Award Summary Recipient - fix for missing business categories

---

src/js/components/homepage/hero/Hero.jsx
src/js/components/homepage/hero/HeroTooltip.jsx

Changed the following values on front-page:
- FY: 2017 -> 2018
- Spending Total: `$3.98` trillion to `$4.11 trillion`
- Modify _Monthly Treasury Link_ in info popup to newly requested URL
- Minor refactoring for easier future maintainability
A few minor edits were made to change hard-coded values into constant variables to simplify maintainability for future changes.
[DEV-1633](https://federal-spending-transparency.atlassian.net/browse/DEV-1633)

Updated Fiscal Year/Document URL/Spending total for 2018

---

src/_scss/pages/explorer/detail/explorerDetail.scss
src/_scss/pages/explorer/detail/visualization/visualization.scss
src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/header/DetailHeader.jsx
src/js/components/explorer/detail/header/RootHeader.jsx
src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
src/js/components/explorer/detail/visualization/table/ExplorerTable.jsx
src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
src/js/containers/explorer/detail/table/ExplorerTableContainer.jsx

Improved user experience while the Spending Explorer is fetching data from the API.
**Technical Details**
Adds a loading state for: Treemap, Table, Initial load (root/ starting over), Detail Header total amount, and Root Header total amount.
[DEV-1872](https://federal-spending-transparency.atlassian.net/browse/DEV-1872)
**Mockup:**
See screenshot in [DEV-1846](https://federal-spending-transparency.atlassian.net/browse/DEV-1846)

Update explorer loading message

---

src/js/containers/award/AwardContainer.jsx
src/js/models/v2/awards/CoreAward.js
tests/containers/award/AwardContainer-test.jsx
tests/models/awards/BaseContract-test.js
tests/models/awards/CoreAward-test.js

Fixes the "Additional Details" tab on IDV Summary pages. 
Addresses an API change to `v1/awards`. Previously, IDVs had a null `category`. Category is now set to `'idv'`. 
Resuted from changes related to [DEV-1924](https://federal-spending-transparency.atlassian.net/browse/DEV-1924)
**Mockup:**
N/A

Hotfix IDV additional details

---

src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/visualization/toolbar/BreakdownDropdown.jsx
src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
src/js/containers/explorer/detail/ExplorerDetailPageContainer.jsx

This hotfix resolves this issue of agency view displaying incorrect data in Spending Explorer.
Reverts React Lifecycle updates for the spending explorer.
[DEV-1906](https://federal-spending-transparency.atlassian.net/browse/DEV-1906)

Hotfix Spending Explorer Agency View

---

src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
src/js/containers/explorer/detail/ExplorerDetailPageContainer.jsx

Hotfix for Spending Explorer display wrong view.
Reverts life cycle updates for Spending Explorer containers and components. 
[DEV-1906](https://federal-spending-transparency.atlassian.net/browse/DEV-1906)

Hotfix spending explorer

---

src/js/containers/explorer/detail/helpers/explorerQuarters.js
src/js/helpers/fiscalYearHelper.js
tests/containers/explorer/detail/helpers/explorerQuarters-test.js
tests/helpers/fiscalYearHelper-test.js

Delays the release of 2019 Q1 Account data until March 21, 2019.
Affects the following components:
- Spending explorer FY and quarter picker
- Custom Account download FY and quarter picker
- Federal Account Landing page `Budgetary Resources` column (API request and heading)
- Federal Account Profile page Sankey (API request and heading), and available time period filters
[DEV-2091](https://federal-spending-transparency.atlassian.net/browse/DEV-2091)
**Mockup:**
N/A

Hotfix delay 2019 Q1

---

src/js/containers/AppContainer.jsx

The [Redux Dev Tools Extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) window variable has been renamed in the latest version.
See https://github.com/zalmoxisus/redux-devtools-extension#usage
Removes this console warning:
> `window.devToolsExtension` is deprecated in favor of `window.__REDUX_DEVTOOLS_EXTENSION__`, and will be removed in next version of Redux DevTools: https://git.io/fpEJZ
N/A (technical improvement)
**Mockup:**
N/A

Update Redux dev tools

---

src/_scss/pages/awardV2/awardPage.scss
src/_scss/pages/awardV2/idv/_infoTooltip.scss
src/_scss/pages/awardV2/idv/awardIdv.scss
src/_scss/pages/awardV2/visualizations/awardViz.scss
src/_scss/pages/awardV2/visualizations/overview/_relatedAwards.scss
src/js/components/awardv2/idv/IdvDates.jsx
src/js/components/awardv2/idv/InfoTooltip.jsx
src/js/components/awardv2/visualizations/amounts/AwardAmounts.jsx
src/js/components/awardv2/visualizations/description/AwardDescription.jsx
src/js/components/awardv2/visualizations/overview/RelatedAwards.jsx
src/js/components/sharedComponents/Tooltip.jsx

Adds info icons with tooltips to multiple IDV summary page sections.
- Created a shared `InfoTooltip` component that includes the `i` icon and handles show/hide logic. It also has the option to display the tooltip to the left or right of the icon
- Added the `InfoTooltip` component to the following sections: Related Awards, Dates, Award Amounts, Description
[DEV-1992](https://federal-spending-transparency.atlassian.net/browse/DEV-1992)
**Mockup:**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/296002761_Award_Summary_2-0_-_IDV_-MVP- (hover over combined award amounts for tooltip styling)

Feature idv tooltips

---

src/js/components/awardv2/idv/IdvContent.jsx
src/js/models/v2/awardsV2/CoreAward.js

"/" was omitted from longDescription of award types 
The lodash method `startCase` was removing this character in the component
[DEV-2225](https://federal-spending-transparency.atlassian.net/browse/DEV-2225)
**Mockup:**
https://bahdigital.invisionapp.com/share/HEIA8W7U43G#/screens
**Commits:**
6000cae -- removing `startCase` from component
db80d49 -- applying `startCase` to model when value in map is undefined
[ ] Design review (if applicable) `N/A`
[ ] API contract approved by @backendDev (if applicable) `N/A`
[ ] [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged (if applicable) `N/A`

[DEV-2225] follow up to ensure model includes "/" character in longDescription

---

src/js/components/bulkDownload/awards/AwardDataContent.jsx
src/js/components/bulkDownload/awards/DownloadTooltip.jsx
src/js/components/bulkDownload/awards/filters/AwardTypeFilter.jsx
src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
src/js/dataMapping/state/awardTypes.js
src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js
tests/containers/bulkDownload/mockData.js
tests/redux/reducers/bulkDownload/bulkDownloadReducer-test.js

Allow users to bulk download IDVs
updated frontend data store to include `idvs` in awardTypes
updated validation
[DEV-2302](https://federal-spending-transparency.atlassian.net/browse/DEV-2302)

add-idv-to-bulkdownload

---

src/js/components/awardv2/AwardV2.jsx
src/js/containers/award/AwardContainer.jsx
src/js/containers/awardV2/AwardV2Container.jsx
src/js/containers/router/RouterRoutes.jsx
tests/containers/award/AwardContainer-test.jsx
tests/containers/award/mockResults.js
tests/containers/awardV2/AwardV2Container-test.jsx

* `/#/award/{id}` urls will now display the v2 summary pages for IDVs
* `/#/award/{id}` urls still display the v1 summary pages for non-IDVs
* `/#/award_v2/{id}` can still be used to preview v2 summary pages for non-IDVs
The `/award` route now points to `AwardV2Container`.
* The `AwardV2Container` makes an API call to the `v2/awards` endpoint, and uses the response to determine if `category === 'idv'`
* `AwardV2Container` checks the current url to see if it contains `'award_v2'`
* If the current award is either an IDV or we are at an `/award_v2/` url, show the v2 Award Component
* If it is not an IDV and we are at a normal `/award/` url, render the v1 `AwardContainer`, which makes an API call to the `v1/awards` endpoint and renders …

Release IDV summary pages

---

src/js/containers/awardV2/idv/AwardMetaDataContainer.jsx

Race condition existed where the API call for `award a` that was initiated at componentDidMount was finishing after the API call for `award b` which was initiated at componentDidUpdate.
In class method that initiates API call, before starting a new one, cancel any existing ones.
[DEV-2303](https://federal-spending-transparency.atlassian.net/browse/DEV-2303)
**Mockup:** `N/A`

[DEV_2303] implementing the cancel pattern to eliminate race condition

---

src/_scss/pages/awardV2/idv/_awardAmounts.scss
src/js/components/awardv2/visualizations/amounts/AggregatedAwardAmounts.jsx
src/js/components/awardv2/visualizations/amounts/AggregatedAwardAmountsInfo.jsx
src/js/components/awardv2/visualizations/amounts/AwardAmounts.jsx
src/js/components/awardv2/visualizations/amounts/charts/NormalChart.jsx
src/js/containers/awardV2/visualization/AwardAmountsContainer.jsx

Updates the design for the IDV Award Amounts visualization. 
- Refactored the bar visualization into its own component; changed it to a BEM block in the scss file
- Changed the terminology `Combined Base & Exercised Options` → `Combined Current Award Amounts` and `Combined Base & All Options` → `Combined Potential Award Amounts`
- Award id for example of this scenario in dev: `69051621`
- Subsequent PRs for the other subtasks will branch off of this branch
[DEV-2355](https://federal-spending-transparency.atlassian.net/browse/DEV-2355), subtask for step 1 of [DEV-2224](https://federal-spending-transparency.atlassian.net/browse/DEV-2224)
**Mockup:**
https://bahdigital.invisionapp.com/share/HQIAA1BT2DP#/screens/296009666
The …

Update Award Amounts design

---

src/js/components/awardv2/AwardV2.jsx
src/js/components/awardv2/idv/IdvContent.jsx
src/js/components/awardv2/idv/referencedAwards/ReferencedAwardsTable.jsx
src/js/components/awardv2/visualizations/description/AwardDescription.jsx
src/js/components/awardv2/visualizations/overview/RelatedAwards.jsx
src/js/containers/awardV2/AwardV2Container.jsx

Fixes links on the IDV page that opened the glossary and pointed to other award pages to use the `award/` url instead of `award_v2/`.
* Glossary link to IDV type description
* NAICS & PSC glossary links
* `Related Awards` section `Parent Award` link
* Links in the `Award ID` column of the `Awards that Reference this IDV` table
* Passing down `awardId` directly from the url params to ensure that the same value is used to create glossary links, because award pages accept either an internal id (e.g. `68891350`) or the generated unique id (e.g. `CONT_AW_3600_-NONE-_V246P00002_-NONE-`). 
* Kept `award_v2/` for the v2 Contract and Financial Assistance pages
[DEV-2233](https://federal-spending-transparency.atlassian.net/browse/DE …

Hotfix award links

---

src/js/components/awardv2/idv/referencedAwards/ReferencedAwardsTable.jsx

Fixes links to award summary pages in the IDV referenced awards table. 
Uses the award id that is compatible with the `awards/v1` endpoint to build the link. It was already available in the API response and model. 
[DEV-2233](https://federal-spending-transparency.atlassian.net/browse/DEV-2233) (Failed test) see comments.
**Mockup:**
N/A

Hotfix Referenced Award links

---

src/_scss/pages/awardV2/idv/_awardAmounts.scss
src/js/components/awardv2/idv/InfoTooltipContent.jsx
src/js/components/awardv2/visualizations/amounts/AggregatedAwardAmounts.jsx
src/js/components/awardv2/visualizations/amounts/charts/ExceedsCurrentChart.jsx
src/js/components/awardv2/visualizations/amounts/charts/NormalChart.jsx
src/js/helpers/aggregatedAmountsHelper.js
src/js/models/v2/awardsV2/BaseAwardAmounts.js
tests/helpers/aggregatedAmountsHelper-text.js
tests/models/awardsV2/BaseAwardAmounts-test.js

Implements the bar graph for the "Overspending" case in the IDV aggregate Award Amounts visualization. 
- Refactored variable names used for percentage calculations to reflect updated terminology in the visualization
- Added `overspending` and `overspendingFormatted` getters to the model. These will be negative and/or unused in other scenarios
- Perform a check for the situation where obligated amounts exceed current amounts and implements the corresponding bar graph. Subsequent PR will check for "Extreme overspend".
- Award id for an example of the overspend in dev: `69146930` 
[DEV-2357](https://federal-spending-transparency.atlassian.net/browse/DEV-2357), subtask for step 3 of …

Handle obligated exceeds current award amounts

---

src/_scss/pages/awardV2/idv/awardAmounts/_charts.scss

Fixes styling for the IDV Award Amounts visualization "Insufficient Data" message (noticed during demos)
Example in staging: https://staging.usaspending.gov/#/award/68862348 
[DEV-2224](https://federal-spending-transparency.atlassian.net/browse/DEV-2224)
**Mockup:**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/296009664_combinedAwardsSection--unavailable

Fixed insufficient data message styling

---

src/js/components/awardv2/visualizations/amounts/charts/ExceedsPotentialChart.jsx

Changes the IDV Award Amounts visualization extreme overspending label from "Exceeds Potential Award Amounts" to "Exceeds **Combined** Potential Award Amounts" per the mockup.
N/A
[DEV-2224](https://federal-spending-transparency.atlassian.net/browse/DEV-2224)
**Mockup:**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/296009663_combinedAwardsSection--overspend

Hotfix Exceeds Combined Potential label

---

src/_scss/pages/awardV2/idv/_awardFundingSummary.scss
src/js/components/awardv2/AwardV2.jsx
src/js/components/awardv2/idv/AwardHistory.jsx
src/js/components/awardv2/idv/FundingSummary.jsx
src/js/components/awardv2/idv/IdvContent.jsx
src/js/containers/awardV2/idv/AwardMetaDataContainer.jsx

Adding link to scroll to Award History Table and select accounts tab
Moved Award History active tab state to shared parent component `IdvContent` page from the `AwardHistory` component's local state
[DEV-2369](https://federal-spending-transparency.atlassian.net/browse/DEV-2369)
**Mockup:**
https://bahdigital.invisionapp.com/share/69IA8EPGPCM#/screens/296001079
**Commits:**
* a616c40 & d825e28 -- Adding `AwardHistoryTable` as a section to be jumped to
* 506eabd -- Passing the `jumpToSection` function to the Federal Spending Summary Page
* fec11f0 -- Moving activeTab state from one component to shared Parent component
* 4a45dea -- Adding styles

[DEV-2369] Adding Federal Account Funding Link on IDV Page

---

src/js/dataMapping/search/awardType.js

Display Subawards with IDV as Prime in the Advanced Search Spending by Sub-Award table.
The request to `api/v2/search/spending_by_award/` was sending `no intersection` for the award type codes filter because the award type codes mapped to the Sub-Contracts tab did not include IDV award types. This PR updates the mapping. 
[DEV-2362](https://federal-spending-transparency.atlassian.net/browse/DEV-2362)
**Mockup:**
N/A

Display Subawards with IDV as Prime in Advanced Search

---

src/js/dataMapping/search/awardType.js

On IDV Summary pages of type "Indefinite Delivery Contract / Definite Quantity", link to the new glossary definition. 
Updates the glossary slug used for award type code `IDV_B_C`. Award ID for an example of this type: `68876388` 
[DEV-2322](https://federal-spending-transparency.atlassian.net/browse/DEV-2322)
**Mockup:**
N/A

Update IDC / Definite Quantity glossary mapping

---

src/_scss/pages/awardV2/idv/awardAmounts/_dataTable.scss
src/_scss/pages/awardV2/visualizations/overview/_relatedAwards.scss
src/js/components/awardv2/AwardV2.jsx
src/js/components/awardv2/idv/IdvContent.jsx
src/js/components/awardv2/idv/referencedAwards/ReferencedAwardsSection.jsx
src/js/components/awardv2/visualizations/amounts/AggregatedAwardAmounts.jsx
src/js/components/awardv2/visualizations/overview/RelatedAwards.jsx
src/js/containers/awardV2/idv/ReferencedAwardsContainer.jsx
src/js/containers/awardV2/visualization/AwardAmountsContainer.jsx
src/js/dataMapping/awardsv2/referencedAwards.js
src/js/models/v2/awardsV2/BaseAwardAmounts.js
src/js/propTypes/index.js
tests/containers/awardV2/idv/ReferencedAwardsContainer-test.jsx
tests/models/awardsV2/BaseAwardAmounts-test.js
tests/models/awardsV2/mockAwardApi.js

This covers adding grandchildren to the Referenced Awards tables, Related Awards and Award Amounts sections of the IDV Summary page.
The `ReferencedAwardContainer` now has three tables `child_idvs` ( previously `idvs` ), `child_awards` ( previously `contracts` ), `grandchild_awards`.
The `BaseAwardAmounts` has been updated to use the new values from the API.
- `rollup_total_obligation` is now `child_award_total_obligation + grandchild_award_total_obligation`
- `rollup_base_exercised_options_val` is now `child_award_base_exercised_options_val + grandchild_award_base_exercised_options_val`
- `rollup_base_and_all_options_value` is now `child_award_base_and_all_options_value + grandchild_award_base_and_all_options_value` …

Dev-2418 IDV Summary Grandchildren

---

src/js/components/awardv2/idv/InfoTooltip.jsx

Adds new condition to handle edge case for tooltips -- when prop `wide` is true and parent component is full width
Adds a condition to see if the `window.innerWidth - tooltip.offsetLeft` is lower than anticipated (lower than 1/6 of the screen) to handle edge case of when tool tip is on a full width component and has the wide property set to true
[DEV-2458](https://federal-spending-transparency.atlassian.net/browse/DEV-2458)

[dev-2458] Quick fix for wide tooltips that were not showing properly on full width components

---

src/js/components/search/visualizations/geo/MapWrapper.jsx

Points the Congressional District layer of maps to a new MapBox tileset. 
- Updated once in the MapWrapper component, which applies to both Advanced Search and State Profile page maps. 
- The old congressional district tileset can be removed once this change has been deployed to production.
- There is a related ticket to investigate how the data is impacted by districts changing over time: [DEV-2572](https://federal-spending-transparency.atlassian.net/browse/DEV-2572)
[DEV-2400](https://federal-spending-transparency.atlassian.net/browse/DEV-2400)
**Mockup:**
N/A

Update congressional districts

---

src/js/containers/glossary/GlossaryContainer.jsx
src/js/helpers/glossaryHelper.js
tests/containers/glossary/GlossaryContainer-test.jsx

Migrating the following two endpoints to v2:
1. POST: `v1/references/glossary/autocomplete/` --> `v2/autocomplete/glossary/`
2. GET: `v1/references/glossary/?limit=500` --> `v2/references/glossary/?limit=500`
Significant refactoring was needed as behavior around `1` has changed. In `v1` of this endpoint we could pass an empty string and the response would contain all the references, in `v2` an empty string returns an empty response.
Now, in order to maintain the previous UX, we add a condition to check for an empty string in `performSearch` and `populateCache`.
If the search string is empty in `performSearch` we exit the method and call a new method, `populateGlossaryWithAllTerms`; if the search string is empty in `populateCache`, we …

[DEV-2430] Migrating to glossary API v2

---

src/index.html
src/js/helpers/analytics/Analytics.js

Adds a new Google Analytics tracking id to the site as requested by the analytics team.
- Also adds the tracker for testing environment that devs can use to test new GA events without skewing production data
- Changes the Analytics wrapper to allow logging to both DAP and the new (default) GA in prod
- See https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers
[DEV-2402](https://federal-spending-transparency.atlassian.net/browse/DEV-2402)
**Mockup:**
N/A

DEV-2402 Google Analytics

---

src/js/components/awardv2/idv/TooltipContent.jsx

Adds missing * in tooltip content in the Award Amount tooltips for Combined Current Award Amounts and Combined Potential Award Amounts.
--
[DEV-2324](https://federal-spending-transparency.atlassian.net/browse/DEV-2324)
**Mockup:**
https://bahdigital.invisionapp.com/share/NDIAADAZPUS#/296001079_Award_Summary_2-0_-_IDV_-future-

[dev 2324/typo] Adds missing * in tooltip content

---

src/js/containers/awardV2/idv/AwardMetaDataContainer.jsx
src/js/models/v2/awardsV2/FederalAccountSummary.js
tests/models/awardsV2/FederalAccountSummary-test.js

Update Federal Accounts ListView to handle negative percentages.
* update error for getAllFederalAccounts to effect treemap flight and error
* update percent to handle negative to n/a and zero obligated amount to zero percent
* update fed account summary model to test for those scenarios
[DEV-1937](https://federal-spending-transparency.atlassian.net/browse/DEV-1937)

Dev-1937 Hotfix Change Negative Percentage

---

src/js/dataMapping/awardsv2/longAwardTypeDescriptions.js
src/js/dataMapping/search/awardType.js

Updates the verbiage for three IDV Award types on the IDV Page and the Advanced Search Page
Updated two data maps on related to the IDV page, the other to the advanced search page.
`Indefinite Delivery, Definite Quantity Contract`
`Indefinite Delivery, Requirements Contract`
`Indefinite Delivery, Indefinite Quantity (IDIQ) Contract`
should be replaced respectively with....
`Indefinite Delivery / Definite Quantity Contract`
`Indefinite Delivery / Requirements Contract`
`Indefinite Delivery / Indefinite Quantity (IDIQ) Contract`
[DEV-2681](https://federal-spending-transparency.atlassian.net/browse/DEV-2681)

[DEV-2681] Updates the verbiage on IDV Page and the Advanced Search Page

---

src/js/components/awardv2/idv/InfoTooltipContent.jsx
src/js/components/awardv2/idv/amounts/charts/ExceedsCurrentChart.jsx
src/js/components/awardv2/idv/amounts/charts/ExceedsPotentialChart.jsx

Info tool tip previously used for exceeds current/potential award amounts is redundant
Removes info tool tip component
[DEV-2697](https://federal-spending-transparency.atlassian.net/browse/DEV-2697)
- ~[ ] Design review (if applicable)~ Not necessary per [this comment](https://federal-spending-transparency.atlassian.net/browse/DEV-2697) in JIRA

[Bug/dev-2697/obstructed tt] Removes redundant info tool tip

---

src/js/components/search/filters/location/LocationPicker.jsx
src/js/containers/search/filters/location/LocationPickerContainer.jsx

Fixes two issues:
- Loading Counties/districts for a state when the state is auto-populated by a city selection
- Allowing for selection of international city
- Tells componentDidUpdate to load counties/districts when state is automatically updated via city selection (42000a5)
- Only sets selected state automatically on city selection if it matches an actual state object in the states array. (930d1ba)
[DEV-2772](https://federal-spending-transparency.atlassian.net/browse/DEV-2772)

[DEV-2772] Hot-fix: City SearchFollow Up & Federal Accounts Tooltip

---

src/js/containers/search/filters/location/POPFilterContainer.jsx
src/js/containers/search/filters/location/RecipientFilterContainer.jsx

A performance concern was identified after a hotfix was delivered late in Sprint 84. This component was designed to be disabled via a prop for such a scenario.
The top-most City Search container was given boolean prop `enableCitySearch` which is now set to false.
This does two things:
1. Hides the city search component
2. Disables API call

[Hotfix] Disabling City Search in Staging

---

src/js/components/search/header/DownloadButton.jsx

Fixes a bug causing the download button to be clickable even though it appeared disabled. 
The `onClick` function was checking for `downloadAvailable` OR `!downloadInFlight` and by default evaluating to `true` because on initial load, a download is not in flight. This PR ANDs the two conditions. 
[DEV-2829](https://federal-spending-transparency.atlassian.net/browse/DEV-2829)
**Mockup:**
N/A

DEV-2829 Disable download button

---

README.md

Based on conversations with @MaxwellKendall , adding a couple Docker commands to build static artifacts and mount to a basic nginx container.
Also noticed travis links (and the beta site link) were dated.

fix travis links, add Docker command walkthrough

---

src/js/models/search/SearchAwardsOperation.js

API was returning inaccurate payload because `primary_place_of_performance_scope` / `recipient_location_scope` was being included in request object when `country !== 'USA'`
Changed condition for including this property in the request object from `country !== USA` to `country === foreign`
[DEV-2751](https://federal-spending-transparency.atlassian.net/browse/DEV-2751)

[DEV-2751] Advanced City Search only Includes *_scope property when country is "All Foreign countries"

---

src/_scss/pages/awardV2/idv/_awardFundingSummary.scss
src/js/components/awardv2/idv/federalAccounts/FederalAccountsSection.jsx

Simple mark up added to explain difference between the treemap and table view
Adds markup and SCSS.
[DEV-2735](https://federal-spending-transparency.atlassian.net/browse/DEV-2735)
**Mockup:**
https://bahdigital.invisionapp.com/share/ENIAAIY6K2P#/screens/296008376_Award_Summary_2-0_-_IDV_-Future-_-Fed_Acct_List_View-
**Screenshot:**

[DEV-2735] Note on Federal Accounts Section explaining difference between table/treemap view

---

src/js/containers/award/subawards/SubawardsContainer.jsx

Subawards table will not do infinite scroll because v2 api response payload changed from 
```javascript
{ page_metadata: { has_next_page: true } }
```
to 
```javascript
{ page_metadata: { hasNext: true } }
```
Updated parseResponse method to anticipate above response object shape.
[DEV-2916](https://federal-spending-transparency.atlassian.net/browse/DEV-2916)

[v2-subawards] updating has_next_page to hasNext per v2 response payload

---

src/_scss/pages/awardV2/idv/activity/idvActivity.scss

Fixes the spacing between IDV Activity legend items to match the mockup.
[DEV-2732](https://federal-spending-transparency.atlassian.net/browse/DEV-2732) (Failed test)
**Mockup:**
https://bahdigital.invisionapp.com/share/GVIAAHOBER9#/296001079_Award_Summary_2-0_-_IDV_-future-

IDV Activity legend spacing

---

src/js/components/search/filters/location/LocationPicker.jsx
src/js/containers/search/filters/location/LocationPickerContainer.jsx
tests/components/search/filters/location/LocationPicker-test.jsx
tests/containers/search/filters/location/LocationPickerContainer-test.jsx

2 things addressed in this PR: 
1. Auto-selecting a country after foreign city selection
2. Handling city de-selection on back space:
- If city-selection resulted in auto-population of country selection, then deselect country
- parseCountries changes `this.state.state`to now has property `autoPopulated`
- `this.selectEntity()` auto-selects country based when country selection is "All Foreign countries"
- All the rest of the updates are prettier updates (my bad!!)
- lots of logic in componentDidUpdate 
- Lots of unit tests for logic
[DEV-2904](https://federal-spending-transparency.atlassian.net/browse/DEV-2904)

[DEV-2904 & 2787] Auto-populate foreign country on city selection, handling city deselection as well

---

tests/models/awardsV2/BaseParentAwardDetails-test.js
tests/models/awardsV2/mockAwardApi.js

Adds simple test for baseParentAwardDetails.js mentioned in comment in PR #1145
Tests `populateCore` method
[DEV-2788](https://federal-spending-transparency.atlassian.net/browse/DEV-2788)

[DEV-2788] Adds test for base parent award details model file per comment in #1145

---

src/_scss/pages/awardV2/idv/activity/idvActivity.scss
src/js/components/awardv2/idv/activity/ActivityChartTooltip.jsx
src/js/containers/awardV2/idv/IdvActivityContainer.jsx
src/js/helpers/idvHelper.js
src/js/models/v2/awardsV2/BaseIdvActivityBar.js
tests/containers/awardV2/idv/IdvActivityContainer-test.jsx
tests/containers/awardV2/idv/mockIdvHelper.js
tests/models/awardsV2/mockAwardApi.js

https://federal-spending-transparency.atlassian.net/browse/DEV-2970
Add API Call to IDV Activity Chart
* update api call
* add tests
* update mock api
* update mock data
[DEV-2909](https://federal-spending-transparency.atlassian.net/browse/DEV-2909)

Dev-2909 IDV Activity Chart API Integration

---

src/js/containers/search/filters/location/LocationPickerContainer.jsx
tests/containers/search/filters/location/LocationPickerContainer-test.jsx

In Prod when searching by a city with commas, we are splitting the string by comma and only using the first part of the string before the first comma:
`strWithComma.split(", ")[0]`;
1. Still splitting city by comma as above, but now including all items in resulting array, except items in the array that are equivalent to `city.code` which is not necessary to include.
2. Re-ogranized the tests on the relevant class method `createLocationObject` to ensure each property on the return object is correct for each scenario: 
1. Searching by country
2. Searching by state
3. Searching by domestic/foreign city
4. Searching by county
5. Searching by congressional district
This was already being done but in a disorganized manner.
3. Refactored class method …

[DEV-3017] Searching for Cities with Commas & Refactor of Tests + Class Method 

---

src/js/components/awardv2/idv/federalAccounts/FederalAccountsSection.jsx

Federal Accounts tooltip was accidentally deleted, restoring it.
Reusing `InfoToolTip` and `federalAccountsInfo` tooltip content.
[DEV-2780](https://federal-spending-transparency.atlassian.net/browse/DEV-2780)
- N/A Design review

[dev-2780] restoring federalAccountsInfo tooltip

---

src/js/components/award/details/additional/ContractAdditionalDetails.jsx
src/js/models/v2/awards/BaseAwardRecipient.js
src/js/models/v2/awards/additionalDetails/BaseContractAdditionalDetails.js
tests/containers/award/mockResults.js
tests/models/awards/BaseAwardRecipient-test.js
tests/models/awards/additionalDetails/BaseContractAdditionalDetails-test.js
tests/models/awards/mockAwardApi.js

Updates the frontend to correctly parse the updated `api/v1/awards` response.
- Executive compensation fields will move from the `recipient.officers` object to `latest_transaction.contract_data` object.
- Example contract summary page: https://dev.usaspending.gov/#/award/25886979 > Additional Details tab > Executive Compensation section (should be no impact to end user)
- Note - no API contract for v1 endpoint
[DEV-3040](https://federal-spending-transparency.atlassian.net/browse/DEV-3040), subtask of [DEV-2923](https://federal-spending-transparency.atlassian.net/browse/DEV-2923)
**Mockup:**
N/A

New executive compensation response

---

src/_scss/elements/_buttons.scss
src/_scss/pages/about/_section.scss
src/js/components/about/AboutContent.jsx
src/js/components/about/Development.jsx

Adds a "Development and Releases" section to the About page.
- Utilizes the shared redirect modal component for links that point to sites outside the Fiscal Service domain.
- Adds a CSS mixin for buttons that look like links
**Mockup:**
https://bahdigital.invisionapp.com/share/MKIAAZFD7S9#/screens

Add Release Notes to About page

---

src/_scss/pages/search/filters/location/location.scss
src/js/components/search/filters/location/EntityDropdown.jsx
src/js/components/search/filters/location/EntityDropdownAutocomplete.jsx
src/js/components/search/filters/location/LocationPicker.jsx
src/js/components/search/filters/location/ZIPField.jsx
src/js/containers/search/filters/location/LocationPickerContainer.jsx

Adding new disclaimer to LocationPicker when a foreign country is selected and the Primary Place of Performance tab is active.
- Adds new logic to `generateMessage` for the appropriate disclaimer message
- Adds icon, shown conditionally, on autoComplete component.
[DEV-2878](https://federal-spending-transparency.atlassian.net/browse/DEV-2878)
**Mockup:**
https://bahdigital.invisionapp.com/share/ZWIAAZHCY5G#/screens/296016970/comments

[DEV-2878] Primary Place of Performance Foreign City Disclaimer

---

src/js/components/awardv2/shared/additionalInfo/RecipientDetails.jsx
src/js/components/awardv2/shared/overview/AgencyRecipient.jsx
src/js/models/v2/awardsV2/BaseAwardRecipient.js

Recipient Details Panel
- Adds Congressional District to the Recipient Address
- Displays `--` when no location information is available
- Displays `--` instead of `Unknown` in the panel when both recipient name and hash are null
Recipient Overview section
- Displays an unlinked name when recipient hash is null
- Displays `Unknown` when the recipient name is null
Follow up to [DEV-2740](https://federal-spending-transparency.atlassian.net/browse/DEV-2740) (Failed Test)
**Mockup:**
https://bahdigital.invisionapp.com/share/GVIAAHOBER9#/296001079_Award_Summary_2-0_-_IDV_-future-

Add Congressional District to Recipient Address

---

src/js/components/awardv2/idv/activity/ActivityChartTooltip.jsx

Tooltip PIID Link uses id.
Tooltip PIID Link uses id.
[DEV-2646](https://federal-spending-transparency.atlassian.net/browse/DEV-2646)

HotFix Dev-2646 PIID uses id

---

src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

Fixes loading a saved search via url hash. A bug is causing the advanced search page to load with a blank screen in production.
The function that creates the top filter bar tags is expecting Treasury Accounts and Federal Accounts to exist in the filter object, but those aren't returned by the API yet in the endpoint that converts url hashes to the filter object. This change check for the presence of the filters before trying to access their `count`. 
[DEV-3199](https://federal-spending-transparency.atlassian.net/browse/DEV-3199)
**Mockup:**
N/A

Production Hotfix loading a saved search via url hash

---

src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
src/js/containers/search/filters/programSource/ProgramSourceAutocompleteContainer.jsx

Fixes a bug that caused TAS Component autocomplete selections to get staged after being deleted from the text input.
Previously, `handleInputText` was only getting called if the input value was truthy, which prevented `clearSelection` from getting called when the entire value was deleted.
[DEV-3219](https://federal-spending-transparency.atlassian.net/browse/DEV-3219)
**Mockup:**
N/A

TAS Autocomplete Bug Fix

---

src/js/containers/explorer/detail/helpers/explorerQuarters.js
src/js/helpers/fiscalYearHelper.js
tests/containers/explorer/detail/helpers/explorerQuarters-test.js
tests/helpers/fiscalYearHelper-test.js

- Removes logic that delayed the release of FY 2019 Q1 due to the gov't shutdown
- Additional tests for dates just before and after the FY switchover (Sept 30 and Oct 1)
[DEV-1630](https://federal-spending-transparency.atlassian.net/browse/DEV-1630)

FY helper tests

---

src/js/containers/search/filters/location/LocationPickerContainer.jsx
src/js/models/search/SearchAwardsOperation.js
tests/containers/search/filters/location/LocationPickerContainer-test.jsx

When an invalid country code is associated with a city, the request object should include the country code returned in the api response, even though it does not match one of our availableCountries.
Adds a wrapper function to the return statement within `createLocationObject` that transforms the object's `.filter` property which is used to build the AwardSearch API Request object.
Changing the `locationObject.filter.country` property from `FOREIGN` to whatever `this.state.city.code` is.
This is an antipattern as we're overriding the local state, which should be the single source of truth in the component.
[DEV-3167](https://federal-spending-transparency.atlassian.net/browse/DEV-3167)
The following are ALL required for the …

[DEV-3167] Handling City Selection on Advanced Search for City with invalid Country Code

---

src/js/components/search/filters/location/EntityDropdown.jsx

Disabled drop down still registers click and throws a big error.
Added condition to onClick handler that only fires when dropdown is `enabled`.
[DEV-2988](https://federal-spending-transparency.atlassian.net/browse/DEV-2988)

[DEV-2988] Disabled EntityDropdown throws error onClick

---

src/js/components/awardv2/idv/activity/ActivityChartTooltip.jsx

IDV activity chart was not handling missing/null recipient hash (recipient_id).  Now, if the hash (id) is missing, the name will display (or `--` if the name is also missing).
[DEV-3184](https://federal-spending-transparency.atlassian.net/browse/DEV-3184)

DEV-3184: Allow activity tooltip to handle missing recipient hash

---

src/_scss/pages/awardV2/idv/_awardFundingSummary.scss
src/js/components/awardv2/idv/federalAccounts/FederalAccountsTree.jsx

- Removes extra "Federal Accounts" label from the IDV treemap
[DEV-2958](https://federal-spending-transparency.atlassian.net/browse/DEV-2958)
**Mockup:**
https://bahdigital.invisionapp.com/share/GVIAAHOBER9#/296001079_Award_Summary_2-0_-_IDV_-future-

Remove extra Federal Accounts label

---

src/js/components/awardv2/idv/activity/chart/ActivityChart.jsx
src/js/components/sharedComponents/VerticalLine.jsx

This PR will not display the Today Line when it's position is outside of the graphs date range.
- move line into own function due to the logic needed to display line
- move text into own function due to the logic needed to display text
- remove default values passed to increase reusability.
[DEV-2733](https://federal-spending-transparency.atlassian.net/browse/DEV-2733)

Hotfix Dev-2733 Today Line should not display when outside graph width

---

src/_scss/pages/search/filters/programSource/programSource.scss
src/js/components/search/filters/programSource/ProgramSourceSection.jsx
src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
src/js/containers/search/filters/programSource/ProgramSourceAutocompleteContainer.jsx

During testing, we noticed that the autocompletes seemed broken when there was a delay in fetching the results. This PR adds a `Loading...` message while the request is in flight.
[DEV-2940](https://federal-spending-transparency.atlassian.net/browse/DEV-2940)
**Mockup:**
N/A

Hotfix loading state for TAS autocompletes

---

src/js/components/search/filters/programSource/ProgramSourceSection.jsx
src/js/containers/search/filters/programSource/ProgramSourceAutocompleteContainer.jsx

- Makes the Availability Type Code autocomplete request case-insensitive
- Changes the `-` between BPOA and EPOA in filter tags to a `/`
- Fixes a bug that caused the input values to get cleared after a filter tag is removed, but the internal component state was not cleared
[DEV-3230](https://federal-spending-transparency.atlassian.net/browse/DEV-3230)
**Mockup:**
N/A

Case-insensitive Availability Type Code

---

src/js/components/awardv2/contract/ContractContent.jsx
src/js/models/v2/awardsV2/BaseAwardAmounts.js
src/js/models/v2/awardsV2/CoreAward.js
tests/models/awardsV2/BaseAwardAmounts-test.js
tests/models/awardsV2/BaseContract-test.js
tests/models/awardsV2/CoreAward-test.js
tests/models/awardsV2/mockAwardApi.js

The floats on the award amount section should only go to one decimal place on the label near the visualization. This was only happening for Contract Awards:
Adjusted the models CoreAward and BaseAwardAmounts as this was only happening for contract-awards. The IDV's & Grants were using the `BaseAwardAmount` model which produced the appropriate float values while the contract awards were using the `CoreAward` model which produced the inappropriate float values.
[DEV-1564](https://federal-spending-transparency.atlassian.net/browse/DEV-1564)
**Mockup:**
https://bahdigital.invisionapp.com/share/U9IAAWH7MA6#/296011639_Award_Summary_2-0_-_Contract

Hotfix/dev 1564/one decimal float

---

src/js/components/account/awards/LegacyResultsTable.jsx
src/js/components/keyword/table/ResultsTable.jsx
src/js/components/search/table/ResultsTable.jsx
src/js/components/search/table/cells/ResultsTableLinkCell.jsx
src/js/components/search/visualizations/rank/RankVisualization.jsx
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
src/js/models/v2/search/visualizations/rank/BaseSpendingByCategoryResult.js
tests/containers/search/visualizations/mockVisualizations.js
tests/containers/search/visualizations/rank/RankVisualizationWrapperContainer-test.jsx

Adds recipient links to Spending by Award and Spending by Category
- Changed `ResultsTableAwardIdCell` to a more robust `ResultsTableLinkCell` component
- Added the `linkSeries` array to hold `recipient_id`s in Rank Visualization components
- Updated the `BaseSpendingByCategoryResult` model to include recipient id
[DEV-872](https://federal-spending-transparency.atlassian.net/browse/DEV-872)
**Mockup:**
N/A
- N/A All `componentWillReceiveProps`, `componentWillMount`, and `componentWillUpdate` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA …

Dev-872 Advanced Search recipient links

---

src/js/components/awardv2/SummaryBarV2.jsx
src/js/containers/awardV2/AwardV2Container.jsx
src/js/dataMapping/awardsv2/awardTypes.js
src/js/helpers/downloadHelper.js
src/js/helpers/idvHelper.js
tests/containers/awardV2/AwardV2Container-test.jsx
tests/containers/awardV2/awardV2Helper.js
tests/models/awardsV2/mockAwardApi.js

Adds download functionality for non-idv award summary pages: contract, financial-assistance.
Calls new function that returns correct service call based on award type.
[DEV-3296](https://federal-spending-transparency.atlassian.net/browse/DEV-3296)
**Mockup:**

[DEV-3296] Implementing the Download button on AS2.0 pages

---

src/_scss/pages/awardV2/idv/activity/idvActivity.scss
src/js/components/awardv2/idv/activity/ActivityChartTooltip.jsx
src/js/components/awardv2/idv/activity/chart/ActivityChart.jsx

This adds a new Grandparent column to the first row of the IDV Activity Chart Bar Tooltip when the award bar is a grandchild. This will also truncate that first row on smaller screens.
Changed the `truncateText` function to `truncateLogic` and made it cleaner and easier to read by creating three new functions `truncatedWidth`, `truncatedCharacterLength` and `truncateText`, and then walking through those steps in the `truncateLogic` function. 
Additionally, the comments are updated to explain the ratios used and the reasons certain widths are set. 
[DEV-3171](https://federal-spending-transparency.atlassian.net/browse/DEV-3171)
**Mockup:**
https://bahdigital.invisionapp.com/share/SQIAB7ZZ6G5#/screens/296010428
The following …

Dev-3171 IDV Activity Chart Grandparent Tooltip

---

src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx

Removes sub-award recipient links from the Spending by Category table, since we don’t have sub-award data on those pages
Adds a check that the sub-award boolean is false before creating recipient links
[DEV-872](https://federal-spending-transparency.atlassian.net/browse/DEV-872)

Hotfix Spending by Category sub-award recipient links

---

src/js/components/awardv2/shared/federalAccounts/FederalAccountsTree.jsx

Fixes a bug causing table sorting to affect how the treemap was displayed.
The treemap now uses d3 `sort` to sort the cells by their `value`
[DEV-1662](https://federal-spending-transparency.atlassian.net/browse/DEV-1662) (Failed test)

Hotfix Award v2 Federal Accounts treemap sort

---

src/_scss/pages/awardV2/idv/awardAmounts/_charts.scss
src/js/components/awardv2/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
src/js/components/awardv2/shared/awardAmountsSection/charts/GrantChart.jsx
src/js/components/sharedComponents/TooltipWrapper.jsx

Previously, we weren't showing any non-federal-funding tool tips when the award had no non federal funding amount.
- Changed trigger event to `mouseOver` due to issues with bubbling (?).
- Changed hover area for tooltip triggering when non-federal-funding is zero
[DEV-3450](https://federal-spending-transparency.atlassian.net/browse/DEV-3450)
**Mockup:**

[DEV-3450] Grant Tooltips appear when non federal funding is zero

---

src/js/components/awardv2/idv/activity/ActivityChartTooltip.jsx

The IDV Activity Chart Tooltips now compare the first and second row widths when the tooltips are not being truncated due to the addition of the grandparent section the first row can now be longer than the second row.
Compare the first two rows of the IDV Activity Tooltip when not truncating.
[DEV-3171](https://federal-spending-transparency.atlassian.net/browse/DEV-3171)

Hotfix Dev-3171 tooltip idv activity

---

src/js/components/awardv2/idv/activity/chart/ActivityChart.jsx

The IDV Activity Chart will now show bars even if their width's are scaled to zero.
Added a check while generating the bar data to set the bar width to 1.5 if the width is < 1.5. This should allow users to be able to see the bars are smaller screens and still scale wider on larger screens
[DEV-3158](https://federal-spending-transparency.atlassian.net/browse/DEV-3158)
**Mockup:**
Is in this [ticket Dev-3389](https://federal-spending-transparency.atlassian.net/browse/DEV-3389)

Dev-3158 IDV Activity Chart Show Bars with Small Date Ranges

---

src/js/components/awardv2/contract/ContractContent.jsx
src/js/components/awardv2/idv/InfoTooltip.jsx
src/js/components/awardv2/shared/overview/RelatedAwards.jsx
src/js/models/v2/awardsV2/BaseContract.js

Award V2 Contract Pages have a Related Awards Section
Add Related Awards Section to Contract Content
Update tooltip logic in Related Awards Section 
[DEV-3098](https://federal-spending-transparency.atlassian.net/browse/DEV-3098)
**Mockup:**
Please refer to the ticket

Dev-3098 Award V2 Related Awards Section for Contracts

---

src/js/components/awardv2/shared/overview/RelatedAwards.jsx

Contracts will now show `Parent IDV` on the contracts page in the related awards section.
[DEV-3098](https://federal-spending-transparency.atlassian.net/browse/DEV-3098)

Dev-3098 Related Awards Verbiage for Contracts

---

src/_scss/pages/search/filters/programSource/programSource.scss

Moves the tooltip for "A note about our TAS data sources" to be centered over the info icon. 
[DEV-2724](https://federal-spending-transparency.atlassian.net/browse/DEV-2724) (Failed test)

[DEV-2724] Center TAS data tooltip over icon

---

src/js/components/search/filters/agency/ShownAgency.jsx
src/js/components/search/filters/awardAmount/SelectedAwardAmountBound.jsx
src/js/components/search/filters/awardID/ShownAwardID.jsx
src/js/components/search/filters/location/ShownLocation.jsx
src/js/components/search/filters/recipient/ShownRecipient.jsx
src/js/components/search/filters/timePeriod/DateRange.jsx

Fixes a bug preventing the `x` icon from displaying in staged filter tags. 
Transitions all components that leverage the `shown-filter-button` class to FontAwesome.
This bug was introduced by changes made for [DEV-2917](https://federal-spending-transparency.atlassian.net/browse/DEV-2917.
**Before**
**After**
- N/A All `componentWillReceiveProps`, `componentWillMount`, and `componentWillUpdate` in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3341](https://federal-spending-transparency.atlassian.net/browse/DEV-3341)

Fix staged filter styling

---

src/js/components/awardv2/shared/InfoTooltipContent.jsx
src/js/components/awardv2/shared/awardAmountsSection/AwardAmountsSection.jsx
src/js/components/awardv2/shared/awardAmountsSection/charts/ExceedsCurrentChart.jsx
src/js/components/awardv2/shared/awardAmountsSection/charts/ExceedsPotentialChart.jsx
src/js/components/awardv2/shared/awardAmountsSection/charts/GrantChart.jsx
src/js/components/awardv2/shared/awardAmountsSection/charts/NormalChart.jsx

- Adding Tooltip to Award amount section
- Only making IDV visualization tooltips from Chart wide. All others are narrow.
[DEV-2992](https://federal-spending-transparency.atlassian.net/browse/DEV-2992)

[DEV-2992] Adding infoTooltip for AwardAmounts Section and making other tooltips narrow

---

src/js/helpers/awardHistoryHelper.js

Changes count API requests from POST to GET
Was observing 5 requests per service call, realized it was supposed to be a GET not a POST. 
Was also getting 301s in google chrome, but not seeing any issues in SAFARI or FIREFOX... must be some weird google chrome thing?
Hitting the endpoints in POSTMAN with the request header from chrome returns a 200 everytime.
Relates to the award history section tickets:
[DEV-3099](https://federal-spending-transparency.atlassian.net/browse/DEV-3099)
[DEV-3100](https://federal-spending-transparency.atlassian.net/browse/DEV-3100)
[DEV-3101](https://federal-spending-transparency.atlassian.net/browse/DEV-3101)
**Mockup:**
The following are …

[count-endpoint-hotfix] POST --> GET

---

src/js/containers/search/filters/AgencyListContainer.jsx
src/js/models/v2/awardsV2/BaseContract.js
src/js/models/v2/awardsV2/BaseFinancialAssistance.js
src/js/models/v2/awardsV2/BaseIdv.js
tests/containers/search/filters/agencyFilter/AgencyListContainer-test.jsx
tests/containers/search/filters/agencyFilter/mockLocalSearch.js

Agency abbreviations are nullable.  Tweaks to prevent the word "null" from showing up when nulls are provided in the response.
[DEV-2752](https://federal-spending-transparency.atlassian.net/browse/DEV-2752)

DEV-2752: Allow nullable agency abbreviations

---

src/js/components/awardv2/shared/awardHistorySection/TablesSection.jsx

Shouldn't be requesting counts for Transactions/Federal Accounts if award type is IDV. New endpoints are required for this which have not been yet built.
If `award.category` is idv, not making a request for counts
[DEV-3099](https://federal-spending-transparency.atlassian.net/browse/DEV-3099)

[DEV-3099] Remove Count in AwardHistory Table for IDV Awards

---

src/js/components/award/details/DetailsTabItem.jsx
src/js/components/awardv2/shared/InfoTooltipContent.jsx
src/js/containers/awardV2/idv/IdvActivityContainer.jsx
src/js/containers/awardV2/idv/ReferencedAwardsContainer.jsx
src/js/containers/awardV2/shared/FederalAccountsSummaryContainer.jsx
src/js/containers/awardV2/shared/FederalAccountsVizContainer.jsx
src/js/models/v2/awardsV2/BaseFinancialAssistance.js
src/js/propTypes/index.js

- Removes console errors by adding componentWillUnmount methods
- 60fe320 -- Fixes issue where CFDA with 0 award amount was not being displayed due to truthy check on property with value of `0` evaluating to falsy. 
- 47aa99a -- adds tooltip copy
- Console errors fixed by CWUnmount 
- CFDA's with `total_funding_amount` of zero were not displaying because there was a truthy check on `total_funding_amount` which was evaluating to falsy.
- Still one console error occurring on the Award Summary 2.0 page due to componentDidMount lifecycle method firing twice -- once after render, once after componentWillUnmount -- wondering if the root cause of this is actually a routing issue?

Award Summary 2.0 Console Errors & Removing truthy check from CFDA Model

---

src/js/components/awardv2/AwardV2.jsx
src/js/dataMapping/search/awardType.js

Fixes the Glossary icon on Financial Assistance pages. 
Also updates the mapping for a few award type codes that were missing glossary urls.
[DEV-3714](https://federal-spending-transparency.atlassian.net/browse/DEV-3714)
**Testing**
Purchase Order: `/award_v2/23325224`
Project Grant: `award_v2/45824393`

DEV-3714 Fix financial assistance glossary links and data mapping

---

src/js/components/awardv2/idv/amounts/AggregatedAwardAmounts.jsx
src/js/components/awardv2/shared/awardAmountsSection/AwardAmountsSection.jsx
src/js/components/awardv2/shared/awardAmountsSection/charts/GrantChart.jsx
src/js/dataMapping/awardsv2/awardAmountsSection.js
src/js/helpers/awardAmountHelper.js
tests/helpers/awardAmountHelper-test.js

The Award Amount visualization was [not according to the mock](https://bahdigital.invisionapp.com/share/QMIAAWKND6B#/screens/295998954_Award_Summary_2-0_-_Grant).
10ea1a8 Refactored determineSpendingScenario logic to reflect the A/C in [3705](https://federal-spending-transparency.atlassian.net/browse/DEV-3705) and in anticipation of implementing this same design for the remaining financial-assistance type awards, which will use these new functions.
5de6552 conforming to mock up
e634738 adding tests
[DEV-3705](https://federal-spending-transparency.atlassian.net/browse/DEV-3705)
**Mockup:**
https://bahdigital.invisionapp.com/share/QMIAAWKND6B#/screens/295998954_Award_Summary_2-0_-_Grant
The following are ALL required for …

[DEV-3705] Updating Award Amount Visualization for Grant Awards

---

src/js/components/awardv2/contract/ContractContent.jsx
src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx
src/js/components/awardv2/idv/IdvContent.jsx
src/js/components/awardv2/shared/AwardPageWrapper.jsx
src/js/components/awardv2/shared/overview/AwardDates.jsx
src/js/containers/awardV2/AwardV2Container.jsx
src/js/dataMapping/awardsv2/descriptionsForAwardTypes.js
src/js/dataMapping/awardsv2/longAwardTypeDescriptions.js
src/js/models/v2/awardsV2/CoreAward.js
src/js/propTypes/index.js
tests/models/awardsV2/CoreAward-test.js

Page titles will now be sourced from a data object based on award type. Similar to the Advanced Search but differing when plural.
* remove long type description
* update long type description data mapping to include all awards, remove plurals, but leave IDV's that were there alone.
* add title to core award and tests
* update a bug in dates section to include insurance
[DEV-3094](https://federal-spending-transparency.atlassian.net/browse/DEV-3094)

Dev-3094 v2 Award Title

---

src/js/components/awardv2/shared/description/AwardDescription.jsx
src/js/components/awardv2/shared/description/LineTree.jsx
src/js/models/v2/awardsV2/BaseContract.js
tests/models/awardsV2/BaseContract-test.js
tests/models/awardsV2/mockAwardApi.js

Fixing two things from Ross' feedback:
1. Not including "SERVICES" header for PSC
2. Not including PSC Code for the first PSC item
0d2318f - removing SERVICES header
912c3b9 - not including PSC Code for first PSC Item and not sorting SERVICES header to top as it no longer exists 
[DEV-1663](https://federal-spending-transparency.atlassian.net/browse/DEV-1663)
**Mockup:**
Needs to be updated!

[DEV-1663] Updating PSC per PO Request - Removing "Services" header and first PSC Code

---

src/js/components/awardv2/AwardV2.jsx
src/js/components/awardv2/contract/ContractContent.jsx
src/js/components/awardv2/idv/IdvContent.jsx
src/js/models/v2/awardsV2/BaseContract.js
src/js/models/v2/awardsV2/BaseFinancialAssistance.js
src/js/models/v2/awardsV2/BaseIdv.js

Updating models so the `redux.awardsV2.overview.id` value can be used for all award types.
We were not passing the `id` property for assistance type awards b/c in the idv/contract awards the `id` property in `redux.awardsv2.overview` was actually the piid.
5948959 This updates the models so that the `piid` is stored in our models/redux specifically as the `piid` rather than as `id`. This allows us to store the `id` for asst type awards in our models and redux.
53ed392 Also refactored our use of `overview.id` in our components to `overview.piid`

Base Award Models now storing .id as apiData.id rather than apiData.piid

---

src/js/components/awardv2/AwardV2.jsx

Subawards table service call was being made with `""` value for awardId property in request object.
This was only happening for Asst type awards, root cause is we were passing different values as the `awardId` prop to `FinancialAssistanceContent.jsx` compared to `ContractContent.jsx` and `IdvContent.jsx`.
**Deeper Root Cause** 
A deeper root cause is arguably that in our IDV/Contract models, were are treating `redux.awardV2.overview.id` as the `piid` when in fact the api provides both a `piid` and an `id` value.
This is problematic because if `redux.awardV2.overview.id` is the `piid` then we cannot define an `redux.awardV2.overview.id` for asst type awards as they do not have a `piid`. 
I am opening another PR shortly to be more specific …

[Hotfix/awardid/subawards] Passing consistent value for AwardId from AwardV2 Container

---

src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx
src/js/components/awardv2/shared/awardHistorySection/TablesSection.jsx
src/js/dataMapping/awardsv2/awardHistorySection.js

Hides sections in FinancialAssistance awards that are specific to grants for non-grant awards.
Removed subaward tab via `.filter()`. There's an existing PR that should fix the tooltip content that was inaccurately showing grant specific info for non grant awards. This PR will have conflicts with that PR.
[DEV-3698](https://federal-spending-transparency.atlassian.net/browse/DEV-3698)

[DEV-3698] Hiding Subawards Tab and Grant Activity Section

---

src/js/components/agency/overview/AgencyOverview.jsx
src/js/components/search/filters/agency/SelectedAgencies.jsx
src/js/components/search/topFilterBar/filterGroups/AgencyFilterGroup.jsx

Trivial fix for certain agency values showing "null" instead of "not available".  Also found a couple of agency abbreviations not accounting for null.
[DEV-2752](https://federal-spending-transparency.atlassian.net/browse/DEV-2752)

DEV-2752: Display "not available" instead of "null" for missing agency values

---

src/js/components/awardv2/contract/ContractContent.jsx
src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx

Smoke testing AS2.0 in DEV saw that glossary links weren't working.
Link url was to awards_v2
[DEV-3439](https://federal-spending-transparency.atlassian.net/browse/DEV-3439)

[as2.0-glossary-links] glossary links were pointing to awards_v2

---

src/js/components/awardv2/subawards/SubawardsTable.jsx
src/js/models/v2/awardsV2/CoreAward.js
tests/models/awardsV2/CoreAward-test.js

Updates the Header text and percentage for the sub award tab in Award History.
[DEV-3778](https://federal-spending-transparency.atlassian.net/browse/DEV-3778)

Dev-3778 Sub Award Tab Summary in Award History

---

src/js/components/awardv2/shared/description/LineTree.jsx
src/js/models/v2/awardsV2/BaseContract.js
tests/models/awardsV2/BaseContract-test.js

I had a lot of confusion with this design for the PSC section of the Description section:
This PR ensures we show the `M: blah blah blah` line, which in staging is currently being replaced by Services.
The API is not returning the PSC Type but it is easily inferred based on the value of the `toptier_code` which in this case is `M` which translates to `SERVICES`.
- Model turns payload from API into new object with the new property `pscType` based on the top tier code
- If the `pscType` is R&D we treat this as a special case and do not show the `toptier_code` because it is always the same as the psc type
- If the pscType is not R&D we attempt to display all the different tier-types of the psc …

[DEV-1663] Displaying PSC Type and TopTier Code except for R&D where we only show type

---

src/_scss/pages/awardV2/awardPage.scss
src/js/components/awardv2/financialAssistance/FinancialAssistanceContent.jsx

Removes the bottom padding for non-grant financial assistance sections.
[DEV-3697](https://federal-spending-transparency.atlassian.net/browse/DEV-3697)

Dev-3697 Award Section Spacing

---

src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx

Changed the name of the cookie so that we're showing the banner to all users until they dismiss it.
Ensures users who had dismissed old info-banners are not missing out on this new one.
[DEV-3382](https://federal-spending-transparency.atlassian.net/browse/DEV-3382)
`N/A` Tagged Design, Testing, and Code Reviewers in `#us-ux-frontend` Slack Channel in the thread under the Post from Github for their SA
`N/A` Scheduled demo including Design/Testing/Front-end `if applicable`
`N/A` Provided instructions for testing in JIRA (for benefit of testing) and PR (for benefit of code reviewer) `if applicable`
`N/A` …

[hotfix] changing name of cookie so that all users will see the banner until they dismiss it

---

src/js/components/awardv2/shared/overview/AwardDates.jsx

Updates the dates section to display no labels when we do not know the award type.
Updates the dates section to display no labels when we do not know the award type.
[DEV-3094](https://federal-spending-transparency.atlassian.net/browse/DEV-3094)
**Testing**
1. Navigate to this url `http://localhost:3000/#/award/ASST_NON_PA26H084068-08S_8630`.
2. Verify the page is not broken and the no titles are displayed for the dates section.
- [N/A] All componentWillReceiveProps, …

Dev-3094 Dates Section Labels Empty Strings for Unknown Award Type

---

src/js/components/awardv2/shared/federalAccounts/FederalAccountsViz.jsx

Moves the federal account table button to the left of the tree-map button.
N/A
[DEV-3815](https://federal-spending-transparency.atlassian.net/browse/DEV-3815)
**Mockup:**
https://bahdigital.invisionapp.com/share/9EIABE5KQ24#/screens/296011639
- [N/A] All componentWillReceiveProps, componentWillMount, and …

Dev-3815 Federal Account Table Button is First

---

src/js/components/awardv2/AwardV2.jsx
src/js/components/awardv2/contract/ContractContent.jsx
src/js/components/awardv2/shared/overview/RelatedAwards.jsx

Adds the related awards section to the contracts v2 page.
* add counts from contract subawards to related awards section
* add subawards section for contracts
* dd another jumptosection for subawards tab in history table
* update post text
[DEV-3814](https://federal-spending-transparency.atlassian.net/browse/DEV-3814)
**Mockup:**
https://bahdigital.invisionapp.com/share/9EIABE5KQ24#/screens/296011639
- [N/A] [API …

Dev-3814 Contract Related Awards Section

---

src/js/helpers/awardAmountHelper.js
tests/helpers/awardAmountHelper-test.js

ASST awards did not have as robust logic as IDVs/Contracts. Adding more robust logic to ensure insufficientData is returned when charting is not currently suitable.
Cases added:
- When all spending categories are zero, return insufficient data
- If any single spending category is negative, return insufficient data
- Removing exceedsBigger case from line 86 of `determineSpendingScenario` b/c loans don't
actually handle exceedsBigger at this time and the logic will only bring us to line 86 if we're dealing with a loan where !allCategoriesAreInPlay
- Lots of tests are added to ensure the expected behavior
[DEV-3743](https://federal-spending-transparency.atlassian.net/browse/DEV-3743)
The following are ALL required for the PR …

[DEV-3743] refactoring spendingScenario logic to show N/A Chart in all scenarios 

---

src/_scss/pages/awardV2/awardFinancialAssistance.scss

Remove padding top from CFDA section header to keep space between sections and content consistent.

Warmfix Remove padding top cfda

---

src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx

Changes verbiage to nonFederalFunding tooltip

[warmfix-award-amounts-asst-tooltips] fixes non-federal funding tooltip

---

src/_scss/layouts/tabbedSearch/header/_downloadButton.scss

Adds more flex box to fix IE flexbog bug ❓ 
[DEV-3900](https://federal-spending-transparency.atlassian.net/browse/DEV-3900)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339)
`N/A` [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) …

[bug-dev-3836] fixes styles for download button in IE

---

src/js/components/search/table/ResultsTable.jsx

Adds link to go to the Parent or Prime Award Id page from advanced search.
`bodyCellRender` in `ResultsTable` component looks for column, handles case where id is truthy -- providing a link -- and falsy, providing a `N/A`
[DEV-3608](https://federal-spending-transparency.atlassian.net/browse/DEV-3608)
& [DEV-3490](https://federal-spending-transparency.atlassian.net/browse/DEV-3490)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers …

[FTR/DEV-3608] adding link to prime award id in SubAward Advanced Search

---

src/_scss/components/tooltips/_index.scss
src/js/components/awardv2/shared/awardAmountsSection/Tooltips.jsx

Style bug in Award Summary 2.0 tooltips w/ integration of component library tooltips. Only existed in Internet Explorer.
A 100% width and height was applied to the `first-of-type` divs under the tooltip-wrapper parent div.
This was only necessary for the tooltips inside the award amounts chart.
- Added a new class to these tooltips
- Scoped 100% width & height for first div to this new class
[DEV-4013](https://federal-spending-transparency.atlassian.net/browse/DEV-4013)
Author:
`N/A` …

[DEV-4013] Fixes Award Summary Tooltips in Internet Explorer

---

src/_scss/pages/awardV2/visualizations/overview/overview.scss
src/js/components/awardv2/financialAssistance/CFDAOverview.jsx
src/js/components/awardv2/shared/overview/AwardDates.jsx
src/js/components/awardv2/shared/overview/AwardingAgency.jsx
src/js/components/awardv2/shared/overview/Recipient.jsx
src/js/components/awardv2/shared/overview/RelatedAwards.jsx

Restores first iteration of PR #1419 w/ some added Internet Explorer polish to the new styles.
Adds `flex(1, 0 45%)` rather than ...50% for IE problems w/ calculating available width.
Author:
`N/A`All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item …

[DEV-1976] Adds spacing to items within the Award Overview Section, w/ IE polish

---

src/js/components/awardv2/idv/referencedAwards/ReferencedAwardsTable.jsx
src/js/components/awardv2/table/FederalAccountTable.jsx
src/js/components/keyword/table/ResultsTable.jsx
src/js/containers/explorer/detail/DetailContentContainer.jsx

Updating links to use the new human readable id.
Mostly updating the `parseApiCallResponse` methods to replace relevant result-storage-objects with the `generated_internal_id` value.
[DEV-3967](https://federal-spending-transparency.atlassian.net/browse/DEV-3967)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant …

[DEV-3967] Award page links use new generated_internal_id

---

src/js/components/awardv2/shared/overview/AwardOverviewLeftSection.jsx
src/js/components/awardv2/shared/overview/Recipient.jsx

Actually provides the Recipient location to the component.
**Mockup:**
Author:
- [N/A] Added Unit Tests …

Warm Fix Dev-1976 Recipient Location

---

package-lock.json
package.json

Removes the USWDS NPM package.
* removes USWDS npm package
* There is a jQuery bundle in out static S3 bucket that our app references.  I initially did not know where this jQuery was coming from but looking at the bundles in the bucket I thought it was coming from bootstrap. On further investigation, there were four references to jQuery in our package lock. Three of them were from the jQuery package and one was from the USWDS dependencies.  I initially upgraded the USWDS package from 0.13.1 to 1.6 which removed jQuery altogether. After consulting the front-end team, we thought we were not using USWDS anywhere. This PR removes the USWDS dependency. I took a quick look locally and in sandbox and did not notice any changes. …

Ops-908 Remove Jquery by Removing USWDS

---

package-lock.json
package.json

Corresponding documentation [here](https://github.com/fedspendingtransparency/data-transparency-ui/pull/20)

[data-transparency-ui] migrating to semver for data-transparency-ui dependency

---

src/js/components/search/filters/programSource/ProgramSourceSection.jsx
src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

Uncaught exception was being thrown in console, resulting in page reload and redirect back to home page:
`value is not an iterable...` or something to that effect.
Identified the root cause as the method call `.keys()` on an immutable map. Appears that IE 11 is not supported by immutablejs? Not sure, but that appears to be the case at least with the `.keys` method.
[DEV-3836](https://federal-spending-transparency.atlassian.net/browse/DEV-3836)
Author:
`N/A` Added Unit Tests for methods in Container …

[DEV-3836] Bug in IE when using TAS section of Advanced Search

---

src/js/containers/award/AwardContainer.jsx
src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
src/js/containers/bulkDownload/modal/BulkDownloadBottomBarContainer.jsx
src/js/containers/keyword/KeywordContainer.jsx
src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx
src/js/redux/actions/bulkDownload/bulkDownloadActions.js
tests/containers/bulkDownload/mockData.js
tests/containers/bulkDownload/modal/BulkDownloadBottomBarContainer-test.jsx
tests/containers/search/modals/fullDownload/DownloadBottomBarContainer-test.jsx
tests/containers/search/modals/fullDownload/mockFullDownload.js
tests/models/awardsV2/mockAwardApi.js

The response for the different download endpoints was updated and as a result, some fields were added and others had their names changed. This PR is to make the necessary changes to work with the new download endpoint responses.
All changes are to change `url` to `file_url` since there is now a `file_url` and a `status_url` on the `/api/v2/download/<type>/` endpoints.
Sample Old Response:
```{
"status": "ready",
"url": "https://files-nonprod.usaspending.gov/generated_downloads/dev/IDV_UNKNOWN_2020-01-10_H18M46S31395245.zip",
"message": null,
"file_name": "IDV_UNKNOWN_2020-01-10_H18M46S31395245.zip",
"total_size": null,
"total_columns": null,
"total_rows": null,
"seconds_elapsed": null
}
```
Sample New Response:
```
{
"status_url": …
```

[DEV-4121] Change url to file_url for download response

---

src/_scss/components/_pageLoading.scss
src/_scss/pages/award/awardPage.scss
src/js/components/award/Award.jsx
src/js/components/award/SummaryBar.jsx
src/js/components/sharedComponents/Footer.jsx
src/js/components/sharedComponents/Loading.jsx
src/js/containers/award/AwardContainer.jsx

Bugs were coming from this behavior, discovered it to be caused by setting `inFlight` from true to false within an AwardContainer method called by compoentDidMount. Render() was hiding the child component based on this property, triggering an unMount on didMount.
Changed default local state for inflight in container from true to false
Added styles / new component for Loading state
[DEV-4100](https://federal-spending-transparency.atlassian.net/browse/DEV-4100)
**Mockup:**
Discussed with design roll out of `Loading...`; also added styles so the content takes up the whole viewport during loading state using flex box.
Author:
`N/A` Verified that this PR does not create …

[DEV-4100] Award V2 Page Un-mounts then re-mounts due to boolean local state property changing on Mount

---

webpack/webpack.common.js

Accidentally removed code that copies the robot.txt file into the public/ folder.

[DEV-4036] adding robots.txt back to webpack copy plugin

---

pull_request_template.md

Adds line item for updating a status report -- made up of a list of check-boxes for every instance of a component -- in github.
This report needs to be up to date as it is visible on the Introduction Page of storybook (At the bottom):

[PR-Checklist-Update] Checkbox for updating component-library integration status report

---

src/js/dataMapping/awards/awardOverview.js
src/js/models/v2/CoreLocation.js
tests/models/CoreLocation-test.js

Uses state property for contract and idvs for foreign recipients when showing the recipient address in the overview section on the award page.
Reviewer(s):

Warm Fix Dev-1976 provide state for foreign contracts

---

scripts/buildSitemap.js
src/_scss/pages/recipient/recipientPage.scss
src/_scss/pages/state/statePage.scss
src/js/components/recipient/RecipientContent.jsx
src/js/components/recipient/RecipientPage.jsx
src/js/components/recipientLanding/table/RecipientLinkCell.jsx
src/js/components/sharedComponents/sidebar/Sidebar.jsx
src/js/components/state/RecipientFYPicker.jsx
src/js/components/state/StateContent.jsx
src/js/components/state/StatePage.jsx
src/js/containers/recipient/RecipientContainer.jsx
src/js/containers/router/RouterRoutes.js
src/js/containers/state/StateContainer.jsx
src/js/dataMapping/recipients/fiscalYearDropdown.js
tests/containers/recipient/RecipientContainer-test.jsx
tests/containers/recipient/mockData.js
tests/containers/state/StateContainer-test.jsx
tests/containers/state/mockData.js

FY Selector is updated via url param.
- Adds to didMount the call to look for the url param; onClick handler in FY Selector now updates both redux and url.
- Reuses Award Page Loading indicator that has icon and dynamic dots (...)
- Updates sitemap script to append `/latest` to state and recipient sitemap pages
[DEV-3942](https://federal-spending-transparency.atlassian.net/browse/DEV-3942)
Author: …

[DEV-3942] Setting FY Dropdown via URL (part 2 - State Page) (Contains Pt. 1)

---

src/js/components/recipient/RecipientContent.jsx
src/js/components/recipientLanding/table/RecipientLinkCell.jsx
src/js/components/sharedComponents/sidebar/Sidebar.jsx
src/js/components/state/RecipientFYPicker.jsx
src/js/containers/recipient/RecipientContainer.jsx
src/js/containers/router/RouterRoutes.js
src/js/dataMapping/recipients/fiscalYearDropdown.js
tests/containers/recipient/RecipientContainer-test.jsx
tests/containers/recipient/mockData.js

Sets the FY Dropdown selection based on URL
Adds new route to include `:fy` param and redirects users to new url if need be
[DEV-3194](https://federal-spending-transparency.atlassian.net/browse/DEV-3194)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle methods](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) per [JIRA item 3339](https://federal-spending-transparency.atlassian.net/browse/DEV-3339) …

[DEV-3194] Setting FY Dropdown via URL (part 1 - Recipient Page)

---

src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
tests/containers/state/StateContainer-test.jsx
tests/containers/state/mockData.js

All awards w/ subaward tab, when clicked on subaward link from advanced search, should go to prime award page and scroll to subaward
Removes conditional that checks award type, this is unecessary as the boolean prop from redux will only be true if the sub-award link was clicked; this link will not appear for awards that dont have a subaward tab
[DEV-4100](https://federal-spending-transparency.atlassian.net/browse/DEV-4100)
Author:
`N/A` Added Unit Tests for methods …

[DEV-4100] removes unnecessary conditional from subaward scroll fn

---

src/js/components/award/contract/ContractContent.jsx
src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
src/js/containers/award/AwardContainer.jsx
src/js/dataMapping/awards/awardHistorySection.js
tests/containers/award/AwardContainer-test.jsx

Ensuring that only awards w/ subaward tab scroll on subaward id click.
- Adds check to useEffect for award category to be either contract/grant
- Resets award redux state on unMount to prevent false positive on second condition above in useEffect
[DEV-4100](https://federal-spending-transparency.atlassian.net/browse/DEV-4100)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers …

[DEV-4100] Adding Conditional Back & Resetting Redux Award Namespace on unMount

---

src/js/components/award/idv/amounts/AggregatedAwardAmounts.jsx
src/js/components/award/idv/amounts/AwardAmounts.jsx
src/js/components/award/shared/awardAmountsSection/AwardAmountsSection.jsx
src/js/components/award/shared/awardAmountsSection/AwardAmountsTable.jsx
src/js/containers/award/idv/IdvAwardAmountsSectionContainer.jsx
src/js/dataMapping/awards/awardAmountsSection.js
src/js/helpers/awardAmountHelper.js
src/js/models/v2/awardsV2/BaseAwardAmounts.js
src/js/propTypes/index.js
tests/models/awardsV2/BaseAwardAmounts-test.js

IDV Awards have two sets of data related to spending:
(a) Aggregated spending across all child and grand child awards
(b) Spending that is directly associated with the IDV and not its children
This complexity is currently not reflected in our models. This manifests itself on the IDV Award Page, in the Award Amounts Section, on the "This IDV" tab.
The problem is we're only showing our aggregated spending on the IDV, and not for the IDV itself.
Updates BaseAwardAmounts Model:
- Currently, model for IDV gets obligated, current, and potential award amounts from child/grand child awards
- Now, we do the same thing but have a new method to override the _obligated/current/potential amounts from the aggregated amount, to the amounts for the IDV …

[DEV-3789] Adding fn to BaseAwardAmounts model

---

scripts/buildSitemap.js

We are using the wrong parent tag for our indexed sitemap. 
[This documentation](https://support.google.com/webmasters/answer/75712?hl=en&ref_topic=4581190) shows the correct syntax for an indexed sitemap. Previously, we were using the same syntax as non-indexed sitemaps.
`indexedSiteMap`: sitemap.xml
Correct Parent tag:   <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
Current Parent tag is `urlset` which is the same as the other sitemaps which are not indexed.
[DEV-4036](https://federal-spending-transparency.atlassian.net/browse/DEV-4036)
Author:
`N/A` Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA …

[DEV-4036] Fixes XML Syntax for indexed sitemap

---

src/js/components/recipient/modal/table/RecipientModalTable.jsx
src/js/containers/recipient/RecipientContainer.jsx
src/js/containers/state/StateContainer.jsx
src/js/dataMapping/awards/additionalDetailsContract.js
src/js/dataMapping/awards/additionalDetailsFinancialAssistance.js
src/js/dataMapping/awards/additionalDetailsIdv.js
tests/containers/recipient/RecipientContainer-test.jsx
tests/containers/state/StateContainer-test.jsx

- State Page (DEV-3942): Updating the url manually, specifically the fy url param (state/stateId/fyparam --> state/01/latest|2019|etc/
- Recipient Page: Updating child recipient links
947793a - State Page: Adds logic to componentDidUpdate to handle this case when only the fy url param is updated
b810b19 - Recipient Page: Updates links
[DEV-3942](https://federal-spending-transparency.atlassian.net/browse/DEV-3942)
[DEV-3194](https://federal-spending-transparency.atlassian.net/browse/DEV-3194)
Author: …

[DEV-3942 && DEV-3194] Refactors componentDidUpdate to handle update to fy url param and updates links

---

src/js/components/sharedComponents/IBTable/components/TableBody.jsx

This was causing the table header to be read twice by the screen reader when in table cells.
Screen readers can read the header cell without the need for an `aria-describedby` attribute. The additional`aria-describedby` causes the header cell to be read a second time by screen readers. Below are screenshots showing Mac OS X's VoiceOver screen reader behavior before and after this change.
Before:
After:
N/A
**Mockup:**
N/A
Author:
- `N/A` Linked to this PR in JIRA ticket
- `N/A` Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- `N/A` Verified cross-browser compatibility
- `N/A` Verified …

Remove redundant aria-describedby

---

src/_scss/pages/bulkDownload/form/_downloadButtons.scss
src/_scss/pages/bulkDownload/form/downloadForm.scss
src/js/components/bulkDownload/accounts/AccountDataContent.jsx
src/js/components/bulkDownload/accounts/UserSelections.jsx
src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx
src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js
tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
tests/containers/bulkDownload/mockData.js
tests/redux/reducers/bulkDownload/bulkDownloadReducer-test.js

Allows user to select mutliple values for file type. These used to be radio buttons, they are now checkboxes as seen below:
A few places required updates:
fdcf402 Reducer now storing an array in redux, was previously storing a single string value
a4de17b Container now making service call w/ an array of values for this property
e44a761 Validation Logic (component level): invalid state of form is now when the length of the array is 0; previously this logic checked for an empty string resulting in a falsey value.
9c1d0a1 Displaying current selections: To display user selections at the bottom of the form, we now are expecting an array of strings rather than just a single string.
4fab5d9 changing class names to reflect shared styles between …

[DEV-4329] Download Account Page now Accepts Array / Checkboxes for submissionTypes

---

src/_scss/pages/agency/v2/index.scss
src/_scss/pages/award/_comingSoon.scss
src/_scss/pages/glossary/glossaryPage.scss
src/js/GlobalConstants.js
src/js/components/sharedComponents/sidebar/Sidebar.jsx
src/js/containers/agency/AgencyContainer.jsx
src/js/containers/agency/AgencyContainerV2.jsx
src/js/containers/router/RouterRoutes.js
tests/containers/agency/v2/AgencyContainerV2-test.jsx

just merge the other one which contains this one; opening this to make review a bit less overwhelming
Lays out CSS / Scaffolding of Page.
Reuses logic for 
(A) detecting active section of page per the scroll position
(B) Jumping to Page
(C) Tooltips
(D) Coming Soon Styles
Seeking feedback for areas to improve reducing duplicate styles!
[DEV-4373](https://federal-spending-transparency.atlassian.net/browse/DEV-4373)
[DEV-4369](https://federal-spending-transparency.atlassian.net/browse/DEV-4369)
**Mockup:**
Author:
`N/A` API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/a …

[DEV-4373 & DEV-4369] Agency Profile Page V2, iteration 1 (Scaffolding + Navigation)

---

scripts/buildSitemap.js
src/js/containers/explorer/detail/DetailContentContainer.jsx
src/js/containers/keyword/KeywordContainer.jsx
src/js/containers/keyword/table/ResultsTableContainer.jsx
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/models/v2/awardsV2/BaseAwardAmounts.js
src/js/models/v2/awardsV2/BaseFederalAccountFunding.js
src/js/models/v2/awardsV2/BaseIdvActivityBar.js
src/js/models/v2/awardsV2/BaseParentAwardDetails.js
src/js/models/v2/awardsV2/BaseReferencedAwardResult.js
src/js/models/v2/awardsV2/CoreAward.js

Not all Unique Award ID URLs don't work; ie, if an award id has a `/` or a `.`
This is because we were using `encodeURI` but should've been using `encodeURIComponent`. The latter encodes everything; the former expects a url and therefore does not encode everything, as the naming implies
[DEV-3994](https://federal-spending-transparency.atlassian.net/browse/DEV-3994)
**Mockup:**
Author:
`N/A` Added Unit Tests for …

[DEV-3994] EncodeURI -->  encodeURIComponent

---

src/_scss/pages/agency/v2/index.scss
src/_scss/pages/bulkDownload/form/_fyPicker.scss

Z Index of sankey was higher than that of the tooltip, so it was hidden in internet explorer.
Lowered index of sankey z-index.
[DEV-4373](https://federal-spending-transparency.atlassian.net/browse/DEV-4373)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …

[DEV-4373] Lowering value of z-index for sankey

---

src/js/containers/keyword/table/ResultsTableContainer.jsx
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/helpers/apiRequest.js
tests/containers/explorer/detail/DetailContentContainer-test.jsx
tests/containers/explorer/detail/mockData.js
tests/containers/keyword/mockResults.js
tests/containers/keyword/table/ResultsTableContainer-test.jsx
tests/containers/search/table/ResultsTableContainer-test.jsx
tests/containers/search/table/mockAwards.js
tests/helpers/apiRequest-test.js
tests/mockData.js
tests/models/awardsV2/BaseAwardAmounts-test.js
tests/models/awardsV2/BaseFederalAccountFunding-test.js
tests/models/awardsV2/BaseParentAwardDetails-test.js
tests/models/awardsV2/BaseReferencedAwardResult-test.js
tests/models/awardsV2/CoreAward-test.js

In the context of a post request, we should be `decoding` the generated_unique_award_ids that are encoded in our models.
API expects raw/non-ecoded award ids in post requests.
Also added a bunch of tests to document how we are supposed to handle these values in every context.
[DEV-4504](https://federal-spending-transparency.atlassian.net/browse/DEV-4504)
Author:
`N/A` Verified that this PR does not create any *new* accessibility issues (via Axe …

[DEV-4504] decoding award IDs on POST request Objects, adding tests for every case

---

.gitignore
src/js/containers/bulkDownload/accounts/AccountDataContainer.jsx
src/js/containers/bulkDownload/archive/AwardDataArchiveContainer.jsx
src/js/containers/bulkDownload/awards/AwardDataContainer.jsx
tests/containers/bulkDownload/mockBulkDownloadHelper.js

Minor tweak to provide new parameter for `list_agencies` endpoint and to remove an unused response array.
[DEV-3932](https://federal-spending-transparency.atlassian.net/browse/DEV-3932)
Author:
Reviewer(s):

[DEV-3932] Adjust download agency list

---

src/js/containers/bulkDownload/accounts/AccountDataContainer.jsx
src/js/helpers/bulkDownloadHelper.js
tests/containers/bulkDownload/accounts/AccountDataContainer-test.jsx

This list was only requesting the first page of results.
Refactors container method to accept param `page`. If page param is greater than 1, append to existing state.
This is a recursive function which calls itself if  `data.hasNext` is true. In this case, the fn calls itself w/ `page + 1` until `hasNext` is false.
Added unit test to ensure that class method appends existing state when the container method is passed a the page param > 1.
[DEV-3999](https://federal-spending-transparency.atlassian.net/browse/DEV-3999)
Author:
`N/A`Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
`N/A` Verified …

[DEV-3999] Download Center, Custom Account Data, Paginate Federal Account List

---

src/_scss/pages/explorer/detail/sidebar/_fyPicker.scss

2017 not click able in spending explorer fy drop down
z index is lower than the button underneath it
[DEV-4516](https://federal-spending-transparency.atlassian.net/browse/DEV-4516)
Author:
`N/A` All componentWillReceiveProps, …

[DEV-4516] spending explorer dropdown 2017 not clickable

---

src/js/components/award/shared/overview/AwardingAgency.jsx
src/js/dataMapping/awards/additionalDetailsContract.js
src/js/dataMapping/awards/additionalDetailsFinancialAssistance.js
src/js/dataMapping/awards/additionalDetailsIdv.js
src/js/models/v2/awardsV2/BaseContract.js
src/js/models/v2/awardsV2/BaseFinancialAssistance.js
src/js/models/v2/awardsV2/BaseIdv.js
src/js/models/v2/awardsV2/CoreAwardAgency.js
tests/containers/award/shared/AwardingAgencyContainer-test.jsx
tests/models/awardsV2/CoreAwardAgency-test.js
tests/models/awardsV2/mockAwardApi.js

Today, when an award is viewed that was awarded by an agency that has no agency page in USAspending, users are taken to a 404 page when they click on the agency link. This pull request aims to rectify that.
[DEV-3935](https://federal-spending-transparency.atlassian.net/browse/DEV-3935)
Author:
Reviewer(s):

[DEV-3935] Prevent linking to agencies without agency pages

---

src/js/components/glossary/definition/GlossaryDefinition.jsx

Fixed glossary share button order
Fixed the order of the glossary share button.
[DEV-4211](https://federal-spending-transparency.atlassian.net/browse/DEV-4211)
Author:
Reviewer(s):

Warmfix DEV-4211 glossary share button order

---

src/js/components/award/shared/overview/RelatedAwards.jsx
src/js/dataMapping/awards/additionalDetailsContract.js
src/js/dataMapping/awards/additionalDetailsIdv.js
src/js/models/v2/awardsV2/BaseParentAwardDetails.js
tests/models/awardsV2/BaseParentAwardDetails-test.js
tests/models/awardsV2/mockAwardApi.js

Makes minor changes to the Contract and IDV Awards pages.
Changes:
- Change `Parent IDV` to `Parent Award` in Related Awards section
- Change `Parent IDV PIID` to `Parent Award ID` in Parent Award Details section
- Change `Parent IDV Agency Name` to pull from the toptier agency, not the subtier, also links to agency profile page
- Add `Parent IDV Sub-Agency Name`, which uses the subtier agency previously under `Parent IDV Agency Name` 
[DEV-3839](https://federal-spending-transparency.atlassian.net/browse/DEV-3839)
**Mockup:**
https://bahdigital.invisionapp.com/share/3KIABNW4PGR#/screens/296008376
Author:
Reviewer(s):

[DEV-3839] Contract/IDV Award page details tweaks

---

src/js/components/search/filters/naics/SelectedNAICS.jsx

Broke the old/existing selectedNaics filter component. Reverting those changes.
Restoring this change: https://github.com/fedspendingtransparency/usaspending-website/pull/1541/files?file-filters%5B%5D=.jsx&hide-deleted-files=true#diff-38fd6a4622d1491a90a800975a23de9f
Reviewer(s):
`N/A` [API #1234](https://github.com/fedspendingtransparency/usaspending-api/pull/1234) merged concurrently `if applicable`

[DEV-3483] Resotring existing selectedNAICS component

---

src/js/containers/search/filters/naics/NAICSContainer.jsx
src/js/helpers/checkboxTreeHelper.js
src/js/redux/actions/search/naicsActions.js
tests/containers/search/filters/naics/NAICSContainer-test.jsx
tests/containers/search/filters/naics/mockNaics_v2.js
tests/helpers/checkboxTreeHelper-test.js

Adding some more unit tests for different scenarios in the NAICS Search Tree.
- `cleanNaicsData` which maps the api object to the shape necessary for the checkbox tree component
- `addSearchResultsToTree` which does three things
1. removes / adds placeholder children when necessary
2. doesn't overwrite existing children
3. add's hide class to non-search result nodes
[DEV-3483](https://federal-spending-transparency.atlassian.net/browse/DEV-3483)
Reviewer(s):

[DEV-3483] Adding more Unit Tests for the NAICS Search Tree

---

src/js/components/search/filters/awardAmount/AwardAmountSearch.jsx

Fix a bug where a user is not able to input a custom award amount.
While working on DEV-4430 to update the Custom Award Download a change was made to the PrimaryCheckboxType and SecondaryCheckboxType with how it passes the updated value(s) to the reducer in order to update the store. This change allowed for the two checkbox types to pass additional information to the Custom Award Download reducer with minimal changes to other components that use the checkbox types. It was missed that the custom input for Award Amount had a separate call to its reducer outside of the checkbox and thus the reducer was getting two different formats for its input. This PR makes a minor change to normalize the inputs to be `{ value: …

Fix custom award amount input

---

src/js/helpers/checkboxTreeHelper.js
tests/helpers/checkboxTreeHelper-test.js

In a unit test only pr, that changed a single line of code, there was a bug where a conditional was evaluating to true when the relevant variables had values of `undefined`. The only reason this slipped under the radar is because we are using the `?` chain operator to traverse an undefined object.
Adds truthy/falsy evaluations to conditional for relevant variables.
[DEV-3483](https://federal-spending-transparency.atlassian.net/browse/DEV-3483)
**Mockup:**
Author:
`N/A` Verified cross-browser …

[DEV-3483] removes bug introduced by unit test pr that changed one line of code

---

src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx

Fix the ability to select all foreign countries as a location selected on the Custom Award Download page.
While testing DEV-4430 it was noticed that this functionality was already broken due to how the location filter handles the value of `FOREIGN`. To fix this the scope filter is used when a user selects all foreign countries.
[DEV-4430](https://federal-spending-transparency.atlassian.net/browse/DEV-4430)
**Mockup:**
N/A
Author:
Reviewer(s):

[DEV-4430] Warmfix all foreign countries selection for custom award download

---

src/js/components/award/table/TransactionsTable.jsx
src/js/components/award/table/cells/TransactionTableHeaderCell.jsx
src/js/containers/award/table/TransactionsTableContainer.jsx
src/js/dataMapping/financialAssistance/financialAssistanceTransactionTable.js
src/js/models/v2/awards/transactions/BaseAssistanceTransaction.js
src/js/models/v2/awards/transactions/CoreTransaction.js
tests/models/awards/transactions/BaseTransactions-test.js
tests/models/awards/transactions/CoreTransaction-test.js

- Adds row containing CFDA Number to the transactions table on the award summary pages
- Tightens up horizontal spacing in transactions table
- Added CFDA number to CoreTransaction and BaseAssistanceTransaction
- Switches between assistance and contract (and loan) tables in TransactionTableContainer
- Switches between contract table mapping and assistance table mapping in TransactionTableHeaderCell when the contract table mapping returns null. 
[DEV-3478](https://federal-spending-transparency.atlassian.net/browse/DEV-3478)
Author:
Reviewer(s):

[DEV-3478] add cfda column to assistance transaction tables

---

src/js/components/bulkDownload/dictionary/DataDictionary.jsx

Track clicks of data dictionary download
Adds event w/ similar event category to other download center actions
`USAspending - Download Center - Data Dictionary`,
action: `download`
[DEV-4606](https://federal-spending-transparency.atlassian.net/browse/DEV-4606)
Author:
`N/A` Added Unit Tests for methods in Container Components, reducers, and …

[DEV-4563] Google Analytics for downloading Data Dictionary

---

src/js/components/bulkDownload/awards/UserSelections.jsx

Display text in the UserSelection component for when the `All` option is selected. Also, change the font for country selection to match other selections.
Use the same CSS class for the country and state selection. Also, add conditional to display `All` when appropriate.
[DEV-4430](https://federal-spending-transparency.atlassian.net/browse/DEV-4430)
**Mockup:**
N/A
Author:
Reviewer(s):
- [N/A] Design …

[DEV-4430] Display text for 'All' option

---

src/js/components/award/financialAssistance/CFDAOverview.jsx
src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
src/js/containers/award/financialAssistance/CFDAVizContainer.jsx

Fixes a bug with CFDA Overview onClick. If you click the link in the overview section initially when in the table view you will have and then navigate to the tree view and then click on the overview link you will not be redirected to the table view.
Fixes a bug with CFDA Overview onClick. If you click the link in the overview section initially when in the table view you will have and then navigate to the tree view and then click on the overview link you will not be redirected to the table view.
[DEV-4697](https://federal-spending-transparency.atlassian.net/browse/DEV-4697)
**Mockup:**
https://bahdigital.invisionapp.com/share/57IAC6CHK84#/screens/295998954
Author:
- …

Dev-4697 update cfda overview onclick logic

---

src/js/containers/search/SearchSidebarSubmitContainer.jsx
tests/containers/search/SearchSidebarSubmitContainer-test.jsx
tests/containers/search/mockSubmit.js

Forgot to deliver functionality to clear NAICs tree when user selects "reset search"
SubmitSearchButtonContainer now takes a new action to clear `redux.naics.checked` and `redux.naics.unchecked`
[DEV-3484](https://federal-spending-transparency.atlassian.net/browse/DEV-3484)
Author: …

[DEV-3484] Clear NAICS tree on reset search

---

src/js/containers/account/awards/AccountAwardsContainer.jsx

Federal Account pages contain a Spending By Award table. The Recipient column cells are now hyperlinks to the appropriate Recipient Profile page.
N/A
[DEV-3142](https://federal-spending-transparency.atlassian.net/browse/DEV-3142)
**Mockup:**
N/A
Author:
Reviewer(s):

[DEV-3142] Federal Account Awards table links to Recipient Profile 

---

src/js/models/accountLanding/BaseFederalAccountLandingRow.js

Display `--` for federal accounts with no Budgetary Resources.
[DEV-4534](https://federal-spending-transparency.atlassian.net/browse/DEV-4534)
Author:
Reviewer(s):

[DEV-4534] Very minor tweak to Profiles -> Federal Accounts page

---

src/js/components/search/visualizations/rank/RankVisualization.jsx
src/js/components/search/visualizations/rank/sections/RankVisualizationSection.jsx
src/js/containers/search/visualizations/rank/RankVisualizationWrapperContainer.jsx
tests/containers/search/visualizations/rank/RankVisualizationWrapperContainer-test.jsx

Display a new error for the Spending by Recipient visualization when a user tries to page past 10k records.
Catching the specific error that is thrown by the Spending by Recipient endpoint to make sure that an error message is only displayed for when the new Elasticsearch functionality is hit. Ideally this would simply check if the `limit * page >= 10k` and could be changed to this in the future so that it is less fragile.
[DEV-4067](https://federal-spending-transparency.atlassian.net/browse/DEV-4067)
**Mockup:**
N/A
Author:
Reviewer(s):

[DEV-4067] Add error for Elasticsearch paging over 10k records

---

src/_scss/pages/award/visualizations/cfdaSectionViz.scss
src/js/components/award/financialAssistance/CFDAViz.jsx
src/js/components/award/financialAssistance/SingleCFDA.jsx
src/js/containers/award/financialAssistance/CFDAVizContainer.jsx

Implements a dropdown button that acts as the single cfda sections title when there are multiple cfdas for an award and allows users to switch between cfdas in the single cfda view.
N/A
[DEV-4788](https://federal-spending-transparency.atlassian.net/browse/DEV-4788)
**Mockup:**
[Please refer to the ticket.](https://federal-spending-transparency.atlassian.net/browse/DEV-4788)
Author:
- [N/A] [Component Library …

Dev-4788 Add Button Title to CFDA Section

---

src/js/components/sharedComponents/CheckboxTreeLabel.jsx
src/js/containers/search/filters/naics/NAICSContainer.jsx

Follow up addressing two bugs.
API was not returning counts until ~1hr ago; found that we weren't showing them properly with the customized label.
Realized a bug around not persisting the NACIS tree.
[DEV-4276](https://federal-spending-transparency.atlassian.net/browse/DEV-4276)
Author:
`N/A` Added Unit Tests for methods in Container …

[DEV-4276] Showing counts w/ customized label for TAS Codes

---

src/js/containers/search/filters/naics/NAICSContainer.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/helpers/checkboxTreeHelper.js
src/js/helpers/naicsHelper.js
src/js/helpers/tasHelper.js
tests/containers/search/filters/naics/NAICSContainer-test.jsx
tests/containers/search/filters/programSource/TASCheckboxContainer-test.jsx
tests/helpers/checkboxTreeHelper-test.js

When a placeholder is in the checked array, and you expand the parent, we need to replace the placeholder checked w/ the real checked data.
This was already implemented and tested code; just moved it to a helper and implemented it in NAICS and TAS.
[DEV-4267](https://federal-spending-transparency.atlassian.net/browse/DEV-4267)
Author:
`N/A` All …

[DEV-4267] Auto Check Nodes on Expand when Placeholder is checked

---

src/_scss/pages/search/filters/otherFilters/_tasCheckbox.scss
src/js/components/search/SearchSidebar.jsx
src/js/components/search/filters/programSource/ProgramSourceSection.jsx
src/js/components/search/filters/programSource/TreasuryAccountFilters.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx

No real big changes, just changing the format to match the mocks. I missed that we are supposed to keep the Tab layout.
Using some dark-release logic and cleaning up some styles; small changes.
[DEV-4278](https://federal-spending-transparency.atlassian.net/browse/DEV-4278)
Author:
`N/A` Added Unit Tests for methods in Container Components, …

[DEV-4278] Search TAS (moving to tab based layout)

---

src/js/helpers/checkboxTreeHelper.js
tests/helpers/checkboxTreeHelper-test.js

Bug fix for logic in decrementCount invoked onUncheck in TAS and NAICS
Added additional condition to `shouldRemoveCount`.
[DEV-4267](https://federal-spending-transparency.atlassian.net/browse/DEV-4267)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future …

[DEV-4267] fixes bug in decrement/onUncheck logic.

---

src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/helpers/checkboxTreeHelper.js

Quick BugFix PR for removing checked items from tree via clicking the Staged Filters tag
Two things:
1. Was passing an object when the fn was expecting a string
2. Was removing `children_of_` from checked array
[DEV-4627](https://federal-spending-transparency.atlassian.net/browse/DEV-4627)
**Mockup:**
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent …

Quick BugFix for removing checked items from tree via clicking the Staged Filters tag

---

src/js/models/search/SearchAwardsOperation.js

To support the upcoming change to Elasticsearch only use the `scope` filter when specifying `All Foreign Countries`. Currently both the `scope` and `location` filter are used and the backend handles the case of a "country" called foreign by ignoring it. 
Instead of using `.map()` when building the request parameters for location use `.reduce()` so that the country value of `foreign` can be ignored and instead added as a separate filter.
Request Before Fix:
```
{
"filters": {
"time_period": [
{
"start_date": "2007-10-01",
"end_date": "2020-09-30"
}
],
"award_type_codes": [
"A",
"B",
"C",
"D"
],
"place_of_performance_scope": "foreign",
"place_of_performance_locations": [
{
"country": "FOREIGN"
}
]
},
"fields": [
"Award ID",
"Recipient …
```

[DEV-4844] Don't add 'foreign' as a country; only scope

---

src/_scss/pages/award/shared/contractGrantsActivity.scss
src/js/components/award/shared/activity/ContractGrantActivityChart.jsx
src/js/helpers/contractGrantActivityHelper.js
tests/helpers/contractGrantActivityHelper-test.js

Adds extension of shading for cases when transactions are before the today line and the today line is before all end dates and a different color of shading when a transaction is past any end date and an extension of shading when the last transaction has an increase in running total obligation.
> • add three extra svg paths to the charts
[DEV-4746](https://federal-spending-transparency.atlassian.net/browse/DEV-4746)
**Mockup:**
https://bahdigital.invisionapp.com/share/7HIADD8Q53D#/screens/296034818
Author:
- [N/A] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated
- [N/A] [Component Library …

Dev-4746 Add Extension of Shading

---

src/_scss/pages/modals/recipient/_table.scss
src/_scss/pages/modals/recipient/recipient.scss
src/_scss/pages/recipient/_overview.scss
src/js/components/recipient/RecipientContent.jsx
src/js/components/recipient/RecipientOverview.jsx
src/js/components/recipient/RecipientPage.jsx
src/js/components/recipient/modal/AlternateNamesRecipientModal.jsx
src/js/components/recipient/modal/ChildRecipientModal.jsx
src/js/components/recipient/modal/table/AlternateNamesRecipientModalTable.jsx
src/js/components/recipient/modal/table/ChildRecipientModalTable.jsx
src/js/containers/recipient/modal/AlternateNamesRecipientModalContainer.jsx
src/js/containers/recipient/modal/ChildRecipientModalContainer.jsx
src/js/models/v2/recipient/BaseRecipientOverview.js
tests/containers/recipient/modal/AlternateNamesModalContainer-test.jsx
tests/containers/recipient/modal/ChildRecipientModalContainer-test.jsx
tests/models/recipient/mockRecipientApi.js

Added new modal to display recipient alternate names on the recipient profile. Attached are two screenshots taken from local to demonstrate this behavior: 
Followed a similar approach used to display child recipient modal. Since there are now two modals on the recipient page that child recipient modal was renamed to avoid future confusion.
[DEV-4642](https://federal-spending-transparency.atlassian.net/browse/DEV-4642)
**Mockup:**
https://bahdigital.invisionapp.com/share/QPIADGPK4FZ#/screens/296035186
https://bahdigital.invisionapp.com/share/QPIADGPK4FZ#/screens/296035190
Author:
Reviewer(s):

[DEV-4642] Add alternate names modal to recipient profile

---

src/js/containers/search/filters/naics/NAICSContainer.jsx
src/js/helpers/checkboxTreeHelper.js
tests/containers/search/filters/naics/NAICSContainer-test.jsx
tests/helpers/checkboxTreeHelper-test.js

When loading a stateful tree from a hash url, we are making the same service call multiple times.
Only fetch each code once, at most.
**Mockup:**
[JIRA Ticket](https://federal-spending-transparency.atlassian.net/browse/DEV-4887)
Author:
`N/A`Verified cross-browser compatibility
`N/A`All componentWillReceiveProps, componentWillMount, and …

[DEV-4887] BUG w/ NAICS tree Load from URL (Performance)

---

src/_scss/components/_verticalLine.scss
src/_scss/pages/award/shared/contractGrantsActivity.scss
src/js/components/award/contract/ContractContent.jsx
src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
src/js/components/award/idv/activity/chart/ActivityChart.jsx
src/js/components/award/shared/activity/ContractGrantActivity.jsx
src/js/components/award/shared/activity/ContractGrantActivityChart.jsx
src/js/components/award/shared/activity/ContractGrantActivityChartAreaPaths.jsx
src/js/components/award/shared/activity/ContractGrantActivityChartCircles.jsx
src/js/components/award/shared/activity/ContractGrantActivityChartVerticalLines.jsx
src/js/components/sharedComponents/SVGLine.jsx
src/js/components/sharedComponents/VerticalLine.jsx
src/js/containers/award/shared/ContractGrantActivityContainer.jsx

Implement the Potential Award Amount Line for the Contract Grants Activity Chart.
> • refactor vertical line component into svg line
> • confirmed with design no text.
[DEV-4556](https://federal-spending-transparency.atlassian.net/browse/DEV-4556)
**Mockup:**
https://bahdigital.invisionapp.com/share/7HIADD8Q53D#/screens/296034817
Author:
- [N/A] [Component Library Integration Status …

Dev-4556 Contract Grant Activity Chart Potential Award Amount Line

---

src/js/containers/search/filters/naics/NAICSContainer.jsx
src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
src/js/helpers/checkboxTreeHelper.js
tests/containers/search/filters/naics/mockNaics_v2.js
tests/helpers/checkboxTreeHelper-test.js

Fns used to incrementally populate the tree were not optimized to handle the four levels of PSC.
When performing a search, we populate the tree partially w/ the search results and placeholders. Then, when a user leaves search and expands down the tree, we complete that partial population. In order to preserve the proper checked state (full or half checked) we have to ensure that as we complete the tree population, we do not overwrite existing nodes from search.
We were doing this in PSC because we weren't anticipating 3 levels of children. **Now, we are via recursion**.
There is some added clean up to the logic as well by extracting some new helper fns outside the scope of the larger complex functions. …

[DEV-4528] Adding Recursion and a few Helpers to Clean Up Logic

---

Dockerfile

> • Add package-lock.json to docker folder so the `npm ci` command knows what to install.

add package lock to docker folder

---

Dockerfile
package-lock.json
package.json
src/js/helpers/apiRequest.js
src/js/helpers/checkboxTreeHelper.js
src/js/redux/reducers/search/naicsReducer.js
src/js/redux/reducers/search/pscReducer.js
src/js/redux/reducers/search/tasReducer.js
tests/helpers/checkboxTreeHelper-test.js

Search populates the tree to the `nth` level, but only partially. This means toggling back to the expand/collapse view, down to the parent of a node that was returned from search, we need to ensure we do not replace that parent that is `less populated` than the existing node.
Made the function that handles populating the tree on expand/collapse recursive. This simplifies the logic and really helps w/ PSC as there are three levels of children compared to just two with TAS and NAICS
[DEV-4527](https://federal-spending-transparency.atlassian.net/browse/DEV-4527)
Author:
`N/A` Verified mobile/tablet/desktop/monitor …

[DEV-4527] Expand Collapse Overwrites Nodes from Search Results

---

src/js/components/search/topFilterBar/filterGroups/ProgramSourceFilterGroup.jsx

TAS active filters, from older filter, are showing as undefined.
This is because in the relevant `.map` over the filter values, I was referencincing `tas.value` when I should've done just `tas`
[DEV-5120](https://federal-spending-transparency.atlassian.net/browse/DEV-5120)
Author:
`N/A`  Added Unit Tests for methods in Container Components, …

[DEV-5120] Updating the Active Filter Tag Title

---

src/js/containers/search/filters/naics/NAICSContainer.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx

Two things:
(1) Nav from search --> award --> back to search breaks the ability to load the tree from hash
Passing empty array rather than `this.props` and changing conditions for invoking `fetchTas`
[DEV-4794](https://federal-spending-transparency.atlassian.net/browse/DEV-4794)
Author: …

[DEV-4794] Load tree from URL on back button select from award page

---

src/js/containers/search/filters/naics/NAICSContainer.jsx
src/js/helpers/apiRequest.js
src/js/helpers/checkboxTreeHelper.js
tests/containers/search/filters/psc/mockPSC.js
tests/helpers/checkboxTreeHelper-test.js

Three issues addressed in this PR:
1. `counting checked nodes twice` when a placeholder was selected and then another placeholder under that was selected. (PSC Specific)
2. `Not removing the hide class` from nodes matching search results (PSC Specific)
3. `Adding nodes to checked from the unchecked array` after a search
1. Refactored the `incrementCount` helper function to allow for a placeholder to be counted by another placeholder.
2. Refactored the `mergeChildren` helper function, now called `appendSearchResultsToChild` such that it has no duplicate logic, utilizes more readable helper functions, and uses recursion.
3. Added simple conditional to container method `autoCheckAfterSearch`
Also added unit tests to prove all this works …

[DEV-4529] 3 Bugs, (a) adding search results, (b) counting selected nodes, (c) auto-adding checked nodes after search

---

src/js/components/search/table/ResultsTable.jsx

Adds links to the Agency profile page under the "Awarding Agency" column on the advanced search page
API will now provide a new field "awarding_agency_id", which will allow linking to the agency profile page.
[DEV-3986](https://federal-spending-transparency.atlassian.net/browse/DEV-3986)
Author:
Reviewer(s):

[DEV-3986] add awarding agency links

---

src/js/components/search/SearchSidebar.jsx
src/js/components/search/filters/programSource/ProgramSourceSection.jsx
src/js/components/search/filters/programSource/TreasuryAccountFilters.jsx

Release the checkbox trees.
Removes the dark release logic in the search sidebar component and, for tas, elsewhere.
[DEV-4469](https://federal-spending-transparency.atlassian.net/browse/DEV-4469)
Author:
Reviewer(s):
`N/A` Design review complete `if applicable`

[DEV-4469] Release Checkbox Trees TAS/NAICS/PSC

---

src/js/components/about/DataSources.jsx
src/js/components/award/shared/description/AwardDescription.jsx
src/js/components/search/SearchSidebar.jsx
src/js/containers/search/helpers/searchAnalytics.js
src/js/helpers/sidebarHelper.js
tests/models/awards/additionalDetails/BaseContractAdditionalDetails-test.js
tests/models/awards/mockAwardApi.js

- Updated incorrect definition for FABS in About Us -> Data Sources
- Fixed a broken link caused by a glossary change
- Replaced "Product/Service" with "Product or Service" wherever it was found
That's about it.  EZPZ.  Hopefully I didn't break anything.
[There is a matching back end ticket](https://github.com/fedspendingtransparency/usaspending-api/pull/2496), but it isn't strictly necessary to merge them together.  A glossary link won't work until they're both merged, but nothing should burst into flames.

[DEV-5119] Update some titles and links

---

src/js/components/agency/v2/accountSpending/AccountSpending.jsx

Design changed since the tabs were implemented in #1667 
[DEV-5225](https://federal-spending-transparency.atlassian.net/browse/DEV-5225)
**Mockup:**
https://bahdigital.invisionapp.com/share/2YIACOYGKF3#/296028021_Agency_Profile_V2_-_Mock_Mid-Fi
Author:
Reviewer(s):

DEV-5225 Remove "Total" from agency v2 tabs

---

src/_scss/layouts/default/stickyHeader/_toolbar.scss

Removes 5px of padding
Prevents the Copy Link drop down item from wrapping into two lines in IE
[DEV-4180](https://federal-spending-transparency.atlassian.net/browse/DEV-4180)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant …

[DEV-4180] onHover, ensuring copy link doesn't wrap into two lines

---

src/js/components/accountLanding/AccountLandingPage.jsx
src/js/components/agencyLanding/AgencyLandingPage.jsx
src/js/components/explorer/ExplorerWrapperPage.jsx
src/js/components/explorer/landing/ExplorerLanding.jsx
src/js/components/recipientLanding/RecipientLandingPage.jsx
src/js/components/stateLanding/StateLandingPage.jsx

- Ensures Explorer Detail Page does not show Share Icon
- Fixes email body details for landing pages.
Minor updates.
[DEV-4180](https://federal-spending-transparency.atlassian.net/browse/DEV-4180)
Author: …

[DEV-4180] Share Icon: Hiding on Explorer Detail Page and Fixing Email Body Content

---

src/js/components/search/SearchSidebar.jsx
src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
src/js/helpers/checkboxTreeHelper.js
tests/containers/search/filters/naics/NAICSCheckboxTree-test.jsx
tests/containers/search/filters/programSource/TASCheckboxContainer-test.jsx
tests/containers/search/filters/psc/PSCCheckboxTreeContainer-test.jsx
tests/helpers/checkboxTreeHelper-test.js

Only search for NAICS/TAS/PSC if the input is greater than or equal to three chars.
Also, corrected the search side bar title for PSC per https://federal-spending-transparency.atlassian.net/browse/DEV-5119.
Adds conditional to `handleInputChange` on all trees and adds identical test for each.
[DEV-4469](https://federal-spending-transparency.atlassian.net/browse/DEV-4469)
[DEV-5119](https://federal-spending-transparency.atlassian.net/browse/DEV-5119)
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent …

[DEV-4469] Checkbox Trees Search Performance and Search Side Bar Title Update for PSC

---

src/js/components/agency/visualizations/obligated/ObligatedVisualization.jsx

Preterite and participle used for 'outlay' is 'outlayed', NOT 'outlaid'. Citation can be found in OMB's A-11: https://www.whitehouse.gov/wp-content/uploads/2018/06/a11.pdf 
Reviewer(s):

Change 'outlaid' to 'outlayed'

---

src/_scss/pages/award/idv/_referencedAwards.scss
src/_scss/pages/award/shared/_awardHistorySection.scss
src/_scss/pages/recipientLanding/recipientLandingPage.scss
src/_scss/pages/search/_tooltips.scss
src/_scss/pages/search/results/table/_resultsTablePicker.scss
src/_scss/pages/search/results/table/_tableTypes.scss
src/_scss/pages/state/topFive/_topFive.scss
src/js/components/award/table/DetailsTabItem.jsx
src/js/components/search/table/ResultsTableTabItem.jsx
src/js/components/sharedComponents/filterSidebar/FilterExpandButton.jsx

Tooltips are not triggering when they're nested under buttons.
Changes button elements to divs, with the role set to button.
https://federal-spending-transparency.atlassian.net/browse/DEV-5198
https://federal-spending-transparency.atlassian.net/browse/DEV-5166
Author:
`N/A` All componentWillReceiveProps, componentWillMount, and componentWillUpdate in relevant child/parent components/containers replaced with [future compatible life-cycle …

[DEV-5198 & 5166] Warmfix IE Tooltip Bugs - Nested tooltips inside buttons

---

src/_scss/pages/award/shared/contractGrantsActivity.scss
src/js/components/award/shared/activity/ContractGrantActivityChartAreaPaths.jsx
src/js/components/award/shared/activity/Tooltip.jsx

Increases the extension shading to 3 and decreases the opacity by 0.1. Sets the height of the tooltip to 300px.
N/A
[DEV-5197](https://federal-spending-transparency.atlassian.net/browse/DEV-5197)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container Components, …

Warm Fix Dev-5197 Contract Grant Activity Chart Updates

---

src/js/components/account/SearchSidebar.jsx
src/js/models/account/queries/queryBuilders/_programActivityTranslator.js

The issue was found where filter titles are not displaying on Federal Account page and the PSC filter does not display checkboxes after closing and re-opening the filter.
The issue with Federal Account filter titles was simply a bit of code that was updated to support an object, but the titles for the filters were not. 
The issue of the PSC filter not populating after closing is due to the `_resetExchange()` function not working as expected. Simply put, Object.assign() can be used to create a shallow copy of an object where there are no nested objects, but this will not work for a deep copy. Explanation and solution are explained in much more detail here: https://scotch.io/bar-talk/copying-objects-in-javascript …

[DEV-5417] Fix bugs on Federal Account page filter

---

src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx

Only condition that was used for showing covid mock data was if it exists. Adding dual condition for `isCaresActReleased`
Adding new conditional
[DEV-5318](https://federal-spending-transparency.atlassian.net/browse/DEV-5318)
Author:
`N/A` Added Unit Tests for methods in Container Components, …

[DEV-5318] Correction of Dark Release Logic for Award Amounts Viz

---

src/js/dataMapping/search/awardsOperationKeys.js
src/js/models/search/SearchAwardsOperation.js
tests/models/search/SearchAwardsOperation-test.js
tests/testResources/defaultReduxFilters.js

Adds def_codes property to `spending_by_award` request object.
This doesnt break the API so we can just add it before the API is ready.
Adds test to confirm the request object shape is right.
[DEV-5310](https://federal-spending-transparency.atlassian.net/browse/DEV-5310)
Author:
`N/A` All …

[DEV-5310] Adding def_codes to request object for the spending_by_award endpoint

---

src/js/components/award/shared/activity/ContractGrantActivity.jsx
src/js/components/sharedComponents/DatePicker.jsx
src/js/helpers/contractGrantActivityHelper.js
tests/helpers/contractGrantActivityHelper-test.js

> • fixes a bug where the action type in the tooltip was displaying the type description.
> • Updates
Given a start date, no end date and one transaction:
• only chart when start date is not equal to transaction date
https://federal-spending-transparency.atlassian.net/browse/DEV-5479
https://federal-spending-transparency.atlassian.net/browse/DEV-4886

Bug & Updates Contract Grant Activity Chart

---

src/_scss/pages/covid19/assistanceListing/_assistanceListing.scss
src/_scss/pages/covid19/spendingOverTime/_awardSpendingOverTime.scss
src/_scss/pages/search/results/table/_tableTypes.scss
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/assistanceListing/SummaryInsightsContainer.jsx
src/js/dataMapping/covid19/covid19.js

Implements award type tabs in the Spending by CFDA Program (Assistance Listing) section of the COVID-19 profile page.
- Relies on the mock API (endpoints and API integration will be completed in a future sprint)
[DEV-5458](https://federal-spending-transparency.atlassian.net/browse/DEV-5458), subtask of [DEV-5299](https://federal-spending-transparency.atlassian.net/browse/DEV-5299)
**Mockup:**
https://bahdigital.invisionapp.com/share/NGIAE7D7H6S#/296040947_COVID-19_Profile_-_Tab_Rework
Author:
- N/A Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR - demo when final subtasks are complete
Reviewer(s):

DEV-5458 COVID profile CFDA section award type tabs

---

src/js/components/award/idv/amounts/AwardAmounts.jsx
src/js/dataMapping/award/awardAmountsSection.js
src/js/models/v2/award/BaseAwardAmounts.js
tests/models/award/BaseAwardAmounts-test.js
tests/models/award/mockAwardApi.js

Fixing undefined error in DEV.
- [The response object for this endpoint](https://dev-api.usaspending.gov/api/v2/idvs/amounts/CONT_IDV_EDFSA09D0012_9100/) was wrong.
- Was not passing the `showFileC` to the AwardAmountsTable component in one context for idvs
- Fixes the Table Label per [this ticket](https://federal-spending-transparency.atlassian.net/browse/DEV-5477)
[DEV-5136](https://federal-spending-transparency.atlassian.net/browse/DEV-5136)
Author: …

[DEV-5136] fixing expected idv_agg response object shape

---

src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
src/js/components/award/financialAssistance/RectanglePercentViz.jsx
src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx

Handling styles for tooltip and label when the covid outlayed amount is zero: `ASST_NON_12FA00PY63083044_12D2`
- Adding class name to covid-outlay label when amount is zero. SS 👇 
- Reusing styles for used for when non federal funding amount is zero 👇 
- Special logic for positioning the tooltip correctly.
[DEV-5538](https://federal-spending-transparency.atlassian.net/browse/DEV-5538)
**Mockup:**
Author:
`N/A` Verified that this PR does not create any *new* …

[DEV-5538] Award Amounts Viz -- Handling case where outlayed amount is zero & [DEV-5477] Small Tweaks to Award Summary

---

src/js/components/search/SearchSidebar.jsx
src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx
src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/helpers/sidebarHelper.js
tests/containers/search/filters/DEFCheckboxxTree-test.jsx

Hooks up the DEFC Filter to the API and cleans up some bugs. Also adds a test.
Previously this checkbox tree was...
- Using Mock Data
- Using local state rather than redux state for the checked state of the tree (**root cause for why it wasnt loading from hash**)
Switch Statement clean up for detecting expanded state of the search side bar 👇 ,
- Deleted dead code in the switch statement for the sidebar (for NAICS/PSC)
- Switch statement now switches on the `filter.title` property
- Adds new case for switch statement for DEFC
Also fixes the title so everywhere it is `Disaster Emergency Fund (DEF) Code` rather than `Disaster and Emergency Fund Code (DEF)` and other inconsistent variations. …

[DEV-5537 & DEV-5491] Hooking up DEFC Filter to API and loading it from Hash

---

src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
src/js/components/award/idv/amounts/AggregatedAwardAmounts.jsx
src/js/components/award/idv/amounts/AwardAmounts.jsx
src/js/components/award/shared/awardAmountsSection/AwardAmountsSection.jsx
src/js/dataMapping/award/awardAmountsSection.js
src/js/models/v2/award/BaseAwardAmounts.js
src/js/models/v2/award/BaseContract.js
src/js/models/v2/award/BaseFinancialAssistance.js
src/js/models/v2/award/BaseIdv.js
src/js/propTypes/index.js
tests/models/award/BaseAwardAmounts-test.js

We were mocking award amounts data to populate the award amounts viz. Now that the API is returning this data, we don't have to do this anymore.
- Remove white list of award ids to populate mock data for
- Update Tests to no longer confirm these white listed award are being mocked
- Remove obsolete properties on the AwardAmounts model
- Show new colors for award amounts table (DEV-5477)
- Only show award amounts table covid data when it is non-zero (DEV-5477)
- Fixing order of legend so outlayed proceeds obligated.
[DEV-5434](https://federal-spending-transparency.atlassian.net/browse/DEV-5434)
Author:
`N/A` Scheduled demo including Design/Testing/Front-end OR …

[DEV-5434] Removing Front End Mock Data Logic for Award Amounts Viz

---

src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
src/js/components/award/idv/amounts/AggregatedAwardAmounts.jsx
src/js/components/award/idv/amounts/AwardAmounts.jsx
src/js/components/award/shared/awardAmountsSection/AwardAmountsSection.jsx
src/js/components/award/shared/awardAmountsSection/AwardAmountsTable.jsx
src/js/dataMapping/award/awardAmountsSection.js

We weren't showing fileC data in the award amounts viz table if they were less than zero.
- Change conditional to show file c data if it is non zero
- Updated class names so legend colors are correct based on award type
**Mockup:**
Author:
`N/A` Added Unit Tests for methods in Container …

[DEV-5136] Showing FileC Data in Award Amounts Table when Outlays or Obligated is non-zero

---

src/js/models/v2/covid19/BaseSpendingByCfdaRow.js
tests/containers/covid19/SpendingByCFDAContainer-test.jsx
tests/models/covid19/BaseSpendingByCfdaRow-test.js
tests/models/covid19/mockData.js

Display just the `code` property from the API response, instead of a combination of `code` and `id`.
- Updates the data model and unit tests
[DEV-5469](https://federal-spending-transparency.atlassian.net/browse/DEV-5469), subtask of [DEV-5299](https://federal-spending-transparency.atlassian.net/browse/DEV-5299)
Author:
Reviewer(s):

DEV-5299 fix CFDA code format

---

src/js/models/search/SearchAwardsOperation.js
tests/models/search/SearchAwardsOperation-test.js

We were expecting the request object to have the same shape as the other checkbox trees. But since the data -- at the moment -- is non-hierachial it doesn't actually require anything more than an array of strings to indicate what's selected.
We're actually keeping the structure in redux as is, and only changing this to an array at the request layer. This is most expedient, but also in the future perhaps the defc data will grow more complex and we will find a use for this data structure.
Updates the test as well 
[DEV-5233](https://federal-spending-transparency.atlassian.net/browse/DEV-5233)
Author:
`N/A` Scheduled demo including Design/Testing/Front-end OR Provided …

[DEV-5233] Changing Request Object shape for DEFC Spending By Award

---

src/js/components/sharedComponents/header/DropdownItem.jsx
src/js/containers/router/RouterRoutes.js

The navigation link to the COVID profile page was added referencing the url `/disaster/covid-19`, but the page still lived at `/covid-19`
- Also fixes a prop types console error in the `DropdownItem` component
[DEV-5414](https://federal-spending-transparency.atlassian.net/browse/DEV-5414)
Author:
Reviewer(s):

DEV-5414 update COVID profile url

---

src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx

Fixes a bug causing the Award Spending by Agency tab counts not to match the number of results in the corresponding table.
Updated the expected order of API responses to match the order of the tabs. 
[DEV-5347](https://federal-spending-transparency.atlassian.net/browse/DEV-5347)
Author:
Reviewer(s):

DEV-5347 warmfix tab counts

---

src/js/models/search/SearchAwardsOperation.js
tests/models/search/SearchAwardsOperation-test.js

A congressional staffer is trying to use the `treasury account components` filter and the request object it's building is not working.
The request object has a `tas_codes : { require: [] }` property/value when selecting a treasury account component (not the tas checkbox tree). This breaks the request object. Not good!!
Adds a test to ensure this doesnt happen.
Author:
`N/A`Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable` …

[hotfix/tas-component-filter] The Treasury Component Filter is Broken, Providing Tests & a fix

---

src/_scss/core/_variables.scss
src/_scss/pages/award/awardPage.scss
src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
src/_scss/pages/covid19/index.scss
src/_scss/pages/search/filters/otherFilters/_defCheckbox.scss
src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
src/js/dataMapping/award/awardAmountsSection.js
src/js/dataMapping/covid19/covid19.js

Wherever we're using COVID colors, we're referring now to a variable that contains the correct hex value.
Also, we had to update the colors for the award amounts viz for proper contrast with the new File C spending categories.
- Creates variables
- Uses variables
- Updates colors passed to Non-Normative Contracts and IDVs so that they look nice. 
[DEV-5535](https://federal-spending-transparency.atlassian.net/browse/DEV-5535)
Author:
`N/A` Verified that this PR does not create any *new* accessibility issues (via Axe …

[DEV-5535] Standardize COVID Colors and Award Amounts Colors

---

src/js/components/covid19/OverviewData.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx

Ensures total Budgetary Resources, Obligations, and Outlays displayed in the Overview visualization match totals in the Budget Categories section.
- Get the values from Redux instead of making another call to the overview endpoint
- Also uses the latest submission date from Redux instead of a hard-coded value
[DEV-5634](https://federal-spending-transparency.atlassian.net/browse/DEV-5634)
Author:
- N/A (no UI changes) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (no UI changes) Verified mobile/tablet/desktop/monitor responsiveness
- N/A (no UI changes) Verified that this PR does not create any *new* accessibility issues …

DEV-5634 consistent totals from overview

---

src/js/dataMapping/search/awardTableColumnTypes.js

Showing the parsed dollar amounts in the Advanced Search table rather than the floating integer.
Updated a data mapping file to flag the column as "currency".
I created [a ticket recommending we migrate this table to implement the model pattern](https://federal-spending-transparency.atlassian.net/browse/DEV-5665) as this data parsing is kind of hard to discover and not tested.
[DEV-5310](https://federal-spending-transparency.atlassian.net/browse/DEV-5310)
Author:
`N/A` Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet …

[DEV-5310] Making the Covid columns display as currency in Advanced Search Results

---

src/js/components/sharedComponents/stickyHeader/ShareIcon.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/dataMapping/covid19/covid19.js
src/js/helpers/socialShare.jsx
tests/helpers/socialShare-test.js

Changes the url of links generated by our social share button from `/#/covid-19` to `/covid-19` (without the hash), which has a redirect in place to go to `/#/disaster/covid-19`. 
- This is for marketing reasons (usaspending.gov/covid-19 is easier to remember & looks cleaner than usaspending.gov/#/disaster/covid-19)
- Redirect is already in place: [https://www.usaspending.gov/covid-19](https://www.usaspending.gov/covid-19) (but will 404 in prod before launch)
[DEV-5633](https://federal-spending-transparency.atlassian.net/browse/DEV-5633)
Author:
- N/A (no UI changes) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (no UI …

DEV-5633 fix COVID share button links

---

src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx
src/js/helpers/covid19Helper.js
tests/helpers/covid19Helper-test.js

Corrects the "Data as of" date displayed above visualizations on the COVID profile page.
- Reference the API field `submission_reveal_date` instead of `submission_due_date`
- Replaces a few places we were still hard-coding the date
- Adds the Date component to the Award Spending by CFDA Section
[DEV-5630](https://federal-spending-transparency.atlassian.net/browse/DEV-5630)
Author:
- N/A (no UI changes) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (no UI changes)  Verified mobile/tablet/desktop/monitor responsiveness
- N/A (no UI changes)  Verified that this PR does not create any *new* accessibility issues (via Axe …

DEV-5630 fix "Data as of" dates

---

src/js/helpers/covid19Helper.js
tests/helpers/covid19Helper-test.js

Spells out the full month (e.g. `June 30, 2020` instead of `Jun 30, 2020`) in "Data as of" notes on the COVID-19 profile page.
Follow-up fix for [DEV-5630](https://federal-spending-transparency.atlassian.net/browse/DEV-5630)
Author:
- N/A Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
Reviewer(s):

DEV-5630 spell out month in "data as of" notes

---

src/_scss/pages/covid19/_searchBar.scss
src/_scss/pages/covid19/index.scss
src/_scss/pages/covid19/recipient/_spendingByRecipient.scss
src/js/components/covid19/SearchBar.jsx
src/js/components/covid19/recipient/SpendingByRecipient.jsx
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
tests/containers/covid19/SpendingByRecipientContainer-test.jsx

Adds a search bar to the COVID Profile **Spending by Recipient** section > **Recipients** tab table
- Adds `query` param to API request when the search string is more than 3 characters
- Creates a `SearchBar` component that could be reused in other sections of the page
- Styles substring of the recipient name that matches the search input
- When only one recipient profile page is available, link the recipient name instead of using `as Child`/ `as Recipient`
- Fixes a bug causing the Loans and Direct Payment tab counts to be swapped
[DEV-5602](https://federal-spending-transparency.atlassian.net/browse/DEV-5602) (search bar), [DEV-5629](https://federal-spending-transparency.atlassian.net/browse/DEV-5629) (recipient links) …

DEV-5602 & DEV-5629 COVID recipient search bar and links update

---

src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
src/js/containers/covid19/SummaryInsightsContainer.jsx
src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx
src/js/dataMapping/covid19/covid19.js

On the COVID-19 Profile page:
- Capitalizes summary insight subtitles (e.g. `for all grants` -> `for All Grants`)
- Changes subtitle `for all other` to `for All Other Financial Assistance`
- Fixes a bug where the all awards tab was displaying `all All Awards`
- Fixes the order of Obligations and Outlays in the Award Spending by Agency section
[DEV-5628](https://federal-spending-transparency.atlassian.net/browse/DEV-5628) & [DEV-5645](https://federal-spending-transparency.atlassian.net/browse/DEV-5645)
Author:
- N/A (text changes only) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (text changes only) Verified that this PR does not create any …

DEV-5628 & DEV-5645 summary insight labels & order

---

src/js/components/bulkDownload/accounts/AccountDataContent.jsx
src/js/components/bulkDownload/awards/SubmitButton.jsx

There is a bug where clicking a disabled quarter on the account download page triggers the download.
This was happening because in the component from the library, we are not preventing an onClick event on the Quarter Picker from bubbling up to the form and creating false positive for the onSubmit event.
Rather than fix the component library now, I've changed our implementation such that we aren't looking for an onSubmit event on the form generally, but rather we're attaching an onClick event to the submit button itself. This avoids the problem. [I created a ticket for the component library so we can fix the root cause later](https://federal-spending-transparency.atlassian.net/browse/DEV-DEV-5687). …

[DEV-5197] Preventing onSubmit triggered by onClick of disabled Quarter

---

src/_scss/pages/award/shared/awardAmountsSection/_charts.scss
src/js/components/award/financialAssistance/RectanglePercentViz.jsx
src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
src/js/components/award/shared/awardAmountsSection/charts/SharedBarComponents.jsx
src/js/dataMapping/award/awardAmountsSection.js
src/js/helpers/apiRequest.js

The award amounts viz works but the lines drawn to outline the bars in the description do not consider the padding or nested position of the bars.
For each award type and each spending category, I have a value for the approximate amount of padding. I apply that padding to the line via a margin and the width of the line.
I have an object that stores these values in a dataMapping file.
Admittedly, the exact padding does not always look right so I have done some hacking here to just make it look right.
Here's a contrast for comparison:
QAT:
LOCAL:
[DEV-5242](https://federal-spending-transparency.atlassian.net/browse/DEV-5242)
**Mockup:**
The following are ALL required for …

[DEV-5242] More Precise Lines for Award Amounts Viz

---

src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx
src/js/dataMapping/covid19/budgetCategories/BudgetCategoriesTableColumns.js

Fixes the sort field parameter for the first column in COVID-19 Profile Federal Accounts, Recipients, Agency, and CFDA tables.
- Previously, the `pagination.sort` param was being incorrectly passed as `name` or left out because it was `undefined`. The first column generally should correlate to sorting by the API field `description`, except for Budget Categories section -> Federal Accounts and Object Classes tabs, which should sort by `code`. 
- Simplifies `BudgetCategoriesTableContainer` by removing `sortAndOrder` from state, since `sort` and `order` are already stored independently
-  Consistent use of `spendingTableSortFields` data mapping and `name` as the `title` of the first column …

DEV-5639 fix sorting by first column

---

src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
src/js/models/v2/covid19/BaseBudgetCategoryRow.js
tests/models/covid19/BaseBudgetCategoryRow-test.js

Updates to COVID-19 Profile Budget Category row formatting:
- Add a period to Object Class codes (e.g. `41.0` instead of `410`)
- Separate code and description with a colon instead of a hyphen for Federal Accounts and Object Classes (e.g. `41.0: Grants, subsidies, and contributions` instead of `41.0 - Grants, subsidies, and contributions`)
- Moves some of the formatting logic from the container to the model by passing the active tab and boolean indicating a child row to the `populate` method
[DEV-5636](https://federal-spending-transparency.atlassian.net/browse/DEV-5636), [DEV-5690](https://federal-spending-transparency.atlassian.net/browse/DEV-5690)
**Mockup:**
https://bahdigital.invisionapp.com/share/ERIAEJU8Y52
The …

DEV-5636 & DEV-5690 Object Class display

---

src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
src/js/containers/covid19/SummaryInsightsContainer.jsx
src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx

Per Ross's feedback from demos, lowercase `all` (e.g. `all Grants` etc.) except in the `All Awards` tab.
[DEV-5628](https://federal-spending-transparency.atlassian.net/browse/DEV-5628)
Author:
- N/A (text change only) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (text change only) Verified mobile/tablet/desktop/monitor responsiveness
- N/A (text change only) Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
Reviewer(s):

DEV-5628 capitalization of 'all' in COVID summary insights

---

src/js/components/covid19/AmountsVisualization.jsx

In the COVID-19 Profile Page Overview section, round dollar amounts to one decimal place for consistency with how these are amounts are displayed elsewhere on the page.
[DEV-5634](https://federal-spending-transparency.atlassian.net/browse/DEV-5634)
Author:
- N/A (text change only) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (text change only) Verified mobile/tablet/desktop/monitor responsiveness
- N/A (text change only) Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
Reviewer(s):

DEV-5634 COVID Overview chart rounding

---

src/_scss/pages/covid19/_stickyHeader.scss
src/js/components/covid19/DownloadHover.jsx
src/js/components/sharedComponents/stickyHeader/DownloadIconButton.jsx

Adds download tooltip on hover for top download button.
[DEV-5592](https://federal-spending-transparency.atlassian.net/browse/DEV-5592)
**Mockup:**
N/A
Author:
- [N/A] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension) **Ability to tab to link in hover tooltip will possibly be post-mvp** …

DEV-5592 covid19 download tooltip

---

src/js/models/v2/award/BaseAwardAmounts.js
tests/models/award/BaseAwardAmounts-test.js

In the models, we were looking at the wrong property on the response object.
Map to correct object property and add test.
[DEV-5751](https://federal-spending-transparency.atlassian.net/browse/DEV-5751)
Author:
`N/A` All `componentWillReceiveProps` and `componentWillMount` in relevant …

[DEV-5751] Mapping to correct property of response object for IDV Aggregate award amounts

---

src/_scss/pages/modals/covid19/_covid19.scss
src/js/containers/covid19/CovidModalContainer.jsx

Updated COVID modal content to reflect recent content changes. Also updated modal styling.
Updated CovidModalContainer.jsx to reflect content changes. Added in "sign up" email functionality. Updated _covid19.scss to address modal margin spacing and left-aligned modal title.
[DEV-5618](https://federal-spending-transparency.atlassian.net/browse/DEV-5618)
**Mockup:**
https://bahdigital.invisionapp.com/share/JGIAEFTP6NX
Author:
- [`N/A`] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with …

Ftr/dev 5618/updating modal content

---

src/js/components/covid19/SearchBar.jsx
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx

Fixes the `x` button / clear search functionality in the COVID Profile recipient search bar. 
[DEV-5602](https://federal-spending-transparency.atlassian.net/browse/DEV-5602) (see Ross's latest comment)
Author:
Reviewer(s):

DEV-5602 fix clear recipient search

---

src/js/components/award/shared/AwardPageWrapper.jsx
src/js/components/award/shared/InfoTooltipContent.jsx
src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx
src/js/components/search/table/ResultsTable.jsx
src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx
src/js/dataMapping/award/awardAmountsSection.js
src/js/dataMapping/navigation/menuOptions.jsx
src/js/dataMapping/search/awardTableColumns.jsx

Non-COVID profile page edits for language change from "Response" to "Spending"
Edited labels for Global Nav, Advanced Seach, COVID badge + tooltip, and Award Summary pages
(homepage edits in separate PR for DEV-5113, modal edits in separate PR for DEV-5618)
DEV-5616 is a sub-task of DEV-5594
[DEV-5594](https://federal-spending-transparency.atlassian.net/browse/DEV-5594)
**Mockup:**
Various mockups for each screen are linked in the ticket A/C above
Author:
- [`N/A`] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [`N/A`] Added Unit Tests for methods in …

Ftr/dev 5616/non covid page updates

---

src/_scss/pages/search/filters/otherFilters/_defCheckbox.scss
src/js/components/search/filters/defc/DEFCheckboxTreeLabel.jsx
src/js/containers/search/filters/def/DEFCheckboxTree.jsx

Updates the label for the checkbox tree such that when multiple public laws  and titles appear we handle them gracefully.
When a `|` is in the response, we know we need to render multiple public law & titles
[DEV-5738](https://federal-spending-transparency.atlassian.net/browse/DEV-5738)
**SS**
Author:
`N/A` Added Unit Tests for methods in Container Components, reducers, helper …

[DEV-5738] DEFC Checkbox Tree Label Update

---

src/js/containers/covid19/SummaryInsightsContainer.jsx

DEV-5628 changed the summary squares on the CFDA section to read "All Assistance Awards". This PR updates the `/disaster/award/amount/` request to utilize a new request parameter to limit the results to assistance awards.
[DEV-5750](https://federal-spending-transparency.atlassian.net/browse/DEV-5750)
Author:
- N/A (change to API request params only) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (change to API request params only) Verified mobile/tablet/desktop/monitor responsiveness
- N/A (change to API request params only) Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
Reviewer(s):

DEV-5750 update CFDA award amounts request

---

src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

**Top of Adv Search page**
DEFC label now uses "Code" singular
**Bottom of COVID-19 Spending selected checkbox**
Selected chip now says "COVID-19 Spending (<count>)"
Edited labels in `DEFCheckboxTree.jsx` (bottom of checkbox filters) and `TopFilterBarContainer.jsx` (top of page)
[DEV-5757](https://federal-spending-transparency.atlassian.net/browse/DEV-5757)
**Mockup:**
N/A - related screenshots are linked in the ticket above
Author:
- [`N/A`] Verified cross-browser compatibility: …

[DEV-5757] Adv Search label corrections

---

src/js/containers/covid19/CovidModalContainer.jsx
src/js/containers/covid19/homepage/CovidHighlights.jsx

When you click a link on the modal, the modal doesn't close.
Add invocation of `hideModal` on click
[DEV-5536](https://federal-spending-transparency.atlassian.net/browse/DEV-5536)
Author:
`N/A` Added Unit Tests for methods in Container Components, reducers, helper functions, and models `if …

QAT -- [DEV-5536] Closing Modal on Link Click

---

src/js/components/award/shared/awardAmountsSection/Tooltips.jsx

Progress bar tooltips still had the word "Response" in their headings. In this PR I corrected those headings so that they match the label of the progress bar and legend.
Edited `FileCOutlayTooltip` and `FileCObligatedTooltip` components so that their heading matches the chart and legend labels.
[DEV-5777](https://federal-spending-transparency.atlassian.net/browse/DEV-5777)
**Mockup:**
N/A - applicable screenshots linked in ticket above
Author:
- …

QAT Bug/dev 5777/award summary tooltips

---

src/js/containers/covid19/SummaryInsightsContainer.jsx
src/js/containers/covid19/recipient/SummaryInsightsContainer.jsx
src/js/helpers/disasterHelper.js

Fixes the "Number of Awards for All Assistance Awards" in the CFDA section.  
Gets the `award_count` from `disaster/award/amounts` endpoint instead of `disaster/award/count`, since the former accepts the `"award_type": "assistance"` param. Phases out use of `disaster/award/count` throughout the page.
[DEV-5774](https://federal-spending-transparency.atlassian.net/browse/DEV-5774)
Author:
- N/A (API request change only) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (API request change only)  Verified mobile/tablet/desktop/monitor responsiveness
- N/A (API request change only) Verified that this PR does not create any *new* …

QAT DEV-5774 assistance award count

---

src/js/components/award/shared/awardAmountsSection/Tooltips.jsx
src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

Progress bar tooltips still had the word "Response" in their headings. In this PR I corrected those headings so that they match the label of the progress bar and legend.
Edited `FileCOutlayTooltip` and `FileCObligatedTooltip` components so that their heading matches the chart and legend labels.
[DEV-5777](https://federal-spending-transparency.atlassian.net/browse/DEV-5777)
**Mockup:**
N/A - applicable screenshots linked in ticket above
Author:
- …

Staging Bug/dev 5777/award summary tooltips

---

src/js/components/covid19/SearchBar.jsx

Resolves an edge case that came up during demos: currently, if you enter a search term and then delete your input, there is no way to reset the search unless you re-type the same search term. These changes auto-reset the search when all input is deleted, and allow users to clear their search with only 1 character of input.
[DEV-5602](https://federal-spending-transparency.atlassian.net/browse/DEV-5602)
Author:
Reviewer(s):

QAT DEV-5602 clear search min chars

---

src/_scss/pages/homepage/features/_covidFeature.scss
src/_scss/pages/homepage/hero/_covid-hero.scss
src/_scss/pages/modals/covid19/_covid19.scss
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

The home page is unacceptable in safari:
Per Marco's request, bolding the font for the `Learn More` link on the home page
Updating the font size in the modal as well.
SCSS updates
[DEV-5773](https://federal-spending-transparency.atlassian.net/browse/DEV-5773)
Author:
`N/A` …

QAT -- [DEV-5773] Home Page Style Polish, including Updates to Modal

---

src/_scss/pages/homepage/features/_covidFeature.scss
src/_scss/pages/homepage/hero/_covid-hero.scss
src/_scss/pages/modals/covid19/_covid19.scss
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

The home page is unacceptable in safari:
Per Marco's request, bolding the font for the `Learn More` link on the home page
Updating the font size in the modal as well.
SCSS updates
[DEV-5773](https://federal-spending-transparency.atlassian.net/browse/DEV-5773)
Author:
`N/A` …

STAGING -- [DEV-5773] Home Page Style Polish, including Updates to Modal

---

src/js/components/award/shared/InfoTooltipContent.jsx
src/js/components/covid19/Covid19Section.jsx
src/js/components/covid19/recipient/map/MapFiltersHeader.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
src/js/containers/covid19/helpers/covid19.jsx

Removes "Coming Soon" tooltips from the COVID profile page for launch.
**JIRA Ticket**
[DEV-5788](https://federal-spending-transparency.atlassian.net/browse/DEV-5788)
Author:
Reviewer(s):

QAT DEV-5788 remove placeholder tooltips

---

src/js/components/homepage/features/Features.jsx
src/js/components/homepage/features/PaneFeature.jsx
src/js/components/sharedComponents/header/Dropdown.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/components/sharedComponents/header/mobile/MobileDropdown.jsx

Hides the following features until the CARES Act launch constant is set to `true`:
- Homepage content
- Updated info banner
- New indicator in Profiles site navigation

Fix CARES Act homepage dark release

---

src/js/GlobalConstants.js
src/js/components/homepage/features/Features.jsx
src/js/components/homepage/features/PaneFeature.jsx

- Adds a new Global Constant which will allow us to hide certain CARES Act features for phase 1 of launch
- Hides some COVID content on the Homepage for phase 1
- `CARES_ACT_RELEASED: true` +  `CARES_ACT_RELEASED_2: false` = phase 1
- Open to discussion about which environments should have phase 2 "turned on" in the meantime

Add CARES Act phase 2 global constant

---

src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx

Hides the Budget Category section spending view dropdown for phase 1.
[DEV-5813](https://federal-spending-transparency.atlassian.net/browse/DEV-5813), subtask of [DEV-5807](https://federal-spending-transparency.atlassian.net/browse/DEV-5807)
Author:
- N/A Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
Reviewer(s):

DEV-5813 remove budget categories dropdown

---

src/js/components/covid19/budgetCategories/BudgetCategories.jsx

For phase 1, hides the paragraph of the Budget Category section description that references award spending.
[DEV-5813](https://federal-spending-transparency.atlassian.net/browse/DEV-5813), subtask of [DEV-5807](https://federal-spending-transparency.atlassian.net/browse/DEV-5807)
Author:
- N/A Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
Reviewer(s):

DEV-5807 hide part of Budget Category description

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
src/js/components/covid19/DataSourcesAndMethodology.jsx

- Hides the Data Sources & Methodologies page "Linked and Unlinked Award Data" section for phase 1
- Adds coming soon language to the Data Sources & Methodology section of the COVID-19 profile
Author:
Reviewer(s):

DEV-5807 hide "Linked and Unlinked Award Data" section

---

src/js/dataMapping/covid19/recipient/map/map.js

Recipient map territory filters all have a min zoom of 2.
> • create new tileset in mapbox for congressional districts
> • create new tileset in mapbox for counties
> • apply the above tilesets in for respective filters
[DEV-5718](https://federal-spending-transparency.atlassian.net/browse/DEV-5718)
**Mockup:**
N/A
Author:
- …

Dev-5718 Recipient Map Min Zoom Territory Filters 2

---

src/_scss/pages/covid19/recipient/recipientContainer.scss
src/js/components/search/table/ResultsTableErrorMessage.jsx
src/js/containers/covid19/recipient/map/MapContainer.jsx

Adds a fix to mapbox which catches the WebGL error when it isn't supported. The user will see an error only for the mapbox map which instructs to user to enable WebGL if they want to see the visualization.
To test WebGL being disabled, open firefox and go type `about:config` for the url. Then, type `webgl.disabled` in the search bar. Set it to enabled or true.
[DEV-5776](https://federal-spending-transparency.atlassian.net/browse/DEV-5776)
**Mockup:**
N/A
Author:
- [N/A] Verified that this PR does not create any …

DEV-5776 catch WebGL error when not supported

---

src/js/components/covid19/recipient/map/MapWrapper.jsx
src/js/dataMapping/covid19/recipient/map/map.js
src/js/helpers/covid19Helper.js

make colors on Covid19 map more distinct to get a better visual representation of the data 
change scale for Covid19 map to better fit data. changed colors for 6 buckets in covid19 map
[DEV-5819)](https://federal-spending-transparency.atlassian.net/browse/DEV-5819)
Author:
Reviewer(s):

change scale to exponential for covid19 map

---

src/_scss/pages/covid19/recipient/recipientContainer.scss
src/js/components/covid19/recipient/map/MapWrapper.jsx

Added HHS Utah disclaimer underneath Recipients section map.
Edited `MapWrapper.jsx` (added in disclaimer text) and `recipientContainer.scss` (added styling for disclaimer text)
[DEV-5830](https://federal-spending-transparency.atlassian.net/browse/DEV-5830)
**Mockup:**
N/A
Author:
- [`N/A`] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [`N/A`] Added Unit Tests for methods in Container …

Ftr/dev 5830/add disclaimer line about utah to map

---

src/_scss/pages/modals/covid19/_covid19.scss
src/js/containers/covid19/CovidModalContainer.jsx

Adds a disclaimer to the COVID-19 Global modal which links to the (future location of) the Known Data Limitations PDF.
[DEV-5838](https://federal-spending-transparency.atlassian.net/browse/DEV-5838)
**Mockup:**
https://bahdigital.invisionapp.com/share/QMIAEO7UFXT 
Author:
Reviewer(s):

DEV-5838 COVID global modal disclaimer

---

src/js/components/homepage/hero/TotalAmount.jsx
src/js/containers/covid19/CovidModalContainer.jsx

Fixes a typo in the COVID-19 modal disclaimer. 
**Technical Details**
- Also resolves a console error when navigating away from the homepage before the number increments to the total
[DEV-5838](https://federal-spending-transparency.atlassian.net/browse/DEV-5838)
**Mockup:**
https://bahdigital.invisionapp.com/share/QMIAEO7UFXT 
Author:
- N/A Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
Reviewer(s):

DEV-5838 fix typo & console error

---

src/js/components/covid19/DateNote.jsx
src/js/helpers/covid19Helper.js
tests/helpers/covid19Helper-test.js

- Fixes the "Data as of" dates on COVID visualizations
- Changes language from "Data as of" to "Data through"
**JIRA Ticket**
[DEV-5840](https://federal-spending-transparency.atlassian.net/browse/DEV-5840)
Reviewer(s):

DEV-5840 Fix data as of notes

---

src/js/components/covid19/recipient/map/MapWrapper.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/containers/covid19/CovidModalContainer.jsx
src/js/containers/covid19/homepage/CovidFeatureContainer.jsx
src/js/containers/covid19/homepage/CovidHighlights.jsx

- Updates copy for the COVID-19 profile note below the recipient map
- Removes "Official" where it was preceding references to COVID-19 data in the banner, modal, and homepage
[DEV-5830](https://federal-spending-transparency.atlassian.net/browse/DEV-5830)
Author:
- N/A (text changes only) Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- N/A (text changes only) Verified mobile/tablet/desktop/monitor responsiveness
- N/A (text changes only) Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
Reviewer(s):

DEV-5830 final CARES Act phase 2 edits

---

src/_scss/pages/covid19/_budgetCategoriesTable.scss
src/_scss/pages/covid19/_tables.scss

Fixes gap between last column and 2nd to last column in our covid19 tables.
Just css to fix it.
[DEV-5754](https://federal-spending-transparency.atlassian.net/browse/DEV-5754)
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with …

DEV-5754 gap between columns

---

src/js/containers/covid19/recipient/map/MapContainer.jsx

Updates the language of the mapbox webgl error message. See commit diff.
None
N/A
**Mockup:**
N/A
Author:
- [N/A] All `componentWillReceiveProps` and `componentWillMount` …

DEV-5890 Fix/Update mapbox webgl error message

---

src/js/components/search/filters/timePeriod/TimePeriod.jsx

Fixes Time Period Filter message being displayed after filter is deselected. It should be displayed when the filter is selected initially.
[DEV-5031](https://federal-spending-transparency.atlassian.net/browse/DEV-5031)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container Components, …

DEV-5031 Fix Time Period Filter message

---

src/_scss/pages/explorer/detail/sidebar/sidebar.scss
src/js/components/explorer/detail/sidebar/ExplorerSidebar.jsx
src/js/containers/explorer/detail/DetailContentContainer.jsx
src/js/redux/actions/explorer/explorerActions.js
src/js/redux/reducers/explorer/explorerReducer.js
tests/containers/explorer/detail/DetailContentContainer-test.jsx
tests/containers/explorer/detail/mockData.js
tests/redux/reducers/explorer/explorerReducer-test.js

Adds the option to choose periods instead of quarters (when applicable) to the Spending Explorer.
[DEV-5401](https://federal-spending-transparency.atlassian.net/browse/DEV-5401)
**Mockup:**
https://bahdigital.invisionapp.com/share/C8IADXT2BD4#/screens
Author:
Reviewer(s):

[DEV-5041 spending explorer periods

---

src/js/components/covid19/SearchBar.jsx

Currently the search bar is allowing someone to search with whitespace surrounding their search. This causes an issue since for backend the search is trimmed of whitespace. The fix will trim off the whitespace before a user submits the search. If the original search is `TEST` and it is updated to be `TEST      ` then once the user clicks to search the whitespace at the end will be removed from the search reflecting this change in the search bar when they click back in.
Trim whitespace from searched strings after a user is done entering their search term.
[DEV-5796](https://federal-spending-transparency.atlassian.net/browse/DEV-5796)
**Mockup:**
N/A
Author: …

[DEV-5796] Remove whitespace from search bar input

---

src/js/components/search/filters/timePeriod/TimePeriod.jsx

Fixes issue with hint message appearing when it should not in time period advanced search filter.
Added `clearHint` logic in `TimePeriod` to hide the hint message in certain cases cases:
1) When removing a filter at any time, we don't want to show the message
(i.e. removing a date range filter after submitting)
2) When switching active tabs, we don't want to show the message.
[DEV-5031](https://federal-spending-transparency.atlassian.net/browse/DEV-5031)
**Mockup:**
See Melissa's clip in jira ticket above and slack message below:
https://data-transparency-bfs.slack.com/archives/C0149JM6A82/p1598552529007800
Author:
- [N/A] Verified cross-browser compatibility: …

DEV-5031 [FIX] added clear hint logic to hide hint in certain cases in advanced search time period filter

---

src/js/containers/search/filters/TimePeriodContainer.jsx
tests/containers/search/filters/TimePeriodContainer-test.jsx

Fixes case in advanced search Time period filter.
When we only have one checkbox and it is unchecked, we don't want it to show the "Filter Selected" hint message.
Added extra logic to dirtyFilters function for Time Period filter.
[DEV-5031](https://federal-spending-transparency.atlassian.net/browse/DEV-5031)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for methods in Container Components, reducers, helper …

DEV-5031 fix case where unchecking one checkbox would show message

---

src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/containers/search/helpers/searchAnalytics.js

Fixes issue with analytics event firing when users click on DEFC filters without submitting search. We want to see the analytics events with the selected filters only on submission.
Added case for DEFC codes in searchAnalytics.js to get the selected filters on submit
[DEV-5655](https://federal-spending-transparency.atlassian.net/browse/DEV-5655)
**Mockup:**
N/A
Author:
- [`N/A`] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [`N/A`] Added Unit Tests for …

DEV-5655 fixes analytics firing for DEFC filters

---

src/js/components/award/Award.jsx
src/js/components/award/idv/IdvContent.jsx
src/js/components/award/shared/AwardPageWrapper.jsx
src/js/components/award/shared/overview/AwardOverviewRightSection.jsx
src/js/components/award/shared/overview/RelatedAwards.jsx
src/js/containers/award/idv/IdvAwardAmountsSectionContainer.jsx
src/js/helpers/covid19Helper.js
src/js/helpers/idvHelper.js
src/js/models/v2/award/BaseContract.js
src/js/models/v2/award/BaseFinancialAssistance.js
src/js/models/v2/award/BaseIdv.js
src/js/models/v2/award/CoreAward.js
src/js/redux/actions/award/awardActions.js
src/js/redux/reducers/award/awardReducer.js
tests/helpers/idvHelper-test.js
tests/models/award/CoreAward-test.js
tests/redux/reducers/award/awardReducer-test.js

Badge for award summary page is present on awards w/o any DEFC spending.
We're ignoring the `apiPayload.disaster_emergency_fund_codes` and look at the payload response that shows the amount. 
For IDVs, we take into consideration the IDV itself as well as child/grand child awards. What this means practically speaking is that we have to look at the response from two end points, rather than just one like we do for all other award types.
[DEV-5749](https://federal-spending-transparency.atlassian.net/browse/DEV-5749)
Author:
`N/A`Verified …

[DEV-5749] Only Show COVID Badge for Awards with non-zero COVID DEFC Spending

---

src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/header/DetailHeader.jsx
src/js/containers/explorer/detail/DetailContentContainer.jsx
src/js/containers/explorer/detail/table/ExplorerTableContainer.jsx

Prevents adding a hyperlink to agency pages in the spending exploreer if there is no agency profile page for that agency.
[DEV-5939](https://federal-spending-transparency.atlassian.net/browse/DEV-5939)
Author:
Reviewer(s):

[DEV-5939] removes broken links for agencies in spending explorer

---

src/js/containers/search/SearchSidebarSubmitContainer.jsx
tests/containers/search/SearchSidebarSubmitContainer-test.jsx

Yet another bug was found on the search page with the new router. This time, we're making sure that when the user unselects all filters and hits submit, we clear the table.

[router-upgrade-warmfix] Clear table when filters are manually deselected

---

src/js/containers/search/SearchContainer.jsx

Fixes a bug that would not check for download availability.
> • Removes a check for if filters are equal within the check for download availability. The check for download availability is only called once and that effect is already checking if the filters are equal, so the check in the function is a dup.
[DEV-4478](https://federal-spending-transparency.atlassian.net/browse/DEV-4478)

Bug Dev-4478 Advanced Search Download Availability

---

src/_scss/pages/explorer/detail/sidebar/sidebar.scss
src/js/components/explorer/detail/sidebar/ExplorerSidebar.jsx
src/js/containers/explorer/detail/helpers/explorerQuarters.js
src/js/redux/reducers/explorer/explorerReducer.js
tests/containers/explorer/detail/DetailContentContainer-test.jsx
tests/redux/reducers/explorer/mockQuarterHelper.js

Fixes issues w/ period selection on the spending explorer, previously was not selecting the latest closed period, but the latest period in the latest closed quarter.
[DEV-5401](https://federal-spending-transparency.atlassian.net/browse/DEV-5401)
**Mockup:**
https://bahdigital.invisionapp.com/share/C8IADXT2BD4#/screens/296036477
Author:
Reviewer(s):

[DEV-5401] fix css/ period selection

---

src/js/helpers/checkboxTreeHelper.js
tests/helpers/checkboxTreeHelper-test.js

Bug where search results match a top tier level node, but zero children creates console error and weird behavior.getting 
- Adds test case to helper function unit test where the search results are a top tier node with no matching children. 
- Updates helper fn to look for this case and handle it.
[DEV-5229](https://federal-spending-transparency.atlassian.net/browse/DEV-5229)
Author:
`N/A` …

[DEV-5229] Checkbox Tree Bug when Top tier node matches w/o any children

---

src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
src/js/dataMapping/agency/objectClassDefinitions.js
src/js/models/v2/covid19/BaseBudgetCategoryRow.js
src/js/models/v2/covid19/BaseSpendingByCfdaRow.js
src/js/models/v2/covid19/CoreSpendingTableRow.js
tests/models/covid19/BaseBudgetCategoryRow-test.js
tests/models/covid19/BaseSpendingByCfdaRow-test.js
tests/models/covid19/BaseSpendingByRecipientRow-test.js
tests/models/covid19/CoreSpendingTableRow-test.js

Remove special handling for Object Class code since Backend will not supply Object Class code formatted with a `.` after two digits. 
Removed special handling of Object Class and update containers to all use the same property of `CoreSpendingTableRow`. 
[DEV-5444](https://federal-spending-transparency.atlassian.net/browse/DEV-5444)
**Mockup:**
N/A
Author:
Reviewer(s):
**Note**
While this is not linked with a backend PR there is some SQL that I will need to run after this is merged in order to format Object Class code correctly.

[DEV-5444] Update handling of code for object class

---

src/js/components/bulkDownload/awards/AwardDataContent.jsx
src/js/components/bulkDownload/awards/UserSelections.jsx
src/js/components/bulkDownload/awards/filters/AgencyFilter.jsx
src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
src/js/dataMapping/bulkDownload/bulkDownloadOptions.js
src/js/redux/reducers/bulkDownload/bulkDownloadReducer.js
tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx
tests/containers/bulkDownload/mockData.js

Adds radio buttons for funding and awarding agency to custom awards download page.
[DEV-4732](https://federal-spending-transparency.atlassian.net/browse/DEV-4732)
**Mockup:**
N/A
Author: …

DEV-4732 custom award downloads funding and awarding agency

---

src/js/components/covid19/Covid19Tooltips.jsx

PR for fixing spacing issues in tooltip contents.
spaces after periods in award spending sections, splitting award spending into 2 paragraphs to replicate total spending
[DEV-5734](https://federal-spending-transparency.atlassian.net/browse/DEV-5734)
**Mockup:**
https://bahdigital.invisionapp.com/share/KWIAE7IT4H2#/screens
Author:
- [`N/A`] Verified that this PR does not create any …

[DEV-5734] Covid tooltips text fixes

---

src/_scss/pages/award/visualizations/_additionalInfo.scss
src/js/app.jsx
src/js/components/award/shared/additionalInfo/Accordion.jsx
src/js/components/award/shared/additionalInfo/AdditionalInfo.jsx
src/js/components/award/shared/overview/RelatedAwards.jsx
src/js/dataMapping/award/additionalDetailsContract.js
src/js/dataMapping/award/additionalDetailsFinancialAssistance.js
src/js/dataMapping/award/additionalDetailsIdv.js
src/js/helpers/awardSummaryHelper.js
src/js/models/v2/award/BaseParentAwardDetails.js
tests/helpers/awardSummaryHelper-test.js

This PR will implement adding a new component to the additional details section for all awards on awards pages, along with updating the text in the Related Awards section of the overview section and adding a new field in the parent award details section on the awards pages for contracts and idvs.
Added uniqueAwardKey component to all additionalDetails files for the different award types
[DEV-4644](https://federal-spending-transparency.atlassian.net/browse/DEV-4644)
**Mockup:**
https://bahdigital.invisionapp.com/share/ZCIACNTUDER#/screens
Author:
- [`N/A`] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced …

[DEV-4644] - Add 'unique award key' box to Additional Information section of award summary v2.0

---

src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/containers/covid19/SummaryInsightsContainer.jsx
src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
src/js/helpers/covid19Helper.js
src/js/redux/actions/covid19/covid19Actions.js
src/js/redux/reducers/covid19/covid19Reducer.js
tests/helpers/covid19Helper-test.js
tests/redux/reducers/covid19/covid19Reducer-test.js

Update unlinked text to match AC and use Award Count when determining missing awards.
Refactored some to minimize calls to `/api/v2/disaster/award/amount/` since the endpoint is causing a lot of trouble. Instead of multiple calls for the same endpoint there is one call to handle the "All Awards" tab across different visualizations and that one call is stored in the Redux store.
[DEV-5551](https://federal-spending-transparency.atlassian.net/browse/DEV-5551)
[DEV-5549](https://federal-spending-transparency.atlassian.net/browse/DEV-5549)
**Mockup:**
N/A
Author:
Reviewer(s):

[DEV-5551][DEV-5549] Fix wording and some award counts

---

src/js/helpers/metaTagHelper.js

Description for award summary page now refers to the funding rather than awarding agency.
Using different property on redux store `award.overview.fundingAgency.toptierName`
[DEV-5971](https://federal-spending-transparency.atlassian.net/browse/DEV-5971)
Author:
`N/A` Added Unit Tests for methods …

[DEV-5971] using the funding agency for the site description rather than the awarding agency

---

src/js/components/covid19/AmountsVisualization.jsx

Displays outlay labels to the left of the vertical line.
N/A
[DEV-5782](https://federal-spending-transparency.atlassian.net/browse/DEV-5782)
Author:
Reviewer(s):

Dev-5782 Update Outlay Labels to the Left

---

src/js/components/search/table/ResultsTable.jsx
src/js/containers/search/table/ResultsTableContainer.jsx
src/js/dataMapping/search/awardTableColumns.jsx

This new column surfaces only COVID DEFC (i.e., L, M, N, O, P). A follow-up ticket will allow all DEFC to be accessed
Created new column in ResultsTable.jsx that retrieves the def_codes from API
[DEV-5766](https://federal-spending-transparency.atlassian.net/browse/DEV-5766)
**Mockup:**
https://federal-spending-transparency.atlassian.net/browse/DEV-5766
Author:
- [`N/A`] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future compatible life-cycle …

[DEV-5766] Advanced Search DEFC column

---

src/js/helpers/metaTagHelper.js

- Agency Name in Award Summary Page description was undefined b/c the api response is different for ASST_AGG type awards.
- Fixing site title for Spending Explorer 
- Adds conditional/null check to handle AST_AGG awards.
[DEV-5971](https://federal-spending-transparency.atlassian.net/browse/DEV-5971)
Author:
`N/A`Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
`N/A` Verified that this PR does not create any *new* accessibility issues (via Axe Chrome …

[DEV-5971] Updating Spending Explorer Site Title and Agency Title Description for ASST_AGG Awards

---

src/js/components/explorer/detail/DetailContent.jsx
src/js/components/explorer/detail/header/DetailHeader.jsx
src/js/components/explorer/detail/header/TruncationWarning.jsx
src/js/components/explorer/detail/visualization/ExplorerVisualization.jsx
src/js/components/explorer/detail/visualization/treemap/ExplorerTreemap.jsx
src/js/containers/explorer/detail/DetailContentContainer.jsx
src/js/helpers/apiRequest.js
src/js/helpers/explorerHelper.js
tests/containers/explorer/detail/DetailContentContainer-test.jsx
tests/containers/explorer/detail/mockExplorerHelper.js
tests/helpers/explorerHelper-test.js

When we truncate results on the treemap (we limit it at 500 cells in the treemap), we are adding a new cell representing all other cells outside the top 500. This ensures that the top 500 display the proper proportions relative to the overall total.
-  Truncating results at container level
- Also truncating results for recipients
- New helper to append special representational cell
- Tests added as well
[DEV-5590](https://federal-spending-transparency.atlassian.net/browse/DEV-5590)
Author:
`N/A` Verified that this PR …

[DEV-5590] Adding Special Treemap Cell to Spending Explorer to make Truncated Results Proportional

---

src/js/models/v2/award/BaseAwardAmounts.js
tests/models/award/BaseAwardAmounts-test.js
tests/models/award/mockAwardApi.js

Quick fix for demo of bug in prod. Including `grandchild_*` in calculation of defc award amounts.
We were ignoring the grandchild property in this response ☝️ 
-  `concat()` child and grandchild arrays in award amount model. 
- adds test
[DEV-5570](https://federal-spending-transparency.atlassian.net/browse/DEV-5570)
Author:
`N/A`Verified that this PR does not create any *new* accessibility issues …

[DEV-5570] IDV Aggregate Award Amounts now includes grand child (Was only looking at children)

---

src/js/containers/award/idv/ReferencedAwardsContainer.jsx
tests/containers/award/mockAward.js

The referenced awards container expects `this.props.award.counts` to be defined, then makes at network request to populate the `Orders Under this IDV` table.
This key on the award object was changed so it is now never defined.
This PR updates the container to look for `this.props.award.idvDetails` instead of `this.props.award.counts`.
Updates methods to look at `idvDetails` instead of `counts`. Updates mockData as well.
[DEV-4976](https://federal-spending-transparency.atlassian.net/browse/DEV-4976)
(@BrianZito found this bug when working this ticket)
Author:
`N/A` Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR …

[DEV-4976] updating key on award object in Referenced Awards Container from counts to idvDetails

---

src/js/containers/AppContainer.jsx
src/js/helpers/analytics/Analytics.js

The custom router did this, we removed the functionality. Currently, all we do is log page views the first time the user loads the site.
When the component loads, we log the pathname
[DEV-6182](https://federal-spending-transparency.atlassian.net/browse/DEV-6182)
Author:
`N/A` All …

[DEV-6182] logging pageviews when a user changes their route via client side router

---

src/js/components/search/table/ResultsTableTabItem.jsx

When a tab is highlighted/selected on the recipient profile landing page, the API call triggers on every key press. This PR resolves the bug by preventing multiple API calls on each key press and only allowing the call to trigger when a user hits enter on the highlighted tab.
Added onKeyDownHandler to ResultsTableTabItem to ensure we are only fetching from API on 'enter'
[DEV-6188](https://federal-spending-transparency.atlassian.net/browse/DEV-6188)
Author:
- [`N/A`] Added Unit Tests for methods in Container Components, reducers, helper …

[DEV-6188] Recipient Profile Landing Page 'gathering your data' triggers every time a key is pressed after clicking tab

---

src/_scss/components/tooltips/_customTooltipContent.scss
src/_scss/components/tooltips/_index.scss
src/_scss/components/visualizations/tooltip/_arrow.scss
src/_scss/layouts/search/header/_downloadButton.scss
src/_scss/layouts/tabbedSearch/header/_downloadTooltip.scss
src/_scss/pages/award/shared/contractGrantsActivity.scss
src/_scss/pages/covid19/visualizations/_amounts.scss
src/js/components/covid19/AmountsVisualization.jsx
src/js/components/covid19/Covid19Tooltips.jsx
src/js/containers/covid19/homepage/CovidHighlights.jsx

After updating the component library tooltip, there were some styling issues:
- COIVD Profile Viz tooltips
- Covid Profile Section Headers
- Spending Explorer tooltips 
Also cleaned up the home page tooltip.
- Biggest change is to the positioning of the Covid Profile Viz tooltips
- All other changes are trivial styling changes / html class name changes
[DEV-2698](https://federal-spending-transparency.atlassian.net/browse/DEV-2698)
Author:
`N/A`Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
`N/A` …

[DEV-2698] Fixing some Tooltip Styling issues 

---

src/js/components/award/shared/awardAmountsSection/charts/AwardAmountsChart.jsx

Remove the "Non-Federal Funding" label in the Award Amounts chart in the Award Summary page* if and only if it is $0*.
Added conditional in chartProps list to only display non-federal funding when awardAmounts._nonFederalFunding is not equal to zero. This field will not render if it is zero.
[DEV-5936](https://federal-spending-transparency.atlassian.net/browse/DEV-5936)
**Mockup:**
screenshot in JIRA link
Author:
- [`N/A`] All `componentWillReceiveProps` and `componentWillMount` in relevant child/parent components/containers replaced with [future …

[DEV-5936] When $0, remove "Non-Federal Funding" labels from Award Summary > Award Amounts chart

---

src/js/containers/explorer/detail/helpers/explorerQuarters.js
tests/containers/explorer/detail/helpers/explorerQuarters-test.js

Fixes a bug where the  fiscal period was being determined incorrectly on the spending explorer page
[DEV-6220](https://federal-spending-transparency.atlassian.net/browse/DEV-6220)
Author:
Reviewer(s):

[DEV-6220] fix month determining bug

---

src/js/components/award/financialAssistance/RectanglePercentViz.jsx
src/js/components/award/shared/awardAmountsSection/charts/SharedBarComponents.jsx

Tooltip doesn't update when mousing over from right to left.
The real fix here is not invoking closeTooltip except for in the parent-most bar. We only need it here because if you're not leaving the parent-most bar, then we don't need to close the tooltip, we just need to update the tooltip content.
[DEV-2698](https://federal-spending-transparency.atlassian.net/browse/DEV-2698)
Author:
`N/A` …

[DEV-2698] Award Amounts Viz Tooltips: showing tooltip going left -> right

---

src/js/containers/Footer.jsx

This PR removes the second occurrence of data dictionary in the resources section so it correctly displays:
Data Dictionary
Data Model
Data Lab
Fiscal Data
[DEV-6108](https://federal-spending-transparency.atlassian.net/browse/DEV-6108)
Author:
- [`N/A`] Verified that this PR does not create any *new* accessibility issues (via …

[DEV-6108] Data dictionary listed twice bug

---

jest.config.js
src/js/containers/search/SearchContainer.jsx
tests/components/covid19/homepage/TotalAmount-test.jsx
tests/containers/search/SearchContainer-test.jsx
tests/containers/search/filters/searchHelper.js
tests/testResources/test-utils.js

- On Advanced Search in QAT, the hash url page (`/search/234qkd234`) was not loading the search
- On Advanced search in PROD, the hash url page was generating a duplicate hash for the same search
changing useEffect conditional logic:
- caller of generateHash updated to look at appliedFilters property in redux for source of truth
- caller of history.replace() updated to look at new previousProps ref & areAppliedFiltersEmpty prop in redux for source of truth
[DEV-6238](https://federal-spending-transparency.atlassian.net/browse/DEV-6238)
Author: …

[DEV-6238] Advanced Search Hash Url (a) Loads search and (b) doesn't generate duplicate hash

---

src/js/dataMapping/search/awardTableColumns.jsx

This PR resizes the column widths of the start and end date columns so they take up less horizontal space
Specify column widths in `awardTableColumns`
[DEV-6246](https://federal-spending-transparency.atlassian.net/browse/DEV-6246)
Author:
- [`N/A`] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [`N/A`] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [`N/A`] [Component Library Integration Status …

[DEV-6246] Advanced Search Results Column Width: Start and End Date

---

src/js/containers/search/SearchSidebarSubmitContainer.jsx
src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx
src/js/helpers/checkboxTreeHelper.js
src/js/redux/reducers/search/naicsReducer.js
src/js/redux/reducers/search/pscReducer.js
src/js/redux/reducers/search/tasReducer.js
tests/containers/search/SearchSidebarSubmitContainer-test.jsx

NOTE: This PR contains #2165 
Handle the case where:
(a) performs a search in a checkbox tree
(b) checks some results
(c) submits the search without clearing it out  -- or -- (c2) resets the search filters w/o clearing out the checkbox tree search
- 62701ba when a user submits a search, that unMounts the component b/c we go to a new url; onUnmount, show all nodes in the tree
- e629f22 if a user selects `reset search` on the search page to clear out all filters, clear out checked expanded etc... and show all nodes in the tree
Code cleanup:
- e629f22 NAICS was not listening for the global `CLEAR_ALL_FILTERS` action type. Now we are
- 9f90602 `showAllNodes` was not recursive as much as it should've been. Making it more so. …

[DEV-5489] Handle when user does not clear their own search in a Checkbox Tree

---

src/js/components/account/Account.jsx
src/js/components/account/AccountOverview.jsx
src/js/components/agency/AgencyContent.jsx
src/js/components/agency/overview/AgencyOverview.jsx
src/js/containers/agency/visualizations/ObligatedContainer.jsx
src/js/helpers/fiscalYearHelper.js

-  Missed a place we were using active FY in the federal account page.
-  Implementing for the agency page. Misunderstood tony about the APIs response for agency detail data.
- 59dc79c using existing prop on federal account detail pg
- e40bc97 reusing WithLatestFy container in agency page
[DEV-6269](https://federal-spending-transparency.atlassian.net/browse/DEV-6269)
**Mockup:**
Author:
`N/A`Verified …

[DEV-6269] Quick Follow Up for Agency and Account Pg

---

src/js/GlobalConstants.js
src/js/components/about/DataQuality.jsx
src/js/components/bulkDownload/accounts/AccountDataContent.jsx
src/js/dataMapping/navigation/menuOptions.jsx
src/js/models/v2/state/BaseStateProfile.js
tests/models/state/BaseStateProfile-test.js
webpack/webpack.common.js

To support the DTI migration hard coded links links to S3 resources have been updated to support specifying DTI in the URL.
Added a new ENV for `FILES_SERVER_BASE_URL` to specify the S3 resources URL. This removes the need to check `ENV` each time the S3 link is referenced and also allows for us to specify DTI as part of the server URL to support migration efforts. 
Currently labeled as `do not merge` until config PRs are made and merged.
[BRUS2DTI-419](https://federal-spending-transparency.atlassian.net/browse/BRUS2DTI-419)
**Mockup:**
N/A
Author:
Reviewer(s):

[BRUS2DTI-419] Add new ENV to specify DTI

---

Dockerfile

Given we bumped node to v12, we do not need to install a specific version of npm anymore since node v12 comes with npm v6.12 and npm install alias was created in npm v6.9. 
https://nodejs.org/en/blog/release/v12.13.0/ 
https://npm.community/t/release-npm-6-9-0/5911

remove npm i

---

src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx

Fixes Federal Account links in the Budget Category table on the COVID profile page.
Reviewer(s):

Hotfix Budget Category table Federal Account links

---

src/js/components/sharedComponents/metaTags/MetaTags.jsx
src/js/containers/AppContainer.jsx
src/js/helpers/analytics/Analytics.js

This PR addresses the bug in production with GA logging mismatched page titles
Moving pageview firing logic to `MetaTags.jsx` so that the pageview event is fired only after the correct page title has been generated
[DEV-6355](https://federal-spending-transparency.atlassian.net/browse/DEV-6355)
**Mockup:**
N/A
Author:
- [`N/A`] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [`N/A`] Added Unit Tests for helper functions, reducers, models and Container/Component …

[DEV-6355] GA Pageview title logging bug

---

src/js/components/bulkDownload/BulkDownloadPage.jsx
src/js/components/recipient/RecipientPage.jsx
src/js/components/sharedComponents/metaTags/MetaTags.jsx
src/js/containers/agency/AgencyContainer.jsx
src/js/containers/recipient/RecipientContainer.jsx
src/js/containers/state/StateContainer.jsx
src/js/redux/reducers/recipient/recipientReducer.js

Fixes bug where previous state/recipient/agency/account page titles were logged under the url.
82b0665 using componentWillUnmount to clear out redux for agency, state, account & recipient pages
936aa98 using helper fn and prevProps to determine when to log a new page view (we have to wait for react and the API in some cases)
510111f removing let declarations resulting in unwanted side-effects
[DEV-6355](https://federal-spending-transparency.atlassian.net/browse/DEV-6355)
Author:
`N/A`Verified that this PR does not …

[DEV-6355] Google Analytics Page Views for Dynamic Page Titles

---

src/js/components/homepage/download/DownloadDetail.jsx
src/js/dataMapping/navigation/menuOptions.jsx

Fixes three homepage links in the download section.
Adds another prop to the `DownloadDetail` component to denote an internal link at a different domain (files.usaspending.gov, api.usaspending.gov).
[DEV-6441](https://federal-spending-transparency.atlassian.net/browse/DEV-6441)
Author:
Reviewer(s):

Warmfix DEV-6441 homepage links to files.usaspending.gov

---

src/_scss/layouts/default/header/_warning.scss
src/js/containers/covid19/Covid19Container.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx

Fix one API request error preventing the rest of the COVID-19 Budget Categories table data from loading and remove the "Unlinked Awards" row from the Award Spending view.
- Added a try/catch block to the award amounts request to match the format of other requests
- Removes the check for total award count (populated by the endpoint that was 504-ing) that was previously required to load table data
- Also fixes a z-index issue that was causing the loading message to display on top of the sticky banner
**JIRA Tickets:**
- [DEV-6420](https://federal-spending-transparency.atlassian.net/browse/DEV-6420)
- [DEV-6414](https://federal-spending-transparency.atlassian.net/browse/DEV-6414) …

DEV-6420 & DEV-6414 COVID Budget Category table resiliency

---

package-lock.json
package.json
src/js/containers/covid19/recipient/SpendingByRecipientContainer.jsx

#2244 
#2243 
Change in `dev` that updated the component library to v 1.3.1 came into conflict with `qat` change that updated to v 1.3.2. This branch resolves the conflict and uses v 1.3.2. The branch was based off of `dev` and `qat` was merged into it.

Demote warmfixes qat -> dev w/ resolved merge conflicts

---

src/js/components/search/visualizations/time/TimeVisualizationSection.jsx

Update wording for Adv Search Time tab tooltip to "Download a CSV of award spending data that matches your search criteria, broken down by year. For complete download results, click on the “Download” button on the top right of this page."
none
[DEV-6486]https://federal-spending-transparency.atlassian.net/browse/DEV-6486)
**Mockup:**
none
Author:
Reviewer(s):

dev-6486 remove "10,000 results" wording from tip

---

src/_scss/pages/aboutTheData/agencyDetailsPage.scss
src/js/components/aboutTheData/AgencyDetailsPage.jsx
src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
src/js/containers/router/RouterRoutes.js
src/js/helpers/agencyV2Helper.js
src/js/models/v2/agencyV2/BaseAgencyOverview.js
tests/models/agency/BaseAgencyOverview-test.js

Refactors the single Agency Submission Statistics page in preparation for API integration. 
- Separates the Agency page UI from the table container
- Adds a mock API request to populate agency name, website, and profile page url based on the toptier code url parameter
- Uses mock data since the `id` property still needs to be added to `v2/agency/{toptier_code}` response (to link to v1 agency profile pages)
- Minor styling updates
[DEV-6488](https://federal-spending-transparency.atlassian.net/browse/DEV-6488)
**Mockup:**
https://bahdigital.invisionapp.com/share/D5IAFOD4YUN#/296052487_003__Publication-Dates-To-SBA
Author:
- N/A [API …

DEV-6488 Agency Submission Statistics refactor (part 1)

---

src/_scss/pages/modals/aboutTheData/_aboutTheData.scss
src/_scss/pages/modals/covid19/_cfdaTable.scss

Fixes a bug that overrides default modal size.
N/A
[DEV-6516](https://federal-spending-transparency.atlassian.net/browse/DEV-6516)
Author:
Reviewer(s):

Dev-6516 Default Modal Size

---

src/js/components/search/visualizations/time/TimeVisualizationSection.jsx

Warmfix: https://federal-spending-transparency.atlassian.net/browse/DEV-6486 (dev PR is https://github.com/fedspendingtransparency/usaspending-website/pull/2278)
Fix "broken down by year" to show year/quarter/month as appropriate.

dev-6486 final wording fix

---

src/js/models/v2/aboutTheData/BaseAgencyRow.js
tests/models/aboutTheData/BaseAgencyRow-test.js

Was looking at the wrong property.
[DEV-6449](https://federal-spending-transparency.atlassian.net/browse/DEV-6449)
Author:
`N/A` [Component Library …

[DEV-6449] Count of Agency TAS in GTAS Not in File A using correct property on API response

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/TimeFilters.jsx
src/js/containers/router/RouterRoutes.js
tests/components/aboutTheData/AboutTheDataPage-test.jsx
tests/components/aboutTheData/TimeFilters-test.jsx

Redirecting `about-the-data/agencies` to a url with the latest fy and period selected
f2e79ee - Adds new paths for the about-the-data page component
5327882 -- TimeFilters refactor to take submissionPeriods and dataAsOf as props
- AboutTheDataPage passes props ☝
- AboutTheDataPage useEffect to look for impartial urls
Note on test coverage:
Trying to mock out react-router-dom didnt go well.
The helper the useEffect relies on is tested
and should be adequate for our coverage. That said,
ideally we should have a test for this. I'm considering
it a "nice to have" for now.
[DEV-6535](https://federal-spending-transparency.atlassian.net/browse/DEV-6535)
Author:
`N/A` …

[DEV-6535] Handling partially defined urls (no fy or period urlParams)

---

package-lock.json
package.json
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
tests/components/sharedComponents/InfoBanner-test.jsx

Sets up the following sitewide banners:
- Pre-migration message on 1/4
- Maintenance message on 1/8
- Switch back to the current COVID banner on 1/14
- Uses a new library, `date-fns` to handle date logic (since `moment.js` is considered a legacy project)
- Changes the cookie each time the banner updates so it will re-appear to users who have previously closed the old banner
- Removes phased COVID release logic
Pre-migration message [DEV-6558](https://federal-spending-transparency.atlassian.net/browse/DEV-6588), Maintenance message [DEV-6576](https://federal-spending-transparency.atlassian.net/browse/DEV-6576), change back to COVID banner [DEV-6577](https://federal-spending-transparency.atlassian.net/browse/DEV-6577). …

Hotfix DEV-6558, DEV-6576, DEV-6577 migration banners

---

src/js/components/search/visualizations/geo/MapWrapper.jsx
src/js/helpers/mapHelper.js
tests/helpers/mapHelper-test.js

Fixes a bug where in rare edge cases, the Advanced Search map would throw an error resulting in a blank screen. E.g. https://www.usaspending.gov/search/13bd5bf59da6f9c844a8b20bc364895a. 
`MapWrapper` groups dollar values into 6 ranges represented by different colors on the map using the helper function `calculateRanges`. 
Old (flawed) approach: 
1. Determine the upper bound for our legend by rounding up the maximum dollar value in our data to an integer that is divisible by 6 * `unit` for the range of values (thousand, million, etc.)
2. Use d3 `scaleLinear` to convert each dollar value to a floating point number between 0 and 6
3. Use `Math.floor` to round down to the index of an array representing that bucket
4. Push the corresponding …

Hotfix DEV-6575 map error

---

Dockerfile

removing unused volume from dockerfile
We do not use the volume mount when building the application  (we instead mount a volume at /node-workspace/public) and removing the creation of the volume during the docker build process reduces the build time significantly.
Reviewer(s):

removing VOLUME directive from the dockerfile

---

src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
tests/components/sharedComponents/InfoBanner-test.jsx

Since the migration was completed a day early, change the sitewide banner back to the COVID-19 message.
Also went ahead and removed the date logic since it is no longer necessary.
[DEV-6577](https://federal-spending-transparency.atlassian.net/browse/DEV-6577)
Author:
Reviewer(s):

DEV-6577 Hotfix reset info banner

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/TimeFilters.jsx
src/js/components/account/Account.jsx
src/js/components/agency/AgencyContent.jsx
src/js/components/covid19/DateNote.jsx
src/js/components/sharedComponents/QuarterPickerWithFY.jsx
src/js/components/sharedComponents/pickers/FYPicker.jsx
src/js/containers/account/AccountContainer.jsx
src/js/containers/account/WithLatestFy.jsx
src/js/containers/account/filters/AccountTimePeriodContainer.jsx
src/js/containers/accountLanding/AccountLandingContainer.jsx
src/js/containers/agency/visualizations/ObligatedContainer.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/containers/covid19/homepage/CovidHighlights.jsx
src/js/helpers/accountHelper.js
src/js/propTypes/index.js
src/js/redux/actions/account/accountActions.js
src/js/redux/reducers/account/accountReducer.js
tests/components/aboutTheData/AboutTheDataPage-test.jsx
tests/components/aboutTheData/TimeFilters-test.jsx
tests/containers/account/AccountContainer-test.jsx
tests/containers/account/filters/AccountTimePeriodContainer-test.jsx
tests/containers/accountLanding/AccountLandingContainer-test.jsx
tests/containers/covid19/homepage/CovidHighlights-test.jsx
tests/redux/reducers/account/accountReducer-test.js

This has been attempted by me twice. I made some mistakes and am now taking all of @jonhill13 's advice on his initial review of this.
-  Update redux to just have `submissionPeriods` from [the endpoint](https://api.usaspending.gov/api/v2/references/submission_periods/). I kept this in the `redux.account` key space because this data is strictly related to account data.
- In all the various places where account data is displayed, use redux as the source of truth and leverage existing unit-tested helpers to extract the following details: (a) the calendar date of the most recent submissions (this data is accurate as of...), (b) the latest Fiscal Year; (c) the latest fiscal period; (d) t he. latest fiscal quarter. 
This PR will be much easier …

[DEV-6609] Ensuring Fiscal Year for Account Data is Accurate in drop downs, tables, and Network Calls

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
tests/containers/aboutTheData/AgenciesContainer-test.jsx

Change signature of `getTableData()` to accept boolean input, by default false, which indicates wherether we should `goToFirst` page.
Tests were failing b/c previous implementation was creating duplicate API calls and breaking tests.
cb6477f
[DEV-6378](https://federal-spending-transparency.atlassian.net/browse/DEV-6378)
Author:
`N/A` Verified that this PR does not create any *new* accessibility …

[DEV-6378] Update currentPage to 1 when searchTerm Changes (About the Data Search when paginated)

---

src/js/containers/Footer.jsx

Re-organizing/deleting links in footer.
994d190
- Removing the Resources tab
- Add our sites as the last option in footer w/ links to fiscal data
and data lab
- Under developers tab, adding release notes
[DEV-6291](https://federal-spending-transparency.atlassian.net/browse/DEV-6291)
Author:
`N/A` …

[DEV-6291] Updating footer Links

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/helpers/aboutTheDataHelper.js

Updating limit/sort did not reset to page one. 
82aa75a
Refactoring logic for fetching new data:
-- (a) trigger a request when page changes
-- (b) go to page one when sort/limit/search changes
-- (c) when sort/limit/search changes and on page one,
refetch.
Refactoring "usePagination":
-- exposing methods that update specific properties in
the paginationObj { page, limit, totalItems }, rather than
one method that updates every property with a new object.
-- only updating totalItems in API response then() block.
Updating the page/limit is redundant.
[DEV-6449](https://federal-spending-transparency.atlassian.net/browse/DEV-6449)
Author:
`N/A` Verified cross-browser …

[DEV-6449] refactoring logic for fetching new data & custom hook "usePagination"

---

src/js/helpers/aboutTheDataHelper.js
tests/helpers/aboutTheDataHelper-test.js

Differences Modal Use Decimals
[DEV-6533](https://federal-spending-transparency.atlassian.net/browse/DEV-6533)
**Mockup:**
N/A
Author:
- [N/A] …

Dev-6533 Differences Modal Use Decimals

---

src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx

Custom Account Download FY Period Quarter Picker is fully functional.
The `period` and `quarter` property are being stored as null values. This updates the logic to falsey.
[DEV-6364](https://federal-spending-transparency.atlassian.net/browse/DEV-6364)
**Mockup:**
N/A
Author:
- [N/A] …

Bug-6364 Custom Account Download FY Period Quarter Picker

---

src/_scss/pages/aboutTheData/aboutTheData.scss
src/js/containers/aboutTheData/AgencyTableMapping.jsx

Prevents Unlinked Award column tooltips from getting cut off at the bottom of About the Data tables by making them wider.
The component library `wide` prop fills available space based on the width of the container. In this case, the width of the column itself caused the tooltip to actually get narrower when using that prop. This change overrides the width with USAS css using the `className` prop.
[DEV-6593](https://federal-spending-transparency.atlassian.net/browse/DEV-6593)
Author:
Reviewer(s):

DEV-6593 About the Data tooltips bug

---

src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
tests/containers/aboutTheData/AgencyDetailsContainer-test.jsx
tests/containers/aboutTheData/mockData.js
tests/models/aboutTheData/BaseReportingPeriodRow-test.js

Changes the single Agency Submission Statistics table default sort to the Reporting Period column
Reporting Period column correlates to sorting by `fiscal_year`, [DEV-6771](https://federal-spending-transparency.atlassian.net/browse/DEV-6771) will add fiscal period as secondary sort on the backend.
[DEV-6773](https://federal-spending-transparency.atlassian.net/browse/DEV-6773)
**Mockup:**
https://bahdigital.invisionapp.com/share/5BIAFVV7KUX#/296054014_003__All-Statistics-To-SBA
Author:
Reviewer(s):

DEV-6773 Agency Stats table default sort

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
tests/containers/aboutTheData/AgenciesContainer-test.jsx

Reset to page one on fy/period change.
A couple parts to this:
(1) get previous page # so we dont make duplicate requests on first render. (see line 207)
(2) Tests needed to be updated so that the rerender is always expected to also call submissionsRequest (see line 181, for instance)
[DEV-6739](https://federal-spending-transparency.atlassian.net/browse/DEV-6739)
Author:
`N/A` [API …

[DEV-6739] About the Data Overview Table Reset to Page 1 on FY/Period change

---

src/js/models/v2/aboutTheData/BaseAgencyRow.js
src/js/models/v2/aboutTheData/PublicationOverviewRow.js
tests/containers/aboutTheData/mockData.js

Updates the name of an API field.
**Technical Details**
Also fixes a bug with links from the "Updates by Fiscal Year" tab (expecting `code` when field was `_code`)
[DEV-6758](https://federal-spending-transparency.atlassian.net/browse/DEV-6758), subtask of [DEV-6714](https://federal-spending-transparency.atlassian.net/browse/DEV-6714)
Author:
Reviewer(s):

DEV-6758 update toptier_code field

---

src/_scss/pages/account/overview/overview.scss
src/js/components/account/AccountOverview.jsx
src/js/models/account/FederalAccount.js
src/js/redux/reducers/account/accountReducer.js

Removes the `Account Description` section from Federal Account profiles.
- Removes description field from our data model
- Simplified HTML & scss for the overview section
- Fixed an accessibility issue with the heading
[DEV-6853](https://federal-spending-transparency.atlassian.net/browse/DEV-6853)
Author:
Reviewer(s):

[DEV-6853] Remove Account Description

---

src/js/components/account/AccountOverview.jsx
src/js/containers/account/AccountContainer.jsx
tests/containers/account/AccountContainer-test.jsx

(warmfix version of #2391)
Fixes a bug that sometimes prevented the overview data from displaying on initial load of the Federal Account profile page.
At first I went down a rabbit hole of refactoring and there is a lot that _could_ be improved with this page. The root of the problem was [here](https://github.com/fedspendingtransparency/usaspending-website/compare/fix/dev-6852-fed-account-bug?expand=1#diff-063e6d3c48538b3cd3ab557395678c9a5a2a726eaa432dab5c9fd3ea99cba8edL54). `AccountContainer` makes two API requests, one for the account overview info (internal id, name, etc) and one for the monetary values (budget authority, obligations, etc). They both are stored in the `account.account` object in redux. The bug occurred when `totals` …

[DEV-6852] Warmfix Federal Account profile bug

---

scripts/sitemaps/buildSitemap.js
scripts/sitemaps/pages.js

Sitemaps are only generated for prod currently. looking to make the process configurable so we can deploy sitemap files and test bot crawling in lower environments as well.
The defaults will keep the script running as normal in production without any additional changes to pipeline code. However, once [this pr](https://github.com/fedspendingtransparency/usaspending-config/pull/1018) is merged in as well, we will be able to select the environment and the backend API independently of one another and generate / deploy a sitemap suitable for the configuration.
[OPS-1678](https://federal-spending-transparency.atlassian.net/browse/OPS-1678)
**Mockup:**
N/A
Author:
- [N/A] …

making sitemapscript configurable for different environments

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
tests/containers/aboutTheData/AgenciesContainer-test.jsx

Refactoring in 611cb3f broke the logic where we call `fetchTotals` and populate this column. SS:
See commit message
[DEV-6739](https://federal-spending-transparency.atlassian.net/browse/DEV-6739)
Author:
`N/A` [Component Library Integration Status …

[DEV-6739] Populate Percent of Total Federal Budget Column

---

src/js/components/sharedComponents/DatePicker.jsx

Fixes an error in the date picker on the advanced search page where if a user updates the month to not include the currently selected date and tries open the date picker will break the page.
> • Check for selected day element before focusing on it.
[DEV-4400](https://federal-spending-transparency.atlassian.net/browse/DEV-4400)
**Mockup:**
N/A
Author:
- [N/A] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if …

Dev-4400 Date Picker Bug

---

src/js/components/aboutTheData/AboutTheDataPage.jsx

Adds the share icon to the page header
Screenshots:
Reusing existing component and styles.
[DEV-6815](https://federal-spending-transparency.atlassian.net/browse/DEV-6815)
Author:
`N/A` Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if …

[DEV-6815] Adding Share Icon to About The Data Pg

---

jest.config.js
src/js/containers/aboutTheData/modals/PublicationDatesContainer.jsx
src/js/helpers/aboutTheDataHelper.js
tests/helpers/aboutTheDataHelper-test.js

Showing EST calendar date from timestamp on table and UTC calendar date from timestamp in modal.
see commit message
[DEV-6805](https://federal-spending-transparency.atlassian.net/browse/DEV-6805)
Author:
`N/A` Added Unit Tests for helper functions, reducers, models and Container/Component …

[DEV-6805] About the data row and modal date discrepancy

---

src/_scss/components/_stickyTable.scss

Vertically aligns values when non-zero cells (with a modal button) are in the same column as "generic" cells (without a modal button) in the Submission Statistics tables.
* Calculated based on the width of the button and the padding to add space between the cell value and the button.
[DEV-6909](https://federal-spending-transparency.atlassian.net/browse/DEV-6909)
**Mockup:**
https://bahdigital.invisionapp.com/share/5BIAFVV7KUX#/296054033_Hover__Unlinked-Assistance
Author:
Reviewer(s):

[DEV-6909] fix padding on generic cells

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/AgencyDetailsPage.jsx
src/js/helpers/aboutTheDataHelper.js
tests/helpers/aboutTheDataHelper-test.js

Forgot to add the share icon to the agency specific page.
Using conditional rendering to wait for the API to resolve so we have the agency name to include in the email.
Screenshot:
[DEV-6815](https://federal-spending-transparency.atlassian.net/browse/DEV-6815)
Author:
Reviewer(s):

[DEV-6815] Adding Share Icon to Agency Detail pg

---

src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
src/js/containers/aboutTheData/AgencyTableMapping.jsx

On the single agency submission statistics page, fixes sorting on the Unlinked Awards columns. 
Also clears the error message when a network error is followed by a successful subsequent request.
[DEV-6930](https://federal-spending-transparency.atlassian.net/browse/DEV-6930)
Author:
Reviewer(s):

[DEV-6930] Fix Unlinked Awards column sort

---

src/js/helpers/stickyHeaderHelper.js

Fixes a bug when the covid banner will cover the main nav when scrolling down the page then back up.
> • removes the `isSticky` condition from the false `isSticky` conditional.
[DEV-6876](https://federal-spending-transparency.atlassian.net/browse/DEV-6876)
**Mockup:**
N/A
Author:
- [N/A] [API …

Dev-6876 Covid Banner Floating Off Course

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
tests/containers/aboutTheData/AgenciesContainer-test.jsx

Fixes a bug that was causing the search to persist even after navigating away from the page. 
[DEV-6929](https://federal-spending-transparency.atlassian.net/browse/DEV-6929)
Author:
Reviewer(s):

[DEV-6929] fix persistent Submission Statistics search string

---

src/js/helpers/moneyFormatter.js
src/js/models/v2/aboutTheData/CoreReportingRow.js
tests/helpers/moneyFormatter-test.js
tests/models/aboutTheData/CoreReportingRow-test.js

Refactoring Submission Statistics Table model and heleprs to distinguish between falsy values. Tests included
See commit messages:
CoreReportingRow.js -- preserving raw values in our underscore
prefixed model properties. These values are later passed to
helper functions that parse the falsy values for us.
+ tests added to confirm the return value for various falsy values
moneyFormatter.js -- formatMoneyWithPrecision refactored to
allow the caller to specify a return value when invalid value is
passed. This follows the precedent set by calculatePercentage.
+ tests added to confirm the return value for various falsy values
[DEV-6951](https://federal-spending-transparency.atlassian.net/browse/DEV-6951)
The following are ALL …

[DEV-6951] Handling falsy values from API for data that represents dollar amounts:

---

src/js/helpers/moneyFormatter.js
src/js/models/v2/aboutTheData/BaseAgencyRow.js
src/js/models/v2/aboutTheData/PublicationOverviewRow.js
tests/helpers/moneyFormatter-test.js

When value is greater than zero, but it gets rounded to zero by the accounting library, show an absolute minimum
See commit message
[DEV-6952](https://federal-spending-transparency.atlassian.net/browse/DEV-6952)
Author:
Reviewer(s):

[DEV-6952] moneyFormatter.calculatePercentage refactor to accept absolute minimum

---

src/js/components/about/AboutContent.jsx
src/js/components/sharedComponents/sidebar/Sidebar.jsx
tests/components/about/AboutContent-test.jsx

Fixes two bugs with the sidebar:
- Overlap with main content after scrolling (in `dev`) caused by a DEV-6356 change
- Active section not highlighting as you scroll (in `qat`)
[DEV-6356](https://federal-spending-transparency.atlassian.net/browse/DEV-6356)
Author:
Reviewer(s):

DEV-6356 fix sidebar overlap

---

tests/helpers/aboutTheDataHelper-test.js

Instead of checking the timezone offset value which changes based
on whether or not we're in DST, we check for the string value of the
current timezone, which is America/New York.

[DEV-6881] fixing time-sensitive broken test.

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Reverting #2437 
Restores https://github.com/fedspendingtransparency/usaspending-website/pull/2437/files#diff-b3e290a801b417a71a707cadc0671efc1e51c75529c2d7228e911555c765bbfcL694

reverting #2437 from DEV-6973 due to bad timing

---

src/js/components/agencyV2/accountSpending/AccountSpending.jsx
src/js/containers/agencyV2/accountSpending/CountTabContainer.jsx
src/js/containers/agencyV2/accountSpending/TableContainer.jsx
tests/components/agency/AccountSpending-test.jsx

Table in Agency V2 had hard-coded FY values. This updates them to use props.
Adds a test file. There are a lot of duplicate API requests. Treating that as outside this delivery.
[DEV-4521](https://federal-spending-transparency.atlassian.net/browse/DEV-4521)
Author:
Reviewer(s):

[DEV-4521] remove hard coded FY in agency v2 table

---

src/js/components/account/Account.jsx
src/js/components/account/SearchResults.jsx
src/js/models/account/FederalAccount.js

- Adds a new API field, `parent_agency_toptier_code` to our data model
- Checks for the value to match `097` (Dept of Defense toptier code)
[DEV-6881](https://federal-spending-transparency.atlassian.net/browse/DEV-6881)
Author:
Reviewer(s):

[DEV-6881] Show a note on DOD-owned Federal Account profiles

---

src/_scss/pages/aboutTheData/_tableControls.scss

Fixes a bug causing the Agency Submission Statistics tab tooltips to display behind sticky table headers.
Added a z-index (of higher value than the table headers) to the tabs' parent element.
[DEV-7038](https://federal-spending-transparency.atlassian.net/browse/DEV-7038)
Author:
Reviewer(s):

Warmfix DEV-7038 Agency Submission Statistics tooltips

---

src/js/containers/agencyV2/accountSpending/TableContainer.jsx
src/js/models/v2/agencyV2/BaseAccountSpendingRow.js

Fixes a bug that prevented the Agency v2 table from displaying any results when total obligation is 0 (as it was in dev). This change will display table results with the percentage column showing `--`.
- Also updates the loading/error state to use built-in `Table` props
- Uses the more robust `calculatePercentage` helper in the data model
- We will continue to refactor this section in the Spending by Budget Category epic
N/A
Reviewer(s):

Fix AgencyV2 table w/ no total obligations

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/helpers/aboutTheDataHelper.js
src/js/models/v2/aboutTheData/PublicationOverviewRow.js
tests/containers/aboutTheData/mockData.js
tests/helpers/aboutTheDataHelper-test.js
tests/models/aboutTheData/PublicationOverviewRow-test.js

In the `Updates by Fiscal Year` tab, fixes the calculation for `Percent of Total Federal Budget` column's denominator.
- Instead of summing the `total_budgetary_resources` for each period in the selected fiscal year, get the (cumulative) `total_budgetary_resources` from the latest fiscal period available in the selected year.
- Moved the parsing logic to a helper function instead of the `PublicationOverviewRow` data model, since we can calculate the total once and pass it to every row. This also eliminates the need to pass the selected FY to every row.
[DEV-7088](https://federal-spending-transparency.atlassian.net/browse/DEV-7088)
Author:
Reviewer(s):

Warmfix DEV-7088 Percent of Total Federal Budget

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
src/js/containers/aboutTheData/AgencyTableMapping.jsx
tests/components/aboutTheData/AboutTheDataPage-test.jsx

Prevents modal buttons from displaying on cells with no data for the `Most Recent Update` and `Number of TASs Missing from Account Balance Data` columns.
Also fixes a discrepancy between "Number of **TAS** Missing from Account Balance Data" and "Number of **TASs** Missing from Account Balance Data" to match the mockup.
[DEV-6954](https://federal-spending-transparency.atlassian.net/browse/DEV-6954)
Author:
Reviewer(s):

DEV-6954 about the data modal buttons

---

src/js/containers/bulkDownload/BulkDownloadPageContainer.jsx
src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx
tests/containers/bulkDownload/BulkDownloadPageContainer-test.jsx

Majority of API endpoints currently use TinyShield to validate requests. Part of that validation is that empty arrays are not permitted. Last sprint and into this sprint TinyShield was put in place for all downloads and the restriction on empty arrays was lifted temporarily to avoid breaking downloads from the frontend. This PR removes those few places where empty arrays occur so that the restriction for the TinyShield can be put back in place. 
Remove filters that have a value of an empty array since we aren't actually filtering on them and remove the `columns` filter / conditionally add it. Currently the columns filter is not implemented anywhere on the frontend. …

[DEV-7059] Prevent empty arrays for downloads

---

src/js/components/bulkDownload/accounts/UserSelections.jsx
tests/components/bulkDownload/accounts/UserSelections-test.jsx

If a user only has selected accountBalances for file type, DEFC filter
selections are not relevant. In the first delivery of this ticket, we made
it so when this was the only selection the DEFC checkbox tree was
disabled.
This delivery ensures the user selection form (SS Below) removes DEFC from
the selected options when relevant. Specifically, this handles the edge
case where a user selects a file type besides accountBalances, selects DEFC, then removes the file type down to
only accountBalances. In this case, we not only disable the tree but
we also remove the DEFC from the selected options.
Adds test!
[DEV-6706](https://federal-spending-transparency.atlassian.net/browse/DEV-6706)
The following are ALL required for the …

[DEV-6706] Account Download DEFC User Selection validation logic update

---

src/_scss/pages/covid19/index.scss

COVID profile Page body content is not shrinking in mobile. This is because the SCSS assumes a class name that is not there. It is not there b/c the new page header component is not.
Adding back class name from [this change](https://github.com/fedspendingtransparency/usaspending-website/pull/2494/files?file-filters%5B%5D=.scss#diff-abf430f3d7ccb81422037aa2956d7179efaad96001e82c03dc49ea6259a6853dR18)
`N/A`
Author:
`N/A`  Linked to this PR in JIRA ticket …

[BUG] COVID Profile Page Mobile responsiveness

---

src/js/components/aboutTheData/AboutTheDataPage.jsx
src/js/components/aboutTheData/AgencyDetailsPage.jsx

- On the main Agency Submission Statistics page, fixes the `Data Sources and Methodology Page` link
- On the single Agency Submission Statistics page, removes a trailing slash from the `Back to All Agencies` link
According to [react-router documentation](https://knowbody.github.io/react-router-docs/api/Link.html), `<Link>` does not support relative paths.
[DEV-7167](https://federal-spending-transparency.atlassian.net/browse/DEV-7167)
Author:
Reviewer(s):

[DEV-7167] fix broken link

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyTableMapping.jsx
src/js/models/v2/aboutTheData/PublicationOverviewRow.js
tests/models/aboutTheData/PublicationOverviewRow-test.js

On the Fiscal Years Tab on the Agencies Submissions page columns removed for 2017, 2018, 2019, and 2020.
> • adds data mapping for specific FY Periods for both the columns and data.
> • filter both the data and columns based on the data mapping for FY.
[DEV-7180](https://federal-spending-transparency.atlassian.net/browse/DEV-7180)
**Mockup:**
N/A
Author:
- [N/A] [Component Library Integration Status …

Dev-7180 Columns Removed for 2017, 2018, 2019, and 2020

---

src/js/containers/covid19/recipient/map/MapContainer.jsx

HHS disclaimer on COVID map referenced UT, should be MN. Also added a space after sentence (JSX quirk).
na
[DEV-7230](https://federal-spending-transparency.atlassian.net/browse/DEV-7230)
**Mockup:**
na
Author:
Reviewer(s):

7230 map hhs disclaimer ut => mn, add space

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
src/js/models/v2/aboutTheData/CoreReportingRow.js

The Agency and Agencies Reporting Pages will show `--` when no data exists and will not show the modal.
> • isNaN everything :)
> • The Agency and Agencies page table rows check raw data value from the `CoreReportingRow` private variables, `_obligationDifference`, `_discrepancyCount`, `_unlinkedContracts`, `_unlinkedAssistance` and decide when to show modal.
> • Agency and Agencies `CoreReportingRow` properties `_obligationDifference`, `_discrepancyCount`, `_unlinkedContracts`, `_unlinkedAssistance` keep raw data value and return formatted value or `--` for their respective public variables.
[DEV-7178](https://federal-spending-transparency.atlassian.net/browse/DEV-7178)
**Mockup:**
N/A
The following are ALL required for …

Dev-7178 Handle Null Value for TAS, Difference, Unlinked Contract & FA

---

src/_scss/pages/agencyV2/overview/_overview.scss
src/js/components/agencyV2/overview/AgencyOverview.jsx
src/js/components/covid19/recipient/map/MapWrapper.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/containers/covid19/recipient/map/MapContainer.jsx
src/js/helpers/apiRequest.js
src/js/models/v2/agencyV2/BaseAgencyOverview.js
src/js/propTypes/index.js
src/js/redux/actions/covid19/covid19Actions.js
src/js/redux/reducers/agencyV2/agencyV2Reducer.js
src/js/redux/reducers/covid19/covid19Reducer.js
tests/models/agency/BaseAgencyOverview-test.js
tests/redux/reducers/covid19/covid19Reducer-test.js

Agency V2 Tooltip when COVID spending is present, tooltip also links to agency page with active section.
See commits!
[DEV-6622](https://federal-spending-transparency.atlassian.net/browse/DEV-6622)
**Mockup:**
https://bahdigital.invisionapp.com/share/WUIAG3CQ4JG#/screens/296054001_DEFC
Author:
`N/A` [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transpa …

[DEV-6622] COVID Tooltip on Agency V2

---

src/js/containers/aboutTheData/AgenciesContainer.jsx
src/js/containers/aboutTheData/AgencyDetailsContainer.jsx
src/js/models/v2/aboutTheData/CoreReportingRow.js
tests/models/aboutTheData/CoreReportingRow-test.js

Shows `--` and removes modal for null properties returned from the api for Missing TAS, Obligation Difference, & Unlinked Columns.
> • use `isNull` from lodash, e.g. `isNull(myBrain) === true`
[DEV-7178](https://federal-spending-transparency.atlassian.net/browse/DEV-7178)
**Mockup:**
Author:
Reviewer(s):

Dev-7178 Handle Null Values for Missing TAS, Obligation Difference, & Unlinked Columns

---

src/js/models/v2/aboutTheData/BaseReportingPeriodRow.js
tests/containers/aboutTheData/mockData.js
tests/models/aboutTheData/BaseReportingPeriodRow-test.js

Updates Agency Reporting Page to display `--` for `null` percentages.
> • updates to `BaseReportingPeriodRow` model.
[DEV-7188](https://federal-spending-transparency.atlassian.net/browse/DEV-7188)
**Mockup:**
N/A
Author:
- [N/A] [API …

Dev-7188 Agency Reporting Page Null Percentage

---

src/js/components/covid19/Covid19Page.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/dataMapping/covid19/covid19.js
tests/containers/account/WithLatestFy-test.js
tests/containers/covid19/Covid19Container-test.jsx

Implements a public law query param on the Covid Profile (`/disaster/covid-19?publicLaw=all` or `/disaster/covid-19?publicLaw=american-rescue-plan`)
Refactoring for separation of duties:
- Moves the page layout and UI logic to a new file, `Covid19Page`
- Keeps just the top-level API requests for overview data and award amounts in `Covid19Container`
[DEV-7217](https://federal-spending-transparency.atlassian.net/browse/DEV-7217)
Author:
Reviewer(s):

DEV-7217 public law query param

---

src/js/components/covid19/Covid19Page.jsx
src/js/components/sharedComponents/GlossaryLink.jsx
src/js/containers/covid19/Covid19Container.jsx
tests/containers/covid19/Covid19Container-test.jsx

Restores the query param "section" overwritten by the "publicLaw" param
See tests and commits
[DEV-6622](https://federal-spending-transparency.atlassian.net/browse/DEV-6622)
Author:
`N/A` [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contra …

[DEV-6622] COVID Page Query Param "section" Restored

---

src/js/components/sharedComponents/header/NavBar.jsx
src/js/components/sharedComponents/header/mobile/MobileNav.jsx
src/js/dataMapping/navigation/menuOptions.jsx

Fixes a bug that caused Data Dictionary and API menu options to show up under both "Resources" and "Download" in production and staging.
Removes `isLowerEnv` logic and removes Data Dictionary and API from the download options mapping.
Author:
Reviewer(s):

Hotfix menu mapping in prod

---

src/_scss/pages/covid19/index.scss

Reduce margins between text blocks and sections
Update margin from 10rem to 5rem
[DEV-7245](https://federal-spending-transparency.atlassian.net/browse/DEV-7245)
**Mockup:**
-screenshots linked to ticket
Author:
- [] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated `if applicable`
- [] [Component Library Integration Status Report](https://github.com/fedspendingtransparency/data-act-documentation/blob/data-transparency-ui/f …

[DEV-7245] update margin between COVID-19 Spending profile text segments and profile sections

---

src/js/containers/Footer.jsx

Update release notes URL to go to wiki which is more user friendly for non-devs
update Footer.jsx
[DEV-7319](https://federal-spending-transparency.atlassian.net/browse/DEV-7319)
**Mockup:**
N/A
Author:
- [n/a] Verified mobile/tablet/desktop/monitor responsiveness
- [n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_ap …

[DEV-7319] Change URL for the release notes in the footer to go to the wiki

---

src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx
src/js/helpers/metaTagHelper.js

Create metatags and add page title and description copy 
Add meta tags to metatagHelper.js
[DEV-7248](https://federal-spending-transparency.atlassian.net/browse/DEV-7248)
**Mockup:**
see ticket for copy attachment
Author:
- [n/a] Verified mobile/tablet/desktop/monitor responsiveness
- [n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tre …

[DEV-7248] Add COVID and Agency Stats DS&M metatags

---

src/js/components/agencyV2/overview/AgencyOverview.jsx

Fixes a bug where a 0 would appear where the tooltip would've appeared if the agency had covid spending
Apparently JSX conditionals evaluate 0 as truthy.
[DEV-6622](https://federal-spending-transparency.atlassian.net/browse/DEV-6622)
Author:
`N/A` Added Unit Tests for helper functions, reducers, …

[DEV-6622] Agency w/ no DEFC was showing a 0

---

src/_scss/pages/covid19/_dataSourcesAndMethodology.scss
src/js/components/covid19/OtherResources.jsx

Adds two new comma delimitted links to treasury section of DS&M section of covid 19 pg.
[DEV-7348](https://federal-spending-transparency.atlassian.net/browse/DEV-7348)
Author:
`N/A`  [API …

[DEV-7348] adding new links on COVID Profile DS&M Section

---

src/js/components/covid19/DateNote.jsx
src/js/helpers/accountHelper.js

The COVID-19 Date Note will display data based on cached submission periods data from the api.
> • submission periods endpoint has an optional param for fetching cached data. Defaults to false.
> • Date Note components always fetch new submission period data from the api. Defaults to using cached data.
[DEV-7396](https://federal-spending-transparency.atlassian.net/browse/DEV-7396)
**Mockup:**
N/A
Author:
- [N/A] Verified mobile/tablet/desktop/monitor …

Dev-7396 COVID-19 Date Note uses Cached Submission Period Data

---

src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/overview/BarChart.jsx
src/js/containers/agencyV2/accountSpending/TableContainer.jsx
src/js/helpers/agencyV2/BudgetCategoryHelper.js
tests/containers/agencyV2/accountSpending/TableContainer-test.jsx
tests/helpers/agencyV2/BudgetCategoryHelper-test.js

Fixes the Agency v2 Spending by Budget Category tables.
- We were calling `setResults` in two different places, causing the "No results" message to be perpetually displayed
- Resolves a couple of console errors
- Moves the helper function that parses table rows out of the component and adds unit tests for it
- More comprehensive unit tests for `TableContainer`
N/A
Author:
Reviewer(s):

Fix Agency v2 Spending by Budget Cateogry tables

---

src/js/components/search/table/ResultsTable.jsx
src/js/components/search/table/cells/ResultsTableFormattedCell.jsx

Advanced Search Page Table COVID-19 Obligations and Outlays columns will display `--` for values that do not exist and `$0` for zero values.
> • updates the logic in the results table to only use `--` if the api response is falsey and is not equal to zero.
> • update the logic in the formatted table cell to only format currency data when the value is not `--`.
[DEV-7431](https://federal-spending-transparency.atlassian.net/browse/DEV-7431)
**Mockup:**
N/A
Author:
- [N/A] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet …

Bug - Advanced Search Covid Columns

---

src/js/components/search/table/ResultsTable.jsx
src/js/components/search/table/ResultsTableSection.jsx
src/js/containers/search/table/ResultsTableContainer.jsx

add new GA event to track advanced search click-through to awards summary
copied & adapted subaward event code; NOTE: we don't know how to test this until it reaches prod
[DEV-7172](https://federal-spending-transparency.atlassian.net/browse/DEV-7172)
**Mockup:**
Author:
- na Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- na Verified mobile/tablet/desktop/monitor responsiveness
- na Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- na Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if …

Dev 7172 add tracking adv search to award summary

---

src/js/containers/account/visualizations/AccountRankVisualizationContainer.jsx
src/js/containers/account/visualizations/AccountTimeVisualizationContainer.jsx
tests/containers/account/visualizations/AccountRankVisualizationContainer-test.jsx
tests/containers/account/visualizations/AccountTimeVisualizationContainer-test.jsx

Fixes a bug that prevented visualization data from being fetched when switching between federal account profile pages.
Added checks to `componentDidUpdate` to watch for changes to the agency id. 
[DEV-7395](https://federal-spending-transparency.atlassian.net/browse/DEV-7395)
Author:
Reviewer(s):

DEV-7395 fix Federal Account profile stale data

---

src/_scss/pages/homepage/features/_carousel.scss
src/_scss/pages/homepage/features/_covidFeature.scss
src/js/components/homepage/features/ImageCarousel.jsx
src/js/components/homepage/features/SpendingExplorerFeature.jsx
src/js/containers/homepage/CovidFeatureContainer.jsx

Fixes a bug that prevented some images on the homepage from displaying in Safari.
We are now using `<picture>` elements with an `<img>` fallback.
[DEV-7432](https://federal-spending-transparency.atlassian.net/browse/DEV-7432)
Author:
Reviewer(s):

DEV-7432 Hotfix homepage images in Safari

---

src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss
src/js/components/agencyV2/visualizations/totalObligationsOverTime/AgencyBudgetLine.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx

Add line representing agency budget per fiscal year and shaded area representing difference between agency budget and most recent submission period obligation per fiscal year
[DEV-7132](https://federal-spending-transparency.atlassian.net/browse/DEV-7132)
**Mockup:**
[Mock](https://bahdigital.invisionapp.com/d/main#/console/14222398/296055430/preview)
Author:
- [n/a] …

[DEV-7132] Obligated Amount Burnup Chart Redline

---

src/js/components/covid19/Covid19Tooltips.jsx
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx

Address testing finds for DEV-7401:
- Update Award spending tooltip copy
- Remove 'Read More' in both sections
[DEV-7401](https://federal-spending-transparency.atlassian.net/browse/DEV-7401)
Author:
- [n/a] [Component Library Integration Status …

[dev-7401] Fix award spending sub-agency and CFDA copy

---

src/js/components/search/table/ResultsTable.jsx

Federal Account Page award id click navigates users to the award page.
> • do not use onClick if not passed.
[DEV-7525](https://federal-spending-transparency.atlassian.net/browse/DEV-7525)
**Mockup:**
N/A
Author:
- [N/A] Added Unit Tests for helper functions, reducers, models and …

Dev-7525 Federal Account Page Award ID Click Bug

---

src/js/components/explorer/detail/visualization/ExplorerAwardTooltip.jsx

Removes the disclaimer from the spending explorer award tooltip when the tooltip is for Non-Award Spending.
> • add condition to exclude disclaimer for Non-Award Spending award tooltips in the spending explorer.
[DEV-7482](https://federal-spending-transparency.atlassian.net/browse/DEV-7482)
**Mockup:**
N/A
Author:
- [N/A] Verified that this PR does not create any *new* accessibility issues …

Dev-7482 Spending Explorer Award Tooltip Disclaimer

---

src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss
src/js/components/agencyV2/visualizations/totalObligationsOverTime/AgencyBudgetLine.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/AreaPath.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/Path.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/PathAndAreaPathLinearGradients.jsx
tests/components/agency/overview/TotalObligationsOverTimeVisualization-test.jsx
tests/components/agency/overview/mockData.js

When obligations exceed the agency budget, the line and area shading will be red.
> • add gradients for the path and area path.
> • hide difference rectangle when obligations exceed the agency budget.
[DEV-6614](https://federal-spending-transparency.atlassian.net/browse/DEV-6614)
**Mockup:**
https://bahdigital.invisionapp.com/share/M8IAH1EZUH5#/screens/296060805
Author:
- [N/A] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) …

Dev-6614 Agency V2 Burn-up Chart Edge Case Obligation Exceeds Agency Budget

---

src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss
src/js/components/agencyV2/visualizations/totalObligationsOverTime/AgencyBudgetLine.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/TodayLineAndtext.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/ZeroLineAndTick.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/AreaPath.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/Path.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/PathAndAreaPathLinearGradients.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/paths/Paths.jsx
src/js/containers/agencyV2/visualizations/TotalObligationsOverTimeContainer.jsx
src/js/dataMapping/agencyV2/visualizations/totalObligationsOverTime.js
src/js/helpers/agencyV2/visualizations/TotalObligationsOverTimeVisualizationHelper.js
tests/helpers/agencyV2/visualizations/TotalObligationsOverTimeVisualizationHelper-test.js

> • to test scenarios of exceeding min/max/both in the `TotalObligationsOverTimeContainer.jsx` replace `setData(addSubmissionEndDatesToBudgetaryResources(obligationsByPeriod, javaScriptSubmissionPeriods, fy).sort((a, b) => a.period - b.period));` with `setData(mockExceedingAmounts(addSubmissionEndDatesToBudgetaryResources(obligationsByPeriod, javaScriptSubmissionPeriods, fy).sort((a, b) => a.period - b.period), agencyBudget));`
and add 
```
const mockExceedingAmounts = (data, agencyBudget) => data.map((d, i) => {
const newData = d;
if (i === 1) {
newData.obligated -= agencyBudget;
}
if (i === 3) {
newData.obligated += agencyBudget;
}
// if (i + 1 …
```

Mod-Dev 7540 BurnUp Chart Min & Max Exceeds Extremes

---

src/_scss/pages/agencyV2/index.scss
src/js/components/agencyV2/AgencySection.jsx

- Remove the "coming soon" tooltip next to "Overview"
- Remove the "coming soon" tooltip next to "This section covers Total and Award Spending"
[DEV-7542](https://federal-spending-transparency.atlassian.net/browse/DEV-7542)
Author:
- [n/a] …

[DEV-7542] Remove placeholder tooltips in agency section

---

src/js/components/sharedComponents/TreemapCell.jsx

In tree view, "Non-award Spending" cell becomes a clickable link that sends you to a broken page.
Non-award spending has an undefined ID causing the broken link. Adding a check for undefined prevents the cell from becoming a clickable link. 
[DEV-7481](https://federal-spending-transparency.atlassian.net/browse/DEV-7481)
Author:
- [n/a] [API …

[DEV-7481] Non-Award Spending on Spending Explorer broken link fix

---

src/js/components/search/filters/programSource/TreasuryAccountFilters.jsx

When users hit Enter on the tree filter, the page would refresh. This fixes that behavior (so nothing happens)
Unlike the other checkbox trees w/ filter, this one was inside a form that caused the behavior. Just change it to a div.
[DEV-6780](https://federal-spending-transparency.atlassian.net/browse/DEV-6780)
**Mockup:**
na
Author:
- na Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- na Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- na Verified mobile/tablet/desktop/monitor responsiveness
- na Verified that this PR does not create any *new* accessibility …

6780 remove form tag to ignore Enter

---

src/js/containers/explorer/detail/DetailContentContainer.jsx

Fixes bug where the `Results after top 500` row was being added to results with less than 500 results
**Technical description:**
Moves the addition of the `Results after Top 500` row to the spending explorer into an `if` statement so it will only add that row if there are more than 500 results.
[DEV-7483](https://federal-spending-transparency.atlassian.net/browse/DEV-7483)
Author:
Reviewer(s):

[DEV-7483] Fix Spending Explorer "Top 500" bug

---

src/_scss/pages/homepage/features/_covidFeature.scss
src/_scss/pages/homepage/features/_featurePane.scss
src/js/containers/homepage/CovidFeatureContainer.jsx

Updated line-height on the feature pane heading (i.e. “The federal response to Covid-19“), before the line height was very large and appeared to have too much white space between lines. Also adding min-width to the decorative before/after lines so they don't disappear on mobile if the title wraps.
The heading was styled to be 16px, so utilized the `$base-font-size` variable. Added the `$base-line-height` style for the line-height to accommodate the font size (before was defaulting to a regular h2 line-height) 
[DEV-7603](https://federal-spending-transparency.atlassian.net/browse/DEV-7603)
Author:
- [n/a] Added Unit Tests for helper functions, reducers, models and …

[DEV-7603] Feature Pane Title Line Height

---

src/_scss/layouts/default/header/_officialSite.scss
src/js/components/sharedComponents/header/Header.jsx

Updated the alignment of the content in the top blue bar in the header to left align with the rest of the content on the page to help with alignment consistency and easy legibility when reading. Also bumped up the text size of the "Official Govt Website" from 10px to 12px  to be more legible and help Lighthouse audits (see https://web.dev/font-size/), confirmed with design team.
Utilized the `fullSectionWrap` mixin for the content wrapper, which matches max-width style of the header and content sections wrappers.
[DEV-7602](https://federal-spending-transparency.atlassian.net/browse/DEV-7602)
**Mockup:**
These are older mockups, but you can see how the top bar links align left to the header logo, etc. …

[DEV-7602] Top Bar Header Alignment

---

src/js/helpers/explorerHelper.js
tests/helpers/explorerHelper-test.js

In Spending Explorer, verify the word "Class" is spelled correctly to say “Sum of all Object Classes after Top 500”
In Spending Explorer, verify the word "Activities" is spelled correctly to say “Sum of all Program Activities after Top 500”
Add logic to determine if the active subdivision is object class or program activity and return the correct pluralization. Currently we only have 2 cases to handle pluralization (object class and program activity), so this solution does not cover all english plural edge cases. 
[DEV-7496](https://federal-spending-transparency.atlassian.net/browse/DEV-7496)
**Mockup:**
N/A
Author:
- [n/a] Scheduled demo including …

[DEV-7496] Fix typo in spending explorer

---

src/_scss/pages/agencyV2/visualizations/_recipientDistribution.scss
src/js/components/agencyV2/visualizations/RecipientDistribution.jsx
src/js/helpers/moneyFormatter.js
tests/helpers/moneyFormatter-test.js

Add labels and formatted monetary values according to mock for top count, middle count, and bottom count
Implement labels using svg <text> and <tspan>
Implement money formatter to match values in mock
[DEV-7341](https://federal-spending-transparency.atlassian.net/browse/DEV-7341)
**Mockup:**
https://bahdigital.invisionapp.com/d/main#/console/14222398/296061875/preview
screenshot in [DEV-4344](https://federal-spending-transparency.atlassian.net/browse/DEV-4344)
Author:
- [n/a] [Component Library Integration Status …

[DEV-7341] Recipient Box and whisker plot labels

---

src/_scss/pages/agencyV2/visualizations/_obligationsByAwardType.scss

Fixes an issue found during testing - the table sometimes extends below the bottom of the tooltip. 
Reproduced with resolution 1920 x 1080 in Chrome at `/agency_v2/012?fy=2017`
[DEV-6616](https://federal-spending-transparency.atlassian.net/browse/DEV-6616)
Author:
Reviewer(s):

Fix DEV-6616 table overflow

---

src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx

Adds award category tabs to subagency section on agency profile page
[DEV-7446](https://federal-spending-transparency.atlassian.net/browse/DEV-7446)
**Mockup:**
https://bahdigital.invisionapp.com/share/CZIAH1ZQGPF#/screens/296056413_agency-Profile-Mvp
Author:
- [n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) updated …

[DEV-7446] Add award category tabs to subagency section

---

src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx

When navigating to the advanced search page with a hash we will preserve checked and staging filters from hash.
> • mounting PSC, TAS, and NAICS trees not on application load we maintain checked and staged filters from hash without fetching data.
[DEV-7106](https://federal-spending-transparency.atlassian.net/browse/DEV-7106)
**Mockup:**
N/A
Author:
- [N/A] [API …

Dev-7106 Checkbox Tree Hash Bug

---

src/js/components/search/SearchSidebarSubmit.jsx
src/js/containers/search/SearchSidebarSubmitContainer.jsx
tests/components/search/SearchSideBarSubmit-test.jsx

When there are no filters, you will not be able to submit a search.
> • check if there are no filters selected before enabling the search submit button.
[DEV-6562](https://federal-spending-transparency.atlassian.net/browse/DEV-6562)
**Mockup:**
N/A
Author:
- [N/A] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) …

Dev-6562 Advanced Search Submit Bug

---

src/js/components/explorer/detail/visualization/table/TableRow.jsx

Fix broken link in table view for non-award spending, tree view was fixed in previous PR
[DEV-7481](https://federal-spending-transparency.atlassian.net/browse/DEV-7481)
Author:
- [n/a] Verified mobile/tablet/desktop/monitor responsiveness
- …

dev-7481 Fix spending explorer broken link table view

---

src/js/components/agencyV2/visualizations/ObligationsByAwardType.jsx
src/js/containers/agencyV2/visualizations/ObligationsByAwardTypeContainer.jsx

add percentage of total to by award type outer ring labels
had to rework label drawing a bit
[DEV-7775](https://federal-spending-transparency.atlassian.net/browse/DEV-7775)
**Mockup:**
in ticket
Author:
Reviewer(s):

dev7775 add percent to award type labels

---

src/js/components/about/AboutContent.jsx

Navigating to /about with a query param section scrolled to the section, but added an entry to history that trapped people using back button.
react-router-dom replace instead of push to prevent the trap
[DEV-7253](https://federal-spending-transparency.atlassian.net/browse/DEV-7253)
**Mockup:**
na
Author:
- [ na] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ na] Verified mobile/tablet/desktop/monitor responsiveness
- [ na] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ na] Added Unit Tests for helper functions, reducers, models and …

dev7253 fix about page back nav

---

src/js/components/covid19/Covid19Page.jsx

Navigating to a specific section of COVID page was adding a 2nd layer to browser history, so back button needed to be hit twice.
changed history.push to history.replace
[DEV-7526](https://federal-spending-transparency.atlassian.net/browse/DEV-7526)
**Mockup:**
na
Author:
- [ na] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ na] Verified mobile/tablet/desktop/monitor responsiveness
- [ na] Verified that this PR does not create any *new* accessibility issues (via Axe Chrome extension)
- [ na] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity …

DEV-7526 fix COVID page back nav

---

src/js/components/agencyV2/overview/FySummary.jsx

Remove box plot in FySummary and add FlexGrid component
[DEV-7814](https://federal-spending-transparency.atlassian.net/browse/DEV-7814)
**Mockup:**
https://bahdigital.invisionapp.com/d/main#/console/14222398/296064992/preview
Author:
- [n/a] …

DEV-7814 Remove box & whiskers plot and update page with 3 viz

---

src/_scss/pages/covid19/index.scss

just shrinking map loading msg
css overrides; only changes are 347-359 (everything else is whitespace corrections)
[DEV-7252](https://federal-spending-transparency.atlassian.net/browse/DEV-7252)
**Mockup:**
none
Author:
Reviewer(s):

7252 add css to map shrink loading msg

---

scripts/sitemaps/buildSitemap.js

improve seo by disallowing query params (now considered to be separate pages, which gives many duplicate contents)
replaced rule to disallow glossary with this to ignore all query params
deployed to qat; resulting file is: https://qat.usaspending.gov/robots.txt
[DEV-7465](https://federal-spending-transparency.atlassian.net/browse/DEV-7465)
**Mockup:**
na
Author:
Reviewer(s):

Disallow robots to recognize query params as separate pages

---

src/_scss/components/_footerLinkToAdvancedSearch.scss
src/_scss/pages/covid19/index.scss
src/_scss/pages/covid19/visualizations/_amounts.scss
src/js/components/covid19/Heading.jsx

For each section heading of the Covid profile that is currently center-aligned, the text is updated to match the latest mockup (left-aligned) 
*note this is prep work for ARP branding ticket https://federal-spending-transparency.atlassian.net/browse/DEV-7877
[DEV-7913](https://federal-spending-transparency.atlassian.net/browse/DEV-7913)
**Mockup:**
https://bahdigital.invisionapp.com/share/4HIAGPS7T3X#/screens
Author: …

[DEV 7913] Left-align Covid Profile headings & descriptions

---

src/js/components/agency/visualizations/objectClass/MinorObjectClasses.jsx

On the Agency Profile page, in the Object Classes section, when clicking on a Major Object class to show the Minor Object classes below it, the tree viz was only showing a gray box. 
I traced the problem to the clearFinalNodes function call in the componentDidUpdate function. It was clearing the nodes for the Minor Object classes just after the tree viz was drawn on the page, causing it to redraw with no data. So I moved the clearFinalNodes call to just before buildTree is called, to clear the old nodes when a new tree viz needs to be drawn.
[DEV-7393](https://federal-spending-transparency.atlassian.net/browse/DEV-1234)
**Mockup:**
n/a
Author:
- [x ] Linked to this …

7393 - object class treeview

---

src/js/components/covid19/budgetCategories/BudgetCategories.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
tests/containers/covid19/budgetCategories/BudgetCategoriesTableContainer-test.jsx

Connects the Spending by Budget Category table to the public law filter.
Utilize `defcParams` in Redux instead of all Covid 19 DEF codes.
[DEV-7218](https://federal-spending-transparency.atlassian.net/browse/DEV-7218)
Author:
Reviewer(s):

DEV-7218 budget category table ARP integration

---

src/js/components/about/DataQuality.jsx

Change one link in the About page bc it was getting a 404 before. Also make sure it does not open the redirect modal when clicked. 
Updated the link and changed from ExternalLink component to an <a>.
[DEV-8037](https://federal-spending-transparency.atlassian.net/browse/DEV-1234)
**Mockup:**
Author:
- [x ] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [x ] Verified that this PR does not create any *new* …

8037 - changed the link to use <a> instead of ExternalLink

---

src/js/apis/agencyV2.js
src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/AgencySection.jsx
src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx
src/js/components/agencyV2/overview/AgencyOverview.jsx
src/js/components/agencyV2/overview/FySummary.jsx
src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
src/js/containers/agencyV2/AgencyContainerV2.jsx
src/js/containers/agencyV2/WithAgencySlugs.jsx
src/js/containers/agencyV2/awardSpending/SubAgencySummaryContainer.jsx
src/js/containers/agencyV2/awardSpending/SubagencyTableContainer.jsx
src/js/containers/covid19/WithDefCodes.jsx
src/js/containers/router/RouterRoutes.js
src/js/redux/actions/agencyV2/agencyV2Actions.js
src/js/redux/reducers/agencyV2/agencyV2Reducer.js
tests/components/agency/overview/FYSummary-test.jsx
tests/containers/account/WithLatestFy-test.js
tests/containers/agencyV2/AgencyContainerV2-test.jsx
tests/containers/agencyV2/WithAgencySlugs-test.jsx
tests/containers/agencyV2/awardSpending/SubagencyTableContainer-test.jsx

Use the agency name slug (e.g. `department-of-the-treasury`) instead of the toptier code (e.g. `020`) in (dark-released) Agency Profile v2 URLs
- Implements a custom hook, `useAgencySlugs`, which returns a mapping of `agency_slug` to `toptier_code` if it exists in Redux. If it does not exist in Redux yet, it makes an API request to the endpoint `v2/references/toptier_agencies`
- Handles the loading state for each section of the page in `AgencySection.jsx` instead of per-component
- Fixes a few console errors about unique keys
- In the containers, get `toptierCode` from the `agencyV2.overview` object Redux (instead of passing it down as a prop or getting it from the URL)
- Bonus! Removes the download button from the page header to match …

DEV-6390 change Agency v2 URLs

---

src/js/components/search/header/NoDownloadHover.jsx

Updates text on Advanced Search/Keyword search pages to reflect new download size limit
Part of: https://github.com/fedspendingtransparency/usaspending-api/pull/3285
[DEV-8103](https://federal-spending-transparency.atlassian.net/browse/DEV-8103)
Author:
Reviewer(s):

[DEV-8103] Limit download row size

---

src/js/components/explorer/detail/UnreportedErrorScreen.jsx

On the Spending Explorer page, under Object Classes, if you select 'Unreported Data' this message is shown on the screen. The ticket was to update the message.
Changed the text to match the new text listed in the ticket.
[DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-3738)
**Mockup:**
N/A
Author:
- [ x] Scheduled demo including Design/Testing/Front-end OR Provided instructions for testing in JIRA and PR `if applicable`
- [ x] Verified that this PR …

3728 - updated the unreported data message

---

src/js/components/search/header/NoDownloadHover.jsx

Update the download hover to text to match the new max of 100k transactions per download.
Reviewer(s):

Change download max up to 100k

---

src/js/containers/covid19/assistanceListing/SpendingByCFDAContainer.jsx
src/js/containers/covid19/recipient/RecipientTableContainer.jsx

Award Spending by CFDA and Award Spending by Recipient have tables that, if sorted by Face Value of Loans, produce errors when switched to another tab.
Current sort is maintained in state then used as API parameter; "face value" is not a valid sort parameter for non-loan requests. This defaults that situation to descending by obligation instead. (note: AwardSpendingAgencyTableContainer was previously corrected)
[DEV-5713](https://federal-spending-transparency.atlassian.net/browse/DEV-5713)
**Mockup:**
n/a
Author:
- [n/a ] Verified …

Fix/5713 "tab memory" errors on COVID page

---

scripts/buildRedirectConfig.js
src/js/dataMapping/agencyV2/agencyIdsToSlugs.js

When agency v2 page is released, URLs will use "slug" name instead of ID. This adds that translation to the server's 301 list.
I tried to use an API call so this list would not need to be updated, but it wouldn't work. The static list probably won't change anyway, unless an agency changes their official name.
[DEV-7675](https://federal-spending-transparency.atlassian.net/browse/DEV-7675)
**Mockup:**
n/a
Author:
- [n/a ] Verified …

7675 add listings for old agency pages to redirect

---

src/js/components/search/table/ResultsTable.jsx

update agency links in account award table to v2 page (not in prod yet)
uses new global constants and API data
[DEV-7881](https://federal-spending-transparency.atlassian.net/browse/DEV-7881)
**Mockup:**
n/a
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and …

7881 use slug & environment to form link

---

src/_scss/pages/agencyV2/overview/_overview.scss
src/_scss/pages/agencyV2/visualizations/_obligationsByAwardType.scss
src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss

AV2 chart(s) overlaps COVID badge tip (chart tips overlap each other as expected)
removes errant z-indexes causing the problem
[DEV-8113](https://federal-spending-transparency.atlassian.net/browse/DEV-8113)
**Mockup:**
n/a
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [n/a ] [API …

8113 remove layering causing chart to overlap covid tip

---

src/js/components/aboutTheData/AgencyDetailsPage.jsx
src/js/components/aboutTheData/DrilldownCell.jsx
src/js/containers/agencyV2/AgencyContainerV2.jsx
src/js/containers/agencyV2/WithAgencySlugs.jsx
src/js/redux/actions/agencyV2/agencyV2Actions.js
src/js/redux/reducers/agencyV2/agencyV2Reducer.js
tests/containers/agencyV2/WithAgencySlugs-test.jsx

Add links to the Agency Profile Page on the Agency Submission Statistics individual Agency Profile page. 
Updated the useAgencySlugs custom hook to also return topTierCodes so we can get either from that return object. Updated the link on the AgencyDetailsPage to use the agencyString from GlobalConstants and the agency slug from useAgencySlugs.
[DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-8167)
**Mockup:**
n/a
Author:
- [x ] Verified that this PR …

8167 links to agency pages

---

src/js/components/covid19/Covid19Page.jsx
src/js/containers/covid19/Covid19Container.jsx
src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
tests/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer-test.jsx

Updates Agency Profile links on the Covid Profile page to use the v2 version of the URL based on our Global Constants for the Agency v2 release.  
- Uses the toptier code --> agency slug mapping added to the `useAgencySlugs` hook by #2826 
- Updates the Covid 19 container to show the loading indicator until API requests for page-level data (now including the Agency Slugs) have completed. This reduces the number of re-renders farther down the DOM hierarchy. 
- Utilize the Loading and Error states built into the component library `Table`
[DEV-8168](https://federal-spending-transparency.atlassian.net/browse/DEV-8168)
Author:
Reviewer(s):

DEV-8168 Covid Profile Agency v2 links

---

src/_scss/elements/filters/_typeahead.scss
src/js/components/sharedComponents/autocomplete/Autocomplete.jsx
src/js/containers/search/filters/cfda/CFDAListContainer.jsx

Increases the limit to the number of CFDA results returned by the autocomplete search, as well as adding a scrollbar to the autocomplete results dropdown
[DEV-8147](https://federal-spending-transparency.atlassian.net/browse/DEV-8147)
Author:
Reviewer(s):

[DEV-8147] adjust CFDA limit, add scrollbar to autocomplete dropdown

---

src/_scss/pages/agencyV2/visualizations/_obligationsByAwardType.scss
src/js/components/agencyV2/visualizations/ObligationsByAwardType.jsx
src/js/components/agencyV2/visualizations/ObligationsByAwardTypeTooltip.jsx
src/js/containers/agencyV2/visualizations/ObligationsByAwardTypeContainer.jsx
src/js/containers/agencyV2/visualizations/RecipientDistributionContainer.jsx
src/js/helpers/agencyV2/visualizations/ObligationsByAwardTypeHelper.js
tests/components/agency/visualizations/ObligationsByAwardTypeTooltip-test.jsx
tests/helpers/agencyV2/visualizations/ObligationsByAwardTypeHelper-test.js

Changed the donut hover behavior so that tooltips only show the award types for the 'hovered' category (ie. either All Financial or All Contracts).  Updated the tooltip design slightly according to mock attached to the JIRA ticket.  Also, the following decisions were made after meeting with the designers - https://data-transparency-bfs.slack.com/archives/GGRP4UMAT/p1639507404028600
- Added a type field to each object in the "details" array in the container to help determine which category the award type belonged to
- The requirements changed some so needed to access the data objects for this feature in different ways than what was intended when this feature was first developed.  
- Added mouseover / out events to outer donut ring and …

Dev-7770: Change the donut hover behavior so that tooltips only show the award types for the selected category

---

src/_scss/pages/agencyV2/overview/_overview.scss
src/js/containers/agencyV2/AgencyContainerV2.jsx
tests/containers/agencyV2/AgencyContainerV2-test.jsx

Current behavior: 
1. Visit an agency page
2. Navigate to another page and click a link to a different agency
3. The name of the last agency viewed is displayed for a moment while the new agency's data loads
Updated behavior:
3. A blank / initial loading state is shown while the agency's data loads
Adds a `useEffect` with a [cleanup function](https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup) that resets the Agency v2 reducer.
Bonus! CSS fix for overview links overflow ([DEV-8230](https://federal-spending-transparency.atlassian.net/browse/DEV-8230))
[DEV-8230](https://federal-spending-transparency.atlassian.net/browse/DEV-8230)
Author:
Reviewer(s):

Fix Agency v2 cleanup on unmount & DEV-8230

---

src/js/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer.jsx
src/js/containers/covid19/budgetCategories/BudgetCategoriesTableContainer.jsx
tests/containers/covid19/awardSpendingAgency/AwardSpendingAgencyTableContainer-test.jsx
tests/containers/covid19/budgetCategories/BudgetCategoriesTableContainer-test.jsx

Fixes a bug that generated links to agencies that don't have profile pages. 
We were previously just checking for the existence of `toptier_code`, but an agency can have a toptier code with no profile page (and therefore no `agency_slug` mapping). 
[DEV-8168](https://federal-spending-transparency.atlassian.net/browse/DEV-8168) follow up
Author:
Reviewer(s):

Fix DEV-8168 Covid profile Agency v2 links

---

src/js/components/agencyV2/visualizations/ObligationsByAwardTypeTooltip.jsx
tests/components/agency/visualizations/ObligationsByAwardTypeTooltip-test.jsx

Added the hyphen where “FY2021 - Total…. “ for both Contract and Assistance tooltips.  Removed the space between fy and the year to match the mocks.  Changed “Award Obligations” to display in two lines for the contract tooltip to match the mockup and be consistent with the assistance tooltip.
Text changes.
[DEV-7770](https://federal-spending-transparency.atlassian.net/browse/DEV-7770) follow-up
Author:
Reviewer(s):

dev 7770 - update agency v2 donut chart tooltip text

---

src/js/apis/agencyV2.js
src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
src/js/components/agencyV2/statusOfFunds/VisualizationSection.jsx
src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
src/js/helpers/agencyV2/StatusOfFundsVizHelper.js
src/js/models/v2/agency/BaseAgencySubcomponentsList.js
src/js/redux/actions/agencyV2/agencyV2Actions.js
src/js/redux/reducers/agencyV2/agencyV2Reducer.js
tests/components/agency/visualizations/StatusOfFundsChart-test.jsx
tests/models/agency/BaseAgencySubcomponentsList-test.js

Replace mock data used to build status of funds chart with data from subcomponents endpoint.
[DEV-8118](https://federal-spending-transparency.atlassian.net/browse/DEV-8118)
Author:
Reviewer(s):

dev-8118 integrate api status of funds subcomponents, refactor to use endpoint, update tests

---

src/js/components/search/visualizations/rank/chart/ChartGroup.jsx

This was returned by testers because agencies with no agency page were being shown as links in the categories tab, with Spending By Awarding Agency chosen from the dropdown.
Before this ticket, in ChartGroup.jsx, any time the linkId was '', we would not build a link, but now we're adding the agecy_v2 string to all linkIds, so we need to check for '' and for 'agency_v2' in the linkId before making it a link.
[DEV-1234](https://federal-spending-transparency.atlassian.net/browse/DEV-7829)
**Mockup:**
n/a
Author:
- [ x] Verified …

7829 v2 links on awarding agency results

---

src/js/containers/search/filters/cfda/CFDAListContainer.jsx

Removes use of js-search from the CFDA autocomplete component, since the backend is now sorting the results by program number and the sorting was not working on the frontend in the first place.
Removes the use of the `Search()` object and just returns the results from the API
[DEV-8147](https://federal-spending-transparency.atlassian.net/browse/DEV-8147)
Author:
Reviewer(s):

[DEV-8147] Fix CFDA autocomplete sorting

---

src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

Testing find - fix bars height on pages with less than 10 results. Bars are currently too large 
Example agency (page 2 bars were too large) /agency_v2/department-of-commerce?fy=2021
Since bar heights scale relatively to the length of results array and chart height, we push descending numbers to the Y axis labels so they fill the height below
[DEV-8118](https://federal-spending-transparency.atlassian.net/browse/DEV-8118)
**Mockup:**
https://bahdigital.invisionapp.com/share/BSIAHSLA9PE#/screens
Author: …

dev-8118 Status of funds Testing fix-- fix height of bars when pagination shows less than 10 results

---

src/js/components/agencyV2/statusOfFunds/IntroSection.jsx
src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
tests/components/agency/StatusOfFunds/IntroSection-test.jsx

AC #3 was overlooked, this updates the intro section to use subcomponents total items value from API response.
[DEV-8118](https://federal-spending-transparency.atlassian.net/browse/DEV-81184)
**Mockup:**
Author:
- [n/a] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api_contracts) …

Dev-8118 Update subcomponents number in status of funds intro section

---

package-lock.json
package.json
src/_scss/mixins/profilePage.scss
src/_scss/pages/agencyV2/index.scss
src/_scss/pages/agencyV2/overview/_overview.scss
src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
src/_scss/pages/covid19/index.scss
src/js/components/covid19/Heading.jsx
src/js/components/covid19/amountsVisualization/AmountsVisualization.jsx
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/components/covid19/awardSpendingAgency/AwardSpendingAgency.jsx
src/js/components/covid19/budgetCategories/BudgetCategories.jsx
src/js/components/covid19/recipient/RecipientSection.jsx

During design review of [DEV-8171](https://federal-spending-transparency.atlassian.net/browse/DEV-8171), we determined that the styling for the Section Title component should be updated to better reflect the latest mockups so that the text in the title aligns with the profile page padded section content (in desktop). 
This PR:
- Updates USAS to use the version of the component library where the Section Title styling has been adjusted [PR #117](https://github.com/fedspendingtransparency/data-transparency-ui/pull/117)
- Standardizes padding around the text content between Agency v2 and Covid-19 Profiles, which resolves [DEV-8102](https://federal-spending-transparency.atlassian.net/browse/DEV-8102)
- Includes some accessibility improvements …

Component library update & DEV-8102

---

src/_scss/pages/agencyV2/visualizations/_obligationsByAwardType.scss

Reposition agency v2 page donut chart tooltip and tooltip caret for 13" or smaller screen sizes.
Added css overrides to the tooltips that are using the 'obligations-by-award-type' class to reposition the tooltip and the tooltip caret based on the browser width.
[DEV-8266](https://federal-spending-transparency.atlassian.net/browse/DEV-8266)
Author:
Reviewer(s):

8266 - Reposition the agency v2 donut chart tooltip based on browser width

---

src/js/components/agencyLanding/table/cells/AgencyLinkCell.jsx
src/js/containers/agencyLanding/AgencyLandingContainer.jsx

change agency links on landing page to v2 format
uses slug instead of ID when available, uses global link
[DEV-8265](https://federal-spending-transparency.atlassian.net/browse/DEV-8265)
**Mockup:**
n/a
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and …

8265 update table link to agency v2 page

---

src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx

This was returned by testing because the banner was showing in all browsers. It should only show in IE.
I added checks for IE in the if blocks that check the date.
[DEV-8234](https://federal-spending-transparency.atlassian.net/browse/DEV-8234)
**Mockup:**
n/a
Author:
Reviewer(s):

8234 end of ie banner

---

src/js/components/agencyV2/visualizations/ObligationsByAwardType.jsx

Ensure tooltip closes when mousing out from the donut chart.
The hit area for the outer ring is so small so the mouseout event to close the tooltip wasn't always getting captured.  I added a padding around the donut so if the user hovers on or over the padding, the tooltip will close.
[DEV-8301](https://federal-spending-transparency.atlassian.net/browse/DEV-8301)
Author:
Reviewer(s):

8301 - Ensure tooltip closes when mousing out from the donut chart

---

src/js/GlobalConstants.js
src/js/containers/router/RouterRoutes.js

Undark Release Agency V2 page
Replaced 'agency_v2' with 'agency' in the router, removed path to agency v1 page from router, and updated the Global Constants to enable linking to agency v2 page.
[DEV-8068](https://federal-spending-transparency.atlassian.net/browse/DEV-8068)
Author:
Reviewer(s):

DEV 8068: Undark Release Agency V2 page

---

src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

Adjusted the text to makes it appear like the text isn't resizing when the browser is resized.  
The chart is a svg so the svg resizes as the browser is resized.  I created a "scale" that is (the initial width svg / the current width of the svg container based on the browser width).  And then applied a transform to the svg text.  The transform scales the text according to the above ratio to counteract any resizing.  This makes it appear like the text isn't resizing when the browser is resized.  
[DEV-8313](https://federal-spending-transparency.atlassian.net/browse/DEV-8313)
**Mockup:**
https://bahdigital.invisionapp.com/share/BSIAHSLA9PE#/screens/296066805
Author: …

8313 - Fix the Status of Funds text size to remain constant when changing the browser width

---

src/js/GlobalConstants.js
src/js/models/v2/award/BaseFinancialAssistance.js
src/js/models/v2/award/BaseIdv.js

This ticket was returned because for non-Contract Awards (e.g. IDVs, Grants, Direct Payments, Loans, and Other) the agency link at the top of the page was returning 404 due to 'undefined' being in the url and the Awarding Agency and Funding Agency links in the Agency Details accordion in the Additional Information section were showing the agency names with no hyperlinks.
Added the slugs to the IDV and FinancialAssistance data objects.
[DEV-8282](https://federal-spending-transparency.atlassian.net/browse/DEV-8282)
**Mockup:**
Author:
- …

8282 - added slugs to IDV and FinancialAssistance data objects

---

src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

Testing fix - we should not be able to drilldown further at the subcomponent level. There was already a line to nullify the onclick handler so added another line to nullify on keypress
[DEV-8052](https://federal-spending-transparency.atlassian.net/browse/DEV-8052)
Author:
Reviewer(s):

dev-8052 bug fix prevent enter keypress at subcomponent level

---

src/js/components/agencyV2/visualizations/ObligationsByAwardType.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx

Enabled tabbing through each individual arc of the donut chart.  Showing the tooltip on tab into an arc / hide the tooltip on tab out.
Added on focus and on blur listeners and event handlers to enable tabbing through the arcs in the donut chart.  However, Every time you mouseover and keypress into the chart, the 'activeType' state is getting updated so the chart tries to re-render.  When you mouseout activeType is cleared and react tries to flush the updates while react is already in a render cycle. So we get this error in the console - Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering. I fixed this by putting the d3 code in a function and only re-render the chart after chart height and chart …

8243 - Fixed the agency v2 donut chart tab functionality

---

src/js/components/agencyV2/visualizations/totalObligationsOverTime/AgencyBudgetLine.jsx
src/js/components/agencyV2/visualizations/totalObligationsOverTime/TotalObligationsOverTimeVisualization.jsx

Users should be able to view the tooltip for the total time over obligations chart by the keyboard
Added onfocus and onblur event listeners/handlers to show the tooltip on tab.
[DEV-8234](https://federal-spending-transparency.atlassian.net/browse/DEV-8234)
Author:
Reviewer(s):

8243 - Show tooltip for total time obligation chart on tab

---

package-lock.json
src/_scss/pages/agencyV2/statusOfFunds/_visualizationSection.scss
src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

Due to data reasons, we’d like to remove the hyperlinks on the graphic on the Status of Funds graphic on the Agency V2 issue. 
Undo updates made in [dev-8053](https://github.com/fedspendingtransparency/usaspending-website/pull/2863/commits/079c7c51b77702bb3060bc09684700af2fa98bdd) 
[DEV-8319](https://federal-spending-transparency.atlassian.net/browse/DEV-8319)
Author:
Reviewer(s):

dev-8319 remove federal account hyperlinks from status of funds chart

---

src/js/dataMapping/agency/tableColumns.js
src/js/helpers/agencyV2/AwardSpendingSubagencyHelper.js
src/js/models/v2/agency/BaseSubagencySpendingRow.js
src/js/models/v2/agency/BaseSubagencySpendingRowChildren.js
src/js/redux/reducers/agencyV2/agencyV2Reducer.js
tests/helpers/agencyV2/visualizations/ObligationsByAwardTypeHelper-test.js
tests/models/agency/BaseSubagencySpendingRow-test.js

In the Agency V2 award spending table, added office code to the office name so the office name is formatted “Office Name (Office Code)”
Added new model for subagency row children (ie. for offices) since the office codes were added to the data.  Changed the office name to “Office Name (Office Code)”. Also Jessica asked the frontend to change the table column "Agency Name" to Sub-Agency Name" (see [DEV-8293](https://federal-spending-transparency.atlassian.net/browse/DEV-8293)) so I did that too.
Please note to review, please use the staging API in GlobalConstants to get the correct data
```
const globalConstants = {
API: 'https://staging-api.usaspending.gov/api/',
``` …

8318 - In Agency v2 award spending table, added office code to office name

---

src/js/components/award/idv/activity/ActivityChartTooltip.jsx
src/js/components/award/idv/referencedAwards/ReferencedAwardsTable.jsx
src/js/dataMapping/award/additionalDetailsContract.js

Remove Agency V1 links from Award Profile page in the following cases:
- Additional Info section, Parent Award Details accordion
- For IDV Awards, the IDV Activity Chart Tooltips and the Orders Made Under this IDV table
** See ticket for exact pages where the issue can be reproduced.
Commented out links and replaced with text.  Added TODO comments so we can easily go back next week and add agency v2 links once api change is in place.
[DEV-8068](https://federal-spending-transparency.atlassian.net/browse/DEV-8068)
Author:
Reviewer(s):

8340 - HOTFIX-Remove additional Agency V1 links from Award Profile page

---

package-lock.json
package.json

PR builds are failing due to vulnerability found in npm audit. Npm audit suggests to upgrade checkbox tree to resolve

Resolve npm audit vulnerability - upgrade checkbox tree 

---

package-lock.json
package.json
tests/helpers/apiRequest-test.js

Bumped up axios version from 0.22 to 0.25
This is in response to the vulnerability detected by dependabot.  See the following PR with comments.
[Technical details for the knowledge of other developers.](https://github.com/fedspendingtransparency/usaspending-website/pull/2880)
Please note, I had to add the url param to unit tests to account for additional error checking in axios - Adding error handling when missing url ([see axios version 0.25 changelog](https://github.com/axios/axios/blob/v0.25.0/CHANGELOG.md) )
Reviewer(s):

Bumped up axios version to 0.25

---

src/_scss/layouts/default/header/_warning.scss
src/_scss/pages/modals/covid19/_covid19.scss
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/containers/globalModal/GlobalModalContainer.jsx
src/js/containers/homepage/UEIModalContainer.jsx

Add a banner and modal to announce the upcoming addition of UEI, to replace DUNS.
Used InfoBanner.jsx for banner, changed the text and did not set an expiration date in the code since that wasn't specified in the ticket. Made a new Modal component, based on the CovidModalContainer. Reused some css from that component and added some '!important' css to make the new component match the mocks.
The latest copy is attached to the ticket.
[DEV-8335](https://federal-spending-transparency.atlassian.net/browse/DEV-8335)
**Mockup:**
link in ticket
Author:
- [x ] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet …

8335 uei banner and modal

---

package-lock.json
package.json

High level description:
Github dependabot flagged the following npm package is security vulnerabilities - tar < 4.4.18 and trim-newlines < 3.0.1 
node-sass uses both package.  node-sass needed to be updated to a later version in package.json to include the updated versions of tar and trim-newlines.

Updated version of node-sass to 7.0.1 

---

src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx
tests/components/agency/visualizations/StatusOfFundsChart-test.jsx

As a user, I can see negative values on the Status of Funds chart as well as on the drilldown on the left. Example: Advanced search “Categories” tab horizontal bar chart
Note: Currently there are no known cases of negative values to test so I created a mock data object to test negative treatment. The mock data object should be created in StatusOfFunds.jsx and passed as a prop to VisualizationSection `results={mockChartData.results}`.
~ Text and axis overlap issue in mobile is known and being worked on by design
```
const mockChartData = {
page_metadata: {
page: 1,
total: 1,
limit: 2,
next: 2,
previous: null,
hasNext: true,
hasPrevious: false
},
results: [
{
name: "National Oceanic and Atmospheric Administration",
_budgetaryResources: …
```

dev-8331 add negative obligations status of funds

---

src/js/components/agencyV2/AgencyPage.jsx
src/js/components/agencyV2/AgencySection.jsx
src/js/components/agencyV2/overview/FySummary.jsx
src/js/components/agencyV2/statusOfFunds/StatusOfFunds.jsx
tests/components/agency/overview/FYSummary-test.jsx
webpack/webpack.prod.config.js

corrects date showing momentarily, then changing to "no data available"
also removes check for selected year, so shows appropriate date for all years
[DEV-8099](https://federal-spending-transparency.atlassian.net/browse/DEV-8099)
[DEV-8422](https://federal-spending-transparency.atlassian.net/browse/DEV-8422)
**Mockup:**
n/a
Author:
- [n/a ] Added Unit Tests for helper …

8099 fix data through date to agency profiles, 8422 show for all FYs

---

package-lock.json
src/_scss/pages/agencyV2/visualizations/_totalObligationsOverTime.scss

This chart was off center and spilling over into the next chart in the carousel, at tablet and mobile sizes only.
I removed the padding that was causing it. I didn't see any spots where this adversely affected any tooltips, but please check for any.
[DEV-8438](https://federal-spending-transparency.atlassian.net/browse/DEV-8438)
**Mockup:**
n/a
Author:
Reviewer(s):

8438 total obl chart overlap

---

src/js/components/recipientLanding/RecipientLandingSearchBar.jsx
src/js/components/search/filters/recipient/RecipientName.jsx

Updated wrong section in previous PR, this fix updates the advanced search placeholder text and reverts previous update
[DEV-8240](https://federal-spending-transparency.atlassian.net/browse/DEV-8240)
Author:
Reviewer(s):

dev 8240 fix add uei to advanced search

---

src/_scss/pages/award/shared/awardAmountsSection/_dataTable.scss
src/js/components/award/shared/awardAmounts/AwardAmountsTable.jsx

ticket AC clarified
update to break on port width, not dynamic
[DEV-7613](https://federal-spending-transparency.atlassian.net/browse/DEV-7613)
**Mockup:**
in ticket comments
Author:
- [n/a ] Added Unit Tests for helper functions, reducers, models and Container/Component Interactivity Expectations `if applicable` [React Testing Library](react-testing-library.md)
- [n/a ] [API contract](https://github.com/fedspendingtransparency/usaspending-api/tree/dev/usaspending_api/api …

7613 static break for wrapping

---

package-lock.json
package.json
src/index.ejs
src/js/containers/glossary/GlossaryListener.jsx
webpack/webpack.common.js

Add Foresee survey
Added survey code snippets for staging (ie. lower environments) and prod to index.ejs.  To set session level options, you can launch the admin panel from usaspending.gov#fscommand=fstest.  The frontend code removes hashes from the URL so updated code to keep hash only for #fscommand=fstest.  This can't be tested locally but the code in the PR is in sandbox.  You'll need to stay on the site for over to 30 seconds and may need to open a few pages for the survey to appear.
[DEV-8287](https://federal-spending-transparency.atlassian.net/browse/DEV-8287)
Author:
Reviewer(s):

8287 - Add Foresee survey to site

---

package-lock.json
package.json
src/_scss/pages/recipient/_recipientInfoBanner.scss
src/_scss/pages/recipient/recipientPage.scss
src/js/components/recipient/RecipientInfoBanner.jsx
src/js/components/recipient/RecipientPage.jsx
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx
src/js/components/sharedComponents/header/UEIInfoBanner.jsx
src/js/dataMapping/stickyHeader/stickyHeader.js

The calculation of the recipient_hash will be check for UEI, then DUNS, then Recipient Name. Due to this change certain links to Recipient Profile pages that depend on the hashes might be broken so we need to add a warning banner to those pages alerting users to update any saved links. 
Refactored the InfoBanner component to be reuseable.  Created separate components for the site wide UEI banner and this recipient profile to include the infobanner component.  Fixed the close button to not show the banner even after refreshing the page.  Removed reference to the IE unsuported banner.
[DEV-8480](https://federal-spending-transparency.atlassian.net/browse/DEV-8480) …

8480 - Added UEI warning banner to recipient profile page

---

package-lock.json
package.json
src/js/components/search/header/NoDownloadHover.jsx

Download limit is getting increased back to 500k. As a result, the frontend message should match the current limit.
[DEV-8499](https://federal-spending-transparency.atlassian.net/browse/DEV-8499)
Reviewer(s):

[DEV-8499] Increase download limit message back to 500k

---

package-lock.json
package.json
src/js/components/agencyV2/visualizations/ObligationsByAwardTypeTooltip.jsx
tests/components/agency/visualizations/ObligationsByAwardTypeTooltip-test.jsx

The percentage figures in the “% of Total” column in the hover state should round to one decimal place.
n/a
[DEV-8428](https://federal-spending-transparency.atlassian.net/browse/DEV-8428)
Author:
Reviewer(s):

8428 - Standardize percentages in award obligation by type tooltip

---

src/index.ejs

Disabling the Foresee Survey in QAT.  The survey is currently blocking ops from testing with the dynamic renderer.  Foresee can disable certain user agents but the turn around time isn't immediate.  Once Foresee disables the correct user agent for the dynamic renderer we can re-enable the survey.
[DEV-8287](https://federal-spending-transparency.atlassian.net/browse/DEV-8287)
Author:
Reviewer(s):

8287 - Disable Foresee survey in QAT

---

src/js/components/recipientLanding/RecipientLandingSearchBar.jsx
src/js/components/recipientLanding/table/RecipientLandingTable.jsx
src/js/models/v2/recipient/BaseRecipientLandingRow.js

Add column for UEI to the table on the Recipients landing page.
Added the column, following the pattern for the DUNS column. Backend changes were required, so for testing you need to use the QAT endpoints. Also added the new var for the DUNS label in that table.
[DEV-8289](https://federal-spending-transparency.atlassian.net/browse/DEV-8289)
**Mockup:**
link to mock in the ticket is bad, but it should look like the DUNS column right next to it
Author:
- [ x] Verified that this …

8289 add uei column to recipients table

---

src/js/components/recipient/topFive/TopFive.jsx
src/js/components/state/topFive/TopFive.jsx

Remove unneeded alt text from the images in the Top Five section on both Recipient Profile and State Profile pages.
This is from our 508 Tech Debt list. Best practice for alt text says the alt text should not repeat any text that is already on the page, and that if no alt text is needed for an image (if it is only decorative and not essential to content) then leaving the alt attribute with a value of empty string is preferred. 
[DEV-7759](https://federal-spending-transparency.atlassian.net/browse/DEV-7759)
**Mockup:**
n/a
Author:
- [ …

7759 - removed unneeded alt text from the Top Five components

---

src/js/components/covid19/DataSourcesAndMethodologiesPage.jsx

Remove infrastructure defc from COVID DS&M
The useDefCode custom hook now returns all defcs including both COVID and Infrastructure.  When using useDefCode on 
covid pages we need to filter for the covid disaster code.
[DEV-8548](https://federal-spending-transparency.atlassian.net/browse/DEV-8548)
Author:
- [n/a] Verified cross-browser compatibility: Chrome, Safari, Firefox, Internet Explorer, Edge
- [n/a] Verified mobile/tablet/desktop/monitor responsiveness
- [n/a] Verified that this PR does not create any *new* accessibility issues (via Axe …

Hotfix/8548 - Remove infrastructure defc from COVID DS&M

---

src/js/components/agencyV2/visualizations/StatusOfFundsChart.jsx

(To go out with sprint 148)
When obligations equal zero, the blue bar is still visible due to logic errors in showing negative obligations. This PR fixes the issue by giving the blue bar a width of zero when obligations equal zero.
[DEV-8450](https://federal-spending-transparency.atlassian.net/browse/DEV-8450)
Author:
Reviewer(s):

DEV-8450 Do not show blue obligations bar when obligations equals $0

---

src/_scss/core/_variables.scss

Updated typography styles global styles to match homepage updates
I made some simple changes in _variables.scss.  It looks like each page is overriding h1 - h5 for the specific page so changing these values global didn't change anything from what I can tell.  However, while working on the homepage we should reference these variables for typography from _variables.scss.  Also see the ticket for a list of variables defined across files.  I scheduled a frontend meeting for the team to discuss how we could consolidate these files moving forward.
[DEV-8519](https://federal-spending-transparency.atlassian.net/browse/DEV-8519)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/621fa649d1b184a0f2a2d1f0
The …

8519:  Updated typography styles global styles to match homepage updates

---

src/_scss/pages/search/filters/keyword/_keywordHover.scss
src/_scss/pages/search/results/table/_tableTypes.scss
src/_scss/pages/search/results/table/resultsTable.scss
src/js/components/search/table/ResultsTableTabItem.jsx
src/js/containers/keyword/table/ResultsTableContainer.jsx
src/js/dataMapping/shared/TableTabsTooltips.jsx

On the Keyword Search page, when you hover over the Loans tooltip icon, the tooltip is displayed behind table.  You can only see the arrow pointing to it
After trying many things, I found that removing overflow: hidden from the tabs section css and adding overflow-x: hidden to its parent solved it.
[DEV-8511](https://federal-spending-transparency.atlassian.net/browse/DEV-8511)
**Mockup:**
n/a
Author:
- [ x] Verified that this PR does not create any *new* accessibility issues …

8511 loans tooltip

---

src/_scss/pages/agencyV2/statusOfFunds/_introSection.scss
src/js/components/agencyV2/awardSpending/AwardSpendingIntro.jsx
src/js/components/agencyV2/awardSpending/AwardSpendingSubagency.jsx

Adding new copy to the Award Spending section of the Agency Profile page.
Made a new component for an intro to the Award Spending section, used the intro section of Status of Funds as a template since the AC specifies that this section should use the same css as that section. 
For some reason I started getting errors related to the css import in the _introSection.scss, it suddenly couldn't find those variables. I tried importing only '_variables.scss' but that didn't work so I imported 'all' and that solved it. If there is a better way to do it, I'm open to that.
[DEV-8583](https://federal-spending-transparency.atlassian.net/browse/DEV-8583)
**Mockup:**
n/a
Author:
- …

8583 - added new component for intro section in Award Spending section

---

scripts/buildRedirectConfig.js

https://www.usaspending.gov/index.html is returning a 404.  Added a server redirect to fix this.
https://data-transparency-bfs.slack.com/archives/C0155EL4AU9/p1647358127740889 
n/a
Reviewer(s):

Fix homepage 404

---

src/_scss/pages/modals/recipient/_table.scss
src/js/components/recipient/modal/table/ChildRecipientModalTable.jsx
src/js/models/v2/recipient/BaseChildRecipient.js

**High level description**
This is a follow up ticket to correct a problem with the headers, found by QA.
At smaller desktop screen sizes the headers were not aligned with each other.
There was also a problem with sorting but that seems to be caused by having many rows with 'UEI not provided' or 'DUNS not provided' and is no longer happening.
Removed vertical-align: top from the table css.
I also changed the key in the table to use uei instead of duns, since duns will go away soon.
[DEV-8562](https://federal-spending-transparency.atlassian.net/browse/DEV-8562)
**Mockup:**
n/a
Author:
- [x ] Verified cross-browser compatibility: Chrome, Safari, Firefox, …

8562 uei column in recipient child table

---

src/_scss/elements/_buttons.scss

Updates the common button styles to have border radius of 4px according to homepage mock. 
*Note that some buttons on the site will not be affected by this change since they are Links styled as buttons and not html button elements
[DEV-8550](https://federal-spending-transparency.atlassian.net/browse/DEV-8550)
**Mockup:**
See ticket for link
Author:
Reviewer(s):

DEV-8550 Update the button common component with design updates in the homepage mock

---

package-lock.json
package.json

Reverting qat to use previous plugin for css asset optimization.  This was breaking the build.
n/a
Reviewer(s):

Restored optimize-css-assets-webpack-plugin

---

src/js/containers/homepageUpdate/HomepageCovidContainer.jsx

Responding to QA feedback, need to add a p tag in the content of the second card, to match the MAC
Added p tag, now there is a break between the two sentences in that card.
[DEV-8515](https://federal-spending-transparency.atlassian.net/browse/DEV-8515)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/621fa593669231a368bf909c
Author:
Reviewer(s):

8515 - added another p to the track card content, to match the MAC

---

src/js/components/homepageUpdate/community/Community.jsx
src/js/components/homepageUpdate/gettingStarted/GettingStarted.jsx

These were sent back from testing to fix the tab highlighting on buttons. Added tabIndex={-1} to anchors to resolve this bug
[DEV-8517](https://federal-spending-transparency.atlassian.net/browse/DEV-8517)
[DEV-8518](https://federal-spending-transparency.atlassian.net/browse/DEV-8518)
Author:
Reviewer(s):

DEV-8517 and DEV-8518 Testing Fix for tab through functionality

---

src/js/dataMapping/bulkDownload/bulkDownloadOptions.js

In Custom Account Data download, add the parentheticals for file name after the business names in the “file type” filter, as well as in the “Your selected options are…” section.
[DEV-8576](https://federal-spending-transparency.atlassian.net/browse/DEV-8576)
Author:
Reviewer(s):

DEV-8576 Update custom account data file type naming

---

src/_scss/pages/homepageUpdate/homepageUpdate.scss

Fixes bug found in testing where image carousel is blank at first in mobile view
Background flair was on top of the image hiding it - updated z-indexes on background and image
Author:
Reviewer(s):

Homepage getting started blank image mobile bug fix

---

src/js/components/recipient/topFive/TopFiveRow.jsx

On Recipients page, in the top 5 tables, the names were not showing.
Added the data for .name to show when there is no slug present
[DEV-8809](https://federal-spending-transparency.atlassian.net/browse/DEV-8809)
**Mockup:**
n/a
Author:
Reviewer(s):

8809 - added names to the top five tables when no slug is present

---

src/js/components/state/topFive/TopFiveRow.jsx

The names were not showing in the top five tables for states
Needed to make the same change that we made for Recipients top five tables last week, add the name without link if no slug is available for the name
[DEV-8816](https://federal-spending-transparency.atlassian.net/browse/DEV-8816)
**Mockup:**
n/a
Author:
Reviewer(s):

8616 - added names without links to top 5 when no slug is available

---

src/js/components/sharedComponents/header/NavBar.jsx

https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1653409627992429
Was testing out the nav bar and accidentally merged this into QAT

Removed the second resources tab that was accidentally committed

---

src/_scss/pages/search/_filterExpand.scss

The word keyword shakes on the tooltip on mobile
There seemed to be conflicting widths being applied in css for screen size <424 px. Forced a single rule to be applied and it fixed the problem.
[DEV-8484](https://federal-spending-transparency.atlassian.net/browse/DEV-8484)
**Mockup:**
Author:
Reviewer(s):

DEV-8484 keyword shake

---

src/js/components/award/contract/ContractContent.jsx
src/js/components/award/financialAssistance/FinancialAssistanceContent.jsx
src/js/components/award/idv/IdvContent.jsx
src/js/components/award/shared/AwardPageWrapper.jsx

***High level description:***
Filter defcode based on covid_19 disaster group
***Technical details:***
Get covid disaster codes from redux and filter award codes to only show COVID codes
[DEV-8832](https://federal-spending-transparency.atlassian.net/browse/DEV-8832)
Author:
Reviewer(s):

Hotfix 8832 covid award tag staging

---

package-lock.json
src/_scss/lib/ibTable/ibTable.scss
src/_scss/pages/search/results/table/resultsTable.scss
src/js/components/keyword/table/ResultsTable.jsx
src/js/components/search/table/ResultsTable.jsx
src/js/components/sharedComponents/IBTable/components/Table.jsx

Add a top scrollbar to the results table on Advanced Search page
Since this is a component that is used in five places, needed to make a prop for the topScroller and also needed to add it to the Keyword Search results table; the table (with three tabs) at the bottom of the Awards page should be unchanged, that table does not get the topScroller; I also removed a couple of functions from this component because they weren't actually ever being called and the code is confusing enough already
[DEV-8729](https://federal-spending-transparency.atlassian.net/browse/DEV-8729)
**Mockup:**
n/a
Author:
- [x ] Verified cross-browser …

8729 add horiz scroll to search tables mod

---

src/js/components/agency/statusOfFunds/VisualizationSection.jsx
src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Adjustments for sticky hover tooltip
Used a query selector call hide the tooltip when outside the svg for edge cases 
[DEV-8767](https://federal-spending-transparency.atlassian.net/browse/DEV-8767)
Author:
Reviewer(s):

DEV-8767 Sticky hover

---

src/js/components/award/contract/ContractContent.jsx
src/js/components/award/shared/awardAmounts/HorizontalSingleStackedBarViz.jsx
src/js/dataMapping/award/awardAmountsSection.js
src/js/helpers/awardAmountHelper.js

Additional fix to DEV-8869.  The following award shows a chart where the outlay greater than obligation.  When the outlay is greater than obligation "Chart Not Available" should show.
https://qat.usaspending.gov/award/ASST_NON_693JG42230000V600AK0083_6925/
[DEV-8869](https://federal-spending-transparency.atlassian.net/browse/DEV-8869)
Reviewer(s):

8869 - Fix issue with infrastructure chart

---

src/js/components/dataDives/EquityCovidSpendingPage.jsx
src/js/components/dataDives/sections/MainCards.jsx

Add Google analytics tracking events to the Data Dives page
Historically these have been tested in an environment instead of locally.  Melissa is going to work with Andrew Ly to get these tested.  Please verify the code looks correct.
[DEV-8883](https://federal-spending-transparency.atlassian.net/browse/DEV-8883)
**Mockup:**
n/a
Author:
Reviewer(s):

8883 - Add Google analytics tracking events to the Data Dives page

---

src/js/components/award/shared/awardAmounts/AwardAmountsChart.jsx

Fixed issue with covid award spending not showing on award summary bar chart 
[Example award
](https://www.usaspending.gov/award/ASST_NON_S425U210041_9100)
[DEV-8938](https://federal-spending-transparency.atlassian.net/browse/DEV-8938)
Author:
Reviewer(s):

8938 - Fixed issue with covid award spending not showing on award summary bar chart 

---

src/js/containers/award/AwardContainer.jsx

QAT found that the msg was not showing in the Federal Account section if the award is IDV and unlinked.
Added a check for the data.count property if the award is idv.
The additional urls to check different types of awards are in a comment from Allie.
[DEV-8931](https://federal-spending-transparency.atlassian.net/browse/DEV-8931)
**Mockup:**
in ticket
Author:
Reviewer(s):

8931 - added logic to detect if an idv is unlinked

---

src/_scss/pages/award/_awardAgencyRecipient.scss
src/_scss/pages/award/shared/awardAmountsSection/_index.scss
src/js/components/award/shared/awardAmounts/AwardAmountsSection.jsx
src/js/containers/award/idv/IdvAwardAmountsSectionContainer.jsx

Add Award Amount chart tabs on mobile.  this affects idv and non-idv awards with infrastructure spending
Switched both idv and non-idv awards to use the Tabs common component from DTUI 
[DEV-8903](https://federal-spending-transparency.atlassian.net/browse/DEV-8903)
Author:
Reviewer(s):

8903 - Add Award Amount chart tabs on mobile

---

src/_scss/_dtui-overrides.scss
src/_scss/all.scss

Temp fix for the tab online on award summary charts
I added a new temporary file for dtui overrides.  I figure we'll have future areas where we'll need to override dtui styles.  Instead of mixing these into css for a specific page this could be a good location.  Planning to remove this particular override after we upgrade DTUI to React 17.
[DEV-8904](https://federal-spending-transparency.atlassian.net/browse/DEV-8904)
Author:
Reviewer(s):

8904 - Temp fix for the tab online on award summary charts

---

src/js/components/homepage/SummaryStats.jsx

Bug fix in summary stats fy and period selection
There was a data mismatch in QAT and PROD.  QAT doesn't have the latest period data and the summary stats are showing up as blank there.  Updated how we're getting the latest year and period in this PR
[DEV-8914](https://federal-spending-transparency.atlassian.net/browse/DEV-8914)
Author:
Reviewer(s):

8914 - Bug fix in summary stats fy and period selection

---

src/js/components/homepage/Homepage.jsx
src/js/components/sharedComponents/PageWrapper.jsx

Add title prop for PageWrapper on homepage
Added the prop, got the string from metaTagHelper.js
[DEV-8916](https://federal-spending-transparency.atlassian.net/browse/DEV-8916)
**Mockup:**
Author:
Reviewer(s):

8916 - added title for pagewrapper on homepage

---

tests/containers/award/idv/IdvActivityContainer-test.jsx

fixed error with jest tests
a function was not mocked when it should have been
[DEV-8976](https://federal-spending-transparency.atlassian.net/browse/DEV-8976)
Author:
Reviewer(s):

DEV-8976 fixed xxx is not a function test

---

src/js/components/sharedComponents/RedirectModal.jsx

Small copy change to the text in the external link modal
I copied the new text from the ticket then pasted it over the old text in the code.
[DEV-9160](https://federal-spending-transparency.atlassian.net/browse/DEV-9160)
**Mockup:**
n/a, but there's a picture attached to the ticket
Author:
Reviewer(s):

9160 - changed copy in the external link modal

---

src/_scss/pages/interactiveDataSources/_sidebar.scss
src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx

The sidebar was overlapping the footer and the text in the Stay in Touch banner was over the sidebar content.
I used examples from work done in branch 8498 (never merged in) to make the sidebar for this page sticky, so it no longer overlaps the footer or Stay in Touch banner.
To make this change to the Sidebar component would require making changes to every instance of the Sidebar in the site.
[DEV-9163](https://federal-spending-transparency.atlassian.net/browse/DEV-9163)
**Mockup:**
n/a
Author:
- [x ] Verified mobile/tablet/desktop/monitor …

9163 - made data sources page sidebar sticky

---

src/js/components/homepageUpdate/HomepageResources/HomepageResources.jsx
src/js/components/interactiveDataSources/InteractiveDataSourcesPage.jsx
src/js/dataMapping/navigation/menuOptions.jsx

https://federal-spending-transparency.atlassian.net/browse/DEV-9180
Remove code to hide the Data Sources page from upper environments (ie. FeatureFlag component)
Remove code to show “Data Model” instead of “Data Sources” in Staging and Prod, in the main nav under “Resources”
Make sure the “Data Sources” item from AC2 links to the /data-sources page 
remove new badge from analyst guide menu option and make sure new badge is on data sources menu option
Added a newTag to data source and removed it from analyst guide 
DEV-9180 https://federal-spending-transparency.atlassian.net/browse/DEV-9180
Author:
- [x ] Verified cross-browser …

Mod 9180 update data source page

---

src/js/GlobalConstants.js
src/js/components/covid19/Covid19Tooltips.jsx
src/js/components/covid19/assistanceListing/SpendingByCFDA.jsx
src/js/containers/covid19/helpers/covid19.jsx
src/js/containers/search/topFilterBar/TopFilterBarContainer.jsx

Responded to QA feedback -
1) Advanced Search (AC -2) - Change Assistance Listings to Assistance Listing
2) Covid Page (AC 8 and 9) - Change Award Spending by Assistance Listings to Award Spending by Assistance Listing for both AC
3) Covid Page (AC 11) - In the Award Spending by Listing section first paragraph, fix the link to the Assistance Listings Glossary term and update the paragraph text to -
“Overall financial assistance awards represent the vast majority of COVID-19 appropriated spending. Assistance Listings [[glossary link](https://www.usaspending.gov/disaster/covid-19?glossary=cfda-program&publicLaw=all)] are programs like the Supplemental Nutrition Assistance Program (SNAP) that provide financial assistance to individuals, organizations, businesses, …

Fix - 8535 update cfda program labels

---

src/js/components/about/AboutContent.jsx

Removed both the data source and data quality from the about page
inside of AboutContent component, I removed data source and quality form the side bar and the actual page its self. 
[DEV-9187](https://federal-spending-transparency.atlassian.net/browse/DEV-9187)
**Mockup:**
NO mocks
Author:
Reviewer(s):

Mod 9187 removed the data sources/quality from about page

---

src/js/components/aboutTheDataSidebar/AboutTheData.jsx
src/js/helpers/aboutTheDataSidebarHelper.js
tests/helpers/aboutTheDataSidebarHelper-test.js

Added a function to escape special chars in the regexp used in search; because search wasn't working with '(', '-', etc.
[DEV-9299](https://federal-spending-transparency.atlassian.net/browse/DEV-9299)
**Mockup:**
n/a
Author:
Reviewer(s):

9299 - added function to escape special chars in the regexp

---

src/content/about-the-data/file-d2.mdx

The link in File D2 stopped working
Had to revert back to the code that was overwritten somehow, using the markdownLink component
[DEV-9344](https://federal-spending-transparency.atlassian.net/browse/DEV-9344)
**Mockup:**
n/a
Author:
Reviewer(s):

9344 - added the markdown link component back the  file-d2 file

---

src/js/components/aboutTheDataSidebar/AboutTheDataListView.jsx
src/js/components/glossary/search/ResultItem.jsx

added google analytics to about the data and glossary.
[DEV-9370](https://federal-spending-transparency.atlassian.net/browse/DEV-9370)
**Mockup:**
Author:
Reviewer(s):

Mod 9370 add g analytics to atd

---

package-lock.json
src/_scss/components/aboutTheDataSidebar/aboutTheData.scss
src/_scss/pages/glossary/glossaryPage.scss
src/js/components/aboutTheDataSidebar/AboutTheData.jsx
src/js/components/aboutTheDataSidebar/AnimatedAboutTheDataWrapper.jsx
src/js/components/glossary/AnimatedGlossaryWrapper.jsx
src/js/components/glossary/Glossary.jsx
src/js/components/sharedComponents/header/DropdownItem.jsx
src/js/containers/aboutTheDataSidebar/AboutTheDataContainer.jsx
src/js/containers/aboutTheDataSidebar/AboutTheDataListener.jsx
src/js/containers/glossary/GlossaryContainer.jsx
src/js/containers/glossary/GlossaryListener.jsx
src/js/redux/actions/slideouts/slideoutActions.js
src/js/redux/reducers/index.js
src/js/redux/reducers/slideouts/slideoutReducer.js

Make sure each of our slideout drawers can open on top of the other one, and leave the bottom one open when the top one is closed
Made a new redux property to keep track of the lastOpened slideout, and used that to set the z-index on the lastOpened slideout
[DEV-9399](https://federal-spending-transparency.atlassian.net/browse/DEV-9399)
Author:
Reviewer(s):

9399 atd drawer behavior 2

---

src/js/components/homepageUpdate/FeaturedContent/FeaturedContent.jsx
src/js/dataMapping/navigation/menuOptions.jsx

Update the homepage training video card to redirect to the training video page.
Added training video to the Resource drop down menu.
Update the homepage training video card to redirect to the training video page.
Added training video to the Resource drop down menu.
NA
[DEV-9384](https://federal-spending-transparency.atlassian.net/browse/DEV-9384)
**Mockup:**
Author:
Reviewer(s):

Updated the Training Video Links

---

src/_scss/components/_genericErrorMessage.scss
src/_scss/pages/modals/video/_trainingVideoModal.scss
src/js/components/sharedComponents/TrainingVideoModal.jsx
src/js/components/trainingVideos/GenericErrorMessage.jsx
src/js/components/trainingVideos/featuredVideo/FeaturedVideo.jsx
src/js/components/trainingVideos/videoCard/VideoCard.jsx

Added loading and error messages to the video modal.  I'm only capturing this one error state for now.  https://app.zeplin.io/project/6307b25775991866c016769c/screen/63c18f0672594e058214f824. The other 2 error states in the mock require more thought and research.  I'm not sure how we would check for the other two error states without hitting the api.
[DEV-9425](https://federal-spending-transparency.atlassian.net/browse/DEV-9425)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/screen/63c18f0672594e058214f824
Author:
Reviewer(s):

9425 - Added loading and error messages to the video modal 

---

src/_scss/pages/trainingVideos/_featuredVideo.scss

Fixed white line on featured card between thumbnail and title
Added background color to featured card container.  I can only reproduce the white line in Safari.  It's pretty consistent.  the fix here fixed it in Safari so hopefully this works!
[DEV-9441](https://federal-spending-transparency.atlassian.net/browse/DEV-9441)
Author:
Reviewer(s):

9441 - Fixed white line on featured card between thumbnail and title

---

src/_scss/components/_genericErrorMessage.scss
src/_scss/pages/homepageUpdate/_wordOfTheDay.scss
src/js/components/sharedComponents/TrainingVideoModal.jsx

* Something went wrong message should be font weight 16px (see Slack message in brus-frontend-ux channel)
* Sorry, we’re unable to load this video. - Font color should be #e6e6e6 per Zeplin
* Report this error button text should be 16px per Zeplin
[DEV-9425](https://federal-spending-transparency.atlassian.net/browse/DEV-9425)
**Mockup:**
https://app.zeplin.io/project/6307b25775991866c016769c/screen/63c18f0672594e058214f824
Author:
Reviewer(s):

9425 - Adjusted font styling per QA feedback. 

---

src/index.ejs

Set up Google Analytics 4 and Data Stream to begin capturing data
Switched to Google Analytics from analytics.js to Google Tag Manager (GTM) configured with Universal Google Analytics and GA4.  I had to add the script for Google Tag Manager (GTM) to every page on the site (ie. in index.ejs) and then config GTM to use GA 3 (the current version of GA that's going to be deprecated in July) and GA4 (the new version).
Screenshot from Google Tag Assistant showing that the tags correctly fired - 
[DEV-9536](https://federal-spending-transparency.atlassian.net/browse/DEV-9536)
Author:
Reviewer(s):

9536 - Set up Google Analytics 4 and Data Stream to begin capturing data

---

src/_scss/pages/agency/visualizations/_statusOfFundsChart.scss
src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Bug ticket for the font and placement of the legend under the sof chart
In a previous ticket I made the mistake of changing a classname.
I changed it back and the bug is fixed.
[DEV-9588](https://federal-spending-transparency.atlassian.net/browse/DEV-9588)
Author:
Reviewer(s):

9588 - changed classname back to fix bug

---

src/_scss/pages/modals/filter/_filterModal.scss
src/js/components/search/table/ResultsTableSection.jsx
src/js/components/sharedComponents/FilterModal.jsx

the mac was hiding on the ticket so I didn't see it at first
i talked with the PO so that the mac won't be hidden on jira in the future for FE devs
there was also a comma as part of 9542 that needed to be deleted and i did it in this PR as opposed to creating a whole new one
Author:
Reviewer(s):

DEV-9543 clarify modal

---

src/_scss/components/tooltips/_customTooltipContent.scss
src/js/components/search/SearchSidebar.jsx
src/js/components/search/filters/tooltips/AdvancedSearchTooltip.jsx

Make new tooltip for Congressional District info
Put it in AdvancedSearchTooltip.jsx; but used class from spending-types-tt bc that class has a line height that matches the mock for this; added a class for margin top and bottom for p elements, to match the mock
[DEV-9600](https://federal-spending-transparency.atlassian.net/browse/DEV-9600)
**Mockup:**
word doc attached to ticket
Author: …

9600 - made new tooltip for congressional districts info

---

src/_scss/pages/agency/visualizations/_statusOfFundsChart.scss
src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Added some wording to a tooltip that changes based on what status of fund level its on
Hover modal on each level of the Status of Funds chart includes the “Click bar to view [next funding level]”
“Click bar…” text is updated to the following in descending order: TBD
Click a sub-component to view Federal Accounts
Click a Federal Account to view Treasury Accounts
Click a Treasury Account to view Program Activities or Object Classes
[DEV-9610](https://federal-spending-transparency.atlassian.net/browse/DEV-9610)
Author:
Reviewer(s):

Mod 9610 status of funds hover modal

---

src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Changed the status of fund outlays chart, to where the entire bar is clickable to the next level instead of just the yellow parts.
Made sure the lowest level is not clickable. 
[DEV-9613](https://federal-spending-transparency.atlassian.net/browse/DEV-9613)
Author:
Reviewer(s):

Changed so a click will drill down  on the full bar

---

src/js/components/search/visualizations/rank/RankVisualizationTitle.jsx

you can click outside the menu and it goes away now
[DEV-9590](https://federal-spending-transparency.atlassian.net/browse/DEV-9590)
Author:
Reviewer(s):

DEV-9590 fixed menu not closing on blur

---

src/_scss/pages/glossary/_definition.scss
src/js/components/glossary/definition/GlossaryDefinition.jsx

Removed an input element according to the 508 scan.
Removed an input element that wasn't doing anything due to 508 scan
[DEV-9657](https://federal-spending-transparency.atlassian.net/browse/DEV-9657)
**Mockup:**
Author:
Reviewer(s):

Removed the input for on Glossary Definition Component

---

src/_scss/pages/covid19/recipient/recipientContainer.scss
src/_scss/pages/search/results/visualizations/geo/geoVisualization.scss
src/_scss/pages/search/results/visualizations/geo/map/map.scss
src/_scss/pages/state/visualizations/geo/geoVisualization.scss

fix qa issue where map controls cover up tooltip on mobile on covid profile page
[DEV-9605](https://federal-spending-transparency.atlassian.net/browse/DEV-9605)
Author:
Reviewer(s):

DEV-9605 qa issue on covid profile map

---

src/_scss/pages/search/results/visualizations/geo/_disclaimer.scss
src/_scss/pages/search/results/visualizations/geo/map/_toggle.scss
src/js/components/search/visualizations/geo/MapLayerToggle.jsx

I had to also added a tooltip-pointer styling to counter act the pointer being off.
Added tooltip for the congressional distract on advance search page on the maps tab.
Made State, County, and Congressional District plural 
[DEV-9666](https://federal-spending-transparency.atlassian.net/browse/DEV-9666)
**Mockup:**
Author:
Reviewer(s):

Added Tooltip Advanced Search Geo Map

---

src/_scss/components/search/_keywordSearchLink.scss
src/js/components/search/KeywordSearchLink.jsx

- needed a hover state (not visited state)
kept Link, added target and noreferrer and hover style
[DEV-9691](https://federal-spending-transparency.atlassian.net/browse/DEV-9691)
Author:
Reviewer(s):

DEV-9691 fix

---

package-lock.json
src/_scss/pages/search/results/visualizations/geo/map/_toggle.scss
src/js/components/search/visualizations/VisualizationWrapper.jsx
src/js/components/search/visualizations/geo/GeoVisualizationSection.jsx
src/js/components/search/visualizations/geo/MapLayerToggle.jsx
src/js/components/search/visualizations/geo/MapWrapper.jsx
src/js/components/state/overview/StateOverview.jsx
src/js/components/state/visualizations/geo/GeoVisualizationSection.jsx
src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx
src/js/containers/state/visualizations/geo/GeoVisualizationSectionContainer.jsx
src/js/dataMapping/shared/mobileBreakpoints.js

tooltip was off to the left on both of these pages between 768 and 992: 
http://localhost:3000/state/alabama/latest (map cd tooltip)
http://localhost:3000/search/?hash=2731f194e8bd5c1506ffcc23c29654d5 (spending by geography tab -> cd tooltip)
Author:
Reviewer(s):

fix bug with tooltip location on tablet

---

src/js/components/recipient/topFive/TopFive.jsx
src/js/components/state/topFive/TopFive.jsx

Based on results of 508 scan, add aria-hidden=true to the icons in the top five tables on Recipient and State pages
added aria-hidden
[DEV-7760](https://federal-spending-transparency.atlassian.net/browse/DEV-7760)
**Mockup:**
n/a
Author:
Reviewer(s):

7760 - added aria-hidden=true to the icons in the top five tables

---

src/js/components/search/filters/location/EntityDropdown.jsx

issue in location dropdown when there is only one element in the dropdown
[DEV-9727](https://federal-spending-transparency.atlassian.net/browse/DEV-9727)
Author:
Reviewer(s):

DEV-9727 bad condition where they were equal

---

src/js/components/agency/visualizations/StatusOfFundsChart.jsx

Agency Profile Pages - Status of Funds Chart Hover State Preventing Mouse Click
Created a let that captures the word length and added a set px to the word length.
I tried to get a useEffect to capture it and use a more condition amount but it kept giving me memory leaking issues. This might be oversimplifying it a little bit 
[DEV-9713](https://federal-spending-transparency.atlassian.net/browse/DEV-9713)
Author:
Reviewer(s):

tooltip changes based on name length.

---

src/js/components/search/modals/fullDownload/screens/DownloadScope.jsx

Removed the let me choose button and added text below the everything button that ben provided
[DEV-9803](https://federal-spending-transparency.atlassian.net/browse/DEV-9803)
Author:
Reviewer(s):

mod-9803 Removed let me choose button

---

src/js/components/aboutTheData/DataSourcesAndMethodologiesPage.jsx
src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx

Add text in two places, explaining more about unlinked awards
added the text where specified; removed the italics class from the html in the ds&m page because that class doesn't exist in the css for that page
[DEV-9806](https://federal-spending-transparency.atlassian.net/browse/DEV-9806)
**Mockup:**
n/a
Author:
Reviewer(s):

9806 - added new text in two places, about unlinked awards

---

src/js/components/bulkDownload/accounts/filters/SubmissionTypeFilter.jsx

Feedback from QA, two small changes in the second page that was changed; Allie left comment on the ticket explaining
Added a space after 'Note:'; made the word 'page' included in the Link
[DEV-9806](https://federal-spending-transparency.atlassian.net/browse/DEV-9806)
**Mockup:**
n/a
Author:
Reviewer(s):

9806 - two small copy changes, feedback from qa

---

src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx

icons in the second column were not the same size
Added the inline css for height and width that was added to the other columns
[DEV-9847](https://federal-spending-transparency.atlassian.net/browse/DEV-9847)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/645cfcc7990ffb0e1b1781d0
Author:
Reviewer(s):

9847 - added size for icons in second column in megamenu

---

src/js/containers/explorer/detail/DetailContentContainer.jsx

Make Spending Explorer links to awards open in a new tab
used window.open instead of history.push;
path to get to an example:
obj class > contractual services > health & human services > prg mgmnt, centers for... > prg operations
then you get a bunch of recipients that you can click on, and will show another level,
then you see some awards that will open an award profile
[DEV-9935](https://federal-spending-transparency.atlassian.net/browse/DEV-9935)
**Mockup:**
n/a
Author:
- [x ] Verified that …

9935 - used window.open to open the links to awards in a new tab

---

src/_scss/layouts/default/footer/_stayInTouch.scss
src/js/components/agency/visualizations/StatusOfFundsChart.jsx
src/js/components/sharedComponents/StayInTouch.jsx

Chart was weird when there was a large pos number and a small neg number; example in ticket
Updated the logic that determines the domain in the chart; so now it uses the larger of the absolute value of the largest positive or negative number
[DEV-9888](https://federal-spending-transparency.atlassian.net/browse/DEV-9888)
**Mockup:**
n/a
Author:
Reviewer(s):

9888 - changed logic for determining the domain in the chart

---

src/_scss/layouts/default/header/nav/_megaMenu.scss
src/js/components/sharedComponents/header/megaMenu/NavbarItem.jsx

Nav button stays grayed out if the dropdown menu is open. 
[DEV-9930](https://federal-spending-transparency.atlassian.net/browse/DEV-9930)
Author:
Reviewer(s):

Mod 9930 mega menu hover

---

src/_scss/layouts/default/header/nav/mobile/_animations.scss
src/_scss/layouts/default/header/nav/mobile/_dropdown.scss
src/_scss/layouts/default/header/nav/mobile/_nav.scss
src/_scss/layouts/default/header/nav/mobile/_top.scss
src/_scss/layouts/default/header/nav/mobile/mobileNav.scss
src/js/components/sharedComponents/header/NavbarWrapper.jsx
src/js/components/sharedComponents/header/mobile/MobileNav.jsx
src/js/components/sharedComponents/header/mobile/MobileTop.jsx

this pr is only for the animation on the mobile menu
Added the animation that was used on the old mobile menu; also had to add a version of that animation to the elements in the mobile-nav-content block so the content list will animate out when user uses Back button; and cleaned up some css and removed the GA tracking from the close button
update after design review:
removed unneeded animation classes for exit because display none overrides them anyway; added a state var to prevent the usas logo from sliding in from the left when the menu opens; removed tophat from the mobile menu, as requested by design
[DEV-9701](https://federal-spending-transparency.atlassian.net/browse/DEV-9701)
**Mockup:** …

Mod 9701 fortmat mobile nav menu

---

src/_scss/layouts/default/footer/_stayInTouch.scss

Spacing isn't correct between the new Stay in Touch sections
Changed from justify-content: flex-start to space-between
[DEV-9976](https://federal-spending-transparency.atlassian.net/browse/DEV-9976)
**Mockup:**
n/a
Author:
Reviewer(s):

9976 - fixed spacing between new stay in touch sections

---

src/data/congressional/ct_districts.json
src/data/congressional/il_districts.json
src/data/congressional/mi_districts.json

Removed the state abbreviation-ZZ from CT, MI, and IL
[DEV-9963](https://federal-spending-transparency.atlassian.net/browse/DEV-9963)
**Mockup:**
Author:
Reviewer(s):

Removed ZZ district code

---

src/_scss/pages/search/filters/location/location.scss
src/js/components/search/filters/location/LocationPicker.jsx

just fixing cursor pointer, the rule was there but I forgot to re-add the class when I switched from span to Button from dtui
Author:
Reviewer(s):

DEV-9912 fix cursor pointer

---

src/js/components/sharedComponents/header/megaMenu/AnimatedNavbar.jsx
src/js/components/sharedComponents/header/megaMenu/ItemContent.jsx

fixed tabbing outside megamenu
[DEV-9928](https://federal-spending-transparency.atlassian.net/browse/DEV-9928)
Author:
Reviewer(s):

DEV-9928 tabbing outside of megamenu will now close menu

---

src/_scss/layouts/default/footer/footer.scss
src/js/components/sharedComponents/header/NavbarWrapper.jsx

adjust width of a tag <768, height kept the same
Author:
Reviewer(s):

DEV-7691 lessens the issue with the mobile hit area without changing how the items look

---

src/_scss/pages/search/results/visualizations/rank/chart/_item.scss
src/js/components/search/visualizations/rank/chart/ChartGroup.jsx

make labels noticeable when you're tabbed on them
**Technical Details**
since these labels are anchor tags and not just text, they don't show up with the outline around them, tried several things to get this to work and I think the smartest solution is to add stroke/stroke width to the labels when you're focused on them, it prevents us from having to overhaul the labels completely and keep the original functionality
the labels aren't just text, they are svg text which is what i think is causing the issue
[DEV-9720](https://federal-spending-transparency.atlassian.net/browse/DEV-9720)
[DEV-9722](https://federal-spending-transparency.atlassian.net/browse/DEV-9722)
Author:
Reviewer(s):

DEV-9720/DEV-9722 make labels perceptible when you're focused on them

---

src/js/components/search/visualizations/rank/chart/ChartGroup.jsx

use this as an example /search/?hash=1b502463b0d4bdd52d42a959d1798d53 then go to sub-agencies, previously this crashed but now it does not crash, the subagencies are not clickable or tabbable just like in prod
9722 shouldn't have existed bc the labels weren't clickable on purpose but i broke them, so here we are
[DEV-9722](https://federal-spending-transparency.atlassian.net/browse/DEV-9722)
Author:
Reviewer(s):

9722 weird error

---

src/js/components/account/SearchSidebar.jsx
src/js/components/search/visualizations/rank/sections/SpendingByAgencySection.jsx
src/js/components/search/visualizations/rank/sections/SpendingByRecipientSection.jsx

Hide all of the "Coming soon" labels and/or sections that aren't coming soon...
[DEV-8653](https://federal-spending-transparency.atlassian.net/browse/DEV-8653)
**Mockup:**
Author:
Reviewer(s):

Mod 8653 remove unneeded coming soon labels

---

src/js/components/search/SearchResults.jsx

when mobile menu is open "Learn how active filters work" isn't rendered, basically the same as 'hiding' it underneath the open menu except the dom is smaller
[DEV-9710](https://federal-spending-transparency.atlassian.net/browse/DEV-9710)
Author:
Reviewer(s):

DEV-9710 hide hover on advanced search on mobile when the menu is open

---

src/_scss/pages/explorer/detail/header/header.scss

Header in Spending Explorer whitespace was off
a classname had been unintentionally altered; i changed it back
[DEV-10217](https://federal-spending-transparency.atlassian.net/browse/DEV-10217)
**Mockup:**
n/a
Author:
Reviewer(s):

10217 - replaced class name for header class

---

src/js/containers/explorer/detail/DetailContentContainer.jsx

due to difficulties with converting to a functional component, just removing withRouter dependency as a first step because it's not even needed
don't move the ticket to testing once this is merged, nothing should change with this PR from a user perspective
[DEV-10211](https://federal-spending-transparency.atlassian.net/browse/DEV-10211)
Author:
Reviewer(s):

DEV-10211 withrouter not needed at all

---

src/js/containers/search/table/ResultsTableContainer.jsx

fix double load on sub awards -> sub contracts 
[DEV-10214](https://federal-spending-transparency.atlassian.net/browse/DEV-10214)
Author:
Reviewer(s):

fix double reload when you click subawards then sub contracts

---

src/_scss/pages/search/results/visualizations/geo/map/_toggle.scss
src/js/components/search/visualizations/geo/MapWrapper.jsx

Z-index issue between the map toggle and the treemap infobox on state pages. 
Was set to 5, changed it to 2, bc if at 0 or 1 then the plus and minus icons in the mapbox window are over the map toggle. Now at 2, the mapbox toggle is over the plus and minus things, and the treemap infobox is over both of them
Also removed an unneeded console.log.
[DEV-10367](https://federal-spending-transparency.atlassian.net/browse/DEV-10367)
**Mockup:**
n/a
Author:
Reviewer(s):

10367 - changed z-index for the map-layer-toggle; removed a console.log

---

src/js/components/agency/visualizations/StatusOfFundsChart.jsx

There's a bug in the chart when there are negative values.
I changed how we're selecting the largest negative value and the logic for setting the domain when there is a negative value
[DEV-10257](https://federal-spending-transparency.atlassian.net/browse/DEV-10257)
**Mockup:**
n/a
Author:
Reviewer(s):

10257 - changed how we find largest negative value for the chart

---

src/js/containers/search/modals/fullDownload/DownloadBottomBarContainer.jsx

Added set state and callback to fix download failure
Converting the Award Container from a class component to a functional component created a timing issue with the downloadbottombar causing the download not be initiated.
[DEV-10493](https://federal-spending-transparency.atlassian.net/browse/DEV-10493)
Author:
Reviewer(s):

Hotfix: DEV-10493 - Added set state and callback to fix download failure

---

src/js/components/glossary/Glossary.jsx

Small bug where the scrollbar wasn't appearing in longer Glossary entries, but it was there on the main Glossary page 
Looking through prs for what might have caused this, i saw that in Glossary.jsx the Scrollbars style prop had been changed recently. Apparently it needs 'height:' in the style prop.
[DEV-10501](https://federal-spending-transparency.atlassian.net/browse/DEV-10501)
**Mockup:**
n/a
Author:
Reviewer(s):

10501 - small fix for glossary scrollbar bug

---

src/js/components/covid19/assistanceListing/CFDADetailModal.jsx

The layout in this modal was off
I noticed that the usa-dt-modal class has width: 91.67% on it, and that for this modal there were two divs with that classname. The first one set the width for the modal in relation to the page, and the second one was setting the width in realtion to the modal. Removing the div with the second usa-dt-modal class solved the problem and didn't affect the rest of the layout.
The 'Files Changed' for this pr is misleading. All I did was remove the div that was right under the <Modal> element.
[DEV-10515](https://federal-spending-transparency.atlassian.net/browse/DEV-10515)
**Mockup:**
n/a
Author: …

10515 - removed a div with second usa-dt-modal class on it

---

src/_scss/pages/about/_section.scss
src/js/components/about/legal/AccessibilityPage.jsx
src/js/components/about/legal/FOIAPage.jsx
src/js/components/about/legal/PrivacyPage.jsx

This link was running off the page at small screen sizes
Added a class to undo nowrap for this one link
[DEV-10499](https://federal-spending-transparency.atlassian.net/browse/DEV-10499)
**Mockup:**
n/a
Author:
Reviewer(s):

10499 - made a class to undo nowrap for this link

---

src/js/containers/search/table/ResultsTableContainer.jsx

Advanced search - Fixed issue where new table rows are not returned after scrolling to the bottom of the table
Updated when we're performing a new search based on paging.  Paging should happen when the user scrolls to the bottom of the table.
[DEV-10569](https://federal-spending-transparency.atlassian.net/browse/DEV-10569)
Author:
Reviewer(s):

10569 - Hotfix:  Advanced search - Fixed issue where new table rows are not returned after scrolling to the bottom of the table

---

src/js/containers/search/visualizations/geo/GeoVisualizationSectionContainer.jsx

DEV-10520 is to zoom into the region selected in the location on the Award Search map but there is a Mapbox issue that needs to be resolved first.  However, DEV-10520 is in QAT currently and selects the Map filter and maplayer based on the location.  This is fine for all filters except for the Country filter.  In QAT now if a country is selected, the map show the error message - 
This PR is not for the completed ticket DEV-10520 but just "reverting" selected the Country map filter and maplayer when a country is selected in the location filter.
Reviewer(s):

Removed country filter selection

---

src/js/components/sharedComponents/header/Header.jsx

Remove the InfoBanner from the Header component, but don't delete the InfoBanner component because we reuse it.
Removed InfoBanner from Header
[DEV-10578](https://federal-spending-transparency.atlassian.net/browse/DEV-10578)
**Mockup:**
n/a
Author:
Reviewer(s):

10578 - removed infoBanner from Header.jsx

---

src/js/components/search/filters/timePeriod/TimePeriod.jsx
src/js/containers/account/filters/AccountTimePeriodContainer.jsx

federal account crashing when you click an FY, needed to pass in searchFilterActions
[DEV-10721](https://federal-spending-transparency.atlassian.net/browse/DEV-10721)
Author:
Reviewer(s):

DEV-10721 fix federal account filter crashing

---

src/js/components/search/visualizations/geo/map/MapBox.jsx

Bug fix - 
From testing "without filtering a location the map is set to the "US States.." toggle but is really zoomed into the US map."

10650 - Fixed zoom level when the contiguous US is selected

---

src/js/components/search/visualizations/geo/map/MapBox.jsx

Initial change to fix showing the contiguous US broke zooming to county and CD.  Zooming to county, state, county, CD, and country should be fixed now.
[DEV-10650](https://federal-spending-transparency.atlassian.net/browse/DEV-10650)
Author:
Reviewer(s):

10650 - Fixed issue with state, county and CD zoom

---

src/js/components/search/visualizations/rank/spendingByCategoriesChart/SpendingByCategoriesChart.jsx

Quick follow up from design.
Made the height of the spending by categories chart taller for desktop screens (from 500px to 600px)
[DEV-10864](https://federal-spending-transparency.atlassian.net/browse/DEV-10864)
**Mockup:**
n/a
Author:
Reviewer(s):

10864 - updated the height of the chart on desktop

---

src/js/components/sharedComponents/RoundedToggle.jsx

Ticket for the latest 508 scan
Added aria label to the Outlays toggle in Status of Funds chart. This was labelled as Critical in the scan.
[DEV-10710](https://federal-spending-transparency.atlassian.net/browse/DEV-10710)
**Mockup:**
n/a
Author:
Reviewer(s):

10710 - added aria label to sof chart outlays toggle

---

src/_scss/pages/search/results/visualizations/rank/rankVisualization.scss
src/js/components/search/visualizations/rank/spendingByCategoriesChart/SpendingByCategoriesChart.jsx

change the color of spending by categories text when it isn't a link
[DEV-10989](https://federal-spending-transparency.atlassian.net/browse/DEV-10989)
Author:
Reviewer(s):

DEV-10989 fix text on spending by categories when it is not a link

---

src/js/components/search/SearchPage.jsx
src/js/containers/search/SearchSidebarSubmitContainer.jsx
src/js/containers/search/table/ResultsTableContainer.jsx

just undoing some of the title filter bar work that i did
[DEV-10984](https://federal-spending-transparency.atlassian.net/browse/DEV-10984)
Author:
Reviewer(s):

DEV-10984 undo title filter bar change

---

package-lock.json
src/js/components/search/newResultsView/ResultsView.jsx

removes console statements left in and fixes the problem with no results on subaward
to test, do a search and then pick subawards in the dropdown on the top then untoggle use previous advanced search and make sure the page loads
Author:
Reviewer(s):

Fix new results page round 1

---

src/js/containers/search/newResultsView/CategoriesVisualizationWrapperContainer.jsx

Removed the uei column from the spending by categories recipient table.  
[DEV-11032](https://federal-spending-transparency.atlassian.net/browse/DEV-11032)
Author:
Reviewer(s):

11032 - Removed the uei column from the spending by categories recipient table

---

src/js/containers/search/newResultsView/ResultsTableContainer.jsx
src/js/containers/search/table/ResultsTableContainer.jsx

to test - in qat when you do a search click on page 3 then switch tabs in the search table, it will stay on page 3, the fixes ensure that when you switch tabs you go back to page 1
Author:
Reviewer(s):

Fix new search pagination

---

src/_scss/pages/interactiveDataSources/_dataSourcesTitles.scss

adjust text location on data sources page for 1366x768 screen widths
[DEV-10097](https://federal-spending-transparency.atlassian.net/browse/DEV-10097)
Author:
Reviewer(s):

DEV-10097 fix for 1366x768 screens

---

src/_scss/pages/aboutTheData/aboutTheData.scss
src/js/containers/aboutTheData/AgencyTableMapping.jsx

fix one tooltip being cutoff
[DEV-7506](https://federal-spending-transparency.atlassian.net/browse/DEV-7506)
Author:
Reviewer(s):

DEV-7506 fix one tooltip on desktop

---

src/_scss/pages/explorer/detail/visualization/table/_table.scss
src/_scss/pages/state/_contentWrap.scss

Found two instances of links that needed updating.
On spending explorer, the links on the table needed changing. On the state profile, the link 'View awards to this state' needed it's color and hover color updated.
[DEV-10022](https://federal-spending-transparency.atlassian.net/browse/DEV-10022)
**Mockup:**
n/a
Author:
Reviewer(s):

Mod/10022 hyperlink style update-2

---

src/_scss/pages/agency/dtuiOverrides.scss
src/_scss/pages/agency/index.scss
src/_scss/pages/agency/statusOfFunds/_dtuiOverrides.scss

This table has black borders instead of gray.
Added a dtuiOverrides file to agency/index.scss to make the borders gray again
[DEV-11194](https://federal-spending-transparency.atlassian.net/browse/DEV-11194)
**Mockup:**
Author:
Reviewer(s):

11194 - fix for table borders on agency page, award spending section

---

src/_scss/pages/homepageUpdate/_awardSearch.scss
src/_scss/pages/homepageUpdate/_exploreTheData.scss

Center button text in the Explore the Data section
Did that by changing padding in the buttons; also noticed that in the Award Search carousel the buttons had margin right that wasn't needed and was making them slightly not centered horizontally, so I removed that
[DEV-11180](https://federal-spending-transparency.atlassian.net/browse/DEV-11180)
**Mockup:**
Author:
Reviewer(s):

11180 - centered text in explore the data section buttons

---

src/js/components/account/visualizations/time/TimeVisualization.jsx
src/js/components/account/visualizations/time/chart/BarChartStacked.jsx
src/js/components/sharedComponents/timeChart/chart/BarChartLegendItem.jsx

change legend so that it's stacked under 576px
http://localhost:3000/federal_account/020-0500 used as an example
[DEV-11272](https://federal-spending-transparency.atlassian.net/browse/DEV-11272)
Author:
Reviewer(s):

DEV-11272 fix fed account legend on mobile so it isn't cut off

---

src/js/components/search/filters/location/LocationSection.jsx
src/js/components/search/filters/timePeriod/TimePeriod.jsx
src/js/components/sharedComponents/filterSidebar/FilterTab.jsx
src/js/components/sharedComponents/filterSidebar/FilterTabs.jsx

Replace time period buttons with tabs from LocationSection
[DEV-11304](https://federal-spending-transparency.atlassian.net/browse/DEV-11304)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/663942629f0e7d977ea7eb9e
Author:
Reviewer(s):

Remove buttons in time period filter and replace with tabs

---

src/js/components/state/topFive/TopFive.jsx

Added missing agency_abbreviation field to fix the Subagency top 5 section link to "View Awards"
Added the missing field from the backend added with their ticket DEV-11405
[DEV-11283](https://federal-spending-transparency.atlassian.net/browse/DEV-11283)
Author:
Reviewer(s):

11283 - Added missing agency_abbreviation field to fix the Subagency top 5 section link to "View Awards"

---

src/_scss/pages/search/filters/timePeriod/timePeriod.scss
src/js/components/search/filters/timePeriod/TimePeriod.jsx

Addresses keyboard accessibility for the Show New Awards Only checkbox under the Time Period Fiscal Year filter.
Used the onKeyUp event handler and conditionals to toggle selecting and unselecting the New Awards Only filter.
[DEV-11395](https://federal-spending-transparency.atlassian.net/browse/DEV-11395)
**Mockup:**
N/A
Author:
Reviewer(s):

11395 - make time period new awards only checkbox filter keyboard accessible

---

src/js/components/search/newResultsView/SearchSectionWrapper.jsx

there is still a small amount of jumping which i think can be chalked up to the table finishing loading bc that is the biggest section on the search page
[DEV-11371](https://federal-spending-transparency.atlassian.net/browse/DEV-11371)
Author:
Reviewer(s):

DEV-11371 minimize jumping

---

src/js/components/search/filters/timePeriod/DateRange.jsx

fix issue mentioned here https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1726073360975559
wasn't caught before bc I had been typing in dates, this problem only occurs when clicking on the calendar icon and selecting dates
[DEV-11396](https://federal-spending-transparency.atlassian.net/browse/DEV-11396)
Author:
Reviewer(s):

DEV-11396 fix end problem on not typing in dates

---

src/_scss/pages/aboutTheData/aboutTheData.scss

The table on this page appeared to be running off the right edge of the page.
Changed the width for the main-content class to make it look more centered. It still isn't perfect, but the css for this page is weird and confusing and this at least makes it no longer appear broken.
[DEV-11458](https://federal-spending-transparency.atlassian.net/browse/DEV-11458)
**Mockup:**
n/a
Author:
Reviewer(s):

11458 - adjusted width of table section

---

src/_scss/pages/covid19/recipient/recipientContainer.scss

Enabled the blue color around the filter dropdown buttons to show. This improves accessibility.
Needed to remove the :focus pseudo-class selector which prevented the default box-shadow styles that were configured at a higher level for indicating focused state.
[DEV-11238](https://federal-spending-transparency.atlassian.net/browse/DEV-11238)
**Mockup:**
N/A
Author:
Reviewer(s):

11238 - enable focus color for covid19 page map filters

---

src/js/components/search/newResultsView/map/MapDsm.jsx

Updated link and replaced it with the Medicare Location Data from 'About the Data'.
Added useDispatch to help render the About the Data page.
[DEV-11298](https://federal-spending-transparency.atlassian.net/browse/DEV-11298)
**Mockup:**
Author:
Reviewer(s):

11298 - updated ds&m link to route to medicare 'about the data' page

---

src/js/components/search/filters/timePeriod/TimePeriod.jsx
src/js/containers/search/filters/TimePeriodContainer.jsx
src/js/models/v1/search/SearchAwardsOperation.js
src/js/redux/reducers/search/searchFiltersReducer.js
tests/redux/reducers/search/searchFiltersReducer-test.js
tests/testResources/defaultReduxFilters.js

change the active tab for time period depending on what you've searched, not sure why timeperiod was keeping track of the active tab while also getting it as a prop from timeperiodcontainer seemed duplicative
[DEV-11508](https://federal-spending-transparency.atlassian.net/browse/DEV-11508)
Author:
Reviewer(s):

DEV-11508 change active tab for time period depending on active filters (search hash)

---

src/js/components/search/newResultsView/table/TableSection.jsx

Chnage the table section heading when subawards is true
Added a ternary in the wrapper props being sent to the section wrapper
[DEV-11605](https://federal-spending-transparency.atlassian.net/browse/DEV-11605)
**Mockup:**
n/a
Author:
Reviewer(s):

11605 - added ternary to change the sectionTitle when subawards is true

---

src/_scss/pages/search/filters/recipient/recipient.scss
src/js/components/search/filters/recipient/RecipientResults.jsx

Design noticed some small changes needed in this filter
Got rid of some unneeded css and changed some classnames; changed font weights and colors where needed; added logic to show 'Not provided' when no uei is in the data. To test this you have to force the data to be blank or false, in order to show the 'Not provided' text, because there are no longer any blank ueis in the data.
This has been thoroughly design reviewed.
[DEV-11644](https://federal-spending-transparency.atlassian.net/browse/DEV-11644)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/66c7387f9edd5064a09eb761
Author:
Reviewer(s):

Mod/11644 recipient filter UI

---

src/js/components/sharedComponents/autocomplete/Autocomplete.jsx

In the Location filter, after selecting something from the dropdown, the text in the input box is bold, and stays bold after you clear it and enter a different string there
Finally found this fn that was firing after the selection is made from the dropdown. It was applying font weight 600 to the input box text, so I changed it to 400.
[DEV-11610](https://federal-spending-transparency.atlassian.net/browse/DEV-11610)
**Mockup:**
n/a
Author:
Reviewer(s):

11610 - changed font weight to 400 after selection from dropdown is made

---

src/js/containers/award/table/AwardHistoryTableContainer.jsx

Added a set state to reset pagination on tab change
[DEV-11628](https://federal-spending-transparency.atlassian.net/browse/DEV-11628)
**Mockup:**
n/a
Author:
Reviewer(s):

11628 - added a set page to useEffect

---

src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/dataMapping/search/searchFilterCategories.jsx

add two filters to search v2 - also add the ability to turn off the info explanation for the tas filter
[DEV-11723](https://federal-spending-transparency.atlassian.net/browse/DEV-11723)
Author:
Reviewer(s):

DEV-11723 agency and tas filter on searchv2 page

---

src/_scss/pages/search/filters/recipient/recipient.scss
src/js/components/search/filters/recipient/RecipientResultsContainer.jsx
src/js/helpers/searchHelper.js

add loading spinner and change request to be 100 results by default
[DEV-11702](https://federal-spending-transparency.atlassian.net/browse/DEV-11702)
Author:
Reviewer(s):

DEV-11702 loading indicator for recipient + 100 results

---

src/_scss/pages/search/_collapsibleSidebar.scss
src/_scss/pages/search/_searchFilter.scss
src/_scss/pages/search/_searchSubmit.scss
src/_scss/pages/search/_searchv2.scss
src/js/components/search/collapsibleSidebar/CollapsibleSidebar.jsx
src/js/components/search/collapsibleSidebar/SearchPagev2.jsx

Added sticky behavior to filter side panel.  It's best to test with a url that has a hash (ie. so the results view has content and the page is long). Still working through the extremes behavior with the designers including the following cases:
1. The initial page load before the default image loads and the results view loads
2. if you scroll all the way to the bottom of the screen when the viewport is narrow
3. scrolling to the top or bottom quickly
4. when the results view height changes after content is rendered in the sections
[DEV-11743](https://federal-spending-transparency.atlassian.net/browse/DEV-11743) …

11743 / 11710 - Added sticky behavior to filter side panel

---

src/js/components/search/collapsibleSidebar/CollapsibleSidebar.jsx

tabbing no longer stuck on sidebar opening - this was caused by calling e.preventDefault twice
[DEV-11790](https://federal-spending-transparency.atlassian.net/browse/DEV-11790)
Author:
Reviewer(s):

DEV-11790 tabbing search v2

---

src/_scss/pages/search/_collapsibleSidebar.scss

In searchv2 side panel, remove tooltips from NAICS and PSC filters
Used css to hide tooltips
[DEV-11814](https://federal-spending-transparency.atlassian.net/browse/DEV-11814)
**Mockup:**
See ticket
Author:
Reviewer(s):

11814 - In searchv2 side panel, remove tooltips from NAICS and PSC filters

---

src/js/containers/search/filters/location/LocationAutocompleteContainer.jsx

missing a prop thus causing the pass in variable to be undefined
[DEV-11875](https://federal-spending-transparency.atlassian.net/browse/DEV-11875)
Author:
Reviewer(s):

DEV-11875 missing prop in parent container

---

src/js/components/search/collapsibleSidebar/CategoryFilter.jsx
src/js/components/search/collapsibleSidebar/CategoryHeader.jsx
src/js/components/search/collapsibleSidebar/SearchSidebarDrilldown.jsx

passed icon properties to category filter and removed the description as they are hard coded in for them, and change ternary for css to fix spacing issue when the description was removed.  
[DEV-11864](https://federal-spending-transparency.atlassian.net/browse/DEV-11864)
**Mockup:**
n/a
Author:
Reviewer(s):

11864 - icons on individual filters

---

src/_scss/pages/search/_collapsibleSidebar.scss
src/_scss/pages/search/filters/otherFilters/_defCheckboxV2.scss
src/_scss/pages/search/searchPage.scss
src/js/components/search/filters/defc/DEFCheckboxTreeLabelv2.jsx
src/js/components/sharedComponents/checkbox/AccordionCheckbox.jsx
src/js/components/sharedComponents/checkbox/AccordionCheckboxPrimary.jsx
src/js/components/sharedComponents/checkbox/AccordionCheckboxSecondary.jsx
src/js/containers/search/filters/def/DEFCheckboxTreeContainer.jsx

Fixed DEFC filter label layout and layout within the v2.0 side panel
Adopted the old component for the DEFC filter labels and updated per the mock.
[DEV-11951](https://federal-spending-transparency.atlassian.net/browse/DEV-11951)
**Mockup:**
https://app.zeplin.io/project/61f8076f4ef77f11fcc37f55/screen/66e4a1d1f5ac7ffb6fdab185
Author:
Reviewer(s):

11951 -  Fixed DEFC filter label layout and the filter's layout within the v2.0 side panel

---

src/js/containers/search/filters/def/DEFCheckboxTreeContainer.jsx
src/js/helpers/search/collapsiblesidebarHelper.js

Addressing testing feedback to sort the Infrastructure filter so alpha is first and numbers are last
[DEV-11951 ](https://federal-spending-transparency.atlassian.net/browse/DEV-11951 )
Author:
Reviewer(s):

11951 - Addressing testing feedback to sort the Infrastructure filter

---

src/_scss/pages/search/filters/naics/naics.scss
src/_scss/pages/search/filters/otherFilters/_defCheckbox.scss
src/_scss/pages/search/filters/otherFilters/_pscCheckbox.scss
src/_scss/pages/search/filters/otherFilters/_tasCheckbox.scss
src/js/components/search/filters/agency/ShownAgency.jsx
src/js/components/search/filters/awardAmount/SelectedAwardAmountBound.jsx
src/js/components/search/filters/awardID/ShownAwardID.jsx
src/js/components/search/filters/location/ShownLocation.jsx
src/js/components/search/filters/recipient/ShownRecipient.jsx
src/js/containers/search/filters/def/DEFCheckboxTree.jsx
src/js/containers/search/filters/naics/NAICSCheckboxTree.jsx
src/js/containers/search/filters/programSource/TASCheckboxTreeContainer.jsx
src/js/containers/search/filters/psc/PSCCheckboxTreeContainer.jsx

changed chips to be icon closed instead of whole button in all instance but DateRange as that will take more refactoring. Josue message about it: https://data-transparency-bfs.slack.com/archives/C038E9G7S4D/p1738364766233509
refactor so that shownValue compenent was used in all chip filter instances
https://federal-spending-transparency.atlassian.net/jira/software/c/projects/DEV/boards/25?selectedIssue=DEV-11869
**Mockup:**
n/a
Author:
Reviewer(s):

changed all chips to be shownValue

---

src/js/components/sharedComponents/checkbox/AccordionCheckbox.jsx
src/js/components/sharedComponents/checkbox/ListCheckbox.jsx
src/js/containers/search/filters/recipient/RecipientSearchContainer.jsx

in order to not break existing search have to put a hard cap on the height of the containers until we deploy search v2
Author:
Reviewer(s):

have to comment out this change UNTIL we deploy search v2, setting to previous value

---

src/_scss/core/_variables.scss
src/_scss/layouts/default/header/_warning.scss
src/js/GlobalConstants.js
src/js/components/sharedComponents/header/Header.jsx
src/js/components/sharedComponents/header/InfoBanner.jsx

Make InfoBanner Component styling dynamic with type 
Update InfoBanner component to adjust styling and icon based on className type "general", "warning", "warning-resolved"
[DEV-12045](https://federal-spending-transparency.atlassian.net/browse/DEV-12045)
Author:
Reviewer(s):

Fix/dev12045  - Make InfoBanner component more dynamic

---

src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx

Display styling was being set in in the same element by two different criteria causing it to get set at incorrect times. The display styling for opening/closing the side bar is now being set on the child component to avoid overlap in logic.
[DEV-12068](https://federal-spending-transparency.atlassian.net/browse/DEV-12068)
**Mockup:**
n/a
Author:
Reviewer(s):

12068 - submit button showing incorrectly while scrolling

---

src/js/components/search/collapsibleSidebar/SearchSidebarDrilldown.jsx
src/js/helpers/search/filterCheckboxHelper.js

DEV-12046 : "1 selected" is displayed for selecting more than one TAS filter
Utilize helper function "generateCount" for tasCodes.
[DEV-12046](https://federal-spending-transparency.atlassian.net/browse/DEV-12046)
Author:
Reviewer(s):

DEV-12046 : "1 selected" is displayed for selecting more than one TAS filter

---

src/_scss/pages/search/_collapsibleSidebar.scss
src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx

Fixed issue where the top sticky bar overlays the mega menu and the mobile menu.  See issue in the screenshot below.
[DEV-12097 ](https://federal-spending-transparency.atlassian.net/browse/DEV-12097 )
Author:

DEV-12097 - Fixed issue where the top sticky bar overlays the mega menu and the mobile menu

---

package-lock.json
src/_scss/pages/search/_collapsibleSidebar.scss
src/js/components/search/collapsibleSidebar/DsmSlider.jsx
src/js/components/search/collapsibleSidebar/SearchSidebarDrilldown.jsx
src/js/components/search/collapsibleSidebar/SidebarContent.jsx
src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx

close dsm slider when you go back or toggle the sidebar closed/open
[DEV-12196](https://federal-spending-transparency.atlassian.net/browse/DEV-12196)
Author:
Reviewer(s):

DEV-12196 dsm slider close on back and toggle

---

src/js/containers/account/AccountContainer.jsx

Noticed that the fed account table does load correctly when the filters are changed on the left.  The original fix was correct
[DEV-12564](https://federal-spending-transparency.atlassian.net/browse/DEV-12564)
**Mockup:**
n/a
Author:

DEV-12564: Fixed issue with loading fed account pages

---

src/js/components/search/collapsibleSidebar/SidebarWrapper.jsx

Set the position of the sidebar to fixed when footer is visible in order to minimize sidebar 'bounce' on scroll.
[DEV-12432](https://federal-spending-transparency.atlassian.net/browse/DEV-12432)
**Mockup:**
n/a
Author:
[DEV-12432]: https://federal-spending-transparency.atlassian.net/browse/DEV-12432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12432 - used fixed positioning to make bouncing less obvious

---

src/js/containers/recipient/RecipientContainer.jsx

Fixed issue with loading the recipient profile page without the fy param in the url.  https://data-transparency-bfs.slack.com/archives/CE5P5AWE8/p1748545288187399 
[DEV-12728](https://federal-spending-transparency.atlassian.net/browse/DEV-12728)
**Mockup:**
n/a
Author:
[DEV-12728]: https://federal-spending-transparency.atlassian.net/browse/DEV-12728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12728:  Fixed issue with loading the recipient profile page without the fy param in the url

---

src/js/components/sharedComponents/ReadMore.jsx

"Read More" component onClick functionality was being masked by parent component.  adding e.stopPropagation() stops the bubbling up action to the parent and allows the child functionality to occur. 
[DEV-12792](https://federal-spending-transparency.atlassian.net/browse/DEV-12792)
*Testing**
To test open advanced search, choose a filter, set to mobile view, in the Results Table scroll until you see a "ReadMore"  --> should only require a single click to expand/collapse.  All other links and buttons within each result grouping/row should work with a single click as well.
Author:
[DEV-12792]: https://federal-spending-transparency.atlassian.net/browse/DEV-12792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …

DEV 12792: Mobile View - User has to click "read more" twice on mobile stacked table

---

src/js/components/search/SearchSidebar.jsx

set Keyword section in legacy search filters to be defaulted open on page load
[DEV-12857](https://federal-spending-transparency.atlassian.net/browse/DEV-12857)
Author:
[DEV-12857]: https://federal-spending-transparency.atlassian.net/browse/DEV-12857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12857 : Adv Search: Expand Keyword Search Accordion on default

---

src/_scss/pages/covid19/index.scss

For some reason the sub-section container width was not fully setting to 100%
[DEV-12044](https://federal-spending-transparency.atlassian.net/browse/DEV-12044)
**Mockup:**
https://app.zeplin.io/
Author:
[DEV-12044]: https://federal-spending-transparency.atlassian.net/browse/DEV-12044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV: 12044: fix weird container width issue.

---

src/_scss/pages/search/_collapsibleSidebar.scss
src/js/components/search/collapsibleSidebar/SidebarContent.jsx

add close button back on mobile/tablet for search 2.0 sidebar
[DEV-13133](https://federal-spending-transparency.atlassian.net/browse/DEV-13133)
**Mockup:**
https://figma-gov.com/design/s8rgQ5B6Rd3snAgGATNvXl/Design-Tickets?node-id=532-5477&m=dev
(on the side there is a mobile mock with a close button)
Author:
[DEV-13133]: https://federal-spending-transparency.atlassian.net/browse/DEV-13133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-13133 add in X (close button)

---

src/content/about-the-data/park.mdx

New request from PO - there was an ask if we can remove the last two sentences from the PARK About the data entry for DEV-12941 "After October 1, 2025 (Fiscal Year 2026), PARK will be associated with specific program activity names on [USAspending.gov](http://usaspending.gov/). However, users will still be able to view PAC and PAN codes related to activities before Fiscal Year 2026."
[DEV-12941](https://federal-spending-transparency.atlassian.net/browse/DEV-12941)
Author:
[DEV-12941]: https://federal-spending-transparency.atlassian.net/browse/DEV-12941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

12941 - Removed last two sentences of park atd

---

package-lock.json
src/js/containers/search/newResultsView/CategoriesVisualizationWrapperContainer.jsx
src/js/containers/search/newResultsView/MapSectionWrapper.jsx
src/js/containers/search/newResultsView/TimeVisualizationSectionContainer.jsx

This is a regression from https://github.com/fedspendingtransparency/usaspending-website/pull/4851.  The legacy advanced search charts must use transaction data when the filter by level is Prime Awards and Transactions.
https://data-transparency-bfs.slack.com/archives/CE892FN21/p1757938158735419
https://federal-spending-transparency.atlassian.net/browse/DEV-13453
**Mockup:**
n/a
Author:

Hotfix:  Fixed Advanced Search legacy page charts to use transaction data
